### PR TITLE
Feature: Upgrade notification 1 - Adaptive link

### PR DESCRIPTION
**Pull request by tbrlpld**
This PR changes which URL is used in the upgrade notification banner.

Previously, the link would always point to the last patch release. This would not be desirable for cases where a minor release lays between the current version and the latest available version. E.g. if the current version is `2.14.3` and the latest version is `2.15.2`, the previous behaviour was to link to the release notes of `2.15.2`. These patch release notes do not contain all the information that is necessary to perform the upgrades, because the most significant changes would be in the release notes for `2.15`. 

This PR changes that behaviour to use the latest minor release notes URL if the version difference is more than a patch release. E.g. for current version `2.15.1` and latest version `2.15.2`, the patch release notes (`2.15.2`)  would be used. But, for current version `2.15.1` and latest version `2.16.2`, the minor release notes (`2.16`) would be used. 

These changes are based on ec0daf604a366b18c842a13e1821391a5e2abdcd and #7671.

This desired behaviour is also described in #7336. The LTS behaviour described in #7336 will be added as a separate PR. 

***

Thanks for contributing to Wagtail! 🎉

Before submitting, please review the contributor guidelines <https://docs.wagtail.io/en/latest/contributing/index.html> and check the following:

* Do the tests still pass? (https://docs.wagtail.io/en/latest/contributing/developing.html#testing) Yes
* Does the code comply with the style guide? (Run `make lint` from the Wagtail root) Yes
* For Python changes: Have you added tests to cover the new/fixed behaviour? n/a
* For front-end changes: Did you test on all of [Wagtail’s supported environments](https://docs.wagtail.io/en/latest/contributing/developing.html#browser-and-device-support)?
    * **Please list the exact browser and operating system versions you tested**.
      * macOS 10.15.7, Firefox 94
      * macOS 10.15.7, Safari 15.1
      * Windows 11, Edge 95
    * **Please list which assistive technologies you tested**. None
* For new features: Has the documentation been updated accordingly? No

### CODE REVIEW

**Comment by tbrlpld** [comment]
cc @nimasmi

**Comment by tbrlpld** [comment]
@gasman @kaedroho Was wondering if either of you could give this one a look 😄

**Comment by gasman** [comment]
@tbrlpld It's only been 3 days since you last gave us a ping on this. Please be patient :-)

**Comment by tbrlpld** [comment]
@gasman Whoops. Sorry. I have been creating a bunch of MRs lately and am loosing track where I have already been annoying people 🤦‍♂️😬

**Comment by lb-** [comment]
Implemented via https://github.com/wagtail/wagtail/pull/7752

**Pull request closed without merging**
