### PR TITLE
Fix status tag font-size units for proper resizing

### PR DESCRIPTION
**Pull request by maryojo**
Fixes issue #9363

Using 'rem' size instead of 'px' makes the font size responsive, the font size of the status tag changes with the rest of the elements on the screen. Therefore, making it easier to see the status tag when using accessibility tools like Magnifier.

Before:

After:

_Please check the following:_

-   [X] Do the tests still pass?[^1]
-   [X] Does the code comply with the style guide?
    -   [X] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour? (NA)
-   [X] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [X] **Please list the exact browser and operating system versions you tested**: Tested on Google Chrome, Firefox, Microsoft Edge and for OS: Windows 11 and Ubuntu 22.04
    -   [X] **Please list which assistive technologies [^3] you tested**: Magnifier 
-   [ ] For new features: Has the documentation been updated accordingly? (NA)

**Please describe additional details for testing this change**.
I tried setting up wagtail locally but I faced issues with installing the dependencies on my PC, so I used GitPod to setup and test

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by maryojo** [comment]
Hi @thibaudcolas , kindly check my PR

**Comment by Scotchester** [comment]
Hi @maryojo, thank you for submitting this PR! Could you please update your original post to include a link to the issue you are addressing, a description of how your changes solve it, and ideally also some before-and-after screenshots?

**Comment by Scotchester** [comment]
Nevermind the request for screenshots; I now realize that this change should not result in anything looking different.

**Comment by maryojo** [comment]
Hi @thibaudcolas, I have screenshots that showed the changes, I'd add them

**Review by Scotchester — APPROVED** [review]
Great work, @maryojo! Congratulations on your first contribution to Wagtail 😄 

I have listed your name on the contributors list as "Mary Ojo". Please let me know if you would like anything different.

**Comment by maryojo** [comment]
Thanks @Scotchester!! I'm fine with that. I learned a lot while contributing to wagtail! 😀

**Pull request merged**
