### PR TITLE
Fix/remove defunct oembed providers

### LINKED ISSUE #12054: Tidy up oembed_providers.py
### Issue Summary

Currently [oembed_providers.py](https://github.com/wagtail/wagtail/blob/ac38343957787b7d7a2ff34164a98538e177ff96/wagtail/embeds/oembed_providers.py) has a list of providers that no longer exist. A quick example would be Revision3.com, it longer exists as a service.

### Steps to Reproduce

```
from wagtail.embeds.embeds import get_embed
get_embed('http://www.revision3.com/demo')
```

Returns an `EmbedNotFoundException` exception, but there's other exceptions underneath because the URL/hostname doesn't exist.

Not a huge issue, but if there's a dead provider that isn't accepting connections - it just hangs:

```
get_embed('http://qik.com/demo')
```

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: Any
-   Django version: Any
-   Wagtail version: 6.1 / main
-   Browser version: n/a

### Working on this

I think this is probably a "good first issue", so would love to see someone else give this one a go.

### PR DESCRIPTION
**Pull request by rahulsamant37**
## Description

This PR removes several defunct oEmbed providers that no longer exist or have shut down their services. This fixes issues where Wagtail attempts to connect to non-existent services, which can cause unnecessary delays or connection timeouts.

### Removed Providers:
- app.net (shut down in 2014)
- bambuser (discontinued)
- blip.tv (shut down in 2015)
- qik (no longer exists)
- rdio (shut down in 2015)
- revision3 (no longer exists)
- vhx.tv (acquired and service changed)

## Motivation and Context

Fixes #12054 

Currently, Wagtail's oEmbed provider list includes several services that no longer exist. This causes issues when:
1. Attempting to embed content from these defunct services (returns `EmbedNotFoundException`)
2. Some providers that aren't accepting connections cause the request to hang (e.g., qik.com)

## How to Test

1. Verify that removing these providers doesn't affect existing functionality:
```python
from wagtail.embeds.embeds import get_embed
# Test with an active provider
get_embed('https://www.youtube.com/watch?v=example')
```
Thank you for the thorough explanation of the problem statement. If I have misinterpreted anything, I am open to any necessary changes. I hope this will help resolve the issue.

### CODE REVIEW

**Review by gasman — APPROVED** [review]
Thanks @rahulsamant37 - this looks good to me!

**Comment by gasman** [comment]
Merged in 5e4c3f12c3

**Comment by rahulsamant37** [comment]
Hello @gasman Sir,

Thank you for acknowledging my contribution! I'd really appreciate some feedback on why the PR didn’t merge. As I'm new to contributing, understanding the reasoning would be incredibly helpful for future contributions. I’m eager to learn and improve, so any guidance you can provide would mean a lot. Thanks in advance for your time and support!

**Comment by gasman** [comment]
Hi @rahulsamant37,
No problem! I can see that you correctly started a new branch from `main` as @lb- suggested in https://github.com/wagtail/wagtail/pull/12376#issuecomment-2387662504 - but your own copy of `main` has a different commit history to the original Wagtail one, as it contains your fix for #12376 followed by some merge commits to make it match the current state of Wagtail's `main` code. As a result, those extra commits made it into this new PR.

Before you start your next PR, you can bring your local copy of `main` back in sync with Wagtail's by running the following:
```
git checkout main
git reset --hard origin/main
git pull
```

You can also bring your Github fork (as distinct from the local checkout on your own machine) back in sync by using the "Sync fork" button:
Screenshot 2024-11-04 at 19 13 01
...although keeping that one in sync isn't really too important - you can see in the screenshot that mine was 6000+ commits behind :-)

**Comment by rahulsamant37** [comment]
@gasman 

Thank you for the clear and straightforward explanation. I completely understand the points you highlighted and will make sure to apply them in future contributions. Looking forward to continuing to contribute meaningfully!!

**Pull request closed without merging**
