### PR TITLE
Alignment support for table block

### PR DESCRIPTION
**Pull request by smendes**
This PR is split into two parts:
- Update Handsontable to version 6.2.2
- Adding support for saving cell classes

I've found the issue https://github.com/wagtail/wagtail/issues/2655 and while I understand the motivation for uncoupling data and formatting, it would seem that being able to specify a class for the data wouldn't violate this desire.

For Twilio, we do need the ability for editors to control the alignment of some cells, but agree with the data vs. formatting principle as well. It seems that a fair compromise would be to allows specifying a "class" for the data and then allow the various presentation templates for the table handle that specific class how they see fit.

For cell-specific information Handsontable stores everything in the metadata. This implementation only keeps the `className` part of it. That attribute stores the HTML class to apply to a given cell. With this patch, table blocks get rendered with those custom classes (`htLeft`, `htRight`, etc..) but without any style rules applied to those classes. Furthermore, the alignment option for the context menu isn't activated by default. This offers the possibility for a developer to activate it, but make it their responsibility to style those classes.

- [x] Do the tests still pass? (http://docs.wagtail.io/en/latest/contributing/developing.html#testing)
- [x] Does the code comply with the style guide? (Run `make lint` from the Wagtail root)
- [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
- [x] For new features: Has the documentation been updated accordingly?

### CODE REVIEW

**Comment by dprothero** [comment]
Hey team! @smendes works with us on the Twilio Developer Education team and we're keen for some kind of method for allowing different cells to be styled differently based on the desires of the editor using the CMS. Let us know what you think of this PR and if there's a different approach you'd prefer for this.

**Comment by dprothero** [comment]
@gasman Do you have some time to take a look at this?

**Comment by dprothero** [comment]
@gasman When do you think we might be able to expect some feedback? Is there something we can do with the PR to make your life easier?

**Comment by gasman** [comment]
Hi @smendes - please can you add a section to https://github.com/wagtail/wagtail/blob/master/docs/reference/contrib/table_block.rst detailing how a developer should enable this?

**Comment by dprothero** [comment]
@gasman How do the docs look?

**Comment by gasman** [comment]
Merged in 51d8cac6f4f28c1b69894303122e9ff68edb12e7 + parents - thanks @smendes!

Have just made one addition in 722cd8be100f2915d76f07b14c0ce689a2fb0356 - to specify the expected HTML output directly in tests, since it doesn't really make sense to check the output against the output of another function performing the same job. (Not an issue with the current PR - the existing tests were doing it too.)

(Also, as a memo for future reference - I wasn't able to confirm that the `language` parameter is doing the right thing, as it didn't appear to have any effect on the context menu, before or after applying this PR. However, I confirmed that the Django language setting _is_ being passed on in that parameter, in the correct format according to https://handsontable.com/docs/6.2.2/Options.html#language.)

**Pull request closed without merging**
