### PR TITLE
Remove unnecessary DOM `Range` polyfill

### PR DESCRIPTION
**Pull request by lb-**
- Remove DOM Range polyfill provided by https://developer.mozilla.org/en-US/docs/Web/API/Range
- All Wagtail supported browsers, as of a few years ago, have built in support for `document.createRange`, see https://developer.mozilla.org/en-US/docs/Web/API/Range & https://caniuse.com/?search=range (even IE9 had this)
- Further progress for https://github.com/wagtail/wagtail/issues/2936

## Additional details

- Polyfill was brought in from original verdant rename.migration 77275e510b5910d1f4b52284c2d5d1812e58f25c
- It has had one update since then (7 years ago) fa97e96cda6a2f758a8f3c6f13e46efe4381d9e7
- jQuery still uses this browser API (`document.createRange`) but this is now provided by browsers
- Polyfill included some non-standard spec items such as `compareNode` but this does not appear to be used by jQuery at all
- Today I learned that DOM Range exists, nice to know we can save a few KB for our admin users.

## Testing

- Poke around the admin, jQuery uses this so anything to do with choosers, expanding formsets, privacy switch, bulk uploads would break if the DOM API was not present.

### CODE REVIEW

**Comment by gasman** [comment]
Looks like this was nicely timed - https://github.com/timdown/rangy/discussions/487 :-)

It seems this was a dependency of hallo.js, and is still referenced in the wagtail-hallo codebase: https://github.com/search?q=repo%3Awagtail-nest%2Fwagtail-hallo%20rangy&type=code. If we still care about the wagtail-hallo package (cc @cnk...) then we should be ready to address that, either by bundling rangy with the package or updating it to use the real Range API. We should also add a "changes to undocumented internals" release note in case any other third-party code is depending on it.

**Comment by lb-** [comment]
Good find @gasman  - I have rebased and added an upgrade consideration.

**Comment by gasman** [comment]
Thanks @lb-! Merged in cae322971649842c4865d9ac213c1acb2a1111e8 (with some rewording of the release note).

**Comment by lb-** [comment]
Thanks, looks good.

**Pull request closed without merging**
