### PR TITLE
Upgrade Draftail to v1.2.1. Fix #4985, adds more Markdown shortcuts

### LINKED ISSUE #4985: Copied content from Word Doc crashes Draftail/Wagtail
### Issue Summary

See https://github.com/springload/draftail/issues/179 by @xfxf, and https://github.com/thibaudcolas/draftjs-filters/issues/27. Opening this here as well so more people are aware of the problem.

> Copying and pasting the attached document (at least using Word for Mac version 16.15, but am fairly sure will do using Word for Windows too) into Draftail or Wagtail causes the editor to crash: "Oops. The editor just crashed." or "The editor just crashed. Content has been reset to the last saved version.".

> This is reproducible in the latest version of Wagtail, as well as the editor at https://www.draftail.org/

> I assume there is a wonky character or element here which Draftail/Draft.js isn't handling properly related to the anchored image (my expectation is Draftail/Wagtail should ignore the image, as it normally does), but copying the image only doesn't seem to make the editor crash, only when the text and image is copied in.

[draftail-crash-elon-musk-article.docx](https://github.com/wagtail/wagtail/files/2746394/draftail-crash-elon-musk-article.docx)

### Steps to Reproduce

1. Open the input document linked above with Word (might also work with other word processors).
2. Copy the content around the image
3. Paste in the editor

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The editor shouldn't crash, instead it should insert the pasted content minus the image.

### Technical details

Stack trace:

```
index.js:3680 TypeError: Cannot read property 'getInlineStyleAt' of undefined
    at EditorState.js:517
    at e.getCurrentInlineStyle (EditorState.js:197)
    at t.value (DraftailEditor.js:594)
    at ro (react-dom.production.min.js:163)
    at oo (react-dom.production.min.js:162)
    at uo (react-dom.production.min.js:171)
    at qo (react-dom.production.min.js:202)
    at Wo (react-dom.production.min.js:203)
    at Mr (react-dom.production.min.js:218)
    at Ar (react-dom.production.min.js:217)
    at Br (react-dom.production.min.js:232)
    at Mn (react-dom.production.min.js:85)
    at HTMLDocument.a (index.js:3221)
```

### PR DESCRIPTION
**Pull request by thibaudcolas**
This includes:

- [v1.0.0](https://github.com/springload/draftail/releases/tag/v1.0.0) (identical to v0.17.2)
- [v1.1.0](https://github.com/springload/draftail/releases/tag/v1.1.0) (contains fix for #4985)
- [v1.2.0](https://github.com/springload/draftail/releases/tag/v1.2.0)
- [v1.2.1](https://github.com/springload/draftail/releases/tag/v1.2.0) (patch for v1.2.0 regression)

Here is the combined CHANGELOG for what's relevant to Wagtail:

## Bug fixes

- #4985 – Prevent crash when filtering pasted content whose last block is to be removed (e.g. unsupported image) ([#179](https://github.com/springload/draftail/issues/179)).
- Stop unnecessarily calling `onSave` in the editor’s `onBlur` ([#173](https://github.com/springload/draftail/issues/173)).
- Prevent crash in `DraftUtils.getEntitySelection`, when the provided entity key isn't valid (undefined, missing) ([#168](https://github.com/springload/draftail/pull/168)).
- Fix entity removal and editing not doing anything when the selection is backwards (right to left) ([#168](https://github.com/springload/draftail/pull/168)).
- Prevent the editor from crashing when copy-paste filtering removes all of its content (https://github.com/thibaudcolas/draftjs-filters/commit/652750f)

Out of all of these the ones that aren't complete fringe cases are #4985, and "fix entity removal when selection is backwards".

## New features

- Add support for Markdown shortcuts for inline styles, e.g. `**` for bold, `_` for italic, etc ([#134](https://github.com/springload/draftail/issues/134), [#187](https://github.com/springload/draftail/pull/187)). View the full list of [keyboard shortcuts](https://www.draftail.org/docs/keyboard-shortcuts).

## New APIs

- Add [`onFocus`](https://www.draftail.org/docs/api#managing-focus) and [`onBlur`](https://www.draftail.org/docs/api#managing-focus) props to use callbacks on those events. This can be useful for [form validation](https://www.draftail.org/docs/next/form-validation). [#170](https://github.com/springload/draftail/issues/170), [#174](https://github.com/springload/draftail/pull/174), thanks to [@TheSpicyMeatball](https://github.com/TheSpicyMeatball).
- Add [`plugins`](https://www.draftail.org/docs/plugins) API to support extensions of the editor using the [draft-js-plugins](https://github.com/draft-js-plugins/draft-js-plugins) architecture ([#83](https://github.com/springload/draftail/issues/83), [#171](https://github.com/springload/draftail/pull/171)).
- Add ability to disable or customise the editor toolbar with [`topToolbar`](https://www.draftail.org/docs/customising-toolbars).
- Add ability to add a toolbar below the editor with [`bottomToolbar`](https://www.draftail.org/docs/customising-toolbars).
- Add data reset parameter to `DraftUtils.resetBlockWithType()`.
- Enable list continuation on Enter for custom `*-list-item` blocks. All that’s required is for the block type to end with `-list-item`.

None of those API additions will be usable within Wagtail (at least without hacks) until corresponding rich text features APIs are built to allow their configuration. The last 2 additions would already be usable but they would only be useful when leveraging the other APIs.

---

* [x] Do the tests still pass? (http://docs.wagtail.io/en/latest/contributing/developing.html#testing)
* ~[ ] Does the code comply with the style guide? (Run `make lint` from the Wagtail root)~
* ~[ ] For Python changes: Have you added tests to cover the new/fixed behaviour?~
* [x] For front-end changes: Did you test on all of Wagtail’s supported browsers? See below. All but mobile browsers
* ~[ ] For new features: Has the documentation been updated accordingly?~

- Chrome	Desktop	72 macOS 10.14.1
- Chrome	Desktop	71 Windows 10
- IE	Desktop	11
- MS Edge	Desktop	18
- MS Edge	Desktop	17
- Firefox	Desktop	65 macOS 10.14.1
- Firefox ESR	Desktop	60 Windows 10
- Safari	macOS	12.0.1
- Safari	macOS	11.1
- Safari	iOS	12
- Safari	iOS	11   
- Chrome	Android	68

### CODE REVIEW

**Comment by thibaudcolas** [comment]
While doing further testing I spotted a regression in how keyboard shortcuts are enabled 😑 I’ll publish v1.2.1 and update the PR shortly.

**Comment by thibaudcolas** [comment]
Ok, the regression with bold/italic/code/underline being always available as keyboard shortcuts should be fixed, and I finished testing on mobile devices. @jonnyscholes @xfxf please go ahead if you can have a look at this and test it a bit.

Beyond the usual manual smoke testing, the interesting bits to test would be:

- #4985 – Prevent crash when filtering pasted content whose last block is to be removed (e.g. unsupported image) ([#179](https://github.com/springload/draftail/issues/179)).
- Fix entity removal and editing not doing anything when the selection is backwards (right to left) ([#168](https://github.com/springload/draftail/pull/168)).
- Add support for Markdown shortcuts for inline styles, e.g. `**` for bold, `_` for italic, etc ([#134](https://github.com/springload/draftail/issues/134), [#187](https://github.com/springload/draftail/pull/187)). View the full list of [keyboard shortcuts](https://www.draftail.org/docs/keyboard-shortcuts).

**Comment by jonnyscholes** [comment]
Tested the above in Chrome on MacOS. All 3 of the referenced issues seem to be resolved/completed. One note about bold/italic shortcuts is they only worked for me if I didnt end my text in a space. eg `**asdf**` worked but `**asdf **` did not. Is that a known limitation @thibaudcolas?

**Comment by thibaudcolas** [comment]
@jonnyscholes 👌 

For the Markdown, yes, this is done on purpose. I tried to find a balance between too eagerly matching patterns that people didn't mean to be Markdown, and not matching things that are valid Markdown but could also be something else. The end result is inspired by [Dropbox Paper](https://paper.dropbox.com/), which has a similar behavior for whitespace.

Here is the magical regex: https://regexper.com/#%28%5Cs%7C%5E%29__%28%5B%5E%5Cs_%5D%7B1%2C2%7D%7C%5B%5E%5Cs_%5D.%2B%5B%5E%5Cs_%5D%29__%24

This is applied to text from the beginning of the block that has focus, to where the cursor is, including the character that's typed when triggering the matching. 

- Relevant code: https://github.com/springload/draftail/blob/d90f9e6bb88c0100e8b2e80a178bdd8ad70af7cc/lib/api/constants.js#L185-L192.
- Corresponding test suite: https://github.com/springload/draftail/blob/d90f9e6bb88c0100e8b2e80a178bdd8ad70af7cc/lib/api/behavior.test.js#L498-L516.

**Comment by jonnyscholes** [comment]
Cool - thanks for the links @thibaudcolas. React storybook is brilliant!

**Comment by thibaudcolas** [comment]
🙂 love Storybook as well! It's been a real time saver.

I've done one more round of testing and all seems ok, will now proceed to merge this.

**Pull request merged**
