### PR TITLE
Display data for Twitter embed blocks

### PR DESCRIPTION
**Pull request by PaarthAgarwal**
Added display data for Twitter embed blocks and tried adding some tests as mentioned by @thibaudcolas.
Build on top of #5545.
Writing tests for the first time so any help or suggestion will be appreciated. Addresses #5176.

### CODE REVIEW

**Comment by lb-** [comment]
May also relate to https://github.com/wagtail/wagtail/issues/1910

**Comment by lb-** [comment]
@PaarthAgarwal  this has been flagged as needs review, someone will get to this soon, I am not too familiar with this code so will remove myself as a requested reviewer.

If you do get the chance, can you rebase on `main` - looks like there are some conflicts.

**Comment by PaarthAgarwal** [comment]
Sure. I'll rebase.

**Review by thibaudcolas — APPROVED** [review]
Looking spot on except for the test cases! The changes are minor enough I will make them as part of merging this.

**Pull request merged**
