### PR TITLE
Stop private pages from breaking display of snippets in moderation dashboard

### LINKED ISSUE #10819: Moderation panel on admin dashboard fails when it contains both snippets and private pages
### Issue Summary

The "Awaiting your review" panel on the admin homepage dashboard breaks with the error "Foo object has no attribute 'path'" when the items awaiting moderation include both a snippet and a private page.

### Steps to Reproduce

1. From a clean bakerydemo installation, log in to admin and go to http://localhost:8000/admin/pages/62/edit/
2. From the Status sidebar, change privacy to "Private, accessible to logged-in users"
3. From the footer menu, select "Submit to Moderators approval"
4. Go to http://localhost:8000/admin/snippets/base/person/edit/4/
5. From the footer menu, select "Submit to Moderators approval"
6. Go to http://localhost:8000/admin/ - receive the error:

AttributeError at /admin/
'Person' object has no attribute 'path'

Traceback:

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/admin/

Django Version: 4.0.10
Python Version: 3.11.1
Installed Applications:
['bakerydemo.base',
 'bakerydemo.blog',
 'bakerydemo.breads',
 'bakerydemo.locations',
 'bakerydemo.recipes',
 'bakerydemo.search',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.api.v2',
 'wagtail.locales',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.contrib.routable_page',
 'wagtail.contrib.table_block',
 'wagtail.contrib.typed_table_block',
 'wagtail.contrib.modeladmin',
 'wagtail.contrib.search_promotions',
 'wagtail.contrib.settings',
 'wagtail.contrib.simple_translation',
 'wagtail.contrib.styleguide',
 'wagtail',
 'rest_framework',
 'modelcluster',
 'taggit',
 'wagtailfontawesomesvg',
 'debug_toolbar',
 'django_extensions',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']


Template error:
In template /Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/admin/templates/wagtailadmin/pages/listing/_privacy_indicator.html, error at line 9
   'Person' object has no attribute 'path'
   1 : {% load i18n %}
   2 : {% load wagtailadmin_tags %}
   3 : 
   4 : {% comment %}
   5 :     Expects a variable 'page', a page object.
   6 :     Tests whether that page is protected from public view, and if so, outputs a 'protected' icon.
   7 : {% endcomment %}
   8 : 
   9 :  {% test_page_is_public page as is_public %} 
   10 : {% if not is_public %}
   11 :     <span
   12 :         class="indicator privacy-indicator"
   13 :         title="{% trans "This page is protected from public view" %}"
   14 :     >
   15 :         {% icon name="no-view" classname="initial" %}
   16 :     </span>
   17 : {% endif %}
   18 : 

Traceback (most recent call last):
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/admin/auth.py", line 184, in overridden_render
    return render()
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/library.py", line 239, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/admin/templatetags/wagtailadmin_tags.py", line 992, in component
    return obj.render_html(context)
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/admin/ui/components.py", line 22, in render_html
    return template.render(context_data)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/admin/templatetags/wagtailadmin_tags.py", line 1064, in render
    children = self.nodelist.render(context) if self.nodelist else ""
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/defaulttags.py", line 541, in render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/template/library.py", line 239, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/admin/templatetags/wagtailadmin_tags.py", line 270, in test_page_is_public
    is_private = any(
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/admin/templatetags/wagtailadmin_tags.py", line 271, in <genexpr>
    page.path.startswith(restricted_path)

Exception Type: AttributeError at /admin/
Exception Value: 'Person' object has no attribute 'path'
```

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11.1
-   Django version: 4.0.10
-   Wagtail version: main (564b52188d721ac59ad0d374124b98fda6f8da70)

### PR DESCRIPTION
**Pull request by gasman**
Fixes #10819

### CODE REVIEW

**Review by laymonage — APPROVED** [review]
Can confirm this fixes the issue. Thanks!

**Comment by lb-** [comment]
Can I merge this in or should we wait for https://github.com/wagtail/wagtail/pull/10823

Additionally, do we want this in the 5.1 branch ?

**Comment by gasman** [comment]
@lb- Yep, this can be merged in now - and yes, I think this is a candidate for the 5.1 branch too.

**Comment by lb-** [comment]
Cherry picked to 5.1  8e495b2b8a725a4a0b8f7f525e94484ff93890e7

**Pull request merged**
