### PR TITLE
Keep applied filters when downloading form submissions

### PR DESCRIPTION
**Pull request by suyash5053**
This PR solves issue #10101  , where I Made use of the `xlsx_export_url` and the `csv_export_url` instead of hardcoding the urls in the template, and added test cases in the test block `TestFormsSubmissionsList`, 
with all the help provided by @laymonage and @lb-

### CODE REVIEW

**Comment by lb-** [comment]
@suyash5053 just a tip for future, please try to avoid creating new PRs for the same issue. All the previous comments are harder to find if you do this, and historic reviews are harder to read through. 

Thanks for addressing the concerns raised on the other PRs though. 

- https://github.com/wagtail/wagtail/pull/10122
-  https://github.com/wagtail/wagtail/pull/10161
- https://github.com/wagtail/wagtail/pull/10162

**Comment by suyash5053** [comment]
@lb- @laymonage I'm sorry for creating different PR's for the same issue, I assure you this would not take place in future. I

**Comment by lb-** [comment]
It's all good - there is a lot to learn. We have done our best to write about everything in this draft guide. Do have a read in full if you haven't already. https://github.com/wagtail/wagtail/issues/10070

**Comment by suyash5053** [comment]
@laymonage I dont know why the test case is failing, some parental key assertion error is taking place, would be very greatful if you help me out in solving this.

**Comment by laymonage** [comment]
@suyash5053 it's OK, the tests only fail when they're run against Django's `main` branch. It's not related to the changes in this PR. I've created a separate issue as #10200.

**Review by laymonage — APPROVED** [review]

**Comment by laymonage** [comment]
Thanks!

It looks good to me so I've merged it, hope that's OK with you @lb-.

**Comment by lb-** [comment]
That's always ok @laymonage - thanks for reviewing and merging.

And thanks @suyash5053 you got there! It's a bit of a rough learning curve I know but well done.

**Pull request merged**
