### PR TITLE
Added comedy 404 template and test URL

### PR DESCRIPTION
**Pull request by davecranwell**
I'm unclear what should be done to make this actually work, though.

### CODE REVIEW

**Comment by kaedroho** [comment]
Nice one @davecranwell!

I think it would be useful if we could have the left-hand menu on this page too

**Comment by kaedroho** [comment]
I've added some code to hook this in here: https://github.com/kaedroho/wagtail/commits/404

**Comment by SalahAdDin** [comment]
:+1:

**Comment by gasman** [comment]
Needs admin menu adding.

**Comment by gasman** [comment]
Superseded by #3705

**Pull request closed without merging**
