### PR TITLE
Add Sphinx Wagtail Theme

### PR DESCRIPTION
**Pull request by allcaps**
This PR adds [Sphinx Wagtail Theme](https://github.com/wagtail/sphinx_wagtail_theme).

Preview: https://wagtail--6930.org.readthedocs.build/en/6930/index.html

- The theme is pinned in setup.py AND docs/requirements.txt (RTD doesn't read the setup.py)
- The title reads 'Wagtail Documentation' instead of 'Wagtail'
- Copyright is 'YYYY, Torchbox and contributors' instead of 'YYYY, Torchbox' (like the licence)
- Searchbox template is updated to reflect the theme (Bootstrap) markup
- Sphinx disables the TOC on pages that have a single heading. We added `:hidetoc: 1` to disable the TOC on pages with multiple headings, but where a TOC is still redundant.

Screenshot 2021-04-18 at 22 07 06

Most work is done on the [theme](https://github.com/wagtail/sphinx_wagtail_theme) and according to the [design prototype](https://www.figma.com/proto/hFjWqQeEjGd8NtTsEHcc4i/Wagtail-Documentation-(wagtail.io)?node-id=1%3A2&viewport=983%2C953%2C1&scaling=min-zoom&hide-ui=1)

The new theme:
- is based on Bootstrap
- is responsive
- takes 100% of the viewport
- has a table of contents
- does not reload the page when open/close main menu items

I expect the commits to be squashed on merge.

* Do the tests still pass? (https://docs.wagtail.io/en/latest/contributing/developing.html#testing) YES
* Does the code comply with the style guide? (Run `make lint` from the Wagtail root) YES
* For Python changes: Have you added tests to cover the new/fixed behaviour? N/A
* For front-end changes: Did you test on all of Wagtail’s supported browsers? **Please list the exact versions you tested**.
- Edge 89
- IE 11 ([search doesn't work](https://discourse.algolia.com/t/algolia-instant-search-v4-5-0-not-working-in-ie11/10492)) Note [the latest docs](https://docs.wagtail.io/en/latest/search.html?q=foo#) also doesn't work on IE11.
- Chrome  90.0.4430.72 OSX
- FireFox 86 OSX
- FireFox 87.0 OSX
- IPad Pro 12.9
* For new features: Has the documentation been updated accordingly? N/A

### CODE REVIEW

**Comment by Stormheg** [comment]
https://wagtail--6930.org.readthedocs.build/en/6930/index.html

**Comment by allcaps** [comment]
[ ] Fix override search
[ ] Drop banner.js

**Comment by tbrlpld** [comment]
The version picker at the bottom appears broken. Maybe some of the removed theme css was injected into it?

**Comment by tbrlpld** [comment]
- [ ] Update project `name` in `conf.py`

**Review by tbrlpld — APPROVED** [review]
LGTM 👍

**Review by Stormheg — APPROVED** [review]
One small nitpick, but apart from that this looks very complete to me! :smile: 

Nitpick: I think we should make it more clear that the version in the footer is the version of sphinx_wagtail_theme. Not the version of Wagtail itself.
image

**Comment by tbrlpld** [comment]
> One small nitpick, but apart from that this looks very complete to me! 😄
> 
> Nitpick: I think we should make it more clear that the version in the footer is the version of sphinx_wagtail_theme. Not the version of Wagtail itself.

Hm, I feed like a reference to the theme in the docs would be odd. I think we are better off just removing that and only showing the project name or nothing in the footer.

**Comment by Stormheg** [comment]
@tbrlpld I think a reference to the version of the documentation is useful for us (wagtail developers) in case we need to publish a new version of the theme.

**Comment by allcaps** [comment]
I changed the line `Wagtail Documentation 5.0.0` into `Sphinx Wagtail Theme 5.0.1` and set display none.

Updated this pr.

**Review by thibaudcolas — COMMENTED** [review]
Things that stand out to me and I think are mandatory to fix:

- The URL to the "Edit on GitHub" link is wrong.

Things I’d prefer to see fixed:

- In the search, I have additional (browser?) suggestions displaying underneath the Algolia dropdown. If I navigate search suggestions with keyboard keys, that will trigger the native search form instead of going to the Algolia result I selected.
- Also in the search, if pressing "Enter" on the search field to get the full list of results in the separate template, there are specific queries that break the page. For example "testintegerblock". Potentially related, I can see this still queries RTD’s search backend as well as Algolia.
- There is a hidden link without text in the header 

Nice to have:

- I don’t think we should have a link / version number for the docs theme in the footer.
- On mobile viewports, placement of the "hamburger" menu toggle button could be better
- Sidebar’s Toctree "Expand" buttons are impossible to use with a keyboard

**Comment by thibaudcolas** [comment]
Re-reviewing this I can confirm there is something funny going on with the search. It looks like our custom Algolia search isn’t completely overriding the built-in one, which causes both search issues I reported above. I think this should be fixed before we merge. Other than that, the "Edit on GitHub" link should be easy to change but I can’t figure out where to set it (cc @allcaps).

Theme default we want to override:

```
github_url = https://github.com/wagtail/sphinx_wagtail_theme/blob/main/docs/
```

**Review by allcaps — COMMENTED** [review]
LGTM, 

we should squash all commits on merge.

**Comment by thibaudcolas** [comment]
@allcaps with the latest version there are two issues:

- The "expand" buttons are gone from the sidebar
- The version picker has also disappeared

**Comment by allcaps** [comment]
> * The "expand" buttons are gone from the sidebar
> * The version picker has also disappeared

@thibaudcolas Speed over quality. Sorry! Updated the theme and fixed the issue.

**Comment by Stormheg** [comment]
Looks like all feedback has been implemented. I'm going to squash and merge this now.

**Pull request merged**
