### PR TITLE
Solevd #12484

### PR DESCRIPTION
**Pull request by ashish-nagmoti**
added docs download functionality in readdocs.yml file

### CODE REVIEW

**Comment by lb-** [comment]
Thanks @ashish-nagmoti however, there is already a PR up for this.

https://github.com/wagtail/wagtail/pull/12490

**Comment by ashish-nagmoti** [comment]
Yes yes 
I was trying to solve problem by myself as I can't run docs viewer in local env ,I had to commit every single time, 
Sorry for any convience.
What do you think for building docs viewer locally for developers?

**Comment by laymonage** [comment]
@ashish-nagmoti You can follow https://docs.wagtail.org/en/stable/contributing/developing.html#compiling-the-documentation, although the local build for non-HTML output is untested and undocumented yet.

**Comment by ashish-nagmoti** [comment]
Ohk 
Thanks ,it wouldn't be that hard I guess ,if you think it's feasible,should we raise a issue for it?

**Comment by laymonage** [comment]
Feel free to give it a go and report your findings. Thanks!

**Pull request closed without merging**
