### PR TITLE
Resolve comment rendering escaped strings in email notification

### LINKED ISSUE #11143: txt comment email notifications rendering escaped strings into email template.
### Issue Summary

Comment notifications sent using the updated_comments.txt template are rendering escaped comment and reply text into the email template. 

The offending code is seen here:
```
{% trans "Deleted comments:" %}{% for comment in deleted_comments %}
 - "{{ comment.text|safe }}"
{% endfor %}{% endif %}{% spaceless %}

{% endspaceless %}{% if replied_comments %}

{% trans "New replies:" %}{% for thread in replied_comments %}

  {% trans 'New replies to:' %} "{{ thread.comment.text }}"{% for reply in thread.replies %}
   - "{{ reply.text }}"{% endfor %}{% endfor %}{% endif %}
```

The bottom two lines are outputting reply.text and thread.comment.text without using the "safe" template filter resulting in the content being escaped for display to the user. You'll note that other output in the file does use the "safe" template filter, as seen above in the "Delete comments" code snippet.

### Steps to Reproduce

1. Enabled comment notifications on a page.
2. As one user make a comment. Be sure to include characters that would normally be escaped. e.g. < > '
3. As a second user, reply to that comment. Be sure to include characters that would normally be escaped. e.g. < > '
4. Inspect the sent email and see that these characters are escaped for presentation to the user.

### Technical details

Found on 
- Wagtail version: 4.1.9 - appears, from the code, to be a problem on latest Wagtail versions also.

### PR DESCRIPTION
**Pull request by rohitsrma**
Fixes #11143 Resolve comment rendering escaped some characters in email notification by updating the updated_comments.txt template.

**Output in Terminal After Changes**

```
Hello rohit,

Testuser has updated comments on "Bread and Circuses".    

New replies:

  New replies to: "good job"
   - "<>'"

You can edit the page here: http://localhost:8000/admin/pages/68/edit/

Edit your notification preferences here: http://localhost:8000/admin/account/#tab-notifications
```

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by lb-** [comment]
Thankyou. I think something like this should also have a unit test added, would you be ok for that @rohitsrma ?

**Comment by rohitsrma** [comment]
@lb- Sure, could you please let me know in which file should I add unit tests?

**Comment by lb-** [comment]
Haha. I know you'd ask that. 

I'm not.100% sure - maybe others on the core team will chime in. 

Maybe https://github.com/wagtail/wagtail/blob/main/wagtail/tests/test_comments.py - might need a new class added there. 

You can see an example of a test that checks the contents of an outgoing (outbox) notification here. https://github.com/wagtail/wagtail/blob/59b07f777f3468b5c4413c2e60a60af15587c5bb/wagtail/admin/tests/pages/test_moderation.py#L314 (moderation is being removed but it's still a good reference for checking the outbox.

**Comment by rohitsrma** [comment]
@lb- I have made an effort to write unit tests for creating a comment and for adding a reply to the comment. However, I faced an issue while attempting to verify the email notification functionality (not getting anything in mail.outbox). I have included the code for the email notification test below:

```
def test_email_notification_on_reply(self):
        revision = self.page.get_latest_revision()


        # Create the main comment with the main user
        comment = self.create_comment(revision, self.moderator_user)
        self.assertIsNotNone(comment, "Comment not created successfully")
        self.assertEqual(Comment.objects.count(), 1)  # Check if the comment is created in the database


        # Add a reply to the previous comment with a different user
        reply_comment = self.create_comment(revision, self.reply_user, parent_comment=comment)


        # Check for the email notification
        self.assertEqual(len(mail.outbox), 1)  # Check if one email is sent
        self.assertEqual(mail.outbox[0].to, ["moderator@example.com"])  # Check if the email is sent to the correct recipient
        self.assertIn(comment, mail.outbox[0].subject)  # Check if the subject contains the comment text
```

I would greatly appreciate any suggestions or insights you may have to help me resolve this issue.

**Review by lb- — APPROVED** [review]
@rohitsrma as this is a very useful fix and does the job (screenshots below) I think we are best to get this into the code and I will also include in 5.2.1 as a cherry pick.

I did not realise tests for this would be so complex, my apologies, I also have seen that we do not really test for this in other notifications.

As such I will merge this PR in without the tests and then raise a new issue for someone to help get some solid starting tests in place for these text notifications.

Thank you for pursuing this and if you are up for that future issue, it would be great to get your help.


**Before**

Screenshot 2023-11-07 at 8 35 53 am

**After**

Screenshot 2023-11-07 at 8 36 24 am

**Comment by lb-** [comment]
Merged in via 42eb8ad82f6273a7670e29a96fe2048e6f475866 (5.2) and 6ef8da04eb9141d8bc43bcbbce65d9d80f4dac2d (main)

**Comment by lb-** [comment]
https://github.com/wagtail/wagtail/issues/11192 raised for better testing of non-escaping (or investigating a different approach).

**Comment by rohitsrma** [comment]
Thanks @lb- I'll do some research and try to work on adding unit tests for this!

**Pull request closed without merging**
