### PR TITLE
Add labels to snippet checkboxes for accessibility (#5328)

### PR DESCRIPTION
**Pull request by martey**
Add labels for checkboxes on snippet list page (including "select all" checkbox) on snippet list page for screen readers.

--- 

* Do the tests still pass? *yes*
* Does the code comply with the style guide? (Run `make lint` from the Wagtail root) *yes*
* For Python changes: Have you added tests to cover the new/fixed behaviour? *n/a*
* For front-end changes: Did you test on all of Wagtail’s supported browsers? **Please list the exact versions you tested**.
    - Google Chrome 75 w/ [ChromeVox extension](https://chrome.google.com/webstore/detail/chromevox/kgejglhpjiefppelpmljglcjbhoiplfn)
    - I would love it if others (especially people on Windows or OS X) could help me test this.

* For new features: Has the documentation been updated accordingly? *n/a*

### CODE REVIEW

**Comment by thibaudcolas** [comment]
Note: this PR fixes #5328.

**Comment by martey** [comment]
@thibaudcolas I've updated this so that the "select all" checkbox's label is "select all <snippet types>". I've also updated the CHANGELOG and release notes for 2.7.

**Comment by thibaudcolas** [comment]
Thank you 🙂 I’ll try to review/test this as soon as I can. For the CHANGELOG / release notes changes – this is something we usually only do while merging pull requests, because it creates lots of conflicts if done prior to that. If you have the chance to remove those changes from the PR that would help, otherwise I’ll take care of rebasing this once I get to it.

**Comment by martey** [comment]
Sorry about that - it looks like I misread the contributing guidelines and thought that modifying the changelog and release notes was necessary when sending in a new pull request. I've removed them, so this shouldn't have merge conflicts anymore.

**Comment by thibaudcolas** [comment]
That’s alright! It’s quite common for people to do this, so I’ve tweaked this documentation slightly (#5483) to hopefully make it clearer in the future. Thank you for taking the time to remove those changes 🙂.

**Comment by thibaudcolas** [comment]
Thank you @martey 🙂I’m really pleased this form is now somewhat usable! This will be released in the next released, Wagtail 2.7.

**Pull request merged**
