### PR TITLE
Bulk actions - action bar UI fixes

### PR DESCRIPTION
**Pull request by KIRA009**
This pr brings the action bar in bulk actions closer to the actual design

## Design
image

## Implementation
image

### CODE REVIEW

**Comment by zerolab** [comment]
Hey @KIRA009,

this certainly needs more work:

1. left margin should ~80px to align with the titles in the listing for pages
2. `.footer_container` needs less padding (~1.25em all around. and `4px 4px 0 0` for border radius)
3. the buttons do not have borders in the designs. at the moment there's a slight hint of the border but it gets lost in the dark bar background

**Comment by zerolab** [comment]
@KIRA009 this is still marked as draft. Is it ready for re-review?

**Comment by KIRA009** [comment]
Yes @zerolab

**Review by Stormheg — COMMENTED** [review]
This looks good @KIRA009!

The amount of whitespace is like the designs, well done 👍 

Here are some minor nitpicks I'd like to address before merging.

- Buttons labels have `font-weight: 700`. The design uses `font-weight: 600` here - meaning labels appear slightly too thick in the current implementation. _Can we reduce the font weight?_
- Observation: the design has the number of objects (e.g. 'All 11 pages') highlighted by making it bold (`font-weight: 700`). _Is there a reason this isn't implemented?_
- The 'more' button has a gray border - unlike the other buttons which have no border. _Can we remove the border?_
- Observation: the 'select all X pages in listing' link (only appears on paginated listings) doesn't mention the total number of objects. _Is there a reason the number of objects is missing?_

**Comment by KIRA009** [comment]
@Stormheg 

> Observation: the design has the number of objects (e.g. 'All 11 pages') highlighted by making it bold (font-weight: 700). Is there a reason this isn't implemented?

The string is part of a whole sentence, so making some words bold would require putting those words in a <span> . We have to fetch the two phrases 2 pages and on this screen selected as separate strings, they’ll need to be translated separately as well. I figured it was too much complexity for a simple effect. That is the reason I omitted that part. Any thoughts @jacobtoppm @zerolab ?

> Observation: the 'select all X pages in listing' link (only appears on paginated listings) doesn't mention the total number of objects. Is there a reason the number of objects is missing?

I believe we decided to remove the number a while back, probably because of translation inconsistencies, and , as far as I remember

**Review by Stormheg — APPROVED** [review]
LGTM - thanks Shohan! 💯

**Pull request merged**
