### PR TITLE
Added multiselect form field

### PR DESCRIPTION
**Pull request by dwasyl**
This is just a simple PR to add an additional form field in response to issue #2960 (that I opened). Only adds a few lines of code and the tests seem to run fine.

### CODE REVIEW

**Comment by dwasyl** [comment]
Whoops - didn't even think about the migration file. Forgot Django even generated them for changes to choices. Let me see if I can generate a quick one.

**Comment by dwasyl** [comment]
Spent some time looking at this and the change is to the definition of the `choices` field on the field of an Abstract model so Django won't generate a migration for it. It's needed to run the checks though, so not sure what I can do to get it to pass.

**Comment by gasman** [comment]
Hi @dwasyl - the missing migration will probably be on one of the models in the test apps. You should be able to generate it by running `django-admin.py makemigrations --settings=wagtail.tests.settings` from the Wagtail root.

**Comment by dwasyl** [comment]
Thanks @gasman, that did the trick. First time doing this, seemed all too easy at first.

**Comment by gasman** [comment]
Sorry for the delay in reviewing - now merged in 240fa9153b86e641497a521ee135b28dfcf1a15b. Thanks @dwasyl!

**Comment by dwasyl** [comment]
Fantastic, thanks for getting this in @gasman

**Pull request closed without merging**
