### PR TITLE
Updated 'integrating_into_django.md' file

### LINKED ISSUE #10741: WAGTAILADMIN_BASE_URL should be mentioned in "Integrating Wagtail" docs
### Pertinent section of the Wagtail docs

The documentation on [WAGTAILADMIN_BASE_URL](https://docs.wagtail.org/en/v5.1/reference/settings.html#wagtailadmin-base-url) says (emphasis mine):

> This is the base URL used by the Wagtail admin site. It is typically used for generating URLs to include in notification emails.
> **If this setting is not present, Wagtail will try to fall back to request.site.root_url or to the request’s host name.**

Yet if you do not configure it, Wagtail will issue a warning:

`(wagtailadmin.W003) The WAGTAILADMIN_BASE_URL setting is not defined` 

https://github.com/wagtail/wagtail/blob/801eccc9304561ffe974b6e16bd977198910726d/wagtail/admin/checks.py#L175-L183

In addition, the ["Settings" section of "Integrating Wagtail into a Django project"](https://docs.wagtail.org/en/v5.1/getting_started/integrating_into_django.html#settings), doesn't mention this setting.

### Details

If`WAGTAILADMIN_BASE_URL` should always be configured, then the docs should reflect this.

### PR DESCRIPTION
**Pull request by Shreshth-Srivastava**
Mentioned WAGTAILADMIN_BASE_URL and the warnings related to it in the 'Settings' section.

Fixes #10741

### CODE REVIEW

**Comment by lb-** [comment]
@Shreshth-Srivastava just a reminder to please avoid deleting PRs when you need to make a change. It makes it hard to track feedback and the status of the PR. Thanks so much for pursuing this fix. 

Also, can you please update the PR description to have the correct link to what you're fixing. The `...` before the `#` can be removed. 

Links to previous PRs
- https://github.com/wagtail/wagtail/pull/10756
- https://github.com/wagtail/wagtail/pull/10757

We have some Info about pull requests in our guide here https://docs.wagtail.org/en/latest/contributing/first_contribution_guide.html#submitting-a-pull-request

**Comment by Shreshth-Srivastava** [comment]
> @Shreshth-Srivastava just a reminder to please avoid deleting PRs when you need to make a change. It makes it hard to track feedback and the status of the PR. Thanks so much for pursuing this fix.
> 
> Also, can you please update the PR description to have the correct link to what you're fixing. The `...` before the `#` can be removed.
> 
> Links to previous PRs
> 
> * [Update integrating_into_django.md #10756](https://github.com/wagtail/wagtail/pull/10756)
> * [Update integrating_into_django.md #10757](https://github.com/wagtail/wagtail/pull/10757)
> 
> We have some Info about pull requests in our guide here https://docs.wagtail.org/en/latest/contributing/first_contribution_guide.html#submitting-a-pull-request

Understood

**Comment by Shreshth-Srivastava** [comment]
Do you want me to include the links to the previous PRs too in the description ?

**Comment by gasman** [comment]
Thanks @Shreshth-Srivastava! Merged in ff16cb5a3e0065a7da1824628eae64cd100ff312, with some minor edits (I don't think we need to mention the warning here).

**Pull request closed without merging**
