### PR TITLE
Add 'wagtail_update_index' as an alias for the 'update_index' command

### LINKED ISSUE #2447: Prefix management commands
The update_index management command is already clashing with haystack's.
AFAIC wagtail management commands could be prefixed with 'wt_' to prevent this in the future.

### PR DESCRIPTION
**Pull request by gasman**
Fixes #2447

### CODE REVIEW

**Comment by kaedroho** [comment]
I've just tried locally and it looks like you can have colons in command names, so ``wagtail:update_index`` should be possible. I kinda prefer the colon as a different separator makes it clear that "wagtail" is a namespace and not actually part of the command name.

**Comment by gasman** [comment]
@kaedroho Does that require putting a colon in the filename, or is there a way to set the command name in the file itself? I'd prefer to keep our filenames as "normal" as possible, given the trouble we've had with gitlab and cookiecutter's filenames with braces...

I don't see a reason to spend more time adding aliases on other commands that haven't had this issue, but I won't object if someone else wants to do it :-)

**Comment by kaedroho** [comment]
It does require adding colons into filenames, and I've just found that this will probably be an issue for Windows users as well.

**Comment by ababic** [comment]
I'm unable to run the command locally due to an issue with my `vagrant-wagtail-develop` setup (https://github.com/wagtail/vagrant-wagtail-develop/issues/22), but from a code/docs perspective, this looks spot on.

**Comment by ababic** [comment]
Okay, local issues sorted, and this is working fine for me. Merge away :)

**Comment by gasman** [comment]
Thanks @ababic! Now merged in 61e1e4c2f961d854ad8dc679f58174eacdaf940a.

**Pull request closed without merging**
