### PR TITLE
Allow spaces in tag fields

### PR DESCRIPTION
**Pull request by alexgleason**
By default, when adding tags, you can't add tags with spaces unless you explicitly surround them with "quotes". This PR just adjusts a setting on the jQuery UI tag-it library to allow for spaces by default. Tags are delimited with a comma.

### CODE REVIEW

**Comment by alexgleason** [comment]
Does anyone disagree with this or can we merge? I'm pretty sure this is a better change.

For instance, say you wrote a blog post and you want to tag it as `cool stuff`. You can't currently do that. You _can_ write `"cool stuff"` and it works, but that's a little weird that you have to write quotes, and there's no instructions for that on the tags field. You can't do it because pressing the space key advances to a new tag.

This change just lets you press the space key in a tag name. You have to press comma to advance. Which is what the instructions on the field say anyway.

**Comment by gasman** [comment]
Personally I'm not a fan of spaces in tags, and I much prefer the ability to enter a list of one-word tags quickly with space as the separator. But given previous tickets (#530, #824, #1438, #1874) I suspect I may be in the minority there, and my judgment is probably clouded by my general feeling that developers would have a much easier time dealing with tagging if everyone could just stick to lower-case URL-safe characters :-)

With that in mind, I wouldn't be too averse to changing it, although I'm wary that this might be a matter of personal preference (and if we change it, we'll just get an equal number of complaining / confused people who were silent until now because it just worked for them)...

Have you tested that this change behaves as expected when the form is saved (e.g. do the tags still show up correctly when you revisit the form)? We've had a few issues arising from our client-side (jquery.tag-it.js) and server-site (django-taggit) libraries not interacting perfectly (#824, #1970) and I'd like to be sure we're not going back to square one by making this change.

**Comment by tomdyson** [comment]
Note we already have a setting for one type of tag behaviour (case sensitivity: http://docs.wagtail.io/en/v1.3.1/advanced_topics/settings.html#case-insensitive-tags). Should space support also be configurable?

**Comment by ababic** [comment]
I'd have to agree with @alexgleason here. To me, it feels like a bug when you try to add spaces to a tag, but can't. Some terms are only relevant when the words are together, and the workaround is fiddly and easy to forget.

**Comment by alexgleason** [comment]
Hi @gasman, can we have this merged? It's needed for a current project. Thanks. :smile:

**Comment by tomdyson** [comment]
@alexgleason can you please reply to @gasman's question:

> Have you tested that this change behaves as expected when the form is saved (e.g. do the tags still show up correctly when you revisit the form)? We've had a few issues arising from our client-side (jquery.tag-it.js) and server-site (django-taggit) libraries not interacting perfectly (#824, #1970) and I'd like to be sure we're not going back to square one by making this change.

and my:

> Should space support also be configurable?

**Comment by alexgleason** [comment]
@tomdyson @gasman 

>Have you tested that this change behaves as expected when the form is saved (e.g. do the tags still show up correctly when you revisit the form)?

I did check this just now; it works perfectly fine.

>Should space support also be configurable?

I don't think so. The other taggit setting you referenced is there because of a global database inconsistency among different types of databases. In this case it is a user preference, but I think the vast majority of the time you will not want to have tags with spaces so it makes sense to make this assumption. There is also the option to use quotes to let your tags have spaces, which works fine.

**Comment by gasman** [comment]
Happy to go ahead with this change, but I think it does warrant a settings flag. Even if the new behaviour is overwhelmingly preferred, there will inevitably be at least one person for whom it's a backwards step - as we found with unicode slug support (#2937), which seems like as unopinionated a change as you can get...

(obligatory XKCD link: https://xkcd.com/1172/ :-) )

**Comment by tomdyson** [comment]
Hi @alexgleason - can you add a settings flag, as @gasman suggests above? Thanks!

**Comment by khink** [comment]
This PR is superceded by https://github.com/wagtail/wagtail/issues/3488 and can be closed.

**Pull request closed without merging**
