### PR TITLE
Use Django ORM query in Page._update_descendant_url_paths.

### PR DESCRIPTION
**Pull request by atombrella**
I'm in doubt about MSSQL, but for the other backends, it can be expressed in Django.

### CODE REVIEW

**Comment by atombrella** [comment]
In the README-file, there's no word about MSSQL. 

> Wagtail supports Django 1.8.x, 1.10.x and 1.11.x, on Python 2.7, 3.4, 3.5 and 3.6. Supported database backends are PostgreSQL, MySQL and SQLite.

**Comment by gasman** [comment]
Thanks @atombrella! There's actually a very similar PR already in the queue for reviewing: #3496, currently blocked by our lack of testing environment for MSSQL. (We don't officially support MSSQL at the moment, but we're working towards doing so, and there are several existing sites running on that setup - so we need to be careful not to break those.)

**Comment by atombrella** [comment]
An alternative could be to keep the proposed change, backed by the mssql check?

**Comment by gasman** [comment]
Addressed via #3496, with an exception added for MSSQL as you suggest. Thanks again!

**Pull request closed without merging**
