### PR TITLE
Resolve error when specifying 'slug' as a read-only field

### LINKED ISSUE #11442: Error when specifying slug as a read-only field
### Issue Summary

I had a goal, to limit the user's ability to change slug on specific pages.
However, I encountered a problem that I found quite difficult to analyze or understand how I could affect it

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Create a simple page class that inherits from wagtailcore.models.Page
3. Specify slug field as read-only field, like `promote_panels = [FieldPanel("slug", read_only=True)]`
4. Open the page for editing through the administration panel

I expected the slug field to be displayed just like any other read-only field in the admin panel, I was referring to the information from version 5.1

### Technical details

-   Python version: 3.11.7.
-   Django version: 4.2.8.
-   Wagtail version: 5.2.1.
-   Browser version: Chrome 120.

### PR DESCRIPTION
**Pull request by rohitsrma**
Fixes #11442 This PR addresses a issue where setting the 'slug' field as read-only would cause a `KeyError`. The issue is resolved by introducing a conditional check to verify the presence of the target. This modification ensures that the page no longer throws a KeyError when the 'slug' field is configured as read-only. 

### Before:

image

### After:

image

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Review by gasman — CHANGES_REQUESTED** [review]
Thanks @rohitsrma! The changes to the tests don't look right here, though: generally, there should never be any need to put conditional code inside a test, because we're always calling the application code with the same input values and should know exactly what results we're expecting to get back. So, in a piece of code like:

        if "slug" in attrs["data-w-sync-target-value"]:
            self.assertEqual(
                attrs["data-w-sync-target-value"],
                "#id_slug",
            )

you've added the `if` line because this assertion was failing - but you've chosen a condition that you know is going to be false, so this is basically the same as commenting out the assertion. And, of course, we don't want to remove assertions from tests unless we understand _why_ they're failing, and decide that they're no longer applicable.

I'm actually not sure why we're seeing a change of behaviour in the existing tests: all of these tests are testing against a form that contains a title field and a target field (such as 'slug' or 'url') - if they didn't, they would be failing with a KeyError just like the bug report in #11442 - so they should be populating the `data-w-sync-target-value` like before. The fact that these tests have started failing would suggest that there's a logic error in your bugfix that you need to investigate.

Once you've solved that, you'll need to add new tests to cover the scenario you're actually fixing: namely, a form without a `slug` field, or a read-only slug. I suggest adding two new tests that work like `test_default_title_field_panel`, but with _just_ the TitleFieldPanel:

        html = self.get_edit_handler_html(
            ObjectList([TitleFieldPanel("title")])
        )

and with a TitleFieldPanel and a read-only slug field: 

        html = self.get_edit_handler_html(
            ObjectList([TitleFieldPanel("title"), FieldPanel("slug", read_only=True)])
        )

Without the bugfix in place, these will fail with the KeyError (if I'm not mistaken) - after the bugfix, they should succeed and return an empty `data-w-sync-target-value` attribute.

**Comment by rohitsrma** [comment]
@gasman I'm really sorry for making senseless updates in tests. Also, thanks for the detailed suggestions. I've made some corrections, and now the existing tests are working fine.

As per your suggestion, I have added a test for a form without a SlugField, and it is working as expected (giving KeyError without the bugfix and returning an empty `data-w-sync-target-value` attribute with the bugfix). However, when I'm trying to add a test for the SlugField as read-only, it is giving an AttributeError.

`AttributeError: 'NoneType' object has no attribute 'slug' `

**Test:**

```
def test_form_with_readonly_slugfield(self):
        html = self.get_edit_handler_html(
            ObjectList([TitleFieldPanel("title"), FieldPanel("slug", read_only=True)])
        )

        self.assertIsNotNone(html.find(attrs={"class": "w-panel title"}))

        attrs = html.find("input").attrs
        self.assertEqual(attrs["data-w-sync-target-value"], "")
```
Without the bugfix, it gives an expected KeyError, but with the bugfix, it gives an AttributeError. I am little confused about the root cause of this error and would really appreciate your suggestions on this.

**Comment by gasman** [comment]
@rohitsrma Thanks for the updates! It looks like this is failing because read-only panels don't work correctly when `None` is passed for the instance, which is happening in `get_edit_handler_html` here. I don't think this ever happens in real-world use, because we're always retrieving the instance from the associated form (and the form will create a fresh instance if none is supplied), so this can be fixed by changing the `get_edit_handler_html` call to:

        html = self.get_edit_handler_html(
            ObjectList([TitleFieldPanel("title"), FieldPanel("slug", read_only=True)]),
            instance=EventPage()
        )

I see that in your updated version you're doing `if target in str(self.form)`. I would advise against using `str(self.form)` for this, as it returns the full HTML rendering of the form, which will contain lots of other text besides the field names that we're trying to match against. For example, this will incorrectly return True for a field named `label` (because the form HTML contains `<label>` tags. I think the code we really want here is `if target in self.form.fields` - this gives us a dictionary of the form fields, so we're directly checking if `target` matches a form field name.

**Comment by rohitsrma** [comment]
Thanks @gasman, your suggestions worked great. Now the PR is ready for your review!

**Comment by gasman** [comment]
Thanks @rohitsrma - all looks good to me! Merged in 33fbbed19da9417266fb90340724296b15061ddf.

**Comment by gasman** [comment]
Cherry-picked to 5.2.x in da31733b9389e6c22671ab9d5a781836aeec8d06, as this is definitely something we want to include in any future LTS bugfix releases.

**Pull request closed without merging**
