### PR TITLE
Adds PostgreSQL row boosting

### PR DESCRIPTION
**Pull request by BertrandBordage**
To use this, simply give a per object boost by defining a method in your model:
```python
def get_search_boost(self):
    return 5
```
Here, this multiplies by 5 the weight of this specific model in search results. So this model will almost always be first in results because that is a huge boost. Smaller boosts make a nicer compromise between relevance to the query and importance of that model.

Boost can be any float, even negative ones, but keeping it positive is better. The default boost is 1. To decrease the boost of a model, take a boost between 0 and 1.

Another more complex example:
```python
def get_search_boost(self):
    return 2 if 'wagtail' in self.title.lower() else 1
```
This gives items containing 'wagtail' in their title a boost. You can imagine any boost adjustment you want from there. For example, you can boost pages depending on their depth in the tree, in order to make categories more easy to find. Or you can boost an item depending on the number of visits it has (a number you’ll fetch from some analytics software).

Note: this pull request depends on merging #3709 first.

### CODE REVIEW

**Comment by kaedroho** [comment]
👍 on the API and implementation, just needs docs and tests.

**Comment by BertrandBordage** [comment]
Thanks @tomdyson! Just applied your suggestion.

**Comment by BertrandBordage** [comment]
This pull request is ready, but not for review.
It contains #3709 and will not pass recent tests unless I add #3951 in it as well.

So once @kaedroho confirms me that I can merge #3951 into master, I’ll make two new pull requests: one for autocomplete, and the other one for row boosting.

I also have 2 other big changes to the PostgreSQL backend that I need to add as well, including one that allows to make multi-languages search. Ideally, it would be easier for me to just make a huge pull request with everything in it, but I guess no-one else will like it ;)

**Comment by BertrandBordage** [comment]
This pull request will be created again once #4059 is merged.

**Comment by BertrandBordage** [comment]
Superseded by #4534.

**Pull request closed without merging**
