### PR TITLE
Group users list

### PR DESCRIPTION
**Pull request by karranb**
### Description
This PR implements a group user listing endpoint.

### Issue

#5801

### CODE REVIEW

**Comment by isandunk** [comment]
Thanks so much for your work on this @karranb 

I've tested this in Squash. I have a couple of suggestions from a UX point of view:

- Perhaps we could rename the button so that it is more obvious what it does? So something like "View users of this group" or "View users of <group.id/>"
- In other sections of wagtail, like Images or Documents, they have actions like this in the header (eg. In Documents, it has "Add Document"). Perhaps this button would be better situated there?

Again, thanks for you work.

**Comment by karranb** [comment]
Thanks for the review. Awesome suggestions, I'll work on them 😄

**Comment by karranb** [comment]
Hey @isandunk, I had to make a small refactor on the heading component to accept other buttons besides 'add' ones. I can implement using another approach if you find one that fits better :smile:

**Comment by isandunk** [comment]
Thanks @karranb! I think that's a great solution!

**Comment by lb-** [comment]
merged in va 7565248438337da81d2d3be5f279d5724db0fd7e

thanks again @karranb

**Pull request closed without merging**
