### PR TITLE
fixed issue Updating the `README.md` file in the default branch #7744

### PR DESCRIPTION
**Pull request by FahimFBA**
Thanks for contributing to Wagtail! 🎉

Before submitting, please review the contributor guidelines <https://docs.wagtail.io/en/latest/contributing/index.html> and check the following:

* Do the tests still pass? (https://docs.wagtail.io/en/latest/contributing/developing.html#testing) -  Not needed for the README
* Does the code comply with the style guide? (Run `make lint` from the Wagtail root) Yes
* For Python changes: Have you added tests to cover the new/fixed behaviour?  -  Not needed for the README
* For front-end changes: Did you test on all of [Wagtail’s supported environments] (https://docs.wagtail.io/en/latest/contributing/developing.html#browser-and-device-support)? -  Not needed for the README
    * **Please list the exact browser and operating system versions you tested**. Chrome and Windows 11
    * **Please list which assistive technologies you tested**.
* For new features: Has the documentation been updated accordingly? -  Not needed for the README

### CODE REVIEW

**Review by lb- — APPROVED** [review]
@FahimFBA thanks for this, we will merge this in soon.

For smaller docs/readme fixes like this we do not add a changelog but we would love to add your name to the contributors list.

I will put you down as `Fahim Bin Amin` but please advise if you want your name listed differently.

**Comment by lb-** [comment]
Merged in via 66237d09e758aa605523c6e1494ea66546c19926

**Comment by FahimFBA** [comment]
> @FahimFBA thanks for this, we will merge this in soon.
> 
> For smaller docs/readme fixes like this we do not add a changelog but we would love to add your name to the contributors list.
> 
> I will put you down as `Fahim Bin Amin` but please advise if you want your name listed differently.

Please list my name as `Md. Fahim Bin Amin` because that is my full name. Thanks!

**Comment by lb-** [comment]
@FahimFBA done - https://github.com/wagtail/wagtail/commit/75bf48d9f7cbabbada863beb700e89387da76327

**Pull request closed without merging**
