### PR TITLE
Support internationalised routes in API find html_path

### LINKED ISSUE #6679: Support internationalized routes in API pages/find/?html_path view
### Is your proposal related to a problem?

It doesn't appear to work to find a page using the `?html_path` query param if it has a locale prefix. I found that the `find_object` method in the pages api view set doesn't seem to consider the locale prefix so that's probably the reason. We're using Wagtail as a headless CMS and the ability to query page data using the `meta.html_url` we get from the `/pages/`-endpoint would be very useful. 

### Describe the solution you'd like

We'd like to be able to simply query the pages using an html path that includes the locale prefix. Eg. `/pages/find/?html_path=/sv/my-page/`.

I subclassed the Pages view set to implement this feature, but I think it belongs in wagtail core.

### Describe alternatives you've considered

I also considered respecting the `locale` query parameter to switch root page in the `find_object` method. However, I think it is neater to use the locale prefix in the path, since that is what we get back from the API in `meta.html_url` on the Page object.

### Additional context

I can make a PR with the changes if you'd like to merge this change.

### PR DESCRIPTION
**Pull request by zerolab**
Fixes #6679

To-Do: tests, if approach is accepted

### CODE REVIEW

**Comment by kaedroho** [comment]
Been thinking about this a little more, I have an alternative suggestion:

How about making this view take a separate ``locale`` get parameter, like the page listing view. Then make it the responsibility of the frontend to add the locale prefix?

For example: ``https://api.mysite.com/api/v2/pages/find/?html_path=/&locale=en``

We should also provide a separate API to allow the frontend to find the available locales: ``https://api.mysite.com/api/v2/locales/``

**Comment by zerolab** [comment]
I like your suggestion @kaedroho as it involves less black magic and is explicit in the needs.

**Comment by andreasnuesslein** [comment]
> For example: `https://api.mysite.com/api/v2/pages/find/?path=/&locale=en` would look up the English homepage.

This is also what I initially expected based on what it says in the docs https://docs.wagtail.org/en/stable/advanced_topics/api/v2/usage.html#filtering-pages-by-locale


This works for me right now:
```
class LocalePagesAPIViewSet(PagesAPIViewSet):
    def find_object(self, queryset, request):
        site = Site.find_for_request(request)
        if "html_path" in request.GET and site is not None:
            #
            # queryset = queryset.filter(locale=locale)
            path = request.GET["html_path"]
            path_components = [component for component in path.split("/") if component]
            print(f"{path_components=}")
            try:
                root_page = site.root_page

            except Http404:
                return
            if request.GET.get("locale"):
                locale = get_object_or_404(Locale, language_code=request.GET["locale"])
                try:
                    root_page = Page.objects.get(
                        locale=locale, translation_key=root_page.translation_key
                    )
                except Page.DoesNotExist:
                    pass
            try:
                page, _, _ = root_page.specific.route(request, path_components)
            except Http404:
                return

            if queryset.filter(id=page.id).exists():
                return page

        return super().find_object(queryset, request)


api_router.register_endpoint("pages", LocalePagesAPIViewSet)
```

let me know if I should PR this

**Comment by zerolab** [comment]
@andreasnuesslein go for it. I will close this as the alternative approach is better

**Pull request closed without merging**
