### PR TITLE
Dispatch events and allow overrides for `CleanController` urlify/slugify

### PR DESCRIPTION
**Pull request by lb-**
# Overview

* Provides a starting solution for the removal of the global URLify function, allowing overrides of this behaviour within the slug widget.
* A full solution will be much more complex, we have some options (see [comment](https://github.com/wagtail/wagtail/issues/11916#issuecomment-2387601638)), but no matter which way we head or not this PR allows us to enhance later. The main enhancement is moving to Promise (async) urlify/slugify functions so that if we do want to either make an API call each time the user types OR delay the first call until we have pulled in the downcode mapping, the code will support this.

## Example usage (opt A)

Using the **undocumented** override would look like this.

Assuming the output is a slugify compatible output, otherwise the developer would need to override slugify also.

This also has a caveat, if you call `event.preventDefault()` and never call `continue`, you will end up with many hanging promises (potential memory issue), no errors will be thrown and it will just 'not work'.

```js
// .../static/js/admin.js
document.addEventListener(
  'w-slug:urlify',
  function (event) {
    if (event.target.name !== 'slug') return;  // return if the event is not from the slug field, would not be needed for most cases
    event.preventDefault();
    console.log('cleaned value is available via detail', event.detail.valueCleaned);
    const newValue = myCustomURLify(event.detail.value, { allowUnicode: event.detail.allowUnicode });
    event.detail.continue(newValue);
  },
);
```

```py
# ... /wagtail_hooks.py
from django.utils.safestring import mark_safe
from django.templatetags.static import static

from wagtail import hooks

@hooks.register('insert_global_admin_js')
def global_admin_js():
    src = static('js/admin.js')
    return mark_safe(f'<script src="{src}"></script>')

```

## Example usage (opt B)

Using the **undocumented** override could look like this (I would need to update the PR to do this).

This usage would be a non-async approach, probably simpler but relies on mutating the event's detail (similar to how we do the filename title update). Once could argue that this is less 'neat' but maybe simpler is best.

```js
// .../static/js/admin.js
document.addEventListener(
  'w-slug:urlify',
  function (event) {
    if (event.target.name !== 'slug') return;  // return if the event is not from the slug field, would not be needed for most cases
    event.detail.valueClean = 'my-custom-prefix-' + event.detail.valueClean; // I think we should change it so that the `valueClean` is the value we are about to apply, not `valueCleaned` but happy for suggestions.
   // OR you can just block the value you do not want to be used for some reason using event.preventDefault();
  },
);
```

```py
# ... /wagtail_hooks.py
from django.utils.safestring import mark_safe
from django.templatetags.static import static

from wagtail import hooks

@hooks.register('insert_global_admin_js')
def global_admin_js():
    src = static('js/admin.js')
    return mark_safe(f'<script src="{src}"></script>')

```

## Outstanding questions

1. [ ] Do we want to provide the downcode mapping to the `event.detail` (or at least a function to resolve it)?
2. [ ] Do we want to provide the base URLify function to the `event.detail` (allowing a custom downcode mapping to be passed)?
3. [ ] Do we want to document this or leave undocumented for now?
4. [ ] Do we want to do this at all? Maybe we just go back to exposing the URLify global and allow it to be overridden, it's less controlled but maybe good enough?
5. [ ] Do we want to throw an error if this override is used and `continue` is not called within X milliseconds?
6. [ ] Are we happy with the call-back being `continue`?
  * Alternative names could be [`resume` (Turbo uses this)](https://turbo.hotwired.dev/handbook/drive#pausing-rendering), or `resolve` (although we may use this pattern and it NOT be a Promise approach).
  * Another approach is object mutation like we do for the [title on upload](https://docs.wagtail.org/en/latest/advanced_topics/documents/title_generation_on_upload.html), however, in hindsight I think this is less robust.

## Additional details for reviewing

* Be sure to validate all slugify/urlify behaviour on the Slug widget, a reminder that only unpublished (not live) pages will use the sync & urlify behaviour when changing the title field.
* Please review one commit at a time, I have improved the unit test structure so it's easier to build on and have renamed the `SlugController` to `CleanController` as this is a more suitable name for future usage such as #7417 (the Slug widget will still use `w-slug` as the identifier though.

### CODE REVIEW

**Comment by thibaudcolas** [comment]
Assigning to @lb- to bring to a core team meeting / solicit feedback.

**Comment by lb-** [comment]
I think I should review this API and maybe see if the mutation of the event is a better approach. E.g. `event.detail.newValue = 'whatever'`

**Comment by gasman** [comment]
Discussed at the core team meeting today.

My gut feeling is that an event listener is the wrong operating model for this. An event is a one-to-many broadcast, indicating "this action is happening, and we're giving external components the opportunity to respond to it (including potentially modifying it)" - but in this case we're not so much responding to the action, as assigning a single component to be responsible for _performing_ the action.

As with previous discussions logged at #11916, there's still some scepticism within the team over whether a general-purpose function override is the best way to handle this - if the one established use case for this is handling languages such as Ukrainian (where the 'global' character mapping isn't usable), then being able to supply a custom mapping table would do the job. (In the longer term, we would hope to incorporate these language-specific mappings into Wagtail itself, enabling the appropriate ones in response to the active locale, so that it wouldn't be necessary for individual sites to maintain their own customisations.)

**Comment by lb-** [comment]
Thanks @gasman - I read the meeting notes also.

See full response on issue https://github.com/wagtail/wagtail/issues/11916#issuecomment-2463238841

I'll close this for now, raise a new PR with just the 'clean up' parts of this PR if that's OK and see if I have some time to give another approach a try.

**Comment by lb-** [comment]
https://github.com/wagtail/wagtail/pull/12554 created with only the clean up (no functional changes) parts from this PR

**Pull request closed without merging**
