### PR TITLE
Add alwaysdata among Cloud providers

### PR DESCRIPTION
**Pull request by nferrari**
Wagtail is available on alwaysdata Marketplace.

### CODE REVIEW

**Comment by nferrari** [comment]
Hi, should I squash and create a new PR for this trailing space problem?
Thank you

**Comment by lb-** [comment]
You can just put a new commit up or if you want you can squash / rebase locally and force push.

It's not a big issue though, when core team Merge in we usually do this squashing (we can also push directly to your branch as you have given permission). 

Note. I haven't reviewed the PR but looked good in principle.

**Review by thibaudcolas — COMMENTED** [review]
Thank you @nferrari, that looks very interesting, I didn’t know about alwaysdata.

Based on your GitHub profile it looks like you work there – we don’t require this but as a general rule if you make changes like this please do state your affiliation.

I’ve tagged this for "needs design decision" as I’d like to check with other people on the core team how much scrutiny we want to give to additions like this – I assume we’d ideally want some external confirmation this platform can indeed run Wagtail sites before we direct people towards it as an option.

Would you happen to have examples of Wagtail sites hosted there, ideally with case studies?

**Comment by nferrari** [comment]
Hi @thibaudcolas and thank you for the answer.

I am indeed part of alwaysdata team, I should have mentioned it. In order to answer your questions, let me give you a bit of context here.

We provide a system to our users, to have easy application installation wizard, and we've added a lot of application in the past few months. I can mention that the system is open to contributions (anyone can propose a new [installation script](https://help.alwaysdata.com/en/marketplace/build-application-script/)). This system was only available through our administration panel, for years, and since a few weeks we've launched the [Marketplace](https://www.alwaysdata.com/en/marketplace/) publicly.

In this context, we're making an effort to become more visible in the related communities (e.g. [Redmine](https://www.redmine.org/projects/redmine/wiki/HowTos#Application-Stacks), [Gitea](https://docs.gitea.io/en-us/install-on-cloud-provider/), [Kirby](https://getkirby.com/docs/guide/quickstart#requirements__installation-guides-for-webhosts), [Django-CMS](https://www.django-cms.org/en/hosting-services/), etc.) by updating a wiki, a documention, or making a partnership if the application's team wants it this way. We estimate this is a give-and-take deal since we gain a bit of visibility while the application provide another hosting choice to their users.

About wagtail, I read on your [documentation](https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#on-other-paass-and-iaass):

    If you have successfully installed Wagtail on your platform or infrastructure, please [contribute](https://docs.wagtail.org/en/stable/contributing/index.html) your notes to this documentation!

This is why I came with this PR.

About our Wagtail applications hosted, I've nothing yet interesting to give you, unfortunately. Probably because the Marketplace has been made public very recently and is not yet well indexed by search engines. We hope, for every application, it's gonna change by letting communities such as yours to know that we exist, and provide a great platform!

Cheers!

**Review by thibaudcolas — APPROVED** [review]
Thank you for the extra info @nferrari – new deployment options are definitely always welcome, and after checking with others we’re all very happy to add alwaysdata.

Looking forward to trying this out!

**Comment by nferrari** [comment]
Do I need to do something to see the changes on the stable version of the documentation?

Regards,

**Comment by gasman** [comment]
No, the stable docs will only be updated when a new release comes out.

**Pull request merged**
