### PR TITLE
Add 'Extending Wagtail' section to docs

### PR DESCRIPTION
**Pull request by gasman**
Given our "Wagtail as a platform" ambitions, it's likely we'll be creating a lot more documentation aimed at developers extending the Wagtail admin (as opposed to routine site-building), so I think this is a good time to make that its own top-level section in the documentation rather than making "advanced topics" even more of a dumping-ground than it is already. :-)

Along with shuffling things out of Advanced Topics, I've added a new howto on writing admin views - pretty straightforward "it's just Django" stuff that was left out up to now because there wasn't really a place for it (so people had to pick it up from the reference docs and source code instead).

The dividing line between "modelling a particularly complex site" and "extending Wagtail functionality" is a bit of a grey area, so the selection of pages being moved here is up for debate - I've taken the stance that things like custom admin forms and StreamField blocks are the sort of thing you might deal with during data modelling for a site, while things like audit logs and workflow tasks would only come up during bona-fide "custom Wagtail development".

In [Diátaxis framework](https://diataxis.fr/) terms, this section will be firmly how-to material - reference docs will remain in the Reference section (because it's impossible to make a call on which bits of that are relevant to site implementers vs core developers).

(Note: as and when this gets merged, we'll need to set up redirects in readthedocs.)

### CODE REVIEW

**Comment by gasman** [comment]
View this on readthedocs: https://wagtail--7367.org.readthedocs.build/en/7367/extending/index.html

**Review by tomdyson — APPROVED** [review]
big thumbs up

**Comment by infinityplusone** [comment]
This is lovely.

**Comment by gasman** [comment]
Redirects now added to readthedocs:

```
/advanced_topics/adding_reports.html => /extending/adding_reports.html
/advanced_topics/audit_log.html => /extending/audit_log.html
/advanced_topics/customisation/custom_account_settings.html => /extending/custom_account_settings.html
/advanced_topics/custom_tasks.html => /extending/custom_tasks.html
/advanced_topics/customisation/customising_group_views.html => /extending/customising_group_views.html
/advanced_topics/customisation/extending_draftail.html => /extending/extending_draftail.html
/advanced_topics/customisation/extending_hallo.html => /extending/extending_hallo.html
/advanced_topics/customisation/rich_text_internals.html => /extending/rich_text_internals.html
```

**Comment by vossisboss** [comment]
This looks like a solid addition to the documentation to me. Logical, well-organized and a useful addition for folks looking to build a more customized backend.

**Comment by gasman** [comment]
Thanks for the feedback, all!

**Pull request merged**
