### PR TITLE
Emphasizing unpublished pages. Issue #5370

### PR DESCRIPTION
**Pull request by saevarom**
Further work on issue #5370 after discussion at Bristol sprint. We agreed that having the whole row greyed out using the diagonal line background is more visually pleasing. After that change, we felt that reduced opacity on the title would not be necessary and probably not visible enough. I also discovered that the status tag of the page is probably not WCAG compliant since it is using a very light grey on top of white background. After discussion with @thibaudcolas we agreed that these status tags and their compliance should be looked into as a separate issue, since they are used in many places and the consequences of changing them are not obvious.

The final result looks like this:
Screenshot 2020-01-23 at 12 30 59

Tested in:
* Chrome Version 79.0.3945.117 (Official Build) (64-bit) in MacOS
* Safari version 13.0.2 (15608.2.30.1.1)
* Firefox developer edition version 72.0b9

### CODE REVIEW

**Comment by saevarom** [comment]
@tomdyson spotted this gap when the last item in a list is in draft state:

Screenshot 2020-01-23 at 14 37 04

This is because the bottom border is part of the navigation element and the margins are calculated in relative units - resulting in different actual pixel values.

**Comment by tomdyson** [comment]
Looks good! Do you think we should use the same styling on the dashboard listing, for consistency? 

image

**Comment by saevarom** [comment]
Good point, that would make sense for consistency throughout the UI.

**Comment by saevarom** [comment]
I see - well the reason I chose to change how borders was done was two-fold. First, some explanation: The spacing issue is caused by a relative margin of 3em on the pagination below the table, which is then negated with a -3em margin on the table above. I looks like these elements are calculating their pixel values relevant to different parent elements, resulting in a very slight pixel difference between those +3em and -3em values. This would be relatively easy to fix using rem units instead of em units, or a fixed px value. However, I thought it would be better for the table itself to define its own borders, instead of relying on a sibling element providing a border which should of course belong to the table. This also fixes another problem I found in the sorting view. The sorting view does not have a pagination sibling element and therefore doesn't have this border:

Screenshot 2020-01-27 at 09 34 08

So the reason I went this way was:

- A border of a table should belong to the table, not a different element which might or might not be present. 
- Relative units can cause issues, and if the border is moved over to the table, this is not an issue anymore.

So

**Comment by saevarom** [comment]
I guess we should decide whether we try to catch all cases of double borders in lists of things in this PR, or simply revert the border fix and go for `rem` or `px` values in the margins.

**Comment by saevarom** [comment]
Any opinion on which way to go @thibaudcolas ?

**Comment by thibaudcolas** [comment]
I’ve finally been able to discuss this with @benenright, and we’d like to go with a much simpler approach (see [5370](https://github.com/wagtail/wagtail/wiki/Sustainability-team)). Sorry this has taken so long @saevarom 🙈

**Comment by saevarom** [comment]
Oh come on @thibaudcolas, it's only been 4 years!

**Pull request closed without merging**
