### PR TITLE
Make update_index command quiet when calling with "--verbosity=0".

### PR DESCRIPTION
**Pull request by BenSturmfels**
The "self.verbosity > 0" is as used in Django's built-in management commands such as "migrate".

### CODE REVIEW

**Comment by BenSturmfels** [comment]
The background on this is that I run `update_index` from a cron.weekly shell script, so I get mail if there's any output from the command. I could potentially redirect stdout to /dev/null, since errors would go to stderr, but the change I've made is more in line with how Django's built-in management commands work.

**Comment by BenSturmfels** [comment]
For what it's worth, it looks like the test failure is a failure of the test pipeline itself, not related to this code change.

**Comment by thibaudcolas** [comment]
This looks like it would be very simple for someone to take on and make the changes suggested by Andy, so I have tagged as "good first issue" if someone wants to take over.

**Comment by yashlamba** [comment]
I was looking for some beginner issues to work on, @thibaudcolas I can complete this if it's still required (which I guess would be?).

**Comment by lb-** [comment]
Replaced by https://github.com/wagtail/wagtail/pull/9271

**Pull request closed without merging**
