### PR TITLE
migrate docs contrib redirects & searchpromotions to md

### PR DESCRIPTION
**Pull request by lb-**
- updates documentation for two pages to be markdown
- relates to #8383

### CODE REVIEW

**Comment by lb-** [comment]
Rebased - updated with sone conflicts resolved.

@zerolab would you mind taking a quick look at this - hopefully an easy one to check running locally compared to the current live docs for two pages. Just avoids this needing to be kept in sync with `main`.

**Review by zerolab — APPROVED** [review]
I've noticed the `versionadded` tag output is different

MD:
md

RST:
rst
d

personally I think the RST one is more visible (and in line with the Note blocks)

**Comment by lb-** [comment]
Ok. All the other markdown ones will look the same. Not sure what to do. 

I can riase a seperate issue about the inconsistent styling - we can use eval-rst in this one only but that won't fix the problem for all their other doc's already migrated

**Comment by zerolab** [comment]
> I can riase a seperate issue about the inconsistent styling - we can use eval-rst in this one only but that won't fix the problem for all their other doc's already migrated

Works for me.

**Comment by lb-** [comment]
@zerolab - https://github.com/wagtail/wagtail/issues/8742 created - please can you add any comments/preference.

**Pull request merged**
