### PR TITLE
Solved missing `invert` attribute bug

### PR DESCRIPTION
**Pull request by ACMCMC**
Solves issue #7725 🙌

### CODE REVIEW

**Comment by lb-** [comment]
@ACMCMC - thanks for taking the time to report and debug/resolve this.

Would you be able to look at creating a unit test to cover this DB specific issue, it would be very easy for something like this to be missed/inverted ;)  in the future and it would be great to have a test to cover it.

**Comment by ACMCMC** [comment]
> Would you be able to look at creating a unit test to cover this DB specific issue, it would be very easy for something like this to be missed/inverted ;) in the future and it would be great to have a test to cover it.

Yes! Of course, that's a great idea 🙌 I will add a commit to this PR with that unit test. However, do you think it's better to add it only to the MySQL backend (`test_mysql_backend.py`), or to instead create a general test that applies to every backend (`test_backends.py`), and specialize that test in the MySQL backend, to add other MySQL-specific features to the test?

**Comment by gasman** [comment]
@ACMCMC Since the bug occurs when running a standard non-database-specific query, I think it'd be most useful to write it as a general test for all backends - that way we'll catch any similar bugs if they exist on the other backends.

**Comment by ACMCMC** [comment]
The latest commit on the branch is the requested change on the unit tests. I chose not to add another test, which would contribute to a higher delay when running all the suite of tests of Wagtail. Instead, I just modified the `test_plain_text_multiple_words_and` test, to test for a 3+ words case.

The tests are now failing because of it, as described in #7727 . I will submit another commit with the fix for that issue.

**Comment by ACMCMC** [comment]
The latest commit on the branch is the requested change on the unit tests. I chose not to add another test, which would contribute to a higher delay when running all the suite of tests of Wagtail. Instead, I just modified the `test_plain_text_multiple_words_and` test, to test for a 3+ words case.

The tests are now failing because of it, as described in #7727 . I will submit another commit with the fix for that issue.

**Review by gasman — APPROVED** [review]
Looks good to me - thanks @ACMCMC!

**Pull request merged**
