### PR TITLE
Rearrange scss

### PR DESCRIPTION
**Pull request by nmorduch**
This PR is written as a step toward making changes called for in #3804. It moves the bulk of our styles to the `client` folder, and splits them into files approximately according to ITCSS.

Replaces #4979 (so that Squash will run), which replaced #4974.

### CODE REVIEW

**Comment by nmorduch** [comment]
@jonnyscholes and @jjanssen, changes look good to me (without having tested yet). Thank you for keeping this going. Looking forward to feedback from @HvandenBerg!

**Comment by HvandenBerg** [comment]
Also tested this and all looks good, no more styling issues in IE11 (and I checked a few other and older versions of a variety of browser for good measure) and no more console errors!

**Comment by nmorduch** [comment]
@jjanssen Are we ready to merge this?

**Comment by jjanssen** [comment]
Yeah, I think so but maybe wait on #5216 for the housekeeping, so we don't end-up in a grey area between 2.5 and 2.6. Are you in the opportunity to merge this when ready or do you like me to take a look at that?

**Comment by nmorduch** [comment]
Definitely after 5216. I'm happy to do the merging, and it's also fine if someone gets to it before me. (I'll say here when I start merging, if no one else does first.)

**Comment by nmorduch** [comment]
Also: thank you again, @HvandenBerg !

**Comment by nmorduch** [comment]
Going to merge this now

**Comment by nmorduch** [comment]
Actually, @jjanssen, would you mind merging? I went to see if any of the commits should be squashed, and there are two commits about updating the font-root, which cancel each other out, and I'm not sure whether that's correct.

**Comment by jjanssen** [comment]
I'll take a look :)

**Comment by jjanssen** [comment]
Squashed the commits and merged with 2668c05

Thanks @nmorduch @jonnyscholes @HvandenBerg for making this happen ❤️

**Pull request closed without merging**
