### PR TITLE
Accessibility issue 11372 resolved aria label

### PR DESCRIPTION
**Pull request by nandini584**
This is the fixed for the issue #11372. I have removed both the `aria-label` and `title`.

Tests are working fine.
Screenshot 2024-01-08 231208

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by nandini584** [comment]
@thibaudcolas Is this alright?

**Comment by lb-** [comment]
@nandini584 can you look at the CI failure. Looks like an integration test also needs updating as it's looking for the aria-label. 

Screenshot_20240110-172544

**Comment by nandini584** [comment]
Sure i will check this out @lb-

**Comment by nandini584** [comment]
There's some issue that I am facing here, my tests are passing tho. 
Screenshot 2024-01-10 233203

**Comment by lb-** [comment]
I have just pushed a change `const trigger = await page.$('.sidebar-footer > button');` for the integration tests.

**Comment by lb-** [comment]
OK I think there's an issue with this test, and it's probably the reason aria-label was added in the first place.

@nandini584  I think for now you can simply remove this integration test for the sake of this PR, the button 100% has a label.

We can then raise a new issue for reinstating that integration test or reviewing how the axe tests work.

cc @thibaudcolas 

```
 FAIL  client/tests/integration/homepage.test.js
  ● Homepage › axe sidebar footer

    expect(received).toPassAxeTests(expected)

    Expected page to pass Axe accessibility tests.
    Violations found:
    Rule: "button-name" (Buttons must have discernible text)
    Help: https://dequeuniversity.com/rules/axe/4.3/button-name?application=axe-puppeteer
    Affected Nodes:
      .w-px-4
        Fix ANY of the following:
        - Element does not have inner text that is visible to screen readers
        - aria-label attribute does not exist or is empty
        - aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
        - Element has no title attribute
        - Element's default semantics were not overridden with role="none" or role="presentation"
    

      41 |     const trigger = await page.$('.sidebar-footer > button');
      42 |     await trigger.click();
    > 43 |     await expect(page).toPassAxeTests({
         |                        ^
      44 |       include: '.sidebar-footer',
      45 |     });
      46 |   });

      at Object.<anonymous> (homepage.test.js:43:24)
```

**Comment by nandini584** [comment]
ok @lb- I have removed this particular test for now

**Comment by lb-** [comment]
Integration test issue has been flagged here https://github.com/wagtail/wagtail/issues/8938#issuecomment-1894834381

**Review by lb- — APPROVED** [review]
Working well, thanks for following up on the integration test item.
Screenshot 2024-01-17 at 12 27 13 pm
Screenshot 2024-01-17 at 12 26 39 pm


I will rebase and merge this in.

**Pull request merged**
