### PR TITLE
Fix #6408: InvokeViaAttributeShortcut makes it impossible to pickle objects

### LINKED ISSUE #6408: InvokeViaAttributeShortcut makes it impossible to pickle objects
### Issue Summary

`wagtail.core.utils.InvokeViaAttributeShortcut` makes it impossible to pickle `BaseSetting` object.

So it effectively kills object level caching.

### Steps to Reproduce

```
import pickle
some_settings_obj = SomeSettings.objects.get(pk=1)
picke.dumps(some_settings_obj, -1)
```
would produce `TypeError: 'str' object is not callable`

### PR DESCRIPTION
**Pull request by ababic**
Resolves #6408

### CODE REVIEW

**Comment by pySilver** [comment]
5c: do we really need slots here? Having '__getstate__' override in BaseSetting seems like a half measure, since you'll have to repeat the same workaround in every implementation that needs a pickle support. It would be nicer to have it fixed on a definition level. I'd say pickle expects this.

**Comment by ababic** [comment]
@pySilver I feel we are right to exclude `page_url` when pickling site settings, because the InvokeViaAttributeShortcut instance does not contribute anything meaningful to the state (it can be recreated like-for-like from non-instance specific data).

Whether or not `InvokeViaAttributeShortcut` uses `__slots__` is mostly irrelevant I thing - because it doesn't ever make sense to pickle an `InvokeViaAttributeShortcut` instance on an object (it isn't meaningful). If it did, it would include another representation of the object, which has a reference to the `InvokeViaAttributeShortcut` instance, creating an infinite loop.

**Comment by pySilver** [comment]
@ababic its almost correct

1. Yes there is no need to pickle page_url, we can simply drop it (I do this for all my Page models usually by checking isinstance cached_property in `__getstate__`)

2. Pickle handles circular references just fine. Its just a gotcha - if you use `__slots__` & together with `__getattr__` then you need to implement `__getstate__` & `__setstate__` In absense of this methods, pickle would fallback to call `__getattr__` and create an infinity loop here.

Either way if there are no plans using `InvokeViaAttributeShortcut` anywhere else, then `cached_property` & state exclusion will work just fine.

**Comment by ababic** [comment]
> If you use __slots__ & together with __getattr__ then you need to implement __getstate__ & __setstate__ In absence of this methods, pickle would fallback to call __getattr__ and create an infinity loop here

Just to clarify for anyone stumbling across this conversation: `__slots__` hasn't got anything to do with the pickle failure here (an instance of `InvokeViaAttributeShortcut` will not pickle, regardless of whether `__slots__` is present or not). The problem is the `__getattr__` override. Adding `__getstate__` & `__setstate__` does resolve the issue though.

**Comment by ababic** [comment]
@gasman this solves the issue of settings objects no longer being pickle-able, as well as making `InvokeViaAttributeShortcut` instances themselves pickle-able (in case they are used anywhere else where pickle-ability is important). Regression tests also included.

**Comment by gasman** [comment]
Thanks @ababic! Merged in 29d564c238c5c6577b4b1f75203c1c77acdb35dc.

**Pull request closed without merging**
