### PR TITLE
Update SiteMiddleware PR

### LINKED ISSUE #3834: Wagtail SQL call on none wagtail pages
Hi,

I have included wagtail to my project as a cms system. But I have also some old static pages which also produce allways this SQL call:

`
SELECT"wagtailcore_site"."id", "wagtailcore_site"."hostname", "wagtailcore_site"."port", "wagtailcore_site"."site_name", "wagtailcore_site"."root_page_id", "wagtailcore_site"."is_default_site", CASEWHEN ("wagtailcore_site"."hostname" = '''127.0.0.1''' AND "wagtailcore_site"."port" = '8000') THEN '0' WHEN ("wagtailcore_site"."hostname" = '''127.0.0.1''' AND "wagtailcore_site"."is_default_site" = 'True') THEN '1' WHEN "wagtailcore_site"."is_default_site" = 'True' THEN '2' ELSE '3' END AS "match", "wagtailcore_page"."id", "wagtailcore_page"."path", "wagtailcore_page"."depth", "wagtailcore_page"."numchild", "wagtailcore_page"."title", "wagtailcore_page"."slug", "wagtailcore_page"."content_type_id", "wagtailcore_page"."live", "wagtailcore_page"."has_unpublished_changes", "wagtailcore_page"."url_path", "wagtailcore_page"."owner_id", "wagtailcore_page"."seo_title", "wagtailcore_page"."show_in_menus", "wagtailcore_page"."search_description", "wagtailcore_page"."go_live_at", "wagtailcore_page"."expire_at", "wagtailcore_page"."expired", "wagtailcore_page"."locked", "wagtailcore_page"."first_published_at", "wagtailcore_page"."last_published_at", "wagtailcore_page"."latest_revision_created_at", "wagtailcore_page"."live_revision_id"FROM "wagtailcore_site" INNER JOIN "wagtailcore_page" ON ("wagtailcore_site"."root_page_id" = "wagtailcore_page"."id") WHERE ("wagtailcore_site"."hostname" = '''127.0.0.1''' OR "wagtailcore_site"."is_default_site" = 'True') ORDER BY "match" ASC | 98,487335358% | 144,35 | SelExpl
  | 
`
This call takes on my desktop computer (in debug mode with sqlite) 150ms. Is there something wrong?
And why is this SQL query also called on a none wagtail page?

### Issue Summary

Wagtail is calling SQL queries which I don't need

### PR DESCRIPTION
**Pull request by timmysmalls**
This PR should resolve #3834. It builds upon PR #5332 by aritas1. For all commentary/discussion/rationale, please refer back to #5332 .

### CODE REVIEW

**Comment by ababic** [comment]
Am I correct in thinking that calling `Site.find_for_request()` will result in a new query each time? If so, I wonder about the affect on performance, as I feel I've come to rely on `request.site` quite a bit over the years for various things. I wonder, could `Site.find_for_request()` not set an attribute on the request on the firs

**Comment by ababic** [comment]
Am I correct in thinking that calling `Site.find_for_request()` will result in a new query each time? If so, I wonder about the affect on performance, as I feel I've come to rely on `request.site` quite a bit over the years for various things. I wonder, could `Site.find_for_request()` not set an attribute on the request on the firs

**Comment by timmysmalls** [comment]
@ababic It caches the result on the request._wagtail_site attribute, so it only queries for the site object once, and it should actually increase performance, as it is also lazily instantiated.

**Comment by ababic** [comment]
@timmysmalls ah, sorry - I don't know how I missed that. That'll teach me to scroll through large diffs late at night. Excellent work!

**Comment by timmysmalls** [comment]
@ababic no problem! And I can't really take credit for the bulk of the work done. This was previously done in another PR by @aritas1. There was quite some confusion on why certain tests had to be altered because of the changes, so I added a few commits on top of the old PR to minimize the changes to the code, and explain what I figured was the cause of the issues. The whole discussion can be found here #5332. I'm not entirely sure about the context['request']. I will look into it this weekend. I'm glad you're taking the time to look at this! This issue first appeared on my radar when I found out there was a conflict between the Wagtail SiteMiddleware and the Django SiteMiddleware, which makes wagtail essentially imcompatible with any package that uses the SiteMiddleware.

I'll take get back to you asap about the `context['request']`. I didn't write that part, so I'll have to look into it.

**Comment by aritas1** [comment]
`context` is of type `class 'django.template.context.RequestContext'` and it's fine to access values like this in that case.

however im not 100% into the internal behavior of django. maybe it's somehow possible that you get a dictionary instead of a class?

looking through the django documentation, it feels like the common way to access values from the context  is like @ababic mentioned with the bracket notation. to be more conservative i would advice to change the line to avoid some unexpected problems.

**Comment by ababic** [comment]
@aritas a `RequestContext` would have a `request` attribute set, but it can be quite common in django to create other types of `context` objects with just the values that are needed and use them to render a template (e.g. Putting together a notification email). Using `context['request']` instead would just make things a little more flexible (usable in more cases).

**Comment by timmysmalls** [comment]
@ababic I will pick this up asap, and resolve the conflicts.

**Comment by timmysmalls** [comment]
@gasman Thanks for the review! I hope I'll be able to get to everything this weekend!

**Comment by gasman** [comment]
Superseded by #5787

**Pull request closed without merging**
