### PR TITLE
make TableBlock reachable by Keyboard

### LINKED ISSUE #8893: TableBlock is impossible to reach with the keyboard
### Issue Summary

Wagtail’s TableBlock table widget is impossible to reach with a keyboard:

table-block-widget

### Steps to Reproduce

1. In StreamField, add a TableBlock
2. Try to navigate to its Handsontable table widget

### PR DESCRIPTION
**Pull request by elhussienalmasri**
Fixes #8893
this issue because `tabindex` so I add `tabindex` attribute in 3 places:
- initial state when the window load 
- when create TableBlock 
- when add  Row or Column

I add `tabindex` in 3 places because for example if I added it to only initial state when the window load and the user add  column or row to TableBlock so this row or column don ,t have tabindex attribute so it ,s become not reachable by keyboard so I added to become `reachable` by `Keyboard` even after the user add column or row , and also `tabindex` added when create TableBlock for this reason also.

so now the `TableBlok` become reachable by Keyboard:
After:
After

Before:
 Before

_Please check the following:_

-   ✅ Do the tests still pass?[^1]
-  ✅Does the code comply with the style guide?
    -   ✅ Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by elhussienalmasri** [comment]
please merge it if it is work as expected , and if this PR need additional work please let me know.

**Comment by lb-** [comment]
@elhussienalmasri  why the usage of contenteditable also?

**Comment by elhussienalmasri** [comment]
@lb-  this attribute enable user to edit the table when the user move using keyboard if this attribute removed,
user can ,t edit the Table when move using keyboard , without this attribute the user must use the mouse to enable hem to edit
the table .

**Review by lb- — APPROVED** [review]
OK I see now, thank you. This works much better!

Two changes recommended, I can put these into the PR when merging though.

1. Let's also add `plaintext-only` - it will just improve the support for most browsers (Firefox ignores this) https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable
2. Let's pull out the attributes to a constant so it's easier to keep them in sync. e.g. `keyboardAccessAttrs`


Tested on Firefox 121, Chrome 122 and Safari 17.2

There are still a few quirks with the table but this is not new (for example, if you are focused on a cell the changes in that cell are not applied on save, you have to blur the cell to save the changes).

I did get some cases where the tabbing would go in a loop through the cells and back again but this was only if you clicked in a cell instead of keyboard tabbing to it.

I think this is a result of the contenteditable but I agree there appears to be no other simple way to get this working without that.

Overall, this is a big improvement. I think we are well beyond stretching this code to be functional though. We really should find a replacement for Handsontable, but that's a journey for another day.

**Comment by elhussienalmasri** [comment]
Thanks very much for valuable info , additional code which really improve the PR, and for approved this PR.

**Pull request merged**
