### PR TITLE
Broken design update accessibility

### PR DESCRIPTION
**Pull request by nandini584**
Fixes : #11449 

1. Added the border in brand-logo in forced-color-mode
Screenshot 2024-03-08 214839

2. Made the mainmenu items and main footer items similar to avoid confusion.
Screenshot 2024-03-08 214853

As the point where contrast of warning has to be increased in darkmode, my proposed solution:
`&.warning 
    background-color: darken(theme('colors.warning.100'), 10%); 
    border-color: darken(theme('colors.warning.100'), 10%);`

### CODE REVIEW

**Comment by laymonage** [comment]
Please don’t commit unrelated files, you have your virtual environment and other stuff in this PR. See that the “Files changed” tab shows there are more than 5000 files changed.

**Comment by nandini584** [comment]
I am not sure what the issue is with those 2 commits, I ran the command npm run format to format the code...could it be the reason for formatting in multiple files? 

Also in some of the issues and broken design could you help me find out where the wagtail component is? There are some components which I am unable to spot...

**Comment by lb-** [comment]
@nandini584 it looks like you have included the entirety of the `mysite` folder in your PR. 

I'd recommend you remove it, then squash the commits so it's not on the PR. If you must have this folder in the same folder as your Wagtail fork, you'll probably want to ignore this for future commits. 

See https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#excluding-local-files-without-creating-a-gitignore-file

However, I'd recommend you not try to have a subfolder in your Wagtail fork for any local sites you are working with. 

As for the question about specific components, I'd suggest you ask on the original issue and someone may be able to help you there. I'm not sure what components you're referring to sorry. 

Good on you for keeping at this, it's a bit of a learning curve I know.

**Comment by nandini584** [comment]
I have removed the folder.

**Comment by thibaudcolas** [comment]
I see this PR contains no changes in its diffs, and when I inspect all of the commits they contain unrelated files to the changes needed, so it looks like there was a git accident here! I’ll close this now, it’ll be easier to recreate this from a new branch / PR.

**Pull request closed without merging**
