### PR TITLE
Fixes Design update - secondary button with icon

### LINKED ISSUE #9198: Design update - secondary button with icon - Wagtail Design System
> **Good first issue** for someone confident with SCSS/CSS

### Is your proposal related to a problem?

* There is not yet a officially supported button with icon that aligns with the secondary button styles (outline only button)
* If `button-secondary` is applied to the current `bicolor` button styles, it works but should align with the new official Wagtail Design System

### Describe the solution you'd like

* [ ] Add support for the with icon (secondary, aka ghost) buttons as per the [design system Figma](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=5172%3A30751)
* [x] Add new variants using `.button-secondary` with `bicolor button-icon` in the styleguide https://github.com/wagtail/wagtail/blob/main/wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html
* [x] Add new variants using `.button-secondary` with `bicolor button-icon` in the pattern library https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/button.stories.tsx
* [ ] Add styles for these variants in https://github.com/wagtail/wagtail/blob/main/client/scss/components/_button.scss
* [ ] Must work in all supported browsers https://docs.wagtail.org/en/stable/contributing/developing.html#browser-and-device-support

#### Normal size button-secondary with icon

Very similar to the `bicolor` currently but with different colours, must support all existing supported DOM elements for buttons (`a`, `button`, and `input[submit`).

* Default
* Hover
* Disabled
* Focus state (existing global focus outline)

Screen Shot 2022-09-14 at 4 55 27 pm

#### Normal size button-secondary with icon

When small and secondary the border is dropped, must support all existing supported DOM elements for buttons (`a`, `button`, and `input[submit`).

* Default
* Hover
* Disabled (not shown)
* Focus state (existing global focus outline)

Screen Shot 2022-09-14 at 4 56 31 pm

### Describe alternatives you've considered

Leave as current state and do not document `.button-secondary` when used with `.bicolor`.

| `button bicolor button--icon button-secondary` | `button bicolor button--icon button-secondary button-small` |
| --- | --- |
| Screen Shot 2022-09-14 at 4 51 53 pm | Screen Shot 2022-09-14 at 4 51 40 pm |

### Additional context

* The bulk of the original button designs issue was completed via https://github.com/wagtail/wagtail/issues/8790
* As this button type was not officially supported or used, it ended up being out of scope.

### PR DESCRIPTION
**Pull request by Seremba**
Styled Secondary buttons with icons to match Wagtail Design System. 
This fixes #9198
Before
seconadry_button_with_icon

After
Screenshot from 2022-10-22 20-55-09

### CODE REVIEW

**Comment by lb-** [comment]
The screenshots look good. Thanks @Seremba 

I'll flag this for a review but in the meantime can you remove the changes to package lock and also see what failed on the CI. This code may need some formatting fixes.

**Comment by Seremba** [comment]
Thanks a lot, @lb-, GitHub keeps tracking the package-lock file looks like I should remove it from git and GitHub.

**Comment by Scotchester** [comment]
> Thanks a lot, @lb-, GitHub keeps tracking the package-lock file looks like I should remove it from git and GitHub.

Please do not remove it. Having it checked in is important to ensuring that our dependency installations are predictable at any given time. It's OK that it changes on your computer when you run `npm install`, just do not add it to your commits.

**Comment by Seremba** [comment]
I understand. Thanks 

> > Thanks a lot, @lb-, GitHub keeps tracking the package-lock file looks like I should remove it from git and GitHub.
> 
> Please do not remove it. Having it checked in is important to ensuring that our dependency installations are predictable at any given time. It's OK that it changes on your computer when you run `npm install`, just do not add it to your commits.

I understand. Do you think I should run JavaScript linting for all CI tests to pass?

**Comment by Scotchester** [comment]
> I understand. Do you think I should run JavaScript linting for all CI tests to pass?

I'm not sure why the frontend CI is failing. It doesn't appear to have anything to do with your changes. Perhaps if you fetch the latest upstream `main` branch and rebase your branch on that, it will go away?

**Comment by Seremba** [comment]
> > I understand. Do you think I should run JavaScript linting for all CI tests to pass?
> 
> I'm not sure why the frontend CI is failing. It doesn't appear to have anything to do with your changes. Perhaps if you fetch the latest upstream `main` branch and rebase your branch on that, it will go away?

Okay fine. Let me try that

**Comment by Seremba** [comment]
Hi @Scotchester I have tried your suggestion several times. I seem not to see any visible change, any more tips?

**Comment by Seremba** [comment]
@Scotchester thank you, maybe I should walk you through what I have done
1) git remote -v
2) git fetch upstream
3) git checkout styleguide/#9198-design-update-secondary-button-with-icon
4) git rebase --autostash styleguide/#9198-design-update-secondary-button-with-icon 
5) git checkout main
6) git merge --ff-only styleguide/#9198-design-update-secondary-button-with-icon 
7) git push --force
Anything I have done wrong?

**Comment by Scotchester** [comment]
Thanks for the steps, that is helpful. It looks like your rebase command would have had no effect.

You should try running:

```sh
git rebase styleguide/#9198-design-update-secondary-button-with-icon upstream/main
```

The addition of `upstream/main` at the end is what tells it to rebase your branch on top of main. (And you don't need the autostash option unless you have made other changes that you haven't yet committed.)

After running that, then try `git push --force` again.

**Comment by Scotchester** [comment]
Oops, quick correction: Make sure you have checked out your `styleguide/#9198-design-update-secondary-button-with-icon` branch before running the rebase command I suggested.

**Comment by Seremba** [comment]
Okay, please!

**Comment by Seremba** [comment]
Screenshot from 2022-10-25 18-34-08

See what I get

**Comment by Scotchester** [comment]
@Seremba Did you **merge** in upstream/main instead of **rebasing** on it? Your PR now includes a lot of changes that are already merged into main.

**Comment by Seremba** [comment]
I have shared the screenshot, git has humbled me today.

**Comment by Scotchester** [comment]
Don't be discouraged, @Seremba. Git is a finicky beast.

At this point, I would probably suggest that you close this PR, create a fresh branch off of upstream/main, reapply your changes there, and open a new PR. It's annoying, but sometimes when branches get too messy, it's the easiest solution.

**Pull request closed without merging**
