### PR TITLE
Always open up a new preview window

### PR DESCRIPTION
**Pull request by kjartansverrisson**
Fixes: #2289 

Addresses an issue with preview windows and how they are reused for
later preview, causing the preview screen to hang in some cases. Always opening up new windows is not perfect, but at least it results in consistent behavior.

### CODE REVIEW

**Comment by jjanssen** [comment]
Merged in 9eef436 - thanks!

**Comment by georgemillard** [comment]
Hello,

I know this issue has been marked as closed, but I think I have the latest version of wagtail (installed with pip) and I am encountering the same problem:

1. Create a page
2. Preview it
3. Return to the edit page tab
4. Make a change and save it
5. Click preview - the preview tab comes up with a spinning arrow

Thanks,

George

**Comment by gasman** [comment]
@georgemillard This fix has not made it into an official pip-installable release yet - it's coming in Wagtail 1.10, which is due in a week or two. (In the meantime, you can test the 1.10 release candidate: https://groups.google.com/d/msg/wagtail/XSP5yDyZzsw/f7xH-Xu2AwAJ )

**Comment by georgemillard** [comment]
That's great thank you - and thanks for replying so quickly!

George

**Pull request closed without merging**
