### PR TITLE
Fixes the Django 1.11 ORM compatibility issue.

### PR DESCRIPTION
**Pull request by BertrandBordage**
This pull request fixes the remaining issue blocking 1.11 compatibility (see #3314).
It is due to the changes done in [django/django@1bc249c](https://github.com/django/django/commit/1bc249c2a67c24fcd28436c85388eff1d826e305).

### CODE REVIEW

**Comment by kaedroho** [comment]
Wouldn't this break cases where the value is not a subquery? For example:

```python
MyModel.objects.filter(category__in=['foo', 'bar']).search()
```

**Comment by BertrandBordage** [comment]
That’s right, we have to add a test for such use cases.
I’ll update the pull request & add a test.

**Comment by BertrandBordage** [comment]
I pushed tests and handled other cases than subqueries.

**Comment by kaedroho** [comment]
Looks good to me, thanks!

**Pull request merged**
