### PR TITLE
Add panel configuration checks

### LINKED ISSUE #2822: Add a system check for incorrect use of content_panels on non-page models
Using `content_panels` instead of `panels` on non-page models (including snippets, ModelAdmin, wagtailsettings, and InlinePanel child models) seems to be a very common mistake:

http://stackoverflow.com/questions/38207208/add-a-multifieldpanel-in-django-wagtail-basesettings
https://groups.google.com/d/msg/wagtail/nqb24PZRlhk/oKkbmUXZAgAJ
https://github.com/torchbox/wagtail/issues/1456
https://groups.google.com/d/msg/wagtail/hs_mX0xOoyY/fr7ktSTRAAAJ
https://github.com/torchbox/wagtail/issues/1912

I suggest we add a system check to warn about models that set a `content_panels` attribute when a `panels` attribute is expected instead. (The solution would need to take care to avoid false positives, since it _is_ valid to set `content_panels` if the edit_handler property is overridden.)

### PR DESCRIPTION
**Pull request by lb-**
Closes #2822 

Adds checks (using Django checks framework) for common mistakes when setting up panels for model editing.

* Tests run/pass locally + tests added for all model types affected
* No docs needed as this simply reinforces correct behaviour
* Linting has been checked

@gasman I would love your thoughts on this as you created the original issue.

### CODE REVIEW

**Comment by lb-** [comment]
@mikedingjan - been a little while but let me know if I can assist with getting this reviewed, happy to close and open as a new PR if needed (as there will be conflicts now).

**Comment by mikedingjan** [comment]
Hi @lb- 
I've reviewed this in the past already, seems like I forgot to mention it here, all worked fine, tested it in a few projects of mine.. I saw some commented code, maybe you can remove that and resolve the merge issues, and I'll do a final check?

**Comment by lb-** [comment]
@mikedingjan  - awesome, thank you. I will get a new/updated PR ready with the conflicts resolved

**Comment by mikedingjan** [comment]
@lb- Nice, looking forward too see it, maybe you can assign/tag me, so it won't get lost (again).. :)

**Comment by lb-** [comment]
This PR has been replaced by #5093

**Pull request closed without merging**
