### PR TITLE
feat(TypedTableBlock): added caption field (#8507)

### PR DESCRIPTION
**Pull request by TommasoAmici**
_Please check the following:_

- [x] Do the tests still pass?[^1]
- [x] Does the code comply with the style guide? 
    - [x] Run `make lint` from the Wagtail root. 
- [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
- [x] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    - [x] **Please list the exact browser and operating system versions you tested**:
	    - [x] Firefox 101: https://www.whatsmybrowser.org/b/P062T
	    - [x] Chrome 101: https://www.whatsmybrowser.org/b/8DU5F
	    - [x] Safari 15.4: https://www.whatsmybrowser.org/b/XPZKV
    - [ ] **Please list which assistive technologies [^3] you tested**: 
- [ ] For new features: Has the documentation been updated accordingly?

image

**Please describe additional details for testing this change**. 

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by lb-** [comment]
@TommasoAmici sorry this never got reviewed, are you still keen on pursuing this? Would you be up for rebasing?

**Comment by lb-** [comment]
Also. At first glance, this looks solid but we probably would want to put the caption field at the bottom. I know the html will add it at the top, but this feels like a secondary field compared to the main table content.

**Comment by minusf** [comment]
> Also. At first glance, this looks solid but we probably would want to put the caption field at the bottom. I know the html will add it at the top, but this feels like a secondary field compared to the main table content.

the handsontable `TableBlock` also has the caption on the top...

as in both cases the tables grow downwards, i think putting any fields under is not the best UX...

**Comment by cnk** [comment]
[w3.org shows table captions at the top](https://www.w3.org/WAI/tutorials/tables/caption-summary/#identifying-a-table-using-a-caption), just below the table tag and above the table header row.

**Comment by minusf** [comment]
> [w3.org shows table captions at the top](https://www.w3.org/WAI/tutorials/tables/caption-summary/#identifying-a-table-using-a-caption), just below the table tag and above the table header row.

i think the comments are about the `caption`'s position in the wagtail table editor, not the rendered table.

**Comment by cnk** [comment]
I don't feel like I am competent to review this PR but I was interested enough in it to rebase it and make sure it still works. 

One thing I did notice is that the styling in the admin form is not exactly like that for the other TableBlock. The field title is not purple and the help text is above the field in most components but below the input field here. 

1. Should we regularize that?
2. Is that done by editing the `dom` constant in typed_table_bock.js?

Screenshot 2023-12-21 at 2 05 19 PM

**Review by lb- — APPROVED** [review]
Looks good, I ran the code also and works well.

I have done a small set of clean up items and will rebase/push & then merge in after the CI runs. Updated trailing commas on newly added kwargs, added a full stop at the end of the help text (and in the table field also), removed the translation file addition as this is done when the release candidate is created.

Thanks @TommasoAmici  & @cnk !

**Pull request merged**
