### PR TITLE
Replace `imghdr` with Willow's built-in mime-type detection

### PR DESCRIPTION
**Pull request by RealOrangeOne**
_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [x] For new features: Has the documentation been updated accordingly?

`imghdr` is deprecated, and will be removed in Python 3.13. `Willow` has already stopped using it in favour of `filetype`, and exposes the mimetype of images - so just use that.

Note that this currently doesn't work for SVGs until https://github.com/wagtail/Willow/pull/129 ships.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Review by zerolab — CHANGES_REQUESTED** [review]
Neat!

It would be good to add a few tests, especially one requesting an AVIF rendition, as this is what prompted/sped up this PR ;)

**Comment by RealOrangeOne** [comment]
> It would be good to add a few tests

I'll double check we're properly covering the case that the mime-type is being passed correctly, but too much testing into the detection itself is more relevant to Willow's tests rather than Wagtail's.

**Comment by zerolab** [comment]
> I'll double check we're properly covering the case that the mime-type is being passed correctly

perfect.

Also, https://github.com/wagtail/Willow/releases/tag/v1.6.2 -- if you want to bump the min willow version

**Comment by RealOrangeOne** [comment]
> I'll double check we're properly covering the case that the mime-type is being passed correctly

The [tests for the view](https://github.com/wagtail/wagtail/blob/main/wagtail/images/tests/tests.py#L323) do assert the mimetypes, although the test images are all PNGs. I've added a test case for SVG and AVIF too, which ought to be enough coverage for here.

**Review by zerolab — APPROVED** [review]
LGTM!

**Comment by lb-** [comment]
Added to 5.1.2 

855fafbded94179cc0256930b32c1df04a0f65b9
57a13c427813554836b1394b45d89d0e554634bd
bbdd700b58e660168f78302cef3d46a8265b0972
7302d74ed02123e8d52a5fb9bee9f1079a6fc9c6

**Pull request merged**
