### PR TITLE
Update frontend tooling packages

### PR DESCRIPTION
**Pull request by jjanssen**
Since I'm in the flow of upgrading: I have updated most of the packages in the `package.json` including the upgrade to React 16. Which was pain-free due to the fantastic Enzyme adapters 🎉 

Some highlights:
- I had to update some tests due to the `shallow`-call being made before mutating the `document.body`.
- `react-addons-perf` is not compatible with React 16 so I have removed this from the code. An alternative for local development would the [React Perf extension](https://github.com/crysislinux/chrome-react-perf) for chrome. Although I have not tested it just yet.

What still needs a little tender, love and care after the merge:
- React Transition group;
- ESLint;

Things which need to done:
- [x] Verify whether the output of the gulp updates did not change drastically;
- [x] Maybe give it a bit of QA goodness (CC @hvandenberg)
- [x] Circle CI configuration check-up :expressionless:

### CODE REVIEW

**Comment by thibaudcolas** [comment]
@jjanssen could you make sure to generate the `package-lock.json` with npm@5.6.0 so this addresses the remaining lockfile difference in #3806?

**Comment by jjanssen** [comment]
The `gulp-autoprefixer` update reintroduced some vendor-prefixes where they were missing previously. Like for eg: `animation`, `transform` and `transition`. In the broader perspective nothing to worry about.

On the left you see a snippet of my update branch and on the right the current master.
image

Right now we define `['last 3 versions', 'ie 11']`. I think the changes showing up is a part of the autoprefixer change on can-i-use library and maybe a stricter version check. We could either narrow the scope down according to our [official browser support list](http://docs.wagtail.io/en/v1.13.1/contributing/developing.html) or leave it be and take the added rules for granted.

Personally I think we should narrow it down, to prevent unnecessary code from being rendered.

**Comment by jjanssen** [comment]
As for `react-transition-group` there are some major changes between the v1 and v2 API. I still have to grasp the new concept of it and update it properly. But I haven't figure it out yet completely. Still hoping to round-up on this as a part of this PR.

**Comment by HvandenBerg** [comment]
Tested this to see if the explorer still works cross browser according to the DoD, test OK.

**Comment by thibaudcolas** [comment]
Merged in 9f65e7001f17e922db32628b43028414351fe05f 🎉 .

**Pull request closed without merging**
