### PR TITLE
Rename project_template homepage to "Home"

### PR DESCRIPTION
**Pull request by kaedroho**
I think it's a better name. Feel free comment/close if you disagree.

### CODE REVIEW

**Comment by tomdyson** [comment]
I prefer this.

AFAIK the title of this page doesn't get translated. Should it?

**Comment by kaedroho** [comment]
Unfortunately, it's a field. So that'll be a job for wagtail-trans or wagtail-modeltranslation

**Comment by tomdyson** [comment]
I guess this only affects the person who runs `wagtail start`, and they probably wouldn't have got as far as setting up Wagtail without knowing enough English to follow the instructions. Either way, it shouldn't block this PR.

**Comment by gasman** [comment]
Merged in c900f71117b15ecc61931eee98c30432a9d8a188

**Pull request closed without merging**
