### PR TITLE
Fixed long filename wrapping issue in document chooser table

### PR DESCRIPTION
**Pull request by shauryapanchal**
Refering to #12390 the deprecated code has been fixed with new preferred way as requested.. Works fine

### CODE REVIEW

**Review by laymonage — COMMENTED** [review]
Thank you, but there is already an open PR with the same changes: #12430.

Edit: OK, I just noticed you left a comment earlier in the issue.

**Comment by laymonage** [comment]
Thank you, but there is already an open PR with the same changes: #12430.

**Comment by shauryapanchal** [comment]
@laymonage is it alright to get merged?

**Comment by gasman** [comment]
Thanks @shauryapanchal! Merged in 97fadba58293d34080887d894b0ee9817719a420.

(Just a tip for future pull requests - I'd recommend starting a new branch before committing any changes. That way, the commits won't be on the `main` branch, and will avoid being mixed in with any later pull requests you create.)

**Comment by shauryapanchal** [comment]
Thanks @gasman I'll keep that in mind from now on.. This was my beginning with open-source contributions.. It's been a pleasure..

**Pull request closed without merging**
