### PR TITLE
Refactor page chooser into a react component

### PR DESCRIPTION
**Pull request by kaedroho**
This pull request refactors the page chooser into a react component that pulls its data in over the Admin API.

This should (hopefully!) simplify the chooser code quite a bit. It removes all the passing of HTML around and the need to `eval()` on snippets of Javascript (which is reported as an Issue #1288 #3011). It also feels a bit faster too (local testing).

There should be no behavioural changes and I've not attempted to change any of the HTML/CSS (beyond what is required for the refactoring).

### CODE REVIEW

**Comment by sebworks** [comment]
Is there a timetable on converting to React?

**Comment by thibaudcolas** [comment]
FYI I had to build something similar for one of my projects so I rebased the existing branch, and did some cleanup / refactoring. This work is available at https://github.com/springload/wagtail/tree/react-page-chooser-rebased.

The rebasing was simple – I did a `git rebase -i master` and completely dropped all of the commits until the first one from @kaedroho. From there, the only difference in the page chooser is the implementation of `user_perms` (parameter forwarded in the chooser URL).

I'll stop there, the code that I write next may depart from what Wagtail needs so I'll keep it separate.

**Comment by kaedroho** [comment]
Thanks @thibaudcolas. I've just updated this branch to use yours (previous version [here](https://github.com/kaedroho/wagtail/tree/react-page-chooser-old))

**Comment by thibaudcolas** [comment]
If anyone stumbles upon this and is interested in helping making this happen, I'd love to help.

Generally when people ask how to extend the link chooser UI I point them at this PR as a way forward (e.g. for tel links, #5086, nofollow attr #4474).

**Comment by kaedroho** [comment]
I've marked up all the strings for translation now and added the translation catalog JS file so we can retrieve translated strings in the frontend.

One problem is that the chooser is in the "client" folder which means it's not in an app so Django's makemessages won't pick up any of the strings.

**Comment by kaedroho** [comment]
I've reverted the above change and redone translations to use the existing method.

**Comment by kaedroho** [comment]
I think all that's left to do on this now:

 - [ ] Open/close fade animation
 - [ ] Accessibility

**Comment by kaedroho** [comment]
This is ready for review now!

**Comment by zerolab** [comment]
Note: this requires someone with React knowledge to review.

One thing that stays at the back of my mind as a non-React developer is.. how does one go about building upon these?

**Comment by kaedroho** [comment]
> One thing that stays at the back of my mind as a non-React developer is.. how does one go about building upon these?

Currently the aim is just to get the current page chooser (that isn't itself customisable) working in React. Wll have to answer this when we get to implementing other choosers such as the link chooser which does allow adding tabs. What I have in mind at the moment is to allow modals to be a hybrid of React and AJAX (so you could create a modal that has a react based image chooser with an AJAX-driven Upload tab, for example).

**Pull request closed without merging**
