### PR TITLE
Add preferred naming convention of `classname` to coding gudelines + refine some existing usage

### PR DESCRIPTION
**Pull request by lb-**
- See https://github.com/wagtail/wagtail/issues/8885
-   [X] Do the tests still pass?
-   [X] Does the code comply with the style guide?
-   [X] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [X] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

I have attempted to not change too much, these are some smaller / newer code items that seemed like quick wins. The primary goal of this PR is to provide a guideline for future code.

* `dialog_toggle` - this component was new in Wagtail 3.0 but not actually used, only has started to be used in 4.0 code and not documented (outside of UI styleguide).
* `paginate` - not documented, small change
* `tab_nav_link` - relatively new include (3.0) - used as part of the tabbed interface code
* `side_panel_button` - relatively new (3.0) - no existing usage of the variable in code but still good to call out in release notes

**Proposed documentation update**

* Some shared template tags or shared template inclusions have had their `classname` variable updated to be more predictable.
* `{% dialog_toggle classnames='button button-primary' %}` should now be `{% dialog_toggle classname='button button-primary' %}`
* `{% paginate pages base_url=pagination_base_url classnames="navigate-pages" %}` should now be `{% paginate pages base_url=pagination_base_url classname="navigate-pages" %}`
* `wagtail/admin/templates/wagtailadmin/shared/tabs/tab_nav_link.html` now accepts `classname` and not `classes`
* `wagtail/admin/templates/wagtailadmin/shared/side_panels/includes/side_panel_button.html` now accepts `classname` and not  `classes`

### CODE REVIEW

**Comment by lb-** [comment]
Rebased

**Comment by lb-** [comment]
This is getting a bit painful to keep rebasing - will close for now and flag for discussion at the core team.

**Comment by gasman** [comment]
@lb- We discussed this in Wednesday's core team meeting, and there are no objections to going ahead with this. Sorry for letting it sit around a while - if you're happy that this is in a reviewable state, I'll commit to reviewing it in the next week and deal with any rebasing / final tweaks to get it over the line.

I don't think any of these changes affect public documented APIs - if they do, we ought to put a deprecation process in place - but it's probably still worth noting them in the upgrade considerations if there's a chance of the old names appearing in third-party code.

**Comment by lb-** [comment]
Marking as draft - will rebase and clean up issues + add release notes callout.

**Comment by lb-** [comment]
Rebased, fixed up & ready for review - upgrade considerations added & tests all passing.

I have also manually checked each other template/include usage updated by this PR for any recent changes - all looks good.

**Comment by gasman** [comment]
Merged in 30585340fd020391aae6d406b02aea4ab73c4177

**Comment by lb-** [comment]
Thankyou Matt

**Pull request closed without merging**
