### PR TITLE
Add the ability to globally disable the "Upload" tab for images and documents

### PR DESCRIPTION
**Pull request by RealOrangeOne**
As a sort-of solution to https://github.com/wagtail/wagtail/issues/8185, this PR adds the ability to disable the "Upload" tab for the images / documents chooser. This forces editors to upload images through the "Images" or "Documents" screens, accessible from the sidebar. It intentionally reuses the same codepaths as if a user didn't have permission to upload, to save duplication.

For obvious reasons, this is enabled by default!

This does slow down UX, but enables permissions checks around the images / documents it's possible to "choose" to be internally consistent.

### CODE REVIEW

**Comment by lb-** [comment]
Thanks @RealOrangeOne - I have seen requests for this in StackOverflow/slack in the past. 

However, it might be nice to see if we can add this functionality without a new setting, 

Maybe the chooser panel takes an arg?
This is used to add a url param to the chooser url
Which is then used to change the tabs that are shown. 

An alternative approach is to put this on the image model as a class method - but this means you have to have a custom image model to change this so probably not ideal.

Another alternative approach would be a hook or an extra arg that gets passed into an existing hook, like an options dict. Modify that option inner value to get the custom behaviour. 

Not necessarily saying these are the way to do this but adding one global setting is probably not the way to go. 

It would be nice to solve for documents in isolation of images, remember that Wagtail can be used with these applications in isolation and not all requirements will match across the two areas.

**Comment by RealOrangeOne** [comment]
Separating the settings probably makes sense, and it more widely usable.

I think the idea of allowing it to be configured on a per-panel level definitely sounds useful, but is a slightly different requirement from what I have here. I want to turn it off _everywhere_, in which case having to specify it for each panel is quite a pain, particularly if they're from 3rd-party packages.

A hook which runs per panel could work, but adds more function calls potentially unnecessarily. 

A method on the image is almost certainly overkill for this, and as you say requires a custom model. 

Personally, I still think this change is useful (post split), but I can definitely see a value of _additionally_ allowing it to be controlled on a per-panel level, but that feels out-of- scope.

**Comment by lb-** [comment]
Sorry for no response on this, I'll post in core team to see if there are any other opinions. If all good, let's try to get this in. It'll need a rebase though sorry.

**Comment by lb-** [comment]
@RealOrangeOne thoughts in the core team chat are that this is probably not the best way forward here. 

It may be good to close this PR and get a bit more consensus on the original issue and a way forward. 

Reasoning

- This may not really be a bug (as per comments on issue)
- Feels like a potential too niche use case
- Other workarounds exist (hide with CSS) / change image form to behave differently

**Pull request closed without merging**
