### PR TITLE
Fix display property used on The CommentControl's ToolbarButton

### LINKED ISSUE #11302: CommentControl toolbar button stacks when registering a new Draftail toolbar button to the control group.
### Issue Summary

The Comment control's toolbar button is wrapped in a span element which is given the property `display: block` instead of `display: inline-block` which is applied to normal `Draftail-ToolbarButton` buttons. This results in Toolbar Buttons stacking when adding a new ToolbarButton to the control group (i.e. `Draftail-ToolbarGroup`).

<details>
<summary>Screenshot</summary>
<br>
The button displaying above the comment button is a new control button using the normal `Draftail-ToolbarButton ` class.
Screenshot 2023-12-04 at 11 56 33
</details>

### Steps to Reproduce

Register a new control button following https://docs.wagtail.org/en/stable/extending/extending_draftail.html#custom-toolbar-controls docs however registering the component using the `inline` prop within draftail instead of `meta` as per the example in the docs.

```
window.draftail.registerPlugin(
  {
    type: 'new-control',
    inline: Component,
  },
  'controls',
);
```

Instead the comment control button should display inline with any newly registered controls.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes (using the bakerydemo and on a seperate project which can be seen here https://github.com/wagtail/wagtail-ai/pull/31#discussion_r1407458557)

### Technical details

-   Python version: Not relevant
-   Django version: Not relevant
-   Wagtail version: Tested on 5.2.1
-   Browser version: All browsers and versions as `display: block` behaves as expected.

### PR DESCRIPTION
**Pull request by Morsey187**
Fixes #11302 

<details open>
<summary>Before</summary>
<br>
Screenshot 2023-12-04 at 12 22 37
Screenshot 2023-12-04 at 12 22 41
</details>

<details open>
<summary>After</summary>
<br>
Screenshot 2023-12-04 at 11 24 30
Screenshot 2023-12-04 at 11 24 44
</details>

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by lb-** [comment]
Thanks @Morsey187  - I have marked as needs review.

**Review by laymonage — APPROVED** [review]
I think this makes sense, especially looking at how all the other buttons in the toolbar use `inline-block`. My guess is that this was added to hide the comment button with `display: none` when the feature is disabled in the settings, but incorrectly assume that it should use `display: block` when it's shown.

## Before

image

image


## After

image

image

Thank you!

**Comment by laymonage** [comment]
- `main`: 09d69d1
- `stable/5.2.x`: caf68095b13d536c8ecc5c76cd9195ed370dcfdb

**Comment by thibaudcolas** [comment]
Congratulations @Morsey187 on a first ever PR to Wagtail! 😌

**Pull request merged**
