### PR TITLE
Control non-Wagtail models indexing with ReferenceIndex

### PR DESCRIPTION
**Pull request by dkirkham**
Addresses #9731.

This PR adds a new Wagtail hook enabling (typically) non-Wagtail models in a project to be ignored when updating and maintaining the Wagtail `ReferenceIndex`. 

During development I noticed there were no tests for the existing `wagtail_reference_index_ignore = True` functionality, so I've added some for that. I've also added a small documentation section, as the only documentation for `ReferenceIndex` was in the release notes.

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [x] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

To test in a project, ideally one with several non-Wagtail apps, set up a `wagtail_hooks.py` with something like this:

```python
from wagtail import hooks

@hooks.register("register_reference_index_ignore")
def reference_index_ignore(ignore_list):
    ignore_list.extend([
        "my_app",
        "my_second_app.data_entry",
    ])
    return ignore_list
```

where the entries are either app_label or app_label.model, as recorded in the Django ContentTypes registry.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by lb-** [comment]
@dkirkham thanks for this, would it be possible for you to split the PRs into two, one that adds the new suggested behaviour and the other that covers testing/documentation of existing behaviour?

Specifically, a standalone PR for these items as described..

> During development I noticed there were no tests for the existing wagtail_reference_index_ignore = True functionality, so I've added some for that. I've also added a small documentation section, as the only documentation for ReferenceIndex was in the release notes.

It will make it easier to approve the existing behaviour PR and then there can be discussion on the new changes without blocking the other items.

**Comment by dkirkham** [comment]
Sure @lb-, I'll start two fresh PRs from the current main, given there is now a conflict.

**Comment by dkirkham** [comment]
Hi @lb-, I've split this PR - it can be closed once the new PRs have been labelled.

**Comment by zerolab** [comment]
Closing as superseded by #9935 and #9936

**Comment by lb-** [comment]
Thanks for splitting this out @dkirkham

**Pull request closed without merging**
