### PR TITLE
Add release dates to release notes

### PR DESCRIPTION
**Pull request by hughrawlinson**
_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [x] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

Add release dates to release notes per #8691 

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by hughrawlinson** [comment]
[Here's the script I used, in case it needs changing](https://gist.github.com/hughrawlinson/0d4a0842e29ea2ec87b65e231d0c42ee).

**Review by gasman — APPROVED** [review]
Awesome, thanks! :-)

**Comment by gasman** [comment]
Merged in 8e4a4fae5df1d77f752f4a476783bf81804e490e

**Comment by hughrawlinson** [comment]
Hi! This change [doesn't seem to have made it to the actual website](https://docs.wagtail.org/en/stable/releases/2.15.5.html) - how does that process work?

**Comment by gasman** [comment]
@hughrawlinson They're showing on the 'latest' branch of the docs (https://docs.wagtail.org/en/latest/releases/2.15.5.html), and it'll be updated on 'stable' when the 4.0 release happens (probably mid next month). readthedocs hosting has the minor quirk that the stable and version-specific branches of the docs only get built when a new tag is pushed, which in practice means they don't get updated outside of actual releases.

**Pull request closed without merging**
