### PR TITLE
Fix query search in filtered image admin listing

### PR DESCRIPTION
**Pull request by ParitoshKabra**
Issue-Id: [8029](https://github.com/wagtail/wagtail/issues/8029)

Do the tests still pass? (https://docs.wagtail.org/en/latest/contributing/developing.html#testing): **Yes**
Does the code comply with the style guide? (Run `make lint` from the Wagtail root): **Yes** 
For Python changes: Have you added tests to cover the new/fixed behaviour? : **Yes**

Please list the exact browser and operating system versions you tested: WSL2 Kali Linux (Debian) over Windows 10 21H2
Browser Settings, Chrome 99.0.4844.51 (Official Build) (64-bit)

### CODE REVIEW

**Comment by ParitoshKabra** [comment]
Hey @lb- ! Please have a look once at this PR 😅

**Comment by lb-** [comment]
@ParitoshKabra please can you clarify which issue this fixes. 

Your title seems to infer that this fixes - https://github.com/wagtail/wagtail/issues/4073

But your issue ID is https://github.com/wagtail/wagtail/issues/8029

It looks like it is fixing 8029 but just wanted to confirm, if that is true could you update the title.

**Comment by ParitoshKabra** [comment]
This fixes the linked issue. I will update the title. Sorry for inconvenience 😅

**Comment by lb-** [comment]
No problems. Just wanted to understand.

**Comment by ParitoshKabra** [comment]
hey @lb- any comment on this??

**Comment by lb-** [comment]
Haven't reviewed yet. It has been flagged as 'needs review' so myself or another team member will get to it when they can

**Review by lb- — APPROVED** [review]
Thanks @ParitoshKabra  sorry it took so long but this fix is great - thank you for adding unit tests so it does not break in the future!

**Comment by lb-** [comment]
I have pushed to your branch remotely - will ensure the CI passes and merge this in.

**Comment by lb-** [comment]
CI error does not seem to be related to this change - running linter locally seems ok.

```
#!/bin/bash -eo pipefail
pipenv run flake8

There was a critical error during execution of Flake8:
plugin code for `flake8-print[flake8_print]` does not match ^[A-Z]{1,3}[0-9]{0,3}$

Exited with code exit status 1

CircleCI received exit code 1
```

**Comment by lb-** [comment]
Thanks for making your first contribution to Wagtail @ParitoshKabra

I have put your name in as `Paritosh Kabra`, please let me know if you want a different name listed.

**Comment by ParitoshKabra** [comment]
Thanks @lb- !

**Pull request merged**
