### PR TITLE
Djangos URLFeld is limited to 200 characters, and some thumbnail valu…

### PR DESCRIPTION
**Pull request by kevinhowbrook**
…es are larger. This is causing an issue with embeds.

### CODE REVIEW

**Comment by ababic** [comment]
Hi @kevinhowbrook. Django's URLField has a default `max_length` of `200`, but it isn't a hard limit. Like many of Django's built-in field types, you can specify an alternative `max_length` value as required. I think that might be a better approach to take here, rather than changing the underlying field type.

How long are the URLs you are seeing?

**Comment by thibaudcolas** [comment]
Relevant: #1985.

**Comment by ababic** [comment]
Thanks @thibaudcolas. I've posted some thoughts there, so that the conversation is in one place.

**Comment by kevinhowbrook** [comment]
> Hi @kevinhowbrook. Django's URLField has a default `max_length` of `200`, but it isn't a hard limit. Like many of Django's built-in field types, you can specify an alternative `max_length` value as required. I think that might be a better approach to take here, rather than changing the underlying field type.
> 
> How long are the URLs you are seeing?

Largest I've seen is 230, I agree that just setting a higher limit on this will be enough. 
Having read https://github.com/wagtail/wagtail/issues/1985, I agree with:

> The simplest fix here is to set max_length=255 in the url field definition to increase the limit a little.

Because a) I haven't seen anything yet > 230 and b) MySQL knock-ons

It would be a good idea to provide better error handling here because without `debug=True` I think a publisher would just see a generic error screen. Not sure how much is going to be involved in that though, I'll investigate. For now, I'll suggest a limit on the field.

**Comment by ababic** [comment]
Thanks for this @kevinhowbrook. Just to be on the safe side (and to help guard against potential regressions), would you mind adding a very basic test to show that an `Embed` object can be created with a long `url` and successfully retrieved again using `Embed.objects.get()`? This should help spot any potential database-related issues.

**Comment by gasman** [comment]
This fix does feel a bit like kicking the can down the road - if 200-255-character URLs are an issue now, it's probably only a matter of time before >255-character URLs become an issue too. Since we're unlikely to be doing any lookups or validation on `thumbnail_url`, it's probably reasonable enough to change it to a `TextField`.

Having said that, there's no reason not to accept this as an immediate solution, so I'll go ahead and merge. (I don't think we need an extra test here - while I'm usually an avid proponent of testing every functional change, a test for "can a `URLField(max_length=255)` store >200 characters" is self-evident to the point of being redundant, I think :-) )

**Comment by gasman** [comment]
Merged in 124827911463f0cb959edbb9d8d5685578540bd3

**Comment by ababic** [comment]
Thanks @gasman.

> while I'm usually an avid proponent of testing every functional change, a test for "can a URLField(max_length=255) store >200 characters" is self-evident to the point of being redundant, I think :-) 

The recommended test addition was more to make sure that the indexes are created okay in `mysql` (because of the column being used in a `unique_together`). I'm not so bothered about the column length itself, per-se.

**Comment by gasman** [comment]
@ababic We're only changing `thumbnail_url` here, which isn't part of the `unique_together` constraint. But yep, if we we're considering changing `url` too, that would be a fair point!

**Comment by ababic** [comment]
@gasman ah, of course! apologies for the confusion.

**Pull request closed without merging**
