### PR TITLE
Turn on strictPropertyInitialization and use declare for existing Stimulus controllers

### PR DESCRIPTION
**Pull request by thibaudcolas**
_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

### CODE REVIEW

**Comment by lb-** [comment]
Great solution @thibaudcolas - no push back from me.

**Review by lb- — APPROVED** [review]
Will merge this in - it's slightly more verbose but gives us the benefit of stricter checks with not too much overhead for Stimulus controllers.

**Comment by thibaudcolas** [comment]
Thank you @lb-! Sorry I forgot to fill in the description 🙄 

This follows how Stimulus documents their TypeScript support on https://stimulus.hotwired.dev/reference/using-typescript.

As I understand, though more verbose, it’s clearly more correct, as we want to only set the properties’ types and _not_ declare the properties as `undefined`.

**Comment by lb-** [comment]
Thanks @thibaudcolas

**Pull request merged**
