### PR TITLE
Add Fuzzy() search query class

### PR DESCRIPTION
**Pull request by nimasmi**
This adds a Fuzzy() search query, similar to the `wagtail.search.query.Phrase` added in Wagtail 2.10. This is supported only by the Elasticsearch backends.

Additionally, since fuzzy searching is computationally expensive, it is not possible with multiple fields, or when partial matching is enabled.

Elasticsearch documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html

To do:

- [x] add documentation
- [x] deal with the deprecation timeline for partial matching (see [comment](https://github.com/wagtail/wagtail/pull/8498/#issuecomment-1151304643))
- [ ] consider handling other parameters, as per https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html#fuzzy-query-field-params

Example result from the Wagtail Bakery:

image

### CODE REVIEW

**Comment by lb-** [comment]
converted to draft as it was in the title - hope that is ok @nimasmi

**Comment by nimasmi** [comment]
I have noticed a side effect of this change is missing matches for multi-term search queries. In the Wagtail Bakery Demo site, searching for "black bread" returns results:

- Bread [Black bread](http://127.0.0.1:8000/breads/black-bread/)
- Blog post: [The Greatest Thing Since Sliced Bread](http://127.0.0.1:8000/blog/sliced-bread/)
- etc.

With the change:

```diff
-            search_results = Page.objects.live().search(search_query, partial_match=False)
+            search_results = Page.objects.live().search(Fuzzy(search_query), partial_match=False)
```

I can get a successful fuzzy match, searching for "back":

- Bread [Black bread](http://127.0.0.1:8000/breads/black-bread/)

but there is one result only, and no results at all for "back bread" or "black bread".

**Comment by nimasmi** [comment]
> I have noticed a side effect of this change is missing matches for multi-term search queries.

This was because the [`fuzzy` query](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-fuzzy-query.html) is a term-level query, whereas the full-text `match` query also supports a "fuzziness" parameter. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-match-query.html#query-dsl-match-query-fuzziness.

The results are closer to expectations with this set:

In the Wagtail Bakery Demo site, a fuzzy search for "back bread" now returns similar results to a standard search query for "black bread":

- Bread [Black bread](http://127.0.0.1:8000/breads/black-bread/)
- Blog post: [The Greatest Thing Since Sliced Bread](http://127.0.0.1:8000/blog/sliced-bread/)
- Blog post: [Bread and Circuses](http://127.0.0.1:8000/blog/bread-circuses/)

**Review by kaedroho — APPROVED** [review]
This all looks good to me, nice work!

**Pull request merged**
