### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by thibaudcolas**
Implements #10056 and #8883. Implements:

- A basic theme switcher in the user account view
- Setting the theme via classes on the HTML element
- Theme-agnostic design tokens for a light and dark theme
- Swap of most of Wagtail’s colors to the new design tokens

Missing (likely during feature freeze or in the next release):

- Contributor documentation about the theming
- Unit tests for theme tokens and CSS variables
- Dark theme applied to the userbar (not sure exactly whether this is a good thing or not)
- Fix contrast issues with error messages in red in the dark theme
- Changing the icon of comments to have the "outline" variant by default and "filled" on hover

---

To test this,

- Static demo site (supports `prefers-color-scheme` only): https://static-wagtail-v5-0.netlify.app/admin/
- Comparison screenshots of the light theme before-after: https://static-wagtail-v5-0.netlify.app/light-before-after/html_report/
- Side-by-side screenshots of the light and dark themes: https://static-wagtail-v5-0.netlify.app/light-vs-dark/html_report/

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Review by laymonage — APPROVED** [review]
Tested it on Chrome 112, Firefox 112, Safari 16.4 and it works as expected. The bugs I raised earlier have also been fixed. Awesome work!

**Comment by lb-** [comment]
@thibaudcolas  dark mode is looking amazing!

Just a heads up - it appears to have broken the styling of TableBlock & I assume Tables when used outside of a block.

Screenshot 2023-04-20 at 7 31 06 am

Background is white but text is also white, making it not possible to see what's being entered.

**Comment by thibaudcolas** [comment]
@lb- thank you for the heads’up, I had left the table out but didn’t realise the text was white as well 🤦 . Sage has addressed this, and I have a list of 10-15 other dark mode changes from design review which I’ll share on a new issue if you spot more.

**Comment by lb-** [comment]
Awesome, thank you. Again the dark mode looks amazing.

**Pull request merged**
