### PR TITLE
Implement pagination improvements(# 9102)

### PR DESCRIPTION
**Pull request by akshay-gupta7**
In response to issue #9102 :

- Inline JavaScript in https://github.com/wagtail/wagtail/blob/main/docs/_templates/search.html has been moved to separate external JS file
- onclick events has been replaced with addEventListener events
- Now one button per page is displayed, Page 2 of 7, along with a previous and a Next button

### CODE REVIEW

**Comment by akshay-gupta7** [comment]
Adding another PR with resolved lint errors

**Comment by zerolab** [comment]
@akshay-gupta7 you can push your changes to the existing branch `akshay-gupta7:pagination-update` and this PR should pick up the changes without the need to open a new PR

**Comment by akshay-gupta7** [comment]
@zerolab , thank you for the suggestion.
However, I have already opened a fresh PR. Let me if I should close the new one and reopen this PR.

**Comment by zerolab** [comment]
No need, it is done now. but do keep that in mind for the future.

**Comment by akshay-gupta7** [comment]
Definitely, shall keep this in mind @zerolab.

**Pull request closed without merging**
