### PR TITLE
Remove opacity property from unpublished page text

### LINKED ISSUE #5370: "Unpublished" styles in pages listings are very hard / impossible to see
### Issue Summary

In listing pages, Wagtail has styles for pages that are not published:

unpublished-styles

These are very hard to see – I’m not sure what value they bring, whether they should be removed altogether or switch to a visual indicator that is less subtle, and doesn’t rely on color alone.

### Steps to Reproduce

1. Go to the CMS admin
2. Create a page as draft, without publishing
3. Go to a listing view showing that page

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Wagtail version: 2.5a0, 2.6a0
* Browser version: latest Chrome

### PR DESCRIPTION
**Pull request by InjuMichorius**
Fixes #5370

### CODE REVIEW

**Review by zerolab — APPROVED** [review]
Tested locally and LGTM

**Comment by zerolab** [comment]
Nice one @InjuMichorius.
Merged in ac38343. Thank you for your first contribution to Wagtail 🎉

**Comment by InjuMichorius** [comment]
Thanks for the opportunity and clear explanation. Glad I could help!

**Comment by thibaudcolas** [comment]
Woo!

**Pull request closed without merging**
