### PR TITLE
ReferenceIndex model registration (rebase of #10339)

### LINKED ISSUE #9731: Additional control of models indexed with ReferenceIndex
### Is your proposal related to a problem?

`ReferenceIndex`, and its related management command, `rebuild_references_index` will by default find relationships between all models in one's project, unless the models have the attribute `wagtail_reference_index_ignore` set to `True`.

This method poses a difficulty for 3rd-party apps that are loaded as a package, but even for "in-house" apps, one ends up with some strange Wagtail configuration for an app that has nothing to do with Wagtail.

### Describe the solution you'd like

Another method that excludes apps or selected models is required, which is configured in the project-specific code, and not in the non-Wagtail app.

### Describe alternatives you've considered

Ideas suggested so far:
* a new Django settings attribute (eg. `settings.WAGTAIL_REFERENCE_INDEX_IGNORE`) which is a list of apps, models or regexes thereof; if there is a match, the model isn't indexed
* a function registered within `wagtail-hooks.py` which specifies models to ignore (as a list of apps, models, or regexes)
* a global optional callable that `ReferenceIndex` could use to get a list of models to index
* allow a child class of `ReferenceIndex` to be registered as the version that will be used for the indexing; the developer can then override `model_is_indexable()` within that child class to control the models to be indexed.

### PR DESCRIPTION
**Pull request by gasman**
Fixes #9731

#10339 rebased with the suggested tweaks from https://github.com/wagtail/wagtail/pull/10339#pullrequestreview-1392332999 applied. @dkirkham, if you have chance to check over the last two commits to check I've not done anything silly, that would be much appreciated! In particular, I couldn't get the tests to fail by reshuffling INSTALLED_APPS, so I'm not totally sure if the extra logic to connect up signals after `wagtail.apps.ready` has completed is actually having any effect...

### CODE REVIEW

**Comment by dkirkham** [comment]
Thanks @gasman. I did consider using two sets but thought it could be coded more tightly.

The reason for the app ordering caveat was my concern was that when running the tests, the signals get disconnected and connected more than in a normal execution.

I've had a quick look at your two latests commits and can't see a problem with it, but I won't be able to look deeply until later today - I have a string of early morning appointments and meetings to attend.

**Comment by dkirkham** [comment]
I had another look @gasman and felt that the ReferenceIndex.initial_signals_connected and associated code wasn't adding much value. I can't see any reason why the signal receivers can't be connected as each indexable model is registered.

So I've updated my original fork so that the receivers are set up as each model is registered for indexing, which I think makes the code a bit cleaner. All the tests still pass. I don't think I can update your fork, so see [05d5d4a](https://github.com/dkirkham/wagtail/commit/05d5d4a1cd729170d49bba93a15fcae31610d01a) for the changes.

**Comment by gasman** [comment]
@dkirkham Thanks! Yep, I'm on board with that fix - I guess I was wary that we might potentially have the opposite problem and end up calling register_model before the necessary initialisation had happened in wagtail.models. But calling that from 'ready' really should be safe, and it's not worth making things more convoluted for the sake of theoretical "what if"s 👍

**Comment by dkirkham** [comment]
Great, @gasman.

Since you own this PR now, it is a bit difficult for me to contribute code directly into it - so let me know what I can do from here.

**Comment by gasman** [comment]
Merged in 85c9b6689fa42bfdb53ba4eb1edf1a7d690f2cb2.

**Pull request closed without merging**
