### PR TITLE
Fixes #7768: Modify misspelled checkbox_aria_label

### LINKED ISSUE #7768: Error in wagtail/admin/templates/wagtailadmin/bulk_actions/listing_checkbox_cell.html
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The if clause of checkbox_aria_label appears to be misspelled as "checbox_aria_label"

### Steps to Reproduce

Not sure of the impact of this error. Noticed perusing the code.

### Technical details

* Wagtail version: 2.15.1

### PR DESCRIPTION
**Pull request by vupham04**
Fix #7768 misspelled checkbox_aria_label

* No extra failed test
* Code comply with style guide

### CODE REVIEW

**Review by jacobtoppm — APPROVED** [review]
Nice one, thanks for making this change!

**Comment by zerolab** [comment]
Thank you @vupham04. Merged in b529753

**Comment by lb-** [comment]
@zerolab I cannot see this fix added to the changelog, nor Vu Pham added to the contributors, just checking if I missed something (maybe a different name). I will add it to the changelog now if that is ok.

**Comment by lb-** [comment]
@gasman  this has been cherry picked into 2.15.x - as per the milestone added to https://github.com/wagtail/wagtail/issues/7768

cf9628567143f3ed65cbec443525f6698dcc8748

**Comment by zerolab** [comment]
thank you @lb- , not sure how I missed the changelog update 🤦🏼

**Pull request merged**
