### PR TITLE
Rearrange SCSS

### PR DESCRIPTION
**Pull request by nmorduch**
This PR is written as a step toward making changes called for in #3804. It moves the bulk of our styles to the `client` folder, and splits them into files approximately according to ITCSS.

The only changes to outputted CSS should be:
- The order of the styles
- `@font-face` is included in more CSS files because I grouped it with settings and tools. I'm not sure this is the right decision, but it does make the includes a lot simpler.

Replaces #4974

### CODE REVIEW

**Comment by jjanssen** [comment]
Hi @nmorduch,

For the time-being I am not sure on whether `datetimepicker.scss` and `tags.tagit.scss` should be a part of our actual components folder. The context of this file is an override to an existing CSS namespace to which we have no control over, so this would be possibly confuse future contributors in how we manage this folder. Perhaps _"Generic"_ is too generic for this (🥁-tsss) but it would make sense to target a separate vendors folder for this (thus being an additional folder on top of the regular ITCSS folder structure). This way everyday knows this is not only the Wagtail-code we are targeting.
Other than this small point of interest this looks a good first iteration!

PS: 
I have asked @hvandenberg to do some cross-browser testing of this PR somewhere this week.
We’ll probably get his report on the testdrive somewhere this week within this PR 👍

**Comment by nmorduch** [comment]
Sounds like a plan! I'll move those.

**Comment by nmorduch** [comment]
I ended up changing the `utilities` folder to `overrides` (like I'd always wanted tbh) and giving it three subcategories: `vendor`, `utilities`, and `pages`. This way we don't have to argue about different kinds of overrides and can have them all, at least for now :)

**Comment by tomdyson** [comment]
> I have asked @HvandenBerg to do some cross-browser testing of this PR somewhere this week.
We’ll probably get his report on the testdrive somewhere this week within this PR

@jjanssen do you know if there's been any progress with this?

**Comment by HvandenBerg** [comment]
I've been testing and so far have found two things:
- 404 errors in console regarding fonts not being loaded
- Layout 'off' on IE11 / Too far to the right (this is not the case when not on PR)

See img's:

**Comment by nmorduch** [comment]
Thank you, @HvandenBerg! I'm hoping to get to look into those problems this week.

**Comment by nmorduch** [comment]
I can't say I've been looking forward to figuring out what precisely is making that happen, so I certainly wouldn't complain if you wanted to (ie yes i would love a hand on that)

**Comment by jonnyscholes** [comment]
@nmorduch I'll have a look.

Is now a good time to solidify these opinions into [the CSS styleguide docs](https://github.com/wagtail/wagtail/blob/master/docs/contributing/css_guidelines.rst)? Or should we do that once the codebase is in a better state so we can more reasonably expect other developers to adhere to them...

**Comment by jonnyscholes** [comment]
I couldn't reproduce the font issues showing in the console of @HvandenBerg's screenshot in IE11... I wonder if there was a build error?

**Comment by jjanssen** [comment]
Hi Naomi and Jonny, 

I took the liberty of applying Jonny's PR to apply to this branch because ideally I would love to have this merged as soon as we can and I can probably can get Hugo to test it final this week. 

Aside from that I did some investigation into the font-issue. Right now this is caused as it is also rendered into subfiles like `css/layouts/home.css` whereas previously we only rendered the font-face definitions in `css/core.css`. When opening the homepage of the admin interface it tries to loads the font-set twice. Once from `css/core.css` (which resolves) and once from `css/layouts/home.css` which doesn't resolve (hence it only goes up two folders).

But I'm not sure on what the best practice would be to resolve it within this naming convention. Perhaps remove them from the general `_settings.scss` and only them to `core.scss`? I'm happy to hear your thoughts about this.

A screenshot from the difference between this branch and the latest master in terms of home.css:
image

**Comment by nmorduch** [comment]
Thank you for doing this, @jjanssen.

How fonts are included is one of the few things I did actually change substantially. The way it was done before was a bit confusing to me, and maybe I need to understand a little better how we go about including css files in the templates. I was thinking that pages get  either `main.css` _or_ another css file, but I see that I was wrong and they get `main.css` _and_ other css files. I will take a look at this later today. I hope just to be able to put in a commit that fixes the font situation, but I might have further questions since I'm seeing some inconsistencies around how the css files are included in the templates.

**Comment by thibaudcolas** [comment]
It's pretty cool to see all of those changes happening! What's the status of this PR @nmorduch @jjanssen @jonnyscholes?

Any other changes to Wagtail's styles will be creating conflicts for this refactor, so we should try not to keep this open for longer than necessary (otherwise it'll just become harder and harder to ever merge this).

**Comment by jonnyscholes** [comment]
@thibaudcolas I actually did some work on this late last week to resolve the font issues raised by @jjanssen. I'll clean it up and commit it tomorrow - you're right it would be great to get this merged sooner rather than later!

**Comment by jonnyscholes** [comment]
Turned out I'd already cleaned it up... Hope you don't mind @nmorduch but I've pushed up a fix for the fonts!

I've moved them out of `settings/_fonts.scss` and to the top of `elements/_typography.scss`. One nice side effect of this is settings now renders no CSS output so can be safely imported in any other file with no side effects. 

I did some testing and it looks like `core.css` is loaded on all pages and then some pages get an additional css file loaded. The commit just added should mean the fontface rules are only ever in `core.css` :)

**Comment by jjanssen** [comment]
I think we're nearly there. Could we close this PR and create a new one so @HvandenBerg can benefit from using our new Squash tooling for that? It will save him the hassle to re-checkout this branch, build it, etcetera.

**Comment by nmorduch** [comment]
This has been replaced by #5215

**Pull request closed without merging**
