### PR TITLE
Fix version number label obscuring menu items in Settings submenu

### PR DESCRIPTION
**Pull request by Igoranze**
If you have a lot of items in the Settings submenu, then the footer breaks some of the items.
You can see in the gif below that the footer should be fixed at the bottom of the screen, but instead the footer is moving the more items are added.

bug

Fixed this by adding the `position: sticky;` and `max-height: unset;` to the new class `footer-submenu`. This way the footer is always shown after the last item on the submenu. But now when the height of the page is smaller than the items, the footer is sticky to the bottom of the browser, and none of the items are broken by the footer.

fixed

Tested with:
Safari: Version 13.0.1 (14608.2.11.1.11)
Firefox: 69.0.2 (64-bit)
Opera: Version:63.0.3368.107
Chrome: Version 77.0.3865.90 (Official Build) (64-bit)

### CODE REVIEW

**Comment by gasman** [comment]
Thanks @Igoranze! This will fix #5358.

**Comment by Igoranze** [comment]
Cool @gasman, thanks for the quick response. I was not aware of the existing issue.

**Comment by rinti** [comment]
I'm not sure what the lowest version of browsers Wagtail targets, but `position: sticky` [is not available in IE11](https://caniuse.com/#feat=css-sticky).
I don't really see the value in it being sticky though, in my opinion it could just be the last item of the list - no need to attach to bottom.

**Comment by gasman** [comment]
@rinti Wagtail's browser support is documented at http://docs.wagtail.io/en/stable/contributing/developing.html#browser-and-device-support - there are already a few limitations in IE11 support noted there.

**Comment by lb-** [comment]
Awesome work @Igoranze  - I made one minor tweak to get this working well in IE 11 (position relative on the outer scrolling container) and validated on:

IE 11 (windows)
Edge (windows)
Firefox (mac)
Chrome (mac)


This has been merged in a459e91692659aba04e662978857d14061aecaee

**Comment by gasman** [comment]
Unfortunately this change causes the footer to no longer be bottom-aligned when the menu is shorter than window height:

Screenshot 2020-01-17 at 12 51 39

While this is only a cosmetic issue, I'd rather avoid any regressions in the out-of-the-box setup given that the bug being fixed here is only really an edge case. Reverted for now in 590bea3b7b47f0bdf90a1557057bd37e04bfd0e8

**Comment by Stormheg** [comment]
This was fixed by https://github.com/wagtail/wagtail/pull/5927 and released in the 2.9 release.
We can close this now :)

**Pull request closed without merging**
