### PR TITLE
Adds mark_safe to the render_form method of StructBlock

### PR DESCRIPTION
**Pull request by bmoe872**
# What this does
Addresses: https://github.com/wagtail/wagtail/issues/5686

Adds `mark_safe` around the `render_form` method of the struct block. 

Jinja2 doesn't seem to return "safe" html, and instead is returning a string of the content, when it really should just be returning the HTML.

### CODE REVIEW

**Comment by gasman** [comment]
Thanks @bmoe872! Could you add a test for this, please?

**Comment by bmoe872** [comment]
@gasman I've added tests that test the Jinja2 rendering engine works with the addition of the `mark_safe` around the `render_to_string` method, and I noticed that there didn't seem to be any tests testing the functionality of a custom form using the Django template engine, but I'm running into some unexpected behavior that I was hoping you might be able to help shed some light on. 


When using the same approach as I have for testing the Jinja2 engine, the Django engine instead throws an error:
`AttributeError: 'Template' object has no attribute 'split'`


I can't seem to find much to shed any light on what is causing this to happen, and having stared at this for most of the day at this point I'm hoping you might have some insights into what's going on, or if its even needed to test custom `form_template` functionality against the Django template engine?

**Comment by bmoe872** [comment]
@gasman I've added tests, and I noticed in testing that there wasn't a test for testing the functionality of adding a custom form template against the Django template engine, so I added a test for that as well.

**Comment by gasman** [comment]
Thanks again @bmoe872! Merged in f8c7d7f5f77b1bb933f0d6a7899e2450f01d373f.

**Pull request closed without merging**
