### PR TITLE
Fix Removing Metadata in API

### LINKED ISSUE #10411: Bug with removing meta fields from API
### Issue Summary
The `_get_serializer_class` method of the `BaseAPIViewSet` class implements this code snippet which causes some (probably) unexpected errors when removing the meta fields.

```python
        all_fields = body_fields + meta_fields

        # Remove any duplicates
        all_fields = list(OrderedDict.fromkeys(all_fields))

        if not show_details:
            # Remove detail only fields
            for field in cls.detail_only_fields:
                try:
                    all_fields.remove(field)
                except KeyError:
                    pass
```

`all_fields` is converted to a `list` but then a few lines down, we try to handle `KeyError`. The list will never give a `KeyError`, but rather `ValueError: list.remove(x): x not in list`.
This can cause weird behavior when you try to remove meta fields, for instance.

### Steps to Reproduce

1. Create the following custom `APIViewSet`
```python
class BlogAPIEndpoint(PagesAPIViewSet):
    base_serializer_class = PageSerializer

    body_fields = [
        'title',
    ]

    meta_fields = []
```
2. Register the endpoint with the custom View Set: `api_router.register_endpoint('blog', BlogAPIEndpoint)`
3. Try to call the endpoint to get the results. You will get the error.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: `Python 3.8.1`.
-   Django version: `4.1.7`.
-   Wagtail version: `4.1.2`.
-   Browser version: irrelevent.

### PR DESCRIPTION
**Pull request by henryh9n**
Fixes #10411 

## Brief Issue Description
When trying to remove the `meta_fields` (also modify those, or possibly in many other cases) with the following snippet: 
```python
class BlogAPIEndpoint(PagesAPIViewSet):
    base_serializer_class = PageSerializer

    body_fields = [
        'title',
    ]

    meta_fields = []
```
you might get `ValueError: list.remove(x): x not in list`.

This is caused by the following code:
```python
        all_fields = body_fields + meta_fields

        # Remove any duplicates
        all_fields = list(OrderedDict.fromkeys(all_fields))

        if not show_details:
            # Remove detail only fields
            for field in cls.detail_only_fields:
                try:
                    all_fields.remove(field)
                except KeyError:
                    pass
```
Since `all_fields` is converted to a `list`, removing an item from the list that does not exist is causing a `ValueError`, but not a `KeyError`.

## Solution
Instead of checking for the `KeyError` in exception handling, I've modified the code to check for the `ValueError`.

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [x] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]~~
    -   [x] **Please list the exact browser and operating system versions you tested**:
    -   [x] **Please list which assistive technologies [^3] you tested**:
-   [x] For new features: Has the documentation been updated accordingly?

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by lb-** [comment]
@henryh9n thanks for this, it seems like a good change and I think the use case for empty meta fields makes sense. 

Would you be able to add some unit tests to ensure that this behaviour is going to stay supported in the future.

**Comment by lb-** [comment]
@henryh9n just checking in, are you still keen to pursue this fix? We would love to see some tests so we can review this.

**Comment by henryh9n** [comment]
@lb- Hi LB!
Yeah, adding some tests for the API part will be nice. As far as I can see, the whole part needs to be covered.
Unfortunately, I did not have much time lately. I'd love to do it sometime, but I need to figure out the timing. 
However, if someone wants to jump in and do it in the meantime, or if we decide to move this into a separate issue, I'd be glad.

**Comment by lb-** [comment]
Thanks for the response @henryh9n  - someone may pick this up, I'll post in new-contributors to see if anyone is keen.

**Comment by lb-** [comment]
Superseded by #10638

**Pull request closed without merging**
