### PR TITLE
Fixed autofill changing admin text input bg-color from dark to light

### LINKED ISSUE #11309: Using browser autofill in admin text input field changes theme from dark to light
There's a minor style bug that changes the theme on input fields when using the browser auto-complete feature:

1. Start position - focus on text input with autocomplete value
image

2. Hover over suggested value - input changes to light theme (input text font changes to system default too, but I think this is a Chrome issue)

image

3. Select value. Theme remains on light, including after moving focus away from input

image

If I edit the input box after using the selected value, the theme returns to dark:

image

Looking at the color style before and after, I see the following:

Before:

image 
image

After:

image 
image

Looks like it's the `input:-internal-autofill-selected` that changes the colours due to the `!important` flag.

```css
input:-internal-autofill-selected {
    ~~appearance: menulist-button;~~
    background-image: none !important;
    background-color: -internal-light-dark(rgb(232, 240, 254), rgba(70, 90, 126, 0.4)) !important;
    color: fieldtext !important;
}
```

I have confirmed that this issue can be reproduced as described on a fresh Wagtail project

### Technical details

-   Python version: 3.12
-   Django version: 4.2.7
-   Wagtail version: 5.2.1
-   Browser version: Chrome 119

### PR DESCRIPTION
**Pull request by gdas37467**
Fixes #11309

Before:
before

After:
after

_Please check the following:_

- [x] Do the tests still pass?[^1]

-   [x] Does the code comply with the style guide?
    -   [x ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [x] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [x] **Please list the exact browser and operating system versions you tested**:
    -   Ubuntu22.04
    -   Firefox 116.0
    -   Chrome 120.0
    -   [ ] **Please list which assistive technologies [^3] you tested**:

### CODE REVIEW

**Comment by gdas37467** [comment]
I need a review for this PR, if this PR works as expected please merge it, otherwise kindly let me know.

**Comment by zerolab** [comment]
@gdas37467 thank you for this PR. We will get to checking/testing this PR hopefully soon.
As you may be aware the period around Christmas tends to be a quiet one as a fair amount of people have some time off and tend to rest with friends and family away from computers.

**Review by thibaudcolas — COMMENTED** [review]
Hi @gdas37467, thank you for giving this a go :)

I’m surprised we’d use this kind of technique over the standard [color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) property, which would allow Chrome’s auto-fill to keep displaying its system colors, while picking a more appropriate theme.

I’ll investigate this more and proceed with either your solution or `color-scheme`.

**Comment by thibaudcolas** [comment]
@gdas37467 I have decided to close this in favour of #11463, with the use of `color-scheme`. I don’t think it’s safe for us to override browser UI when there is a standardised way to do this instead.

**Pull request closed without merging**
