### PR TITLE
fix: Status tag in page explorer should have a font size in rem rathe…

### PR DESCRIPTION
**Pull request by 4the4ryushin**
…r than pixels #9363

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [x] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [x] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by zerolab** [comment]
Hey @4the4ryushin, thank you for your contribution.
It is however a duplicate of #9382 and @maryojo mentioned working on this in https://github.com/wagtail/wagtail/issues/9363#issuecomment-1279259415

Will close it on that basis.

**Comment by 4the4ryushin** [comment]
yea , i got aware of that , infact i would like apologize i did without even checking in , looking forward to contribute more !!

**Comment by 4the4ryushin** [comment]
> Hey @4the4ryushin, thank you for your contribution. It is however a duplicate of #9382 and @maryojo mentioned working on this in [#9363 (comment)](https://github.com/wagtail/wagtail/issues/9363#issuecomment-1279259415)
> 
> Will close it on that basis.


yea , i got aware of that , infact i would like apologize i did without even checking in , looking forward to contribute more !!

**Comment by zerolab** [comment]
No worries at all. Looking forward to more contributions ;)

**Pull request closed without merging**
