### PR TITLE
Update the release URL to the new .org domain

### PR DESCRIPTION
**Pull request by RealOrangeOne**
As a part of https://github.com/wagtail/wagtail/issues/7841, we need to update which domain is primarily used to receive emails for the Wagtail project.

Note: There may be CSP ramifications of changing this domain, which will need to be made obvious in the release notes

## To do

- [x] Create new infrastructure to serve `releases.wagtail.org`, ensuring existing permissions and access are maintained.
- [x] ~~Confirm `latest.sh` is runnable by those who need to, and makes the relevant changes.~~ No changes necessary, see below
- [x] ~~Confirm frontend code will transparently deal with redirects to new domain~~ Old domain will not redirect due to CORS issue, will continue to serve assets normally as before.

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
Because of everyone's favourite CORS, the redirect unfortunately doesn't work. I'm instead going to update the configuration such that rather than a redirect, both domains just serve the same content, which both simplifies configuration and removes the need for a redirect.

The release process will not change.

**Review by lb- — APPROVED** [review]
Looks good. Thanks @RealOrangeOne

**Comment by RealOrangeOne** [comment]
Due to the CSP issues mentioned above, this could be considered a breaking change.

**Comment by lb-** [comment]
@RealOrangeOne added a checklist item to https://github.com/wagtail/wagtail/issues/7841 so we do not forget to do this.

**Pull request merged**
