### PR TITLE
WIP - Add image rotation in image edit screen. (#2901)

### PR DESCRIPTION
**Pull request by mrchrisadams**
I've added this after a quick chat with @thibaudcolas at Wagtail space, to help resolve [issue 2901](https://github.com/wagtail/wagtail/issues/2901), giving us a way to rotate images in the server UI.

### WIP tag removal checklist

- [ ]  Do the tests still pass? (http://docs.wagtail.io/en/latest/contributing/developing.html#testing)
- [x]  Does the code comply with the style guide? (Run `make lint` from the Wagtail root)
- [x]  For Python changes: Have you added tests to cover the new/fixed behaviour?
- [x]  For front-end changes: Did you test on all of Wagtail’s supported browsers? **Please list the exact versions you tested**.
- [x]  For new features: Has the documentation been updated accordingly?

### Da current plan 

- [x] add a basic, unstyled rotate button
- [x] add some js to increment the rotate element when the button is pushed
- [x] add rotate field to the image edit form
- [x] add a code for calling `rotate()` when a user submits the form

When the button is pushed, and we update the rotate value, we use a bit of CSS to add a transform to the image, and animate it using a CSS transition to make it for a user to see what just happened (rotating is a bit jarring without this).

CSS transforms and transition animations seem to well supported, and it saves us needing much in the way of extra js dependencies:

https://caniuse.com/#search=transform
https://caniuse.com/#feat=css-animation

### CODE REVIEW

**Comment by thibaudcolas** [comment]
👍 current WIP for reference: https://github.com/simo97/wagtail/commit/ef404c775559722b9ad6be61a2cc6d6ca6ed8f69.

**Comment by mrchrisadams** [comment]
Okay, I think I might need some pointers here on how best to call the new methods on Willow that I added in a previous PR.

### What I think I need to do

I see examples here where you encapsulate a call to willow, by using a context manager, and then calling the Willow method like so:

```python
def get_suggested_focal_point(self):
        with self.get_willow_image() as willow:
            faces = willow.detect_faces()
```

I'm assuming we'd need to do something similar - when we see a rotation in the `request.POST` dict, we'd need to: 

- call some kind of `image.rotate(DEGREES)`  method, that calls willow in a context manager the same way
- save the updated image
- make sure the updated image triggers an update of all the renditions reliant on it

Sound about right?

**Comment by mrchrisadams** [comment]
Okay, spoke to @gasman .

It looks like where we currently save a new image and set hashes, these might be better off in the image. This way, when we call `form.save()` in `wagtail.images.views.edit`, we can can encapsulate the fact that we're saving a form submission, and the view method doesn't need to know whether the form is being updated vs rotated.

https://github.com/wagtail/wagtail/blob/master/wagtail/images/views/images.py#L99

In `imageform.save`, we'd move some of this logic currently in the view like this:

```
if 'file' in form.changed_data:
                # Set new image file size
                image.file_size = image.file.size

                # Set new image file hash
                image.file.seek(0)
                image._set_file_hash(image.file.read())
                image.file.seek(0)
```

Into the form behaviour, and do our check for rotation there, rather than having to mess around with with calls to `form.save()` with `commit=false` and so on,

Thanks Matt!

**Comment by mrchrisadams** [comment]
Alright - I've tested this with the following browsers:

- OS X Firefox - v67
- OS X Chrome - v73
- OS X Safari - v 12.1

I've also added some basic docs - I didn't add a new screenshot, as I wasn't sure about the numbering conventions for the images because they have a numeric naming scheme like `screen32_image_edit_page.png`, I didn't want to mess with this when adding my onw.

I think the last steps here would be to clean up the commits, and see why the tests are failing - since I rebase onto master there's some new bits I think I need to update to get these green again, then I'll remove the WIP tag.

**Comment by lb-** [comment]
@mrchrisadams  - thanks for all the epic work on this, would be great to see this ready to be reviewed fully if you have time to get the last bits done & cleaned up.

In regards to the docs images, I reckon just create one, if the numbers don't line up when this gets merged in one of the core team can rename then to avoid conflicts.

For now we are converting all PRs with WIP in the title to drafts, the CI will still run but helps us have a clearer view of items needing actions. 

Feel free to make a non-draft once this is good to get a full review.

**Comment by lb-** [comment]
Closing as no response for a few years on this and still in draft.

**Pull request closed without merging**
