### PR TITLE
Set up CSS LTR-RTL direction variable and fix incorrect transforms (#9914). Fix #9800

### LINKED ISSUE #9800: Broken page edition UI for RTL languages
### Issue Summary
In page editing UI when language is a RTL one things get funny (broken)
[See this](https://drive.google.com/file/d/11tPK0n5GegrQx8lS4Ya37AaW7x5b5yYH/view?usp=share_link) 

### Steps to Reproduce

Active a RTL language of your choice

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project

### Technical details

-   Wagtail version: 4.1.1

### PR DESCRIPTION
**Pull request by thibaudcolas**
Fixes most of #9800, and a few other RTL mirroring issues due to usage of `transform` translations that always reference physical directions.

### CODE REVIEW

**Comment by zerolab** [comment]
Took this for test and the interface looks and works so much better! 🌟🌟
The only thing that is counterintuitive is the gripper/resizer works the other way around -- e.g. you have to pull to the left to expand the side panel to the right

[test.webm](https://user-images.githubusercontent.com/31622/213406647-33c81ea4-be9e-4110-9de4-096939852f85.webm)

**Review by zerolab — APPROVED** [review]
The styling changes look sensible to me.

Would be nice to get another pair of FE eyes on it (@lb- perhaps?)

**Comment by lb-** [comment]
@thibaudcolas  looks good to me - love the custom properties approach!
Did a few quick smoke tests locally and works well.

**Comment by thibaudcolas** [comment]
Thank you both! @zerolab could you open separate issues for those two?

**Comment by zerolab** [comment]
@thibaudcolas done.
and thank you for the prompt and excellent tweaks! 🙌

**Pull request merged**
