### PR TITLE
Add option to insert tel links in rich text editor

### PR DESCRIPTION
**Pull request by SableWalnut**
As there is presently an option to insert email links, I figured it would be appropriate to add the option to insert tel links in addition to mailto links.

### CODE REVIEW

**Comment by gasman** [comment]
Hi @SableWalnut,
As mentioned at https://github.com/wagtail/wagtail/issues/490#issuecomment-53415721, I'm sceptical about whether there's a valid use for tel: links within rich text - the common uses I can think of would be better handled as a 'Contact' object with a 'telephone' field.

Now that we've implemented configurable rich text features (#3736), perhaps we could make this an optional (off-by-default) feature?

**Comment by chosak** [comment]
After digging into the code and bit and coming up to speed on Draftail, I think I'm coming around to @gasman's preference to implement this as a rich text feature.

If the approach in this PR is used for now, it'd be nice if there were some additional validation for the phone number part (a la [django-phonenumber-field](https://github.com/stefanfoulis/django-phonenumber-field)).

**Comment by thibaudcolas** [comment]
This is one of the features we've made Draftail for, along with "link with fragment identifier" #1049.

At the moment, Draftail is 100% reliant on Wagtail's chooser widget for links. If the idea is to add a new tab within the link chooser, it would be very straightforward to integrate with Draftail for Wagtail 2.0.

To build this with [WagtailDraftail](https://github.com/springload/wagtaildraftail), I made an entirely separate "rich text feature" that had its own toolbar button and chooser UI. It was very rushed (no validation, very basic input form), but may be a useful start if we choose to go this way.

**Comment by mikaelengstrom** [comment]
@gasman, Does the removal of this feature from the roadmap mean that it will not be implemented?

**Comment by benebun** [comment]
Any chance that will be on the roadmap?
We're also running into this. Using phone numbers in richtext is a common use case for our clients.
Two examples:
1. numbers that should be on the same line as text: "Please call us under +12 2345" if you don't want a separate paragraph for the number.
2. In Germany and Austria a non standard number format is very common (*sigh*): +12 (0)1 234 where 0 is only required if you call from within the country without the country code +12. On mobiles this number is recognised as a phone number but can't be reached because the 0 will be included: +12 01 234, correct would be +12 1 234. This could be fixed via a corrected tel: url.
Of course it's arguable that for use case 2 there could be other solutions (JS, mobile vendors…)...

**Comment by gasman** [comment]
Completed in #5478

**Comment by vsalvino** [comment]
Thank you @gasman and @mikaelengstrom for implementing this feature! Is it safe to assume this will be in the next version of wagtail (2.7)?

**Pull request closed without merging**
