### PR TITLE
Fix 404 error in user search

### LINKED ISSUE #12297: 404 page in admin Search
### Issue Summary
When clicking the user tab in search a 404 error appears.

image

### Steps to Reproduce

1. Start a new project with `wagtail start myproject` or use bakery demo/existing project
2. go to the universal search page (search for "a" in the admin nav bar)
image
3. click the "users" option.
image
You will then see a 404 error
image

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

- The error is do to the link using the namespace without converting to url - "http://localhost:8000/admin/pages/search/wagtailusers_users:index/?q=a"
-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details
-   Django version: 5.1
-   Wagtail version: 6.2 and 6.3 (dev)

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

### PR DESCRIPTION
**Pull request by smark-1**
fixes #12297

### CODE REVIEW

**Comment by vsalvino** [comment]
Thanks, I also ran into this issue on some sites we were upgrading, and we arrived at the exact same fix.

**Review by laymonage — APPROVED** [review]
Thanks for the report and fix! This was a regression in b6fdd8c408047a8eaa2f06374b40004f95924cbf.

I've added some test assertions for the fix. I'm leaving this unmerged in case other core team members would like to do the exercise, but I'll merge it if it's not merged by the time we want to put out a new 6.2.x release.

**Comment by vsalvino** [comment]
Thanks @laymonage . Go ahead and merge if you have the time, there is no shortage of exercises :P

**Comment by gasman** [comment]
Merged in 4e0236d5c20352c1dd790f210faf7418fbb5cdd6 (main) and 5d0bb0636fd54f0c63aa7b73b1f3ec714c8b0fd9 (6.2.x)

**Pull request closed without merging**
