### PR TITLE
Embed chooser panel

### PR DESCRIPTION
**Pull request by jordij**
First implementation https://github.com/torchbox/wagtail/issues/634 and reusable embeds in richtext fields.

Tags added as an Embed field but not yet implemented in the admin interface (could be useful I guess).

Edit link set to `display: none;` as the functionality is not ready yet (could be useful I guess).

### CODE REVIEW

**Comment by kaedroho** [comment]
Thanks @jordij 

I really like the ability to search and choose a past embed! :+1: 

Just checking, does this link to embeds by their URL or does it use a ``ForeignKey`` to ``Embed``?

**Comment by jordij** [comment]
Yeah I thought it be useful. I still need to work in a couple of things
though, like the listing styles and the creation (haven't tested from the
chooserpanel, only from the richtext).
As per your question, it works with a ForeignKey, following the way Image
and Document work. Makes sense to you guys?

**Comment by kaedroho** [comment]
@jordij 
I think it would be best if it used the URL (this is how they are stored in rich text and streamfield). This allows the ``Embed`` objects to be thrown away and Wagtail will automatically regenerate them (which is useful when you do configuration changes such as switch to using embedly and want your embeds to be consistent).

**Comment by jordij** [comment]
Sounds good. I'll revert to URL field instead of FK and commit the changes.

**Comment by tomdyson** [comment]
We like this, @jordij! Could you please add some tests and docs?

**Comment by jordij** [comment]
Cheers Tom, I'll be happy to add some tests&docs for this one and the other pending PR when I have some time :)

**Comment by jordij** [comment]
I sill need to work on this, sorry guys.

**Comment by jordij** [comment]
Hi there, I think this is almost ready. I have a question related to the `max_width` field of the `Embed` class:
```
class Meta:
        unique_together = ('url', 'max_width')
        verbose_name = _('Embed')
```
Why do we need the pair url-max_width to be unique? Shouldn't `max_width` only be passed as a parameter from the front-end but being excluded from the db? As we are reusing embed from multiple templates/pages it makes things easier to have one and only one Embed with a unique URL, regardless of `max_width`. Why do we wanna save `max_width` in the db?
Cheers :)

**Comment by kaedroho** [comment]
Thanks @jordij 

> Why do we need the pair url-max_width to be unique?

``max_width`` is sent as a parameter to the oEmbed provider/Embedly. It's possible that the HTML code they send back for one width is different for another. We enforce uniqueness on both fields so it's possible to fetch the same embed in multiple widths (but, IIRC, if max_width is omitted the provider *should* return a responsive embed so this is probably not necessary for most people).

**Comment by jordij** [comment]
Then I think there's a bit of inconsistency since the relationship from a `Page` model to the `Embed` is done through the `url` field only and not with the `id`.
I've set an update of the `max_width` field each time the `Embed` is fetched from the front-end but doesn't look like the best solution as it prevents storing the same embed with different `max_width` values. IMHO It also would potentially cause some confusion to the user when searching past embeds.
I might be wrong but I think we either get rid of the `unique_together` or we implement the field relationship through the `id`?
Or maybe I'm missing something here? :)

**Comment by gasman** [comment]
Hi @jordij - it's a bit misleading to think of `Embed` as an object with relations to pages. In our design, the Embed model is simply a cache of HTML responses that we get back from the embed code lookup - nothing more than that. As @kaedroho says, those responses depend on the URL and the max_width parameter, so we need to look up on both.

With this PR, you've actually taken things in a bit of an unexpected direction by treating the Embed model as a listing of previously-used, reusable media items. That's not in itself a bad thing, but it does mean that we'll need a bit of fudging of the current data model to make it fit that use-case (since it's possible for a single media item to have multiple Embed entries, corresponding to different sizes). I guess the quick fix would be to fetch a list of *unique* URLs from the Embed table, using something like `Embed.objects.values_list('url', flat=True).distinct()`.

From a data model perspective, we definitely do want to reference videos within page content by their URLs, not their embed IDs. When an editor places a video on a page, they are specifying a particular video (as identified by the URL) but *not* a particular embed size (which would be implied by referencing a specific embed ID) - the embed size is a decision for the template developer, not the content editor.

**Comment by jordij** [comment]
Thanks heaps for the clarifications @gasman 
Embeds are kind of filtered by `url` when displayed in the editor interface. If the same video exists in the database but with several `max_width` values, only the first one is displayed in the modal/search results. The editor user don't really need to know that there are N instances of the same video, only a nice thumbnail and a title should be enough to make him/her happy.

Have a look and let me know if you guys are happy with it.

**Comment by jordij** [comment]
Let me know if you need anything else on this one. Cheers

**Comment by gasman** [comment]
Hi @jordij,
After further discussion, we don't think that making embeds into a full-fledged user-facing model is going to work well, I'm afraid. It means that the model will end up serving two conflicting purposes - as a cache (with one record for each url + max_width combination), and as a way of representing a specific video to the user (which implies that fields such as tags/title have to be shared between all records for that embed). Also, I'm not sure that that the idea of re-using previously-used items fits with the way that most sites are likely to use embeds.

We'd prefer to go for a simpler 'enter a URL' modal - i.e. the same way that the embed chooser for the rich text area works now, but as a standalone panel too. The chooser widget itself is working very well, and we plan to 'cherry-pick' this side of the PR for 1.3. Thanks!

**Comment by jordij** [comment]
That sounds good @gasman, no worries.

**Comment by auvipy** [comment]
@jordij hi are you willing to continue your effort or looking for a new taker for this? thanks for starting this.

**Comment by jordij** [comment]
hey mate feel free to continue the work. cheers

**Comment by auvipy** [comment]
Awesome will ping you soon to accept my PR on your branch, you should get the author credit too

**Comment by yedpodtrzitko** [comment]
@auvipy hi, just want to check if you made any progress on this to avoid potential redundant work... thanks for response .)

**Comment by auvipy** [comment]
> @auvipy hi, just want to check if you made any progress on this to avoid potential redundant work... thanks for response .)

sorry I couldn't! if you want to work on this go ahead,if not i will start work

**Comment by gasman** [comment]
Closing as per https://github.com/wagtail/wagtail/pull/1553#issuecomment-159911447 - given the age of this PR it's highly unlikely that any future implementation of #634 will be based on this code.

**Pull request closed without merging**
