### PR TITLE
Fix reverse migration errors in images and documents

### LINKED ISSUE #6907: Reverse migration for documents 0011 and images 0023 fail
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The reverse migration for documents.migrations.0011 and images.migrations.0023 both fail for the same reason.

These migrations were introduced by #6466 

Here are the stack traces for each:

```
  File "/lib/python3.6/site-packages/wagtail/documents/migrations/0011_add_choose_permissions.py", line 80, in remove_choose_permission_from_collections
    GroupCollectionPermission.objects.filter(permission=choose_permission).delete()
    ...
    'The QuerySet value for an exact lookup must be limited to '
ValueError: The QuerySet value for an exact lookup must be limited to one result using slicing.
```

```
  File "/lib/python3.6/site-packages/wagtail/images/migrations/0023_add_choose_permissions.py", line 80, in remove_choose_permission_from_collections
    GroupCollectionPermission.objects.filter(permission=choose_permission).delete()
    ...
    'The QuerySet value for an exact lookup must be limited to '
ValueError: The QuerySet value for an exact lookup must be limited to one result using slicing.
```

### Steps to Reproduce

1. Install wagtail 2.12.3
2. Migrate forward
3. Run `manage.py migrate documents 0010` or `manage.py migrate images 0022`

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.6.8
* Django version: 2.2.17
* Wagtail version: 2.12.3
* Browser version: N/A

### PR DESCRIPTION
**Pull request by m3brown**
This PR resolves #6907 

The root of the issue is that get_choose_permission() returns a Queryset.

### CODE REVIEW

**Comment by ababic** [comment]
Hi @m3brown. Thank you for this! I was just looking at the code here and wondered whether the implementor really intended for `get_choose_permission()` to return a queryset, or whether they may have just forgot to replace `filter()` in that method with `get()` to return a single object. What do you think?

**Comment by m3brown** [comment]
> Hi @m3brown. Thank you for this! I was just looking at the code here and wondered whether the implementor really intended for `get_choose_permission()` to return a queryset, or whether they may have just forgot to replace `filter()` in that method with `get()` to return a single object. What do you think?

I assumed the query set was intentional because of the for loop on line 67.

A logical explanation is that the function was initially a singular implementation, and the implementer updated the function to return a queryset but forgot to update one of the two scenarios that called it.

**Comment by ababic** [comment]
Yes, perhaps that is the case. Either way, I think most sensible fix here is actually to update `get_choose_permission()` to use `first()`, making it return the correct `Permission` object (if it exists), or `None` (if it doesn't). Then, `copy_choose_permission_to_collections()` should be updated accordingly.

**Comment by m3brown** [comment]
@ababic I updated the PR to reflect your suggestion. Note the new implementation has the risk of regressions to the forward migration if the queryset were ever to return more than one result. I trust your insight is better than mine on this matter.

**Comment by ababic** [comment]
That's brilliant. Thanks very much @m3brown! I think we should be okay, since Permissions have a [unique_together restraint](https://github.com/django/django/blob/main/django/contrib/auth/models.py#L71) on `content_type` and `codename`:

**Review by ababic — APPROVED** [review]

**Pull request merged**
