### PR TITLE
Split out backend functionality out for easier extensibility

### PR DESCRIPTION
**Pull request by marcelkornblum**
Having extended the core search functionality to a fairly high degree, we realised we would benefit from splitting out some of the functionality into smaller units for easier overriding; this PR brings those changes upstream so others can also benefit.

This doesn't add any functional changes or fix any logged issues, as far as we're aware. 

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour? (No, I don't believe this is necessary - should I add some?)

The below are not applicable:
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by thibaudcolas** [comment]
@marcelkornblum 👋 even if this doesn’t address any predefined tasks, could you make sure to use our pull request template for something like this? We want to use it consistently to simplify our reviews.

In particular I’d be keen to hear whether it’d make sense to add tests for those changes. If this is about extensibility, it also seems to me like we’d want to take a moment to add documentation so we don’t inadvertently refactor the code in ways that compromise said extensibility in the future.

**Comment by marcelkornblum** [comment]
@thibaudcolas thanks for your comment 🙂 

> use our pull request template

Apologies, yes I've updated it now. I didn't write any new tests since we're specifically trying not to change any behaviour here. Is that OK?

> add documentation so we don’t inadvertently refactor the code

These are pretty low level things. I was going to open an RFC to discuss the approach we've taken and whether it merits being the default for Search across wagtail, before adding anything too opinionated. The refactors in this PR allow easier overriding of the logic used in the query compilation, which is useful if you want to add new first order SearchQuery objects and manipulate the ES DSL generation. Right now the docs don't go into anything like that level of detail so I don't think there's an easy update anywhere to make - I may be wrong though, please advise 🙂.

**Comment by thibaudcolas** [comment]
👍 let’s see what others think, I don’t work much on search functionality myself.

**Review by gasman — APPROVED** [review]
All looks good to me!

**Comment by gasman** [comment]
Merged in 24ebc590fb58c862c896ebd94ef2c4fd04d02535

**Comment by gasman** [comment]
Not sure if the new commit is aimed at fixing the previous test failures, but either way, it makes it a lot harder to review if we're introducing bigger changes on top of the smaller failing ones, since I can no longer look at the incremental changes commit-by-commit and verify that they're correct.

FYI, I'm planning to drop the ES5 / ES6 backends in Wagtail 5.3, and make ES7 the base implementation - given that this PR is going to need reworking anyhow, I think it might make sense for me to go ahead and do that now. We can then rebuild this PR on top of ES7, and hopefully have fewer moving parts to deal with.

**Comment by gasman** [comment]
> I'm planning to drop the ES5 / ES6 backends in Wagtail 5.3

Actually, on closer inspection those backends are tagged as RemovedInWagtail60Warning - so if we were to remove them, then the next release would become 6.0. And I'd be on board with that idea!

**Comment by marcelkornblum** [comment]
Sorry about the bigger changes; we thought we were improving the situation but it got increasingly messy; I've reverted it now to the simpler code that was initially passing all the tests; we're fairly confident it works.

If you're going to drop es5 and es6 that will definitely simplify all of this a lot; feel free to either merge this in ready for 5.3 or 6, whichever works for you.

**Comment by marcelkornblum** [comment]
@gasman thanks for removing the es5/es6 support; it does make this much easier to work with now 😅
@CamLamb has brought it all up to date and all the tests are passing so it should (I think) be good to merge now

**Review by gasman — APPROVED** [review]
Thanks - all looks good!

**Comment by gasman** [comment]
Rebased at #11199

**Pull request closed without merging**
