### PR TITLE
Remove workflows/create_task.html template

### LINKED ISSUE #7758: Extraneous action button when creating/editing Workflow Tasks
### Issue Summary

When creating or editing a Workflow Task in Wagtail 2.15.x, a thin (text-less) action button appears in the top right corner of the interface, linking to the URL already loaded.

Screenshot 2021-12-07 at 11-43-22 Wagtail - New workflow task

### Steps to Reproduce

1. Log in to the Wagtail admin
2. Navigate to _Settings_->_Workflow tasks_
3. Press the _New workflow task_ button: the button will appear on the admin page which loads

I've traced this issue back to https://github.com/wagtail/wagtail/commit/b89e298c084fd0c55c147e255f1eb51e57f3f5f9 - specifically, the lines in _wagtail/admin/views/generic/models.py_ which add `context['action_url']` in the `get_context_data()` method of the [`CreateView`](https://github.com/wagtail/wagtail/commit/b89e298c084fd0c55c147e255f1eb51e57f3f5f9#diff-e1bcd86f7d82181d10043d53e7cc8eda34f657fe28c7a75c3768b707ad000e10R60) and [`EditView`](https://github.com/wagtail/wagtail/commit/b89e298c084fd0c55c147e255f1eb51e57f3f5f9#diff-e1bcd86f7d82181d10043d53e7cc8eda34f657fe28c7a75c3768b707ad000e10R155) classes.

I assume that these lines can't simply be removed, as this is intended to be generic code. One possible fix might be to alter the template which is responsible for outputting the action button (_wagtail/admin/templates/wagtailadmin/shared/header.html_) to only do so in particular circumstances - e.g. if the `action_url` doesn't match the current URL, or if both an `action_url` and `action_text` are provided. I'm happy to submit a PR if either of those solutions seem viable.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

### Technical details

* Python version: 3.6.9
* Django version: 3.2.10
* Wagtail version: 2.15.1
* Browser version: Firefox 94.0 (Linux) and others

### PR DESCRIPTION
**Pull request by gasman**
Prompted by #7758, I looked deeper at what this template is doing and came to the conclusion that it's not needed at all - I suspect it's been copied from workflows/create.html which does have substantial customisations (as it uses edit handlers and formsets).

For the sake of thoroughness, the differences between the current create_task.html and generic/form.html (and why we don't need them) are as follows...

* CSS / JS declarations - The form on this page is a plain Django ModelForm (as per `wagtail.admin.forms.workflows.get_task_form_class`) so we can rule out the possibility of it having inline panels, which would be the main motivation for bringing in _editor_js.html and friends. All media required by form widgets (e.g. choosers) should be brought in via `{{ form.media.js }}` / `{{ form.media.css }}`, as generic/form.html does - as far as I can tell, create_task.html's references to `edit_handler` and `view.media` here are incorrect, as these are not defined anywhere.
* wagtailadmin/shared/header.html include - is missing the all-important `only` that fixes #7758
* Stylistic differences (use of `nice-padding`, and page-editor-style submit button in footer) - these introduce inconsistencies with similar 'create' forms in the admin, which are best avoided
* Long-running submit button - no reason to expect this form to be longer-running than others. (FWIW I wouldn't be particularly against making this the standard button style for generic forms, but then this shouldn't be a special case.)
* 'Create' rather than 'Save' as the submit button text - this one _is_ an improvement that we should roll out to other generic views, and I'll open a PR for that shortly.

### CODE REVIEW

**Comment by zerolab** [comment]
This solves the issue for create, but it is there when editing a task

**Comment by zerolab** [comment]
This solves the issue for create, but it is there when editing a workflow task

<details>
<summary>📸 screenshot</summary>

Screenshot 2021-12-08 at 14 53 29

</details>

**Comment by gasman** [comment]
@zerolab Doh! Was so caught up in checking the code paths for the create task, create workflow and generic create views that I forgot to check edit views :-) PR updates on the way.

**Comment by gasman** [comment]
aha, I see the 'edit task' view does have customisations that justify using the footer submit button style, so the 'add task' view should be consistent with that - and that has knock-on effects on our ability to piggyback on generic/form.html. Let's stick with the simple fix in #7762 for now then!

**Pull request closed without merging**
