### PR TITLE
Change event handler to keypress. This fixes the IE10 + IE11 submit i…

### PR DESCRIPTION
**Pull request by ralphjacobs**
Change oninput handler to keypress. This fixes the IE10 + IE11 pagination issue. 
Refs: #3433

### CODE REVIEW

**Comment by ababic** [comment]
Hey there @ralphjacobs. It looks as though some unrelated changes have been committed along with this PR (Various icon class / gravatar related changes). Would you be able to revert those so that this PR only contains changes relating to the IE10 issue?

**Comment by thijskramer** [comment]
Good point. pasting with something else than the keyboard won't work with `keypress`. 
I think `change` won't work either, because the `onchange` event fires _after_ losing focus (see [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Events/change)), and that's not something we want. 

So to cover both typing and pasting, would listening to both `keypress` and `paste` be enough, with something like `$(window.headerSearch.termInput).on('keypress paste', function() { .... }` ?

**Comment by ababic** [comment]
@thijskramer You're completely right about `onchange` - that will not do. `keypress`, `cut`, and `paste` cover all of the cases I can think of currently, and I can't think of any tidier implementation. But, I would invite a more front-end focussed team member to comment here, as my JS skills are limited. @jjanssen how do you feel about the multiple trigger approach?

**Comment by gasman** [comment]
Listening to events that assume a specific input device (keyboard) is raising accessibility alarm bells for me, although I don't know whether that's a real concern or just a theoretical one.

We encountered something similar before, where the initial focus on the search box was triggering a search: https://github.com/wagtail/wagtail/commit/a2fe305aa0342e332931265b5f9b3d44585371bf - in this case, I fixed it by ignoring searches for the empty string. Maybe there's something similar we can do here?

**Comment by ralphjacobs** [comment]
We cleaned up the commits and added more handlers

**Comment by thijskramer** [comment]
@gasman I think that listening to `keypress`, `cut` and `paste` are sufficient for the use case, namely the search-as-you-type functionality. Just by using `oninput` raises unexpected behaviour in IE11, as I mentioned before.

**Comment by ababic** [comment]
I thought initially about the changing the search to only launch when the value wasn't blank. But, in a scenario where you typed something to initiate a search, then used the delete key to reduce the search string to nothing, the 'blank' search would fail to initiate, and you'd still see results for the last remaining character. We'd need to introduce something else to indicate whether or not the user has actually interacted with the input or not - which could only really be done by adding additional listeners, calling a separate method. And by that point, it's more complicated than it needs to be.

**Comment by ralphjacobs** [comment]
At least this reduces multiple requests everytime using IE10 or IE11. Even when you visit the user listing the first time it would generate two requests because the event was fired.

**Comment by ababic** [comment]
I'm happy with this one now, if the core team are?

**Comment by ralphjacobs** [comment]
@ababic thanks

**Comment by gasman** [comment]
Yep, sounds good to me. (Haven't tested it myself, but I'm satisfied that the simple solution is the way to go here, rather than an over-engineered one :-) )

**Comment by jjanssen** [comment]
Reviewing it right now :)

**Comment by ralphjacobs** [comment]
I will look in to it

**Comment by jjanssen** [comment]
Thanks! Merged in cf815e8

**Pull request closed without merging**
