### PR TITLE
Fix touchpad scrolling on macbook in datetimepicker

### PR DESCRIPTION
**Pull request by ralphjacobs**
- We upgraded the datetimepicker jquery library to a version which doesn't need re-wiring in page-editor.js
- Also no scss changes are needed.
- In the library itself we changed one small variable to make the scrolling even more user-friendlier on touchpads.

Refs: #3113

### CODE REVIEW

**Comment by tomdyson** [comment]
Thanks @ralphjacobs! Should we use a later / minified version? e.g. https://github.com/xdan/datetimepicker/blob/master/jquery.datetimepicker.min.js

**Comment by jjanssen** [comment]
@hvandenberg can you take this for a testdrive tomorrow?

**Comment by ralphjacobs** [comment]
Hi Tom,

I've tried newer versions, but then the complete design and functionality breaks.
Also the current one wasn't minified.

**Comment by HvandenBerg** [comment]
tested OK, time now scrolls smoother. day/month is still a bit too fast

**Comment by jjanssen** [comment]
Overall I think we are good to go with this one. There are no regressions showing up and it at least fixes the annoying scroll within the time picker. The comment @HvandenBerg mentions is valid but current behaviour. 

The upgrade to a more recent version would probably more desirable but would also have more impact. Doing that is probably part of a larger discussion on what we are going to do regarding updates. The general concern we are a falling a bit behind on maintenance whereas browsers are moving forward. That would be something for the team discussion.

**Comment by jjanssen** [comment]
Thanks! Merged in 87a7a79

**Pull request closed without merging**
