### PR TITLE
Updated and renamed upgrading.rst to upgrading.md (v2)

### PR DESCRIPTION
**Pull request by sandeep280993**
Apologies for accidentally creating a new PR for the updated **upgrading.md** file with review comments.

Replaces https://github.com/wagtail/wagtail/pull/8761

### CODE REVIEW

**Review by lb- — APPROVED** [review]
@sandeep280993 looking good, I had to do one minor tweak to the code blocks in the list but other than that it worked great.

I have updated your branch with two commits (one to rename and the other to apply the markdown formatting) and will merge this in shortly.

I have added your name as `Sandeep M A` to the contributors list but please let me know if you want a different name listed.

**Comment by sandeep280993** [comment]
I am happy with how you have added my name to the Contributors list. Thanks for the opportunity. One thing, I see 'text' and 'console' appear in the output. I hope they are correct.

**Comment by lb-** [comment]
Thanks for the heads up. Looks like something went wrong there. I'll fix it up. 

Screenshot_20220703-092237

In an attempt to next the code snippets in the list - looks like it treated the while thing as a code block.

**Comment by lb-** [comment]
PR up to fix the above issue https://github.com/wagtail/wagtail/pull/8793

**Pull request merged**
