### PR TITLE
Add panel configuration checks

### LINKED ISSUE #2822: Add a system check for incorrect use of content_panels on non-page models
Using `content_panels` instead of `panels` on non-page models (including snippets, ModelAdmin, wagtailsettings, and InlinePanel child models) seems to be a very common mistake:

http://stackoverflow.com/questions/38207208/add-a-multifieldpanel-in-django-wagtail-basesettings
https://groups.google.com/d/msg/wagtail/nqb24PZRlhk/oKkbmUXZAgAJ
https://github.com/torchbox/wagtail/issues/1456
https://groups.google.com/d/msg/wagtail/hs_mX0xOoyY/fr7ktSTRAAAJ
https://github.com/torchbox/wagtail/issues/1912

I suggest we add a system check to warn about models that set a `content_panels` attribute when a `panels` attribute is expected instead. (The solution would need to take care to avoid false positives, since it _is_ valid to set `content_panels` if the edit_handler property is overridden.)

### PR DESCRIPTION
**Pull request by lb-**
Closes #2822

Replaces previous PR #4226 
* Now merges without conflicts
* Added checking of snippet models (not in original PR)
* Also added .vscode folder to gitignore

* Do the tests still pass?  Yes
* Does the code comply with the style guide? (Run `make lint` from the Wagtail root) - Done
* For Python changes: Have you added tests to cover the new/fixed behaviour? - Yes
* For new features: Has the documentation been updated accordingly? - N/A documentation already exists, this reinforces the documentation with Django checks.

### CODE REVIEW

**Comment by lb-** [comment]
@mikedingjan ready for review again :) thank you

**Comment by mikedingjan** [comment]
@lb- thanks! LGTM!

**Comment by lb-** [comment]
Thanks @mikedingjan

**Comment by lb-** [comment]
@mikedingjan - should I update the changelog for this one?

**Pull request merged**
