### PR TITLE
Improve CSS authoring guidelines

### PR DESCRIPTION
**Pull request by thibaudcolas**
Additional guidelines when writing stylesheets. This contains general guidelines about how we write stylesheets, and very specific information on Windows high contrast mode / Contrast themes and right-to-left languages support.

I chose to keep this more minimal than I initially planned so it’s easier to review and merge. And yeah went through with #11365 first so there were fewer "legacy" things to document.

### CODE REVIEW

**Comment by lb-** [comment]
Just a thought. I'd like us to document that we should always consider how those that build with Wagtail can customise styling. 

- If a component is styled 100% with tailwind, we still want to have a root class for it so it's easier to 'grab' with custom styles. Example is breadcrumbs using `w-breadcrumbs` for this purpose only. 
- Somehow, we need to consider that the ephemeral nature of tailwind usage (lazy load) means that some Tailwind classes could exist and then not be available in a future release. Not sure if this needs a technical solution though. 
- Using / making available CSS custom properties where appropriate. 

While we may never document officially classes that will be guaranteed to be available (except CSS custom properties) we should still consider this audience when writing CSS

**Comment by thibaudcolas** [comment]
@lb- I chose to go ahead without your suggestion. We have close to no guidelines on styling currently, pretty poor quality of stylesheets, I think we need to get our house in order before we introduce more ways to make UI components customizeable.

If we wanted to encourage customisations in my opinion the first order of business would be to document specific components that are designed for reuse. Comparatively, being able to override styles or reusing utility classes feels useful now and then but not where we should spend our time currently

**Comment by lb-** [comment]
@thibaudcolas no problems at all. I'm happy for any improvement to our guidelines.

Thanks for getting back to me on this.

**Review by laymonage — APPROVED** [review]
One minor comment but otherwise this looks good to me!

**Pull request merged**
