### PR TITLE
Make bird glow on hover

### PR DESCRIPTION
**Pull request by kapito**
~~https://gfycat.com/OrdinaryTemptingAsiandamselfly~~
https://gfycat.com/TallSkeletalAdeliepenguin

Also acts as a timer of sorts for the version number to appear.

### CODE REVIEW

**Comment by BertrandBordage** [comment]
What is the purpose of making it glow?
Sorry to be so rude, but my opinion is that it gives a “pimp my bird” impression with that neon under it.

**Comment by tomdyson** [comment]
I kind of liked it! I don't think you need to close this yet, however much we respect @BertrandBordage's opinion :) Let's see what other people think.

**Comment by Proper-Job** [comment]
I kind of like it too :)

**Comment by BertrandBordage** [comment]
Yeah, we should keep this issue open to get more opinions on it as it’s a rather important change, symbolically.
@kapito Sorry again I expressed myself very directly, my point was not to say “Uh, ugly, I definitely don’t want that and nobody won’t”, it was more “I don’t feel the need of this, plus I’m not a huge fan, but I’m not strongly opposed either”.

**Comment by tomdyson** [comment]
@kapito can you share an updated gif, please?

**Comment by kapito** [comment]
@BertrandBordage No need to apologise! In hindsight it was silly of me to close the PR straight away before seeing more opinions. I can completely understand how it may come across as somewhat over the top -- I've made some changes to its brightness/radius which will hopefully make it look less 'in-your-face'.

@tomdyson I will try to get an updated gif up in the next hour, currently having some issues with Vagrant on my desktop but I'm sure I can get it sorted.

**Comment by kapito** [comment]
Updated gif: https://gfycat.com/TallSkeletalAdeliepenguin

**Comment by gasman** [comment]
Closing in favour of #3740

**Pull request closed without merging**
