### PR TITLE
Customisable media forms

### LINKED ISSUE #6444: Support large document uploads
I asked a question in slack and didn't get a response.   I occasionally have large documents (i.e. product pdfs and such) that should be downloadable.  However, I don't want to allow arbitrarily large uploads through nginx or whatever frontend is in use.  I do not see a simple way to hook in here.

In [wagtailmedia we allowed the site to provide a custom base form](https://github.com/torchbox/wagtailmedia/blob/master/wagtailmedia/forms.py#L47) to set custom widgets to handle this case.  Would you accept this approach?

Since very large documents are out of the ordinary, it doesn't concern me that they are not compatible with the multi-uploader javascript so I would be happy if it was restricted to the single document upload form.  But it would be helpful if there was a handy link on the multi-upload form users reach by default to upload a single document.  And perhaps a way to nudge users to use this form if their upload fails because the file is too large

### PR DESCRIPTION
**Pull request by zerolab**
This PR introduces two new settings that allows customising the image/document forms. Closes #6444

### CODE REVIEW

**Comment by thenewguy** [comment]
What is holding this up? Anything I can do to get it merged?

**Comment by Scotchester** [comment]
Hey @thenewguy, could you test out this branch and let us know if it solves the issue for you?

**Comment by thenewguy** [comment]
@Scotchester sure thing - could this make it into 2.11?

**Comment by Scotchester** [comment]
@thenewguy Sorry, I don't believe so. The first release candidate is already out, so I think everything is frozen other than regressions or critical bug fixes.

**Review by gasman — APPROVED** [review]

**Comment by gasman** [comment]
Merged in 05587e0d84ffd8795d461ac0ac7dc94ab1188296.

**Comment by kaedroho** [comment]
I really hope we get to the point someday where we can solve issues like this more generally by letting people subclass the views/viewsets instead of having to add new settings/hooks every time a bit of one of these interfaces needs to be changed by someone!

**Pull request closed without merging**
