### PR TITLE
Fix/5919 nested inline panels ordering buttons

### LINKED ISSUE #5919: Nested orderable inline panels have the same sort arrows as their orderable parent
### Issue Summary

I have a page which displays a list of Carousels, grouped into CarouselGroups. Both models are Orderable, and are displayed using InlinePanels. When the edit page loads, each CarouselGroup has the correct sort arrows - just down for the first one, up/down for middle ones, and just up for the last one. But the list of Carousels under each CarouselGroup has the same set of arrows for each one in the list: just down for the Carousels under CarouselGroup 1, up/down for the Carousels under CarouselGroup2, etc. If I change the sort order for one of the Carousels, the arrows change to what they should be (i.e. down for the first, up/down for the middle ones, and up for the last).

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows...
```
from django.db import models
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel
from wagtail.admin.edit_handlers import InlinePanel, FieldPanel

from wagtail.core.models import Page, Orderable


class HomePage(Page):
    content_panels = Page.content_panels + [
        InlinePanel('parent_panels', label="Parent panels")
    ]


class Parent(ClusterableModel, Orderable):
    page = ParentalKey(HomePage, related_name='parent_panels')
    title = models.TextField()
    panels = [
        FieldPanel('title'),
        InlinePanel('child_panels', label="Children", min_num=1)
    ]


class Child(Orderable, models.Model):
    title = models.TextField()
    page = ParentalKey(Parent,
                       on_delete=models.CASCADE,
                       related_name='child_panels')
    panels = [
        FieldPanel('title')
    ]
```
3. Edit the home page in the wagtail admin
3. Add a Parent panel and 3 child panels
4. Click save draft (or publish) - the 3 child panels will not have a sort arrow as the parent panel does not
5 . Add a second parent panel and 3 child panels
6. Save draft. The sort arrows in the first child list will all point down, and in the second will all point up
7. Click one of the child sort arrows. The arrows will now display correctly

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.6.7 and 3.6.9
* Django version: 3.0.4
* Wagtail version: 2.8
* Browser version: Firefox 74 on linux, Chrome 80 on windows, another browser on Mac

### PR DESCRIPTION
**Pull request by hamadr**
Fixes #5919

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [x] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [x] **Please list the exact browser and operating system versions you tested**:
        - Firefox 115.7.0esr on Debian GNU/Linux 12 (bookworm)
        - Chromium 121.0.6167.85 on Debian GNU/Linux 12 (bookworm)
    -   [ ] **Please list which assistive technologies [^3] you tested**: None
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

This change can be tested on the admin interface, when there are nested inline panels.

Example is available on this repo https://github.com/hamadr/bakerydemo/tree/fix/5919-nested-inline-panels-ordering-buttons  (branch `fix/5919-nested-inline-panels-ordering-buttons`) based on https://github.com/wagtail/bakerydemo/

Steps to reproduce are :
- launch the bakery demo after running all of the migrations
- Go to the admin page to edit a country (http://127.0.0.1:8000/admin/snippets/breads/country/edit/24/ for example)
- Add a hierarchy of regions/cities and save
- Play with the up and down arrows

Without the fix : cities up/down arrows move also the regions + cities up/down arrows are in the same state as their parent's up/down arrow

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Review by lb- — APPROVED** [review]
Thank you @hamadr  I have done a bunch of testing an this is working well.

We really appreciate you taking the time to fix this and put up a PR.

I will rebase and merge in shortly, we will add you to the contributors list as 'Adrien Hamraoui', do let us know if you want a different name listed.

**Comment by lb-** [comment]
Might be good to backport to the 5.2 branch. 

Any push back @gasman ?

**Comment by gasman** [comment]
@lb- In this case I'd say no to backporting - it's not a recent regression or a site-breaking bug, so I think it should just be part of the regular round of bugfixes in 6.1.

**Comment by lb-** [comment]
OK

**Comment by harrislapiroff** [comment]
Coming here from the future say, this sort of bug is quite bad for those of us who stick to LTSes. It's not a site-breaking bug, but it does mean some of our pages are effectively uneditable by editors (without a lot of pain) and we don't have great options besides breaking our LTS policy, changing our data structures because of a javascript bug, or telling editors they can't update that page for a couple months. (If anyone has a better workaround, I'm eager to hear it!)

**Comment by lb-** [comment]
Thanks @harrislapiroff - we understand the frustration. It's a hard balance to make in regards to back porting fixes vs ensuring stability. 

I'm this specific case, the bug had been around for over three years (from my understanding), hence the hesitation to bring it into older releases.

Thank you though for posting a workaround though on the issue. https://github.com/wagtail/wagtail/issues/5919#issuecomment-2400346988

**Comment by harrislapiroff** [comment]
Totally understandable. Our scenario is perhaps unusual because we only recently built some pages for a new project using nested orderables assuming they'd work and were taken by surprise when they didn't, but I can see that this may not have come up for that many people in the intervening period between fix earlier this year and LTS release later this year.

**Pull request merged**
