### PR TITLE
Remove unused WorkflowStatus view, urlpattern, and JS code

### PR DESCRIPTION
**Pull request by Stormheg**
Ref #10403

> The workflow_status view is now unused: https://github.com/wagtail/wagtail/blob/main/wagtail/admin/views/pages/workflow.py#L205.

> It needs to be removed, as well as its corresponding URL patterns, and _any test still relying on it being a ModalWorkflow implementation._

(emphasis mine)

I'm not sure what tests this is referring to. I expected there to be test failures after this change but there were none.

-   [x] Do the tests still pass?
-   [x] Does the code comply with the style guide?
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?

### CODE REVIEW

**Review by laymonage — COMMENTED** [review]
Thanks! I think we should also remove the same view for snippets:

https://github.com/wagtail/wagtail/blob/39a723f9d1e585100a10054686835847b54198a6/wagtail/snippets/views/snippets.py#L1482-L1486

and its accompanying code, e.g. the `workflow_status_view` property, the class.

**Review by gasman — APPROVED** [review]

**Comment by Stormheg** [comment]
@laymonage I removed the generic `WorkflowStatus` view and the its Snippet implementation. Does this look alright to you?

**Review by laymonage — CHANGES_REQUESTED** [review]
The dialog, which is no longer loaded via AJAX, seems to still work for both pages and snippets. The tests are passing as well, so hopefully this should be OK.

image

One final thing is that I think we also need to remove [workflow-status.js](https://github.com/wagtail/wagtail/blob/main/client/src/entrypoints/admin/workflow-status.js), and any mentions of it:

https://github.com/wagtail/wagtail/blob/801eccc9304561ffe974b6e16bd977198910726d/client/webpack.config.js#L61

https://github.com/wagtail/wagtail/blob/801eccc9304561ffe974b6e16bd977198910726d/wagtail/admin/templates/wagtailadmin/pages/_editor_js.html#L26

As expected, looking for `data-action-workflow-status` in the codebase doesn't return anything other than `workflow-status.js`, so this should be safe to remove as well.

**Review by laymonage — APPROVED** [review]
Looks good, thanks! Just waiting for CI to pass before merging this.

**Pull request merged**
