### PR TITLE
Internal anchor links/links with fragment identifiers. Fixes #1049

### LINKED ISSUE #1049: Not possible to add link with fragment identifier
Currently it is not possible to add [fragment identifier](http://en.wikipedia.org/wiki/Fragment_identifier) to Wagtail rich text links:

https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/rich_text.py#L104

### PR DESCRIPTION
**Pull request by imansyed000**
Fixes #1049

Tested on Chrome, Safari and Firefox.

image
image
image
image

User is able to input some know fragment identifier.
Anchor field currently lacks any validation.

### CODE REVIEW

**Comment by lb-** [comment]
merged in via https://github.com/wagtail/wagtail/commit/794d40b86b3d9c652c37acbc00163890077a78b5 thanks @imansyed000

**Comment by johnraz** [comment]
Awesome! Thanks a lot @imansyed000 this PR will help me understand how the all thing works and be used in my project as well! 👍 🎉

**Comment by zerolab** [comment]
https://github.com/jacobtoppm/wagtail_draftail_anchors/ provides the ability to add/edit anchors so should go well with this feature

**Comment by kaedroho** [comment]
Wonder if we should have this switched off by default? It's not a commonly requested feature and requires some frontend development to make it work. I worry it could actually be confusing for editors of sites that don't actually support it.

**Comment by awhileback** [comment]
> Wonder if we should have this switched off by default? It's not a commonly required feature and needs some frontend development to make it work. I worry it could actually be confusing for editors of sites that don't actually support it.

There also seems to be a bug in draft vs publish. I coupled this with the package zerolab linked above your reply, which is really a requirement to use this because there's otherwise no way to insert anchor ids, and when saving a draft all of the links got converted to 'default' draftail links.  After editing them again, and not previewing them or saving a draft but rather publishing the changes directly, they stuck properly.

**Pull request closed without merging**
