### PR TITLE
Issue #6388 --> Changed <input type=button> to <button type=button>

### PR DESCRIPTION
**Pull request by paqman85**
Thanks for contributing to Wagtail! 🎉

Before submitting, please review the contributor guidelines <https://docs.wagtail.io/en/latest/contributing/index.html> and check the following:

* Do the tests still pass? (https://docs.wagtail.io/en/latest/contributing/developing.html#testing) 
* Does the code comply with the style guide? (Run `make lint` from the Wagtail root) 
* For Python changes: Have you added tests to cover the new/fixed behaviour? N/A
* For front-end changes: Did you test on all of Wagtail’s supported browsers? **Please list the exact versions you tested**.
* For new features: Has the documentation been updated accordingly? N/A

### CODE REVIEW

**Review by Scotchester — APPROVED** [review]
Thank you, @paqman85! We appreciate it.

**Review by Scotchester — CHANGES_REQUESTED** [review]
Whoops, too hasty with my approval. `<button>` is not a self-closing tag, so these tags need to be converted to this format:

```html
<button type="button" class="button">value</button>
```

(replacing the `value` with the value of the `value` attribute from before)

**Comment by paqman85** [comment]
No prob! I'll update it.

**Comment by paqman85** [comment]
I may have missed  something again, did you want the `value="drop up"` to be between the button tags, not as a tag attribute?

**Comment by Scotchester** [comment]
> I may have missed something again, did you want the `value="drop up"` to be between the button tags, not as a tag attribute?

Yes, the attribute should go away, and just `drop up` should appear between the tags.

**Comment by paqman85** [comment]
Ok I think I got them all now. Sorry about the extra commits!

**Review by Scotchester — APPROVED** [review]

**Comment by Scotchester** [comment]
Beautiful, thanks again, @paqman85!

**Pull request merged**
