### PR TITLE
Ensure `WagtailAdminFormPageForm.clean` is applied regardless of rela…

### PR DESCRIPTION
**Pull request by jsma**
…ted name

- Dynamically detect the `related_name` of any form fields attached to the page so that validation is actually run for custom related_names. 
- This also will apply validation even if there are multiple `AbstractFormField` subclasses related to the page (perhaps there are two forms on a page, and Form A must be submitted before Form B). 
- Return `cleaned_data` for more consistent subclassing. 
- Updated documentation with an example of adding custom page validation for form fields.

Tests pass, but it appears there currently aren't any tests when a custom `related_name` is used. I can potentially add such tests later, if necessary.

### CODE REVIEW

**Comment by lb-** [comment]
@jsma I recommend that there are some tests added to ensure that this explicit support is not accidentally removed in future changes.

**Comment by thibaudcolas** [comment]
Assigning to @lb- to work on adding the tests (or otherwise share w/ other contributors for them to consider that)

**Comment by lb-** [comment]
Backup made of the branch, will force push a rebase soon.

https://github.com/lb-/wagtail/tree/form-field-validation-updates

**Comment by lb-** [comment]
OK, part one, here's a test that will fail on `main` due to us not correctly validating unique clean names for custom related fields.

```
# wagtail/contrib/forms/tests/test_views.py
#...

class TestDuplicateFormFieldLabels(WagtailTestUtils, TestCase):
    #...

    def test_adding_duplicate_form_labels_with_custom_related_name(self):
        """
        Ensure duplicate field names are checked, even if a custom related_name is used.
        ``FormPageWithCustomSubmission`` uses the related_name `custom_form_fields`.
        """

        post_data = {
            "title": "Drink selection",
            "content": "Some content",
            "slug": "drink-selection",
            "custom_form_fields-TOTAL_FORMS": "3",
            "custom_form_fields-INITIAL_FORMS": "3",
            "custom_form_fields-MIN_NUM_FORMS": "0",
            "custom_form_fields-MAX_NUM_FORMS": "1000",
            # Duplicate field labels
            "custom_form_fields-0-id": "",
            "custom_form_fields-0-label": "chocolate",
            "custom_form_fields-0-field_type": "singleline",
            "custom_form_fields-1-id": "",
            "custom_form_fields-1-label": "chocolate",
            "custom_form_fields-1-field_type": "singleline",
            # Unique field label
            "custom_form_fields-2-id": "",
            "custom_form_fields-2-label": "coffee",
            "custom_form_fields-2-field_type": "singleline",
        }

        response = self.client.post(
            reverse(
                "wagtailadmin_pages:add",
                args=(
                    "tests",
                    "formpagewithcustomsubmission",
                    self.root_page.id,
                ),
            ),
            post_data,
        )

        self.assertEqual(response.status_code, 200)

        self.assertContains(
            response,
            text="There is another field with the label chocolate, please change one of them.",
        )
```

**Comment by lb-** [comment]
OK and a test, that fails on `main` that allows customisations to build on the 

```py
class TestFormPageCreate(WagtailTestUtils, TestCase):
    # ...
    def test_form_page_creation_error_with_custom_clean_method(self):
        """
        CustomFormPageSubmission uses a custom `base_form_class` with a clean method
        that will raise a ValidationError if the from email contains 'example.com'.
        """

        post_data = {
            "title": "Drink selection",
            "slug": "drink-selection",
            "from_address": "bad@example.com",
        }

        response = self.client.post(
            reverse(
                "wagtailadmin_pages:add",
                args=("tests", "formpagewithcustomsubmission", self.root_page.id),
            ),
            post_data,
        )

        self.assertEqual(response.status_code, 200)

        self.assertContains(
            response, "The page could not be created due to validation errors"
        )
        self.assertContains(
            response, "<li>Email cannot be from example.com</li>", count=1
        )

```

```py
# wagtail/test/testapp/models.py
# ...


# FormPage with a custom FormSubmission


class FormPageWithCustomSubmissionForm(WagtailAdminFormPageForm):
    """
    Used to validate that admin forms can validate the page's submissions via
    extending the form class.
    """

    def clean(self):
        cleaned_data = super().clean()
        from_address = cleaned_data.get("from_address")
        if from_address and "example.com" in from_address:
            raise ValidationError("Email cannot be from example.com")

        return cleaned_data


class FormPageWithCustomSubmission(AbstractEmailForm):
    # ...

    base_form_class = FormPageWithCustomSubmissionForm

```

**Comment by lb-** [comment]
Looks like this PR does not accept pushing, raising a new one shortly.

**Comment by lb-** [comment]
Unable to push to remote branch, see new PR up instead -> https://github.com/wagtail/wagtail/pull/12480

@thibaudcolas

**Pull request closed without merging**
