### PR TITLE
Extend simple translations with parent locale and hooks

### PR DESCRIPTION
**Pull request by NotANormalNerd**
Hello everyone,

We are working extensively with translations and have been missing a few features, some of those we think make sense for the upstream projects, that's why we want to contribute them here. 

Extend the simple translation contrib packages with two features:
* Add parent locale to the TranslatableMixin to be able to track where a translation comes from
* Add hooks before and after a translation to be able to intercept the process with custom process

I would love to get some feedback if these features are wanted/interesting before we add more time into writing tests and documentation.

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [x] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by NotANormalNerd** [comment]
Ready for review.

**Comment by NotANormalNerd** [comment]
@lb-  Sorry for tagging you. Would love to know how to proceed.

**Comment by lb-** [comment]
Thanks @NotANormalNerd - I've tagged this for review, it's not my area of expertise so I'm probably not the best person to review.

I might suggest splitting the PR into two, one for the parent locale and the other with the hooks but only if they make sense as isolated improvements.

@loicteixeira / @th3hamm0r / @Stormheg - would any of you be up for a review here. We can maybe flag the idea of adding hooks in the core team chat also.

**Review by Stormheg — COMMENTED** [review]
Hi @NotANormalNerd, thanks for the pull request! ❤️

I'm no expert on translations in Wagtail – so please forgive any ignorance on my part – but I do have some questions I hope you can help answer.

## On the parent locale field

You are proposing we add a field `parent_locale` to `TranslatableMixin` to keep track of what Locale was used to create the translation.

_Could you please motivate as to why you would like to see this field added?_ I'm sure how this information could be utilized (besides just displaying it in the editor that is, but I'm not sure how that would remain relevant once a page is translated? This reason alone does not convince me)

Side note: if we add this field, it should be documented too. As it stands such documentation is missing.


## On the hooks

Providing hooks to allow basic extension of `simple_translation` might be a good idea? I can see it allow customization desperately needed, while not needing to go full third-party package to provide missing functionality. Happy to hear other reviewers point of view on this.

Expecting the hook to return an object with a status code is weird to me. Why not just return a HttpResponse to override default behavior? That's how most other hooks in Wagtail work.

Some other small notes:

- `before|after_translate_object` --> rename object to snippet. This hook can only affect snippets and all other snippet-related hooks have snippet in their name.
- The documentation example for the before hooks show them being used to do permission checks. I'm not sure if a hook is the best place to do additional permission checks. Ideally we'd not present users with a translate button if they don't have permission to translate the object. But this is a minor gripe and I would not consider it a blocking issue.
- Codecov is warning that the hooks code is not covered by tests. There should be tests to prove the hooks are triggered and can affect the response returned.

**Comment by th3hamm0r** [comment]
I'm also a little hesitant about the `TranslatableMixin`-changes (`parent_locale`).
For me it looks like the additional locale field mainly helps with the simple_translation-module.
I've never used the simple_translation-module, but if a parent locale (alternatives names: source? origin?) is really helping here, it should be somehow added to the simple_translation-module, but not the `TranslatableMixin`.
Changing the `TranslatableMixin` always affects all translatable models, even if you're not using simple_translation.
[wagtail-localize](https://github.com/wagtail/wagtail-localize/tree/main) for example already displays the origin of the translation, so it won't require this additional field.
Unfortunately, adding this functionality only to the optional simple_translation-module probably requires some additional hooks in the core. For example, I'm not sure if you could add your desired output to the locale-side-panel without additional hooks in the core(?).

The original PR https://github.com/wagtail/wagtail/pull/6528 for simple_translation has been submitted by @allcaps, maybe he could give his opinion too.

**Comment by allcaps** [comment]
Thanks for pinging me, and thanks for the pull request.

Generally I think it is a good idea to open up the translation flow so that first-party and third-party translation features can extend Wagtail.

I see the Wagtail hooks mechanism is used. I've got doubts this is the correct approach. From the docs:

> Hooks are typically used to customise the view-level behaviour of the Wagtail admin and front-end. For customisations that only deal with model-level behaviour - such as calling an external service when a page or document is added - it is often better to use [Django’s signal mechanism](https://docs.djangoproject.com/en/stable/topics/signals/) (see also: [Wagtail signals](https://docs.wagtail.org/en/stable/reference/signals.html)), as these are not dependent on a user taking a particular path through the admin interface.
https://docs.wagtail.org/en/stable/reference/hooks.html

I think the copy_for_translation is "model level", so signals seem the better fit. Maybe a `before_copy_for_translation` and a `after_copy_for_translation` signal?

Back in the days, Wagtail did not support multi-language. Third-party packages had to do all kinds dirty hacks. Wagtail hadn't a preference for a specific multi-language solution, as the "best solution" depends on project requirements. Therefore, the core team decided to add translation fields and admin features to Wagtail so it could make it easier for third-party solutions to extend Wagtail.

With above in mind, I would be hesitant to add `parent_locale` field (or `source_locale`, or whatever naming), as this field is useful to some, and redundant, or even confusing in other projects. As the mental model of a source locale isn't relevant in all websites. On top of that, it would be fairly easy for first- and third-party code to add a field, and populate that field when signals are in place.

I do get that some sites like additional behaviour on top of Contrib Simple Translation. I wrote Simple Translation with the idea that it could be a starting point for more advanced solutions (and as a counter to Wagtail Localize). Wagtail Simple Translations is just a bunch of custom views. I guess the best way to add functionality to Simple Translation is to copy/paste Simple Translation and build on that.

**Comment by allcaps** [comment]
Ref: https://github.com/wagtail/rfcs/pull/96

**Comment by NotANormalNerd** [comment]
Closed as this or something close to this has found it's way into wagtail.

**Pull request closed without merging**
