### PR TITLE
Implents ruff into wagtails CI

### PR DESCRIPTION
**Pull request by ollz272**
Not sure how this will go down, but i think this is a worthwhile thing to do and would love to hear thoughts!

I've been using [ruff](https://github.com/charliermarsh/ruff) alot in newer projects as a replacement for flake8 and been really enjoying it. Its speed is very handy on larger projects. I thought it was worthwhile to see if wagtail can benefit from this, and i believe it does.

This PR adds ruff as a dependency, and adds its pre-commit hook & command to the make file

The config for ruff is stored in `ruff.toml`. We could move this to `pyproject.toml` or `.ruff.toml`. The feature set is on parity with flake8 with 2 exceptions.
1. W503. The maintainer [explains](https://github.com/charliermarsh/ruff/issues/1746) that black takes care of this anyway, so ruff doesn't support it.
2. E203. The maintainer is working on it (see https://github.com/charliermarsh/ruff/issues/2402)

In terms of performance, here are some timings i ran locally:
```bash
$ time flake8

real    0m4.054s
user    0m5.739s
sys     0m0.504s

$ time ruff check .

real    0m0.039s
user    0m0.021s
sys     0m0.094s
```
Which is a massive speed up.

This PR doesn't attempt to remove flake8 _yet_, i dont think that is my call, merely this is just to showcase the improvement this can give to a local developer experience. In the future i'd see no reason why flake8 couldn't be removed.

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [x] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [x] **Please list the exact browser and operating system versions you tested**:
    -   [x] **Please list which assistive technologies [^3] you tested**:
-   [x] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

To test try reinstall dependencies and try running `make lint`. Introduce some formatting errors into the code, and check them using `ruff check .`

### CODE REVIEW

**Comment by lb-** [comment]
Flagging as needs design decision. 

@ollz272 do you know if this library will have any issues for Windows developers?

**Comment by ollz272** [comment]
> Flagging as needs design decision.
> 
> @ollz272 do you know if this library will have any issues for Windows developers?

**Comment by ollz272** [comment]
> Flagging as needs design decision.
> 
> @ollz272 do you know if this library will have any issues for Windows developers?

As far as im aware there shouldn't be any issues for windows developers, though im unable to verify this. Given the large projects already using ruff, and there being _some documentation_ on [windows ](https://beta.ruff.rs/docs/faq/#i-want-to-use-ruff-but-i-dont-want-to-use-pyprojecttoml-is-that-possible), i'd guess it would be fine.

**Comment by laymonage** [comment]
Thanks! I'm personally in favour of this. That said, if ruff is up to parity (or close enough) with flake8 and all the plugins we use, we should drop flake8, as otherwise there isn't much value to this (it just adds yet another tool without improving the DX).

**Comment by ollz272** [comment]
> Thanks! I'm personally in favour of this. That said, if ruff is up to parity (or close enough) with flake8 and all the plugins we use, we should drop flake8, as otherwise there isn't much value to this (it just adds yet another tool without improving the DX).

I believe it should be up to parity with what wagtail uses, and supports flake8-comprehension but not flake-8 assertive, though there is an [issue](https://github.com/charliermarsh/ruff/issues/2417) for this. In theory we could also drop isort.

**Comment by lb-** [comment]
I have just done some reading and think this looks like a great idea, it actually replaces a lot of other linting tooling and comes baked in with some things like Django flake8 rules.

It also looks like custom rules are on the roadmap - which could help with our checking of how translations are written. https://github.com/charliermarsh/ruff/issues/283 (in Python, not in html).

https://pypi.org/project/flake8-django/ (note: these rules can be used but without the dependency, it's just part of Ruff). These look like they would be good to enable - as a future PR.

I know that we would not get the assertive checks (unit test assertions), but maybe that's ok with the goal of having less tooling overall.

**Comment by ollz272** [comment]
> I have just done some reading and think this looks like a great idea, it actually replaces a lot of other linting tooling and comes baked in with some things like Django flake8 rules.
> 
> It also looks like custom rules are on the roadmap - which could help with our checking of how translations are written. [charliermarsh/ruff#283](https://github.com/charliermarsh/ruff/issues/283) (in Python, not in html).
> 
> https://pypi.org/project/flake8-django/ (note: these rules can be used but without the dependency, it's just part of Ruff). These look like they would be good to enable - as a future PR.
> 
> I know that we would not get the assertive checks (unit test assertions), but maybe that's ok with the goal of having less tooling overall.

Thanks! Glad you think it's a good idea. How would you like me to proceed now - shall we remove flake8 and isort from pre-commit checks?

**Comment by lb-** [comment]
@ollz272 yeah, do you mind updating this PR with an additional commit on top that does this.

I think there is still a bit of discussion from the core team to confirm this is the way to go, but so far there has not been major push back.

At least if the PR has the flake8/isort removal as a second commit, everyone can review the potential impact and benefits a bit easier.

**Comment by ollz272** [comment]
@lb- Is there any movement on this with the core team? Anything i can do to assist?

**Review by gasman — APPROVED** [review]
Just tested - works nicely here. Very enthusiastic about this!

Only (very tiny) thing I can add is that https://github.com/wagtail/wagtail/blob/main/docs/contributing/python_guidelines.md#pep8 may need an update. I think we probably just need to change "according to isort 5.6.4 rules" to "according to isort rules" - everything else is still accurate, as we're still following PEP8 and isort rules even if we're not using isort itself. (And I see we're pinning ruff to a specific version, so we still avoid the issues with isort potentially being a moving target.)

**Comment by gasman** [comment]
Merged in 459fbb2cc93b733e2ac1b96dfcd7baf5f21dcd3f - thanks @ollz272!

**Pull request closed without merging**
