### PR TITLE
Refactored page fetching logic and cached on request

### LINKED ISSUE #9564: Refactor page fetching logic and cache on request
Reference: https://github.com/wagtail/wagtail/issues/3066#issuecomment-1292028660 from @gasman 

> So, in terms of the change to be made to Wagtail itself, this would just involve building, documenting and testing the find_page_for_request helper - nothing about that needs to indicate that it's intended for use in middleware / CSRF handling. (If you were to subsequently write up a recipe detailing how to use this for CSRF control, I'd sure that would be welcomed, but probably out of scope for the main Wagtail docs and a better fit for a blog post or similar.) For the tests, we'd just need to validate that `find_page_for_request` returns the right result and that `assertNumQueries` gives 0 for any calls after the initial one.

### PR DESCRIPTION
**Pull request by thenewguy**
Fixes #9564

### CODE REVIEW

**Comment by lb-** [comment]
@thenewguy are you still up for pursuing this PR?

If not, we may close this and put a note on the issue.

Otherwise, could you rebase and mark as non-draft so we can see if this can get reviewed.

**Comment by thenewguy** [comment]
Yes. I should be able to make time for this in February.

**Comment by lb-** [comment]
Thanks. No pressure, just checking in on some older PRs.

**Comment by thenewguy** [comment]
> @thenewguy are you still up for pursuing this PR?
> 
> If not, we may close this and put a note on the issue.
> 
> Otherwise, could you rebase and mark as non-draft so we can see if this can get reviewed.

I am refreshing myself on this. Looks like a minimal change. Are we still happy with the implementation per https://github.com/wagtail/wagtail/issues/3066#issuecomment-1292028660

**Comment by thenewguy** [comment]
replaced by #11683 11683

**Pull request closed without merging**
