### PR TITLE
Add deprecation warning for LockUnlockAction

### PR DESCRIPTION
**Pull request by lb-**
- Unsure if we need / want this in so creating as a draft
- #9882

### CODE REVIEW

**Comment by lb-** [comment]
@thibaudcolas  is this something we should put in the release notes?
cc @Lovelyfin00  as per our discussion this week

**Comment by Lovelyfin00** [comment]
Yeah
I think it should be there
Something like this for be available for any release that a major component has been implemented with Stimulus

**Review by thibaudcolas — COMMENTED** [review]
Yep, in this case I don’t think we want to do this, because it being a global variable was only an implementation detail and we never encouraged reuse of this code in third-party implementations anyway.

**Comment by lb-** [comment]
Thanks Thibaud. Agreed.

**Pull request closed without merging**
