### PR TITLE
Updated Linting

### PR DESCRIPTION
**Pull request by PaarthAgarwal**
This PR addresses "Update Linting" part of #8121.

- I have updated to the latest version of stylelint-config-wagtail.
- I have added necessary stylelint rules where we want to retain uppercasing.

### CODE REVIEW

**Comment by PaarthAgarwal** [comment]
Any fix for this conflict?

**Comment by PaarthAgarwal** [comment]
> It looks like the ci failed when trying to use Airbnb
> 
> ```
> [frontend20199](https://app.circleci.com/pipelines/github/wagtail/wagtail/6700/workflows/8a68600b-2369-41c1-b025-c213fbd3f15c/jobs/20199/parallel-runs/0)
>     npm run lint:js
> 
> 0s
> 
> #!/bin/bash -eo pipefail
> npm run lint:js
> 
> 
> > wagtail@1.0.0 lint:js
> > eslint --ext .js,.ts,.tsx --report-unused-disable-directives .
> 
> 
> Oops! Something went wrong! :(
> 
> ESLint: 8.8.0
> 
> ESLint couldn't find the config "airbnb" to extend from. Please check that the name of the config is correct.
> 
> The config "airbnb" was referenced from the config file in "/home/circleci/project/node_modules/@wagtail/eslint-config-wagtail/index.js".
> 
> If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
> 
> 
> Exited with code exit status 2
> 
> CircleCI received exit code 2
> ```
> 
> https://app.circleci.com/pipelines/github/wagtail/wagtail/6700/workflows/8a68600b-2369-41c1-b025-c213fbd3f15c/jobs/20199/parallel-runs/0/steps/0-107

Change in package.lock.json must be the reason for it. How to fix this?

**Comment by lb-** [comment]
What version of Node were you running locally? @PaarthAgarwal check that you used node 16 maybe. 

We are using node 16 in this project and that can be the cause of some odd package lock file differences compared to node 14.

**Comment by lb-** [comment]
Our documentation at the latest (not stable) indicates node 16. 
https://docs.wagtail.org/en/latest/contributing/developing.html#setting-up-the-wagtail-codebase

This may have caused some confusion

**Comment by PaarthAgarwal** [comment]
@lb- you are right. I was using node 14. that was causing the error.
I have resolved the conflicts.
The text-transform conflicts will be resolved when you will merge #8129. I'll rebase this branch then.

**Review by lb- — APPROVED** [review]
looking good @PaarthAgarwal - I reworked your commits and fixed a small linting issue, ran the code locally and new update works great.

Thanks again!

**Comment by PaarthAgarwal** [comment]
> looking good @PaarthAgarwal - I reworked your commits and fixed a small linting issue, ran the code locally and new update works great.
> 
> Thanks again!
Awesome!🔥

**Pull request merged**
