### PR TITLE
Switch TableBlock’s header controls to a field that requires user input

### PR DESCRIPTION
**Pull request by salty-ivy**
addresses issue #5989

### CODE REVIEW

**Comment by salty-ivy** [comment]
> _Please check the following:_
> 
> * [x]  Do the tests still pass?[1](#user-content-fn-1-d60683ee28eab2e858c0b6c4fe076e71)
> * [x]  Does the code comply with the style guide?
>   
>   * [ ]  Run `make lint` from the Wagtail root.
> * [ ]  For Python changes: Have you added tests to cover the new/fixed behaviour?
> * [ ]  For front-end changes: Did you test on all of Wagtail’s supported environments?[2](#user-content-fn-2-d60683ee28eab2e858c0b6c4fe076e71)
>   
>   * [ ]  **Please list the exact browser and operating system versions you tested**:
>   * [ ]  **Please list which assistive technologies [3](#user-content-fn-3-d60683ee28eab2e858c0b6c4fe076e71) you tested**:
> * [ ]  For new features: Has the documentation been updated accordingly?
> 
> **Please describe additional details for testing this change**.
> 
> ## Footnotes
> 1. [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing) [↩](#user-content-fnref-1-d60683ee28eab2e858c0b6c4fe076e71)
> 2. [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support) [↩](#user-content-fnref-2-d60683ee28eab2e858c0b6c4fe076e71)
> 3. [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets) [↩](#user-content-fnref-3-d60683ee28eab2e858c0b6c4fe076e71)

**Comment by thibaudcolas** [comment]
Thank you for giving this a shot @salty-ivy! Could you spend a moment to:

- Update your pull request following our [official template](https://github.com/wagtail/wagtail/blob/main/.github/PULL_REQUEST_TEMPLATE.md). It really helps us to have that information, in particular knowing how much testing has been done already.
- And additionally comment on how this pull request differs from #6763

**Comment by salty-ivy** [comment]
> Thank you for giving this a shot @salty-ivy! Could you spend a moment to:
> 
> * Update your pull request following our [official template](https://github.com/wagtail/wagtail/blob/main/.github/PULL_REQUEST_TEMPLATE.md). It really helps us to have that information, in particular knowing how much testing has been done already.
> * And additionally comment on how this pull request differs from [Converted column and row headers from checkboxes to a dropdown menu #6763](https://github.com/wagtail/wagtail/pull/6763)

@thibaudcolas  thanks for the feedback it still needs little bit more work i would update everything after that
i apologize for the inconvenience

**Comment by lb-** [comment]
@salty-ivy just checking in if you are still keen on pursuing this PR?

It's all good if not, feel free to close and maybe add a comment on the original issue that a WIP PR was raised and then others may be able to pick up where you left off.

**Comment by salty-ivy** [comment]
@lb-  I would  like definitely love to pursue this one but I got little busy with other PRs and it swiftly glided away from my radar.

As of now I think this PR is complete in its own although there's one small issue I wasn't able to figure out why is it really happening. will provide complete info soon.

however if time doesn't permits would love to pass this to other fellow contributors.

**Comment by salty-ivy** [comment]
> @lb- I would like definitely love to pursue this one but I got little busy with other PRs and it swiftly glided away from my radar.
> 
> As of now I think this PR is complete in its own although there's one small issue I wasn't able to figure out why is it really happening. will provide complete info soon.
> 
> however if time doesn't permits would love to pass this to other fellow contributors.

@lb- would request a view on this one, as I am not sure about how this strange behavior is taking place.

**Comment by lb-** [comment]
Thanks Aman, I will flag myself for a review on this.

**Comment by lb-** [comment]
Sorry I have not had time to review this, it may need to be rebased / redone for a new review. Alternatively, this PR can be closed and then @salty-ivy you can add a bunch of notes / questions on #5989 for someone else to pick up later.

**Comment by lb-** [comment]
Replaced with #11327

**Pull request closed without merging**
