### PR TITLE
Migrate Styleguide ad-hoc JS to use styles only

### PR DESCRIPTION
**Pull request by lb-**
With #11136 & #11140 merged - I thought it would be good to finish off these changes with a migration away from the jQuery JS used in the Styleguide.

I think the animated progress bar is probably not the most critical feature for this page but I have kept it and re-implemented with a simpler CSS animation.

A previous PR I made has a JS implementation if we do feel the JS is important to showcase #11153 .

The main benefit of this change is that we no longer rely on jQuery and avoid an inline script, a small step towards #1288 (CSP compliance).

### CODE REVIEW

**Comment by lb-** [comment]
Getting an odd CI error.

```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    semgrep==1.40.0 from https://files.pythonhosted.org/packages/40/f3/21bc26804dbf890ded5e638ec1c8b61575ad98ae683f73ff6ace3ccb9948/semgrep-1.40.0-cp37.cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl#sha256=89d9405ab3fcbfb37d52a450da69ad706518ec820ba07e0f078c46c48dd837e1 (from wagtail==6.0a0->-r /tmp/pipenv-biwvh_ym-requirements/pipenv-1de1e96h-requirement.txt (line 1)):
        Expected sha256 89d9405ab3fcbfb37d52a450da69ad706518ec820ba07e0f078c46c48dd837e1
             Got        3e365e408ad72b4524e094551673d6c89c4be809618d68e57d6b53b1588bc506
```

**Review by Stormheg — APPROVED** [review]
This looks simple enough to me 👍

**Comment by Stormheg** [comment]
> A previous PR I made has a JS implementation if we do feel the JS is important to showcase https://github.com/wagtail/wagtail/pull/11153 .

I don't feel like the JS is important to keep. Your css version shows the same thing: use the `width` property to control the progress.

**Comment by lb-** [comment]
Thanks @Stormheg

**Comment by lb-** [comment]
Added changelog entry and will merge in.

**Pull request merged**
