### PR TITLE
Fix FieldBlocks commenting

### PR DESCRIPTION
**Pull request by jacobtoppm**
Fixes https://github.com/wagtail/wagtail/issues/9035 in Wagtail 4

This occurred because the DOM element used as a template for the "comment added" buttons could potentially not exist when the `FieldBlock` initialisation ran and attempted to add its own field level comment widget (if this JS ran before the `CommentPanel` HTML that includes the declaration of this element loaded), resulting in it trying to clone a null element when comments were added using that widget. For now, this PR makes it fall back to initialising the comment adding widget post DOM load if this element is currently missing (alternative options: we could put the annotation template element earlier in the DOM, replicate the annotation template node in the block, hardcode it into the widget code rather than cloning an existing element, or do all streamfield initialisation after DOM load)

### CODE REVIEW

**Comment by lb-** [comment]
@jacobtoppm  thanks for this fix - I agree that maybe a re-think of how we load this JS is probably a good long term solution but this fix is solid and works well.

Will merge in

**Review by lb- — APPROVED** [review]

**Comment by jacobtoppm** [comment]
Thanks for the review and merge LB! I think this should probably go into
the 4.0 branch as well as it's a nastier bug fix, though I know it wasn't
introduced in 4 - what do you think?

**Comment by lb-** [comment]
@jacobtoppm yep - on it - I think we want to fix this in 4.0 and maybe even backport to 3.0 stable.

**Comment by lb-** [comment]
* stable/4.0 cherry pick - 0a28ed60fd0c70e25122d6969056e57cd3fe99b4
* stable/3.0 cherry pick - f57f0d5aaf2810836ff1584c52b0e5ca3d76a2ba

**Comment by thibaudcolas** [comment]
Thank you both for figuring this one out 😌

**Pull request merged**
