### PR TITLE
Upgrade to jQuery v3

### PR DESCRIPTION
**Pull request by jjanssen**
Related issue: #3977

For now it is a work in progress PR in order to upgrade jQuery to version 3. With Wagtail 2.0 coming closer it also makes sense to update since our current version 2 will no longer receive patches. Fortunately the jQuery team has [`jquery-migrate`](https://github.com/jquery/jquery-migrate/blob/master/warnings.md) to support the upgrade process.

**What has been done so far:**
- Referenced the latest jQuery from the CDN.
- Referenced the latest jQuery UI from the CDN.
- The main warnings that were throwing all had to do with the [jQuery.fn.click() event shorthand being deprecated](https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated) (and other relevant shorthands). This caused the most warnings throughout our codebase which were easily to find and replace.

**What still has to be done:**
A few things I noted on the spot although I have not clicked around that thoroughly.

- [x] Hallo.js throws a few warnings
- [x] Hallo-bootstrap.js throw a few warnings
- [x] Investigate: react-focus-trap suddenly throws an unexplaining error
- [x] Remove jQuery CDN reference and integrate in codebase
- [x] Rangy-select.js throws a warning (unrelated to jQuery)
- [x] Validate additional vendor scripts for issues
- [x] Test all the things
- [x] Remove jQuery migrate when done testing

**Strategy:**
Only update vendor libraries whereas necessary on the methods which are throwing migration warnings. The benefit of having the vendor code locally is that we can easily change it to the current migration. Later we can investigate whether to upgrade some libraries completely (maybe download from npm as well?).

**Testing:**
This will need a double check to verify the touched code areas still work as intended. When ready, every help with that would be appreciated since it is a lot to go through.

**UI Testing:**
If I still have time available I'd like to setup a local [Cucumber project](https://github.com/webdriverio/cucumber-boilerplate) (based on either the demo or the bakery repository) to validate if the UI interaction still works as intended.

### CODE REVIEW

**Comment by tomdyson** [comment]
@jjanssen thanks very much for your work on this so far. Are you able to make an instance available somewhere, so I can organise some UI testing?

**Comment by jjanssen** [comment]
Not at the moment unfortunately, will have to look into that. 
But I'd first want to make a bit more progression.

**Comment by thibaudcolas** [comment]
@jjanssen I can have a look at `react-focus-trap` if you want, not sure why that would fail.

This PR would also be a good opportunity for me to resurrect the UI regression testing I had in [wagtail-dev-tooling](https://github.com/thibaudcolas/wagtail-dev-tooling). I've been very keen to do that for a while now, this feels like the right use case.

**Comment by jjanssen** [comment]
@thibaudcolas would be great if you could have a look into the focus-trap issue.

You are testing with BackstopJS right? I think either way (Cucumber or Backstop), it can provide us a foundation for having regression testing. Think the main goal is to validate the specific methods of touched files gets validated and then we can extend further on.

**Comment by thibaudcolas** [comment]
Yep, BackstopJS. It's not like I have much experience (or success) with it, so if you feel Cucumber works for you go for it!

**Comment by thibaudcolas** [comment]
@jjanssen I can't reproduce the issue with the focus trap, were you testing on a specific browser or section of the admin?

**Comment by jjanssen** [comment]
@thibaudcolas Yeah come to think of it. I just did a rebuild and I don't encounter it either. Possibly I executed a find & replace into the compiled version of that code. Seriously forgot to re-enable my brain after my 4 week absence. Sorry :-(

**Comment by thibaudcolas** [comment]
@jjanssen took me a bit longer than I thought to finish this, sorry. My tests aren't as easy to use as I'd like, but it all seems to be working fine anyway. I've spotted differences in how some elements are positioned but this is very small (1 pixel difference), and there is only one I've been able to reproduce consistently – the Hallo toolbar position (going back and forth between master and this branch here):

jquery-upgrade-diff

Very subtle. On the jQuery-upgraded branch, the toolbar is given `top: 412.375px;`, whereas on master it gets `top: 413.094px;`. I've also observed similar sub-pixel differences in `width`. Visually it's not too significant so I think we can assume jQuery changed how they do some of those calculations and move on. 

Here's another change in positioning / width for which I couldn't even find the origin. This may just be Chrome behaving differently based on my inspector / viewport resizing, because I don't see what jQuery has to do with this.

jquery-upgrade-diff-2

See the full report (with plenty of false positive fails) at https://thibaudcolas.github.io/wagtail-dev-tooling/backstop_data/html_report/index.html.

NB: https://bakerydemo-thibaudcolas.herokuapp.com/ has been updated to reflect the latest changes.

**Comment by jjanssen** [comment]
@thibaudcolas thanks for helping me out with this. Do you still have the report available? The 1st link to github.io is giving me a 404 error.

**Comment by jjanssen** [comment]
Gathering my last bits and remarks as a comment:
- [ ] Clicking in the save button within snippets does not submit the page (migration issue)

**Comment by gasman** [comment]
The save button on snippets was a bug fixed in #4002 - presumably a rebase will fix it here.

**Comment by jjanssen** [comment]
Well this PR was a bit of pain to go through as it involved a lot of manual testing and seeing if warnings would show up on any given page. As stated when opening I only updated vendor libraries whereas necessary on the methods which were throwing migration warnings (with the exception of rangy-select). For now this PR is rebased with master and also follows the new path structure. As we speak the space @thibaudcolas provided is not yet up-to-date, but I would guess that would be a bit of burden since it would also require the 2.0 branch for the Bakerydemo. 

The only thing left is some help with some manual testing:
- To see if I missed on possible deprecation warnings 
- Or malfunctioning functionalities due to the changes

For the time being I left the inclusion of jQuery migrate from the CDN. If anyone comes across console warnings then they are easier to trace.
The side-note is that it currently throws two untraceable (and maybe false) deprecation warnings on pages:
- `JQMIGRATE: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos`
- `JQMIGRATE: jQuery.unique is deprecated; use jQuery.uniqueSort`

From what I have gone through so far based upon the Bakerydemo in the latest Chrome:
- Uploading of images
- Uploading of documents
- Paginating through images
- Editing pages and contents
    - Page tabs: content, promote, settings
    - Date picker within the settings tab
- Editing content:
    - Which involved StreamField blocks
    - Which involves the HalloJS editor (inserting an image)
- Modals: 
    - Image Chooser
    - Document Chooser
    - Page Chooser
- Wagtailadmin views
- Form submission listing
- Settings and its contents

@thibaudcolas Earlier you reported of the HalloJS toolbar wrapping onto the second line but I have not been reproduce this on the exact some content. Are there particular steps for reproduction?

**Comment by thibaudcolas** [comment]
Just updated https://bakerydemo-thibaudcolas.herokuapp.com/ with the latest changes if other people want to help with manual testing. Sorry about the regression report, I think I broke it completely and I don't have the time to update it right now.

The Hallo difference before-after is the positioning of the toolbar (the wrapping happens when you open the page on a small viewport, then resize it to be bigger). It's very subtle so nothing to worry in my opinion.

I did quite a bit of manual testing (before the rebase, same time as https://github.com/wagtail/wagtail/pull/4021#issuecomment-346966195), and everything I tried worked. Also didn't see any other warnings than the ones you mentioned above.

You can see the full list of things I tested at https://github.com/thibaudcolas/wagtail-dev-tooling/blob/master/backstop/scenarios.js (pretty much everything Wagtail does), I'll highlight the parts that actually rely on JavaScript:

- Account dropdown in navbar
- Navbar sub-menu, both settings & ModelAdmin
- Explorer menu navigation
- Edit page "more" dropdown
- Explorer page "set privacy" modal
- Edit page "set privacy" modal
- Page chooser, both choose and clear
- Image chooser, both choose and clear
- Edit page tabs
- Add page tabs
- All Hallo controls
- All Streamfield manipulations (add, remove, move up - down)
- Forms date filter
- User tabs
- Groups permissions add/remove
- Collections "set privacy" modal
- Add search pick

Note I only went through this all in Chrome. Happy to give it a go in other browser(s) if you think that will help.

For the warnings, from what I can see both of those deprecated functions are used in jQuery UI. Here are the un-minified snippets I found:

```js
// There are 4 instances of `.expr[":"]` in the code.
t.extend(t.expr[":"], {
        focusable: function(e) {  
```

```js
// There are 3 instances of `.unique(` in the code.
this.childWidgets = t(t.unique(i)),
```

I think those are valid warnings, but it seems that jQuery UI 1.12 claims to support jQuery 3 so I think we can move on as-is (see https://stackoverflow.com/questions/40493815/can-i-use-jquery-ui-1-12-1-with-jquery-3-x).

**Comment by jjanssen** [comment]
As just discussed within the Core meeting we're going to merge this for 2.0. Any additional testing will take place in the release candidate by the community. I have just removed the reference to the jQuery migrate script in the template.

**Comment by lb-** [comment]
@jjanssen I have just gone through manually testing each of the scenarios mentioned above at https://bakerydemo-thibaudcolas.herokuapp.com/

Tested on:

* Safari Version 11.0.2 - macOS Sierra (10.12.6)
* Firefox 57.0.1 (64-bit) - macOS Sierra (10.12.6)

The only issues I ran into were the `.expr[":"]` item already mentioned.

All works great!

**Pull request merged**
