### PR TITLE
Update jquery-datetimepicker to 2.5.18

### PR DESCRIPTION
**Pull request by Pomax**
- Fixes an `eval()` CSP violation
- includes touch scroll fix from commit 87a7a79 (L909)

closes https://github.com/wagtail/wagtail/issues/4329

### CODE REVIEW

**Comment by Pomax** [comment]
Can you explain what you're looking for in terms of what else is included? This bumps up the datetimepicker from 2.3.8 to 2.5.18 (so a minor version bump, which should not impact the API for the datetimepicker, only the stability/internals - the changelog between those two versions [is rather large](https://github.com/xdan/datetimepicker/compare/2.3.8...2.5.18)), with the patch that @gasman pointed out needed to be preserved.

Browsers tested: Chrome 64, Firefox Nightly (60.0a1), Edge 41, Vivaldi 1.14 (I do not have access to the full list of browsers the dev docs suggests to test with). All browsers tested on Windows 10 Pro x64.

I mainly tested by clicking "edit" for a variety of `class CustomPageType(Page): ...` implementations and hitting up the "settings" tab to edit the publish/expiry datetimes for a wagtail instance we're trying to get set up at the Mozilla Foundation.

**Comment by thibaudcolas** [comment]
👌 

I see the library has no explicit CHANGELOG, which would be what I'm after in order to know what to look out for when testing. It's a minor version bump but I don't think this tells much – there's still been 3+ years and 20+ versions.

No worries for the browsers you couldn't test on, we'll get through this in further reviews/tests.

**Comment by Pomax** [comment]
Yeah fair - I'll see about reproducing those errors and figure out if they're easily addressed; are any of these things you caught things that can be automated? (mocha/selenium testing for instance?)

**Comment by Pomax** [comment]
Looks like datepicker itself has some silly bugs around touch vs mouse events. I've filed https://github.com/xdan/datetimepicker/pull/654/files to get those resolved.

**Comment by Pomax** [comment]
@thibaudcolas  My PR to datetimepicker landed, and 2.5.19 got released, which should fix all those weird issues by no longer throwing and breaking UX =)

I've updated the PR to use that version instead now if you'd like to re-review.

**Comment by thibaudcolas** [comment]
@Pomax 👏 thank you for taking the time to land a PR there. I'm sure it wasn't easy, it's much appreciated. I'll get on with the review.

**Comment by thibaudcolas** [comment]
It's in 🙂 scheduled for release in Wagtail 2.1

Thank you @Pomax!

**Comment by Pomax** [comment]
awesome, many thanks! I also have another PR up for tackling the same issue but in modal-workflow, replacing the `eval()` call there a different way to effect the same thing, hopefully that can make it into 2.1 too =)

**Pull request merged**
