### PR TITLE
remove dateformat library usage

### PR DESCRIPTION
**Pull request by lb-**
* Fix for #7904 
* Do the tests still pass? ✅ 
* Does the code comply with the style guide? ✅ 
* For front-end changes;
  * Chrome 99 MacOS, Firefox 96 MacOS, Safari 15 MacOS, Edge 97 Windows 10
  * NVDA Windows 10
* Note: This will NOT work in IE11
* Had to use the any for the date format options due to this current ts issue https://github.com/microsoft/TypeScript/issues/38266#issuecomment-912508678 (while the issue is closed, reading the comments says the bug still exists)
* Update: added time element also for better screen reader support with no visual changes https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

## Screenshots
**Edge / NVDA**
Screen Shot 2022-02-01 at 8 10 16 am

**Chrome**
Screen Shot 2022-02-01 at 8 06 07 am

**Safari**
Screen Shot 2022-02-01 at 8 05 38 am

**Firefox**
Screen Shot 2022-02-01 at 7 56 14 am

**Time element**
Reminder - ISO strings are always UTC

Screen Shot 2022-02-01 at 8 18 30 am

### CODE REVIEW

**Review by thibaudcolas — APPROVED** [review]
Thank you @lb-! Great to have this dependency removed.

It’s worth noting the `dateStyle` and `timeStyle` options are only supported in Safari 14.1+ / 14.5+ on iOS, which is only about a year old. On Safari iOS 13, I get the following format: `4/2/2022`, which I think is ok.

```diff
-4 Feb 2022 13:43
+Chrome: 4 Feb 2022, 13:43
+Firefox: 4 Feb 2022, 13:43
+Safari 15: 4 Feb 2022 at 13:43
+Safari iOS13: 4/2/2022
+Android 10 Chrome: Feb 4, 2022, 1:59 PM
+MS Edge: 4 Feb 2022, 15:02
```

**Comment by lb-** [comment]
@thibaudcolas thanks for flagging the older safari uusage - I must have missed that in my digging.

How did you actually practically check iOS 13? Do you use browserstack?

**Comment by thibaudcolas** [comment]
@lb- yes – do you want access?

**Comment by lb-** [comment]
@thibaudcolas  I have an account for work, but if there is a proper Wagtail account for the open source stuff that may be more appropriate. Do you just run the code locally and use the browserstack local system?

**Pull request merged**
