### PR TITLE
Makes it possible to set a custom Gravatar source

### PR DESCRIPTION
**Pull request by bloodywing**
I made this for personal use, but think it's nice enough to share it with the rest of the wagtail users. Also makes it possible to no longer query gravatar.

### CODE REVIEW

**Comment by bloodywing** [comment]
Travis had a Timeout on pypi.python.org here ...

**Comment by gasman** [comment]
Thanks @bloodywing! Just so you're aware, there's an existing PR #4062 currently in review that makes major changes to avatar handling - we'll revisit this one once that one is merged.

**Comment by bloodywing** [comment]
@gasman yes I know that pull request and I would remove the `gravatar.py` file. But my code can go into the `wagtail/wagtail/users/utils.py` after #4062 has been merged.

**Comment by gasman** [comment]
Now incorporated into #4462

**Pull request closed without merging**
