### PR TITLE
Updated dynamic sidebar Wagtail logo & other logos

### PR DESCRIPTION
**Pull request by OsafAliSayed**
Fixes: [#10404](https://github.com/wagtail/wagtail/issues/10404)

Using the previous PR: [#10659](https://github.com/wagtail/wagtail/pull/10659)

| Before | After | 
| ------------- |:-------------:| 
|  image    |  image |

### CODE REVIEW

**Review by lb- — APPROVED** [review]
Thanks @OsafAliSayed  looks good.

Left - old, Right - new
Screenshot 2024-03-23 at 6 35 52 pm


I have made one tweak to the CSS 'transform', instead of making this change in CSS, I have made this change in the SVG path.

**Comment by lb-** [comment]
I prepared the new logos and was about to post an update on the issue but as the logos are done I will just put them as part of this PR.

**Comment by lb-** [comment]
Screenshot 2024-03-23 at 7 53 34 pm

Favicon update looks good and has worked when deployed.

**Comment by BertrandBordage** [comment]
Lovely new animation, great job @OsafAliSayed! You captured well the playfulness of wagtails 🥲 
Before/after of the animation:

https://github.com/user-attachments/assets/1f15f35d-3f21-416a-8d40-4b29bc1435d6

**Pull request merged**
