### PR TITLE
{% include_block page.block as block_content %}

### PR DESCRIPTION
**Pull request by brabant**
Allows to store result of {% include_block %} in a variable for further use of filters

Thanks for contributing to Wagtail! 🎉

Before submitting, please review the contributor guidelines <http://docs.wagtail.io/en/latest/contributing/index.html> and check the following:

* Do the tests still pass? (http://docs.wagtail.io/en/latest/contributing/developing.html#testing)
* Does the code comply with the style guide? (Run `make lint` from the Wagtail root)
* For Python changes: Have you added tests to cover the new/fixed behaviour?
* For front-end changes: Did you test on all of Wagtail’s supported browsers? **Please list the exact versions you tested**.
* For new features: Has the documentation been updated accordingly?

### CODE REVIEW

**Comment by gasman** [comment]
Thanks for the contribution @brabant!

Note that this will need tests and documentation before it's ready to be merged.

I'd really need to know more about the motivation for this change before we can decide it's something we want to adopt, though. Normally, the output of `{% include_block %}` would be an HTML fragment produced by a template, and it would be quite unusual to apply filters to that output - you'd normally apply those filters as part of that template. For blocks that return non-HTML values, such as DateBlock, `{{ my_block.value|date:"D d M Y" }}` would be a more natural thing to do. Is there something that can't be achieved by either of these options?

**Comment by brabant** [comment]
At present I use it to wrap the h2 and h3 tags in difficult layout. 
Now headings are inserted through RichText and it would be possible to make the separate block - "Beautiful heading", but there are no wish to produce many blocks.

**Comment by gasman** [comment]
Thanks for the clarification. After thinking about this some more, I think this option is likely to cause confusion for users - the natural reading of the `include_block` tag is that it will include the rendered version of the value into the page, so `{% include_block ... as var %}` is effectively saying "include this without including it".

For your application, adding the filter to `block.value` should work - e.g. `{{ block.value|transform_header_tags }}`. Django's `{% filter %}` tag would be another option: https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#filter

**Comment by brabant** [comment]
Really, it can create confusion. Just I modified inlcude_block under the needs and have thought that it can be useful also for others. 
Filter { { block.value|transform_header_tags } } - hasn't suited me since for some of my blocks the context, for example, a block-form insert is necessary

**Pull request closed without merging**
