### PR TITLE
Update port usage instructions to suggest alternatives

### PR DESCRIPTION
**Pull request by ankit02327**
-Clarified instructions for handling port conflicts.
-Suggested using alternative ports (e.g., 8001, 8002) when the default port is in use.

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
I'm not sure this really adds anything. The guidance for "Have a look at what `manage.py runserver` outputs" should be enough. It's not necessary to specify example ports etc.

**Comment by ankit02327** [comment]
@RealOrangeOne I understand your point, but I believe that port conflicts are a very common issue that users might encounter. Mentioning alternative ports explicitly can help users resolve the issue quickly without having to look for solutions elsewhere.

**Comment by gasman** [comment]
If someone is unfamiliar enough with `runserver` that they need this advice, telling them to "try using an alternative port" probably isn't going to be helpful - at minimum you'd need to tell them to run the command `python manage.py runserver 0.0.0.0:8001`.

**Comment by ankit02327** [comment]
@gasman That's a valid point. I agree that more detailed guidance might be necessary. I'll update the suggestion to include the full command (python manage.py runserver 0.0.0.0:8001) for clarity and to make it more helpful for users unfamiliar with runserver.

**Comment by ankit02327** [comment]
Actually, running `python manage.py runserver 8001` works fine as an alternative if the default port is in use. I believe simply mentioning the port number should be sufficient for most users, as it's a common issue and can be easily resolved without further explanation.

**Comment by RealOrangeOne** [comment]
This part of the docs is specifically about how to access your site. Therefore, telling people to check how they ran the server is enough. It's up to `runserver` to tell a person if a port is in use.

I don't think any change to the docs is necessary.

**Comment by ankit02327** [comment]
Thanks for the feedback! I agree that the existing instructions are sufficient. I'll close this PR now.

**Pull request closed without merging**
