### PR TITLE
Update Sphinx Wagtail Theme to 5.3.0

### PR DESCRIPTION
**Pull request by lb-**
- https://pypi.org/project/sphinx-wagtail-theme/5.2.0/
- https://pypi.org/project/sphinx-wagtail-theme/5.3.0/
* https://github.com/wagtail/sphinx_wagtail_theme/blob/main/CHANGELOG.md#530---2022-08-20
* https://github.com/wagtail/sphinx_wagtail_theme/blob/main/CHANGELOG.md#520---2022-08-17
- Contains some CSS fixes that would be really good to go live with in 4.0 - mainly around the menu scrolling on smaller devices, dark mode, many accessibility fixes and styling alignment with Wagtail latest font stack & colours.

### CODE REVIEW

**Comment by lb-** [comment]
Flagging for 4.0 if possible - will not make a huge difference to the release candidate process but just ensures that there will be styling fixes in the docs going live alongside the new release.

**Comment by zerolab** [comment]
Preview: https://wagtail--9013.org.readthedocs.build/en/9013/

The first thing that jumps out is that the sidebar menu has a horizontal scroller.
Clicked around and could not find anything else that is obvious

**Comment by lb-** [comment]
@zerolab give it a go now - will fix on the Wagtail theme side but will do that in a future release, for now added a custom.css fix.

**Comment by zerolab** [comment]
@lb- 🌟
That fixed it. Can't find any other issues. Would be good to get a second pair of eyes, but it is a go from me

**Comment by lb-** [comment]
Pausing this. We will hopefully have a better docs update soon.

**Comment by lb-** [comment]
Latest styling updates do not appear to be compatible with the algolia - may not be practical to fix quickly.

Screen Shot 2022-08-20 at 2 43 51 pm
Screen Shot 2022-08-20 at 2 43 43 pm

To investigate

* docs/_static/css/docsearch.overrides.css  -> can we add more styling overrides so that the drop-down appears outside of the max width overflow none sidebar
* might need to see if there is some config or way to ensure the `background-color: transparent;` is not set as an inline style on the search box OR add more css overrides that re-apply the desired styles for dark-mode and not

**Comment by lb-** [comment]
@zerolab @vsalvino - this is ready for another review.

Most issues are fixed that were mentioned above.
* Dark mode / light mode (and whatever is default) now have the correct search field colour
* When the search results are opened - they no longer overflow (by un-setting overflow scroll on the sidebar when open) - this is not ideal but I cannot see another way around this aside from giving up on the nice left sidebar scrolling completely
* Dark-mode will not work for the algolia results list - but that is probably not critical and can be a new issue
* We can bring some nicer solutions into the Sphinx theme - https://github.com/wagtail/sphinx_wagtail_theme/issues/201 raised - but there may still be a need to do some algolia specific 'hacks' long term.

I still think this is worth reviewing for 4.0 but understand if this is now too much of a change.

There are a huge amount of small issues fixed with the docs upgrade, the menu is now much more usable on mobile, accessibility fixes, colour / font alignment with Wagtail and of course dark mode.

@gasman  - feel free to chime in with thoughts on this.

**Comment by zerolab** [comment]
Nice work @lb- .
The tweaks work with the latest theme. There is a small issue when switching between light and dark modes:

[docs-algolia.webm](https://user-images.githubusercontent.com/31622/185755598-53147f32-b3bd-486c-823b-d684b150195d.webm)

but it works on reload so not the end of the world.

**Comment by lb-** [comment]
@zerolab good find - I have raised a docs bug for this https://github.com/wagtail/sphinx_wagtail_theme/issues/203

I agree it is probably not a huge problem and not a blocker.

Unfortunately we cannot really fix that without a new docs theme release.

**Comment by vsalvino** [comment]
Looks good to me!

**Comment by lb-** [comment]
Thanks @vsalvino - appreciate those final tweaks.

I will merge this in and then do a separate commit for changelog.

**Comment by lb-** [comment]
cherry picked to 4.0 stable
98ddf8d8d1772c51ff65c663cd805d7965c5ffb5 & 8329f25c01f9016cc5888c2c4e0d96ebea41445e

**Comment by lb-** [comment]
Pulled out the documentation improvements to their own section in the release notes, also with a bit of a summary of the Sphinx Wagtail theme improvements.

* f072bffb747cb35cc18901bb60abd7e84be88302 (main)
* 2220301dc26a9e9c94ed2af88b958b17096db164 (4.0 cherry pick)

**Pull request merged**
