### PR TITLE
Fix sass build on Windows

### PR DESCRIPTION
**Pull request by vsalvino**
On a Windows development environment, the SCSS to CSS build was not functional, putting the CSS files next to their SCSS counterparts, instead of moving them to the appropriate static directory. I believe the cause of this was a faulty gulp script (which actually perplexes me how it worked correctly on any platform?). Perhaps this was related to a gulp/vinyl/path handling behavior change in some combination of gulp + node?

Additional context in [slack thread](https://wagtailcms.slack.com/archives/C81FGJR2S/p1630464172090400) and another [slack thread](https://wagtailcms.slack.com/archives/C81FGJR2S/p1632504378114400).

Changes:
* Refactor gulp scss renaming pipeline, following the example of other working pipelines.
* Drop path separator rewriting during gulp build in favor of using actual system paths.
* Ignore `.venv` directory (I thought this was common... maybe it's just me!)

Confirmed the npm build fully works on Windows 10 (Using Node 16.10.0). Help testing this on **clean git clones** (not containing any pre-built files) on Mac, Linux, and other Windowses would be much appreciated!

### CODE REVIEW

**Comment by lb-** [comment]
@vsalvino I have not tested this yet, but just a heads up we are actually on Node 14 (see `.nvmrc`), it should not make too much difference (as no new packages were added).

Do you mind testing a build locally on Node 14 also and checking it works, (e.g. `nvm use` and then `npm ci` to clear packages & reinstall) then `npm run build`/ `npm run watch` (to test the dev watcher also).

**Comment by vsalvino** [comment]
I just tested on node 14.17.6 on Windows and confirmed it also works as expected.

**Comment by lb-** [comment]
I have tested this out on macOS (new clone) and builds fine, but would be good to get another validation from a Windows user.

**Comment by gasman** [comment]
Tested successfully on Windows 10. Following the existing install steps at https://docs.wagtail.io/en/stable/contributing/developing.html resulted in .css files being placed in static_src - retrying with this branch, all is working as intended 👍

**Comment by gasman** [comment]
Merged and release note added in f8e7a049c0f2dcbbeecc32344fa7c20d7f2c63a3 - thanks @vsalvino!

**Pull request merged**
