### PR TITLE
issue#12299 , as directed the issue regarding that element seems to overflow its parent wrapper

### LINKED ISSUE #12299: ViewSet filter date picker missing margin
### Issue Summary
filtering a snippet by date shows the date field missing margins on one side.
image

### Steps to Reproduce
I am using the model BreadPage from the bakery demo as a ModelViewSet to demo this issue since the other viewsets do not make use of any date fields.

1. In bakery demo bakerydemo > breads > wagtail_hooks.py 

Add the following to the bottom
```python
from bakerydemo.breads.models import BreadPage
class ExampleModelViewSet(ModelViewSet):
    model = BreadPage
    add_to_admin_menu = True

    panels = [
        FieldPanel("title"),
    ]
    list_filter = ["last_published_at"]

register_snippet(ExampleModelViewSet)
```
2. in the admin sidebar click Bread Pages
3. Click filter options > Last published at. It will show below
image

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Wagtail version: 6.3 (dev)
### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

### PR DESCRIPTION
**Pull request by Rohit-Singh-01**
Fixes #12299.

### CODE REVIEW

**Comment by zerolab** [comment]
Thank you @Rohit-Singh-01, but will close as duplicate of #12336

**Comment by laymonage** [comment]
#12336 is an incorrect fix, so I'm reopening this. Will review later.

**Review by laymonage — APPROVED** [review]
Thanks!

## Before

image

## After

image

**Comment by laymonage** [comment]
Merged in 105338d.

**Pull request closed without merging**
