### PR TITLE
Added the function get_gravatar_url with Unit Test

### PR DESCRIPTION
**Pull request by nandini584**
This is an extension of PR #11077, where a new improvement of adding gravatar images was to be added, I have done the same and written two test cases, first for default size and second for custom_size, the function increases the original size to 2X and generated a safe_md5 hash for the email to constitute a URL,

Below is the screenshot of the passing test case.

Screenshot 2024-03-26 103751

### CODE REVIEW

**Comment by lb-** [comment]
@nandini584 thank you. 

Could you please look at the failing test 

```
======================================================================
FAIL: test_adapt (wagtail.admin.tests.ui.test_sidebar.TestAdaptMainMenuModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/wagtail/wagtail/wagtail/admin/tests/ui/test_sidebar.py", line 235, in test_adapt
    self.assertEqual(
AssertionError: {'_ty[168 chars]'', 'attrs': {}, 'url': '/pages/'}]}], [{'_typ[461 chars]0'}]} != {'_ty[168 chars]'', 'url': '/pages/', 'attrs': {}}]}], [{'_typ[461 chars]m'}]}
Diff is 1499 characters long. Set self.maxDiff to None to see it.
```

My guess is the URL generation has changed for.the sidebar data, maybe this is not intentional. 


Also, you'll need to do a `make format` to ensure the CI format checks pass. 

Great stuff - myself or someone will do a full review when possible.

**Comment by nandini584** [comment]
Ohk...

**Comment by lb-** [comment]
Ohh wait, I think we DO want to change the default (re-reading the previous PR), so the failed test may need to be updated to reflect the new behaviour.

**Comment by lb-** [comment]
@nandini584 just checking, it would be good for you to also have a full read of the previous PR's comments. I did a review of that suggesting a different approach where we do this change but also support reading any other default params from the configured (in settings) URL.

**Comment by nandini584** [comment]
Sure @lb- , I will have a full read and make updates.

**Comment by lb-** [comment]
How are you going with this @nandini584  are you still keen to pursue this PR?

If not, we maybe can consider raising an issue with this and the previous PR linked, seeing if others may be up for the enhancement in the future.

**Comment by nandini584** [comment]
Hey @lb- I am not working on this pr currently.

**Comment by lb-** [comment]
OK, no problems @nandini584  thanks for giving it a go.

I will close this PR and have raise two new issues instead.

https://github.com/wagtail/wagtail/issues/12658
https://github.com/wagtail/wagtail/issues/12659

**Pull request closed without merging**
