### PR TITLE
[WIP] Unify link choosers

### PR DESCRIPTION
**Pull request by mx-moth**
This is still a work in progress, but the concept works!

My colleague @seb-b and I recently tried to add a News Article chooser for [Wagtail News](https://pypi.python.org/pypi/wagtailnews/), and we found it to be much more difficult than it needed to be. We needed to make a new hallo plugin, even though there were multiple ones already there that did the same basic thing. We needed to add a DB whitelister in a completely different place. We needed to register against many different hooks, and make a variety of magical classes and views. We needed to insert some funky JS snippets to register our plugin and register a URL. Lots of this had already been done in other places, and it felt like we were duplicating a lot of code.

I had a look through it, and there were so many more similarities than there were differences, so I had a go at unifying it all together. This PR is my progress so far.

Internal links, external links, and email links are now all handled in a similar fashion, with DB whitelisters and being registered via hooks. Document links got a similar treatment. There is now a single hook that takes care of setting it all up - whitelisting, adding to the link chooser panel, and other related things. The definition for a chooser is contained to a single, basic class. You can see these classes in the `link_handlers.py` files I have added.

This needs some documentation, and some thoughts on how to make it backwards compatible. Your thoughts on what I have done so far are also welcome.

### CODE REVIEW

**Comment by gasman** [comment]
Hi @timheap - this is something that I'd definitely be keen to pursue. Have you seen @mitchellrj's work on #1521 to make hallo.js a swappable module? It seems like that's something that could link into this - if all our "inserting things into rich text" plugins follow a common pattern/interface, then there's only a single integration point that needs to be implemented to support a new rich text library.

**Comment by mitchellrj** [comment]
The concept would fit in just fine with #1521 as far as I can see. I'd be happy to help review this when it's ready. Thanks for the heads-up, @gasman.

**Comment by mope** [comment]
I +1 this. My understanding is that there are two issues remaining to be resolved:

1. Add backwards-compatibility with the old-style page links.
2. Get the tests to pass.

**Comment by timheap** [comment]
This was fairly broken. It really was a WIP commit as it turns out, I thought I had left it in a better state. Anyway, ordering on Python3 should now work, the JS modals should work again, and saving a document link actually works.

**Comment by jimr** [comment]
This looks like a great contribution to the project and something that would be highly valuable for us and presumably others. Is there anything we can do to help get some momentum on this again? I had a quick look at merging master into the WIP branch, but there were a couple of conflicts that didn't have obvious (to me) resolutions.

I'm also interested in what the ultimate goal is here. Will adding a new link handler be as simple as defining a class in `rich_text.py`, hooking it up in `wagtail_hooks.py` and letting magic take care of the rest?

**Comment by tomdyson** [comment]
@jimr thanks for the encouragement. Merging and testing would definitely help. @timheap can you reply on 'the ultimate goal'? AFAIK backwards compatibility with old-style page links is still outstanding - is that right?

**Comment by timheap** [comment]
The ultimate goal of this PR is to make it easier to add new link choosers. It will not be quite as simple as adding a new class in `rich_text`, as there will need to be some views made as well. However, it will make the JS registration and whitelister integration much, much simpler. I do have some thoughts on making the modal picker lists easier to create, but that is for a different pull request in the future.

The outstanding items for this PR are: merging it with current master, writing some tests, writing some documentation, and working out what to do about backwards compatibility.

I'll try and rebase this on current master, and see if I can get everything working again. I can then write some documentation, if everyone is happy with the general direction of the implementation. Backwards compatibility might be tricky, but I will have to remember everything that I changed first before I can make a full judgment there. Because rich text links in the past were handled in a very manual process, some of that magic will have to be kept around for now. I honestly do not know what the result would be if old-style rich text was passed through the new-style handlers.

**Comment by timheap** [comment]
Oh, and another outstanding point: The new chooser pop up also has a `wagtaildocs` section, which has a Browse/Upload tabs. It looks terrible right now, as I've done terrible things to the UI trying to get the multiple chooser types and the document chooser working together. I am unsure how to fix this.

**Comment by timheap** [comment]
I've rebased this on `master`, and everything still seems to be working fine.

I looked over the code, and I *think* the backwards incompatibilities are fairly minimal:

* The `register_rich_text_link_handler` hook is no longer used. This could be reinstated but deprecated.
* The `register_rich_text_link_chooser` hook is used instead. This expects a subclass of `LinkChooser` with all the relevant attributes filled out, instead of the plain `object` subclass used in the previous hook.
* `LinkChooser.expand_db_attributes` returns a `dict` now, instead of an HTML fragment. It makes the code simpler, as well as making `expand_db_attributes` and `get_db_attributes` the inverse operation of each other.

RichText generated from previous versions of Wagtail do not have a `linktype` attribute for external links, or email links. If run through the system in this PR, they should be returned unmodified by the `expand_db_html` method. This means your old content will continue to work, but it will not have any of the new smarts behind it. This is fine, because the external and email link choosers do not do anything fancy anyway.

**Comment by timheap** [comment]
Note that if `register_rich_text_link_handler` was reinstated but deprecated it would *not* show anything in the chooser modal. It would only be for running old-style link handlers.

**Comment by timheap** [comment]
Alright, I made all the tests pass! I will need to add some new tests as well, to test the new EmailLinkChooser, and the new chooser modal set up, but all the existing tests pass.

**Comment by jimr** [comment]
@timheap thanks for updating, I'll try to have another look today.

> It will not be quite as simple as adding a new class in `rich_text`, as there will need to be some views made as well.

Would the excellent `wagtailmodeladmin` potentially be of use here? The mechanics of "take a Django model and make a list view & create form from it" are already there. 

For our use case, we are adding hyperlinks in rich text to models that are registered with `wagtailmodeladmin`. It seems like most of the pieces are more or less there, they just aren't joined up yet. What you've done here goes a long way to achieving that though.

**Comment by timheap** [comment]
> Would the excellent wagtailmodeladmin potentially be of use here? The mechanics of "take a Django model and make a list view & create form from it" are already there. 


Not yet, sadly. `wagtailmodeladmin` makes the basic CRUD interface, but does not make a modal popup chooser interface. It would be possible to make it do this, though.

**Comment by timheap** [comment]
I've pushed two new commits to this PR. One renames the hook to better convey how I intend to extend it in the future, and the other adds backwards compatibility with the old-style link handlers.

The intended future extension is a generic link widget/form field/block/model field. As the link choosers exist in this PR, they deal purely with dicts of attributes that are serialised in and out of the database. Storing/expanding those dicts in HTML elements is handled in `DBWhiteLister`/`expand_db_html`. The dicts themselves could be stored as JSON in a different field, which could then use similar machinery to expand a link stored in a field to a URL. This would solve #381. This functionality is for a future PR though.

This PR needs a once over from a UI / frontend person, as the link chooser popup currently looks terrible. It also needs documentation, including how to convert an old-style rich text link handler in to a new style link chooser. I'll try and get to the documentation next week. Could someone else have a go at the UI?

**Comment by JoshBarr** [comment]
I could have a go at some UI!

**Comment by timheap** [comment]
@JoshBarr: The new modal popup looks a bit terrible. There is a tab bar kind of link set up, taken from the old modal, that is just some plain looking links. These could probably be made in to an actual tab bar. The problem there though is that the Document chooser also has a tab bar, and I am not sure if two stacked tab bars will play nicely, from either a CSS, aesthetic, or useability point of view.

**Comment by JoshBarr** [comment]
The stacked tab bars works okay, actually. Something like this:

screen shot 2016-02-09 at 4 21 33 pm

Is there any reason the submit button for the search isn't locked up inline with the input? That would save lots of vertical space and look much better.

**Comment by timheap** [comment]
The button was already arranged like that before I unified the modals. If it works better on one line, I'm sure you can change it in this PR as well.

**Comment by JoshBarr** [comment]
Cool. I'm thinking something like the image below. We should change the placeholder text, as right now the user sees "search" three times. Maybe the placeholder should be an example? That's quite a common UI pattern. It could say something like `e.g. MyFile.pdf`? 

screen shot 2016-02-09 at 4 41 21 pm

**Comment by timheap** [comment]
I fixed an issue @mope spotted with a stray `@staticmethod` that should have been a `@classmethod`. I also took the opportunity to rebase on top of master and squash some commits in to sensible chunks. Hopefully they make a bit more sense now as logical chunks, instead of one chunk of work crossing multiple commits!

If other people are happy with this general approach, I will write some documentation. Hopefully that is the only thing standing in the way of a merge!

**Comment by SalahAdDin** [comment]
:+1:

**Comment by coredumperror** [comment]
Over the next week or so, I'll be working on #2401, in which I will be implementing a new "View in Admin" permission for Pages and Collections. Once that's done, I'll also add permissions-awareness to this issue's new unified choosers, so they will be able to limit the content that editors can choose to only those pages and collections for which they have permission.

**Comment by coredumperror** [comment]
So what's the status on this PR? I'm going to need to base the next PR I do (followup to #2463 for Choosers rather than the Explorer) on this change, and I'm not really sure how to go about starting a PR that's a branch off of two other PRs.

**Comment by lb-** [comment]
@timheap  - as per the other PR, we are making WIP PRs drafts, I am not sure if this will still need to be implemented though with the changes to how links can be added in Draftail.

Nonetheless, feel free to mark as a non-draft & remove the WIP tag from the title when this is close to ready for a review.

Thanks again

**Comment by timheap** [comment]
Hey @lb-, I no longer have time to contribute to Wagtail, so I am unlikely to pick this PR up again. It is your call what you want to do with PR, in terms of closing it or opening a new one to continue the work, but I won't be taking the work on.

**Comment by lb-** [comment]
As much newer work is in play for choosers I think it's best to close this for now.

See https://github.com/wagtail/wagtail/pull/9246

**Pull request closed without merging**
