### PR TITLE
Change UniqueConstraint for SQL Server (and Postgres) database support

### LINKED ISSUE #6393: Migration fails with MS SQL
### Issue Summary

Wagtail versions < 2.10 have worked with Microsoft SQL Server.  Wagtail 2.10 introduced a change (related to configurable moderation workflow) that is not supported by Microsoft SQL Server.  Specifically, Microsoft SQL Server does not support the OR keyword in the WHERE clause for unique indexes.

Migration 0050 in Wagtail Core (issue #6047 and commit 74a8cf8) only allows one record with status of In Progress **OR** Needs Changes per page. 

```
migrations.AddConstraint(
    model_name='workflowstate',
    constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress'), ('status', 'needs_changes'), _connector='OR'), fields=('page',), name='unique_in_progress_workflow'),
),
```

This migration generates the following SQL statement, which is invalid:

```
CREATE UNIQUE INDEX [unique_in_progress_widget]
    ON [widgets_widgetstate] ([widget_id])
    WHERE ([status] = 'in_progress' OR [status] = 'needs_changes');
```

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`.
2. Configure Django to connect to MS SQL server.

Example:
```
DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'HOST': 'localhost',
        'PORT': '',
        'NAME': 'database-name',
        'USER': 'username',
        'PASSWORD': 'password',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
}
```

3. Run `migrate` command.

Error message:

```
 Applying wagtailcore.0050_workflow_rejected_to_needs_changes...Traceback (most recent call last):
  File "/Users/rjschave/pycharm-projects/clients/rjs/wagtailtest2/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/rjschave/pycharm-projects/clients/rjs/wagtailtest2/venv/lib/python3.8/site-packages/sql_server/pyodbc/base.py", line 553, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'OR'. (156) (SQLExecDirectW)")
```

I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: Yes

I have also confirmed this problem is not specific to Wagtail.  A unique constraint with the OR keyword on any model (allowed by Django) will fail with MS SQL Server.

This is the only reference I could find in published Wagtail documentation related to Microsoft SQL Server - https://docs.wagtail.io/en/v2.10.1/advanced_topics/performance.html#database

I know Microsoft SQL Server is not officially supported by the Django or Wagtail projects, but until Wagtail version 2.10, it has worked great!  

Is it possible to get Wagtail working with Microsoft SQL Server again?

### Technical details

* Python version: 3.8.1
* Django version: 3.0.10
* Wagtail version: 2.10
* pyodbc verson: 4.0.30
* ODBC Driver 17 for SQL Server
* django-mssql-backend version: 2.8.1
* SQL Server 2017 (but relevant for any version of MS SQL supported by django-mssql-backend)

### PR DESCRIPTION
**Pull request by davidjb**
This fixes #6393 by modifying the constraint to use an IN condition which supports both Postgres and SQL Server. Previously, the `|` (OR) condition was only supported by Postgres because SQL Server only supports AND conditions, meaning that migrations would crash mid-way through on the latter.

The implementation follows suggestions from @gasman in https://github.com/wagtail/wagtail/issues/6393#issuecomment-732161057:

* Migration 0050 is modified to not break on SQL Server
* Added migration 0060 to add or replace the constraint in a manner that supports both of these databases

Additionally, this allows for and documents a `DATABASE_DRIVER` env variable to be set for testing, to allow a different SQL Server driver (e.g. FreeTDS on Mac/Linux); and adds the specific `host_is_server` option for FreeTDS (won't affect SQL Server Native Client on CI).

Note: 8 other database-related tests are failing (see https://gist.github.com/davidjb/be2849b5bbb5d4c3e3db1e317d644a17 for log) when tested against SQL Server; this could be a FreeTDS driver issue or something else but they don't seem related to this PR.

Other database backends (SQLite, MySQL) see their tests pass.

This PR depends on changes in #6585, hence why it has 2 commits present.  Once that other is merged, it's just one.

----

Thanks for contributing to Wagtail! 🎉

Before submitting, please review the contributor guidelines <https://docs.wagtail.io/en/latest/contributing/index.html> and check the following:

* [x] Do the tests still pass? (https://docs.wagtail.io/en/latest/contributing/developing.html#testing) - yes existing tests do on _other_ database engines; please see comments
* [x] Does the code comply with the style guide? (Run `make lint` from the Wagtail root)
* [x] For Python changes: Have you added tests to cover the new/fixed behaviour? - the fact the tests run?
* For front-end changes: Did you test on all of Wagtail’s supported browsers? **Please list the exact versions you tested**.
* [x] For new features: Has the documentation been updated accordingly?

### CODE REVIEW

**Comment by tomdyson** [comment]
Thanks @davidjb! This looks really good. Can you give us any advice on how to test against SQL Server, either locally or in CI? I don't think any of the core team have much SQL Server expertise.

**Comment by davidjb** [comment]
@tomdyson Thanks for the feedback. 

For sure. Here’s my cheat sheet for running wagtail tests on all the various db backends: https://gist.github.com/davidjb/643272824f469386f933e7a4e081a81e - SQL Server is down the bottom. 

I spin up a Docker container for each server - thankfully SQL Server was released for Linux, install the requisite engine and client and run the tests. In this case, the install instructions are for Mac but adaptable for Linux - not sure about Windows. For CI, you could run the Docker container and then the tests; I’ve done this style of thing on Travis.  If that doc is helpful, feel free to take it for the wagtail docs or I can submit a PR. 

You’ll notice things are a little messy at the moment on the latest version of Django 3.1 because of the engine needing fixes for db internal changes. I’ve got pull requests open to the engine repo at https://github.com/ESSolutions/django-mssql-backend/pull/86 which will be merged at some point (code is broken in 3.1+ without it), hence the temporary use of a branch in my fork. Otherwise you could use the backend’s current master branch with Django 3.0 in tests.

**Comment by davidjb** [comment]
Rebased on the latest `master` so it's able to be merged; anything else you'd like me to change or update?

**Comment by gasman** [comment]
Thanks @davidjb - all looks good to me! Merged in 3a5b7255adfb7eefbd9a48b56fdb7654b636d7cb.

**Comment by davidjb** [comment]
Thanks @gasman - much appreciated.  I also created the work-in-progress https://github.com/ESSolutions/django-mssql-backend/pull/97 with the database backend to catch situations where an unsupportable constraint is present.

**Pull request closed without merging**
