### PR TITLE
Don't render edit link in userbar on previewed pages

### LINKED ISSUE #8765: Editing a page from the preview tab results in loss of data if the user edits in a new tab
### Issue Summary
When a user edits a page and clicks Preview, a new tab is opened with the preview and the tab is somehow registered. The edit bird (userbar) is displayed on the preview page since the user is logged in. If the user then clicks the edit link on the preview tab and edits something and clicks preview again, the edit interface is loaded from the database and the user assumes the data is lost (it is still present in the previous edit tab).

Possible solutions to this are
1. Do not render the edit bird (userbar) when the request is a preview (easy fix)
2. Somehow de-register the preview tab when the user clicks the edit link in the preview tab. This would leave the previous tab with the previously changed data somehow still open and cause more confusion, I think.

I would prefer solution nr. 1

### Steps to Reproduce

1. Edit a page
2. Click preview which opens in a new tab
3. Click the edit bird in the new preview tab
4. All the changes made in the previous tab are not present and the user thinks the data is lost.

### Technical details

-   Python version: 3.8.13.
-   Django version: 4.0.5
-   Wagtail version: main branch
-   Browser version: Chrome 102 on macOS (Monterey)

### PR DESCRIPTION
**Pull request by saevarom**
Fixes #8765 

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [x] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [x] **Please list the exact browser and operating system versions you tested**:
    -   [x] **Please list which assistive technologies [^3] you tested**:
-   [x] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by lb-** [comment]
As per comment - https://github.com/wagtail/wagtail/issues/8765#issuecomment-1169531604

Not sure this is the best course of action - it feels a bit heavy handed.

**Comment by saevarom** [comment]
Fine by me to close this PR if that's the case, but I think #8765 needs some kind of solution.

**Comment by zerolab** [comment]
I do wonder, what good/benefit does the edit bird bring in a preview? I am thinking especially when #8671 gets added.

**Comment by lb-** [comment]
Yeah. I thought of that also haha. I've added a comment on the original raised issue for this and also on the PR.

**Comment by saevarom** [comment]
> I do wonder, what good/benefit does the edit bird bring in a preview? I am thinking especially when #8671 gets added.

I don't really see the benefit, but it is a change in behaviour, so a design decision is needed.

**Comment by Scotchester** [comment]
> In the meantime – if we want to go ahead with what this PR suggests, I think we could instead only hide the "Edit" button within the userbar when previewing pages.

This feels like the right way to go, to me.

**Comment by lb-** [comment]
@saevarom would you be ok to update this PR (or raise a new one) that disables or removes the edit page link from the user bar in previews?

**Comment by saevarom** [comment]
> @saevarom would you be ok to update this PR (or raise a new one) that disables or removes the edit page link from the user bar in previews?

Sure

**Comment by zerolab** [comment]
Excellent!
Needs one test and we're good to go :)

**Review by zerolab — APPROVED** [review]
LGTM

**Comment by zerolab** [comment]
Thank you @saevarom, merged in 34734d252fcda6f6f554d8295808eb114ef476eb

**Pull request closed without merging**
