### PR TITLE
Formalise support for Django 5.1

### PR DESCRIPTION
**Pull request by gasman**

### CODE REVIEW

**Review by laymonage — APPROVED** [review]
Looks good to me! Are we backporting this to 6.2? The upper bound in `setup.py` already allows Django 5.1 though, so people can already use it.

**Comment by gasman** [comment]
Thanks @laymonage! I don't think we need to backport - as you mention, the dependency in setup.py allows people to install 5.1 if they wish, and we had it running successfully against the 5.1 stable branch for a while, so the changes here are only really a formality.

**Comment by Stormheg** [comment]
I don't understand why we are not backporting Django 5.1 support to Wagtail 6.2.

Judging from the above this is a supported combination - what exactly is stopping us from formally recognizing support by changing the [compatibility table](https://docs.wagtail.org/en/latest/releases/upgrading.html#compatible-django-python-versions) in the docs?

**Comment by gasman** [comment]
@Stormheg I suppose the answer boils down to a combination of "the ability to upgrade to a new feature release of Django is itself a feature, that belongs in a feature release of Wagtail rather than a patch" and "it would be marginally more work, for a marginal benefit" :-)

Since we broadened the dependency to `Django>=4.2,<6.0` in #11296, there's nothing to stop people from installing the latest Django if they have a burning desire to - whether we state formal support for it or not. The only practical difference it makes is that by declaring formal support, we're making a commitment to keeping that combination of Django / Wagtail versions working throughout their lifetimes.

Even that distinction is a pretty theoretical one - if Django are doing things right there won't be any breaking changes in a patch release, and in the rare cases they've introduced one they've been quick to address it. So in the end, the question really becomes "in the hypothetical case that Django screws up, is it Wagtail that takes on that risk, or the end user?"

On our side, the incentives are towards A) not taking on commitments that we don't need to, and B) not making non-critical changes to stable branches - and pushing mainstream devs towards a new Django feature release is something that I'd consider to be non-critical. (That's "mainstream" as opposed to the kind of power users who would happily disregard our official recommendations and install the new Django release anyhow :-) )

**Comment by Stormheg** [comment]
@gasman thanks for the extensive answer, I can understand not willing to take on the commitment. Time and effort fixing issues that may surface would be better spent focusing on new releases.

The reason I asked is because we've done backporting of Django versions before; with Django 5.0 support in the Wagtail 5.2 LTS.

With Wagtail 6.2 not being an LTS, I presume that contributes to the diverging decision in this case. Or maybe the 'marginal more work, marginal benefit' argument didn't exist at that time 😉 

Totally fine with this decision - I'm not in a hurry to upgrade to Django 5.1 anyway. I'll wait around for formal support in 6.3 👍

**Comment by gasman** [comment]
@Stormheg The backport for Django 5.0 support happened before we widened the dependency range to `Django>=4.2,<6.0` (or rather, it was the thing that prompted us to do the widening...) so it was needed to accommodate the "power users".

**Pull request merged**
