### PR TITLE
Add missing translation for workflow

### PR DESCRIPTION
**Pull request by marteinn**
I noticed a missing translation in the `workflow_tasks.html` template.

### CODE REVIEW

**Comment by kaedroho** [comment]
Thanks for catching this before the release!

**Comment by kaedroho** [comment]
Backported to 2.10 in https://github.com/wagtail/wagtail/commit/e88b23aa051d7ade0ca2daeb20c61b8120a23d80

**Comment by gasman** [comment]
Have now also regenerated and pushed the new strings file containing this translation (in aef01d1aca2403ecd2e756c8591b5c965ad06e0f for 2.10 and 95c0a29aaff3f00d2e93e73cfe628134747c95ae for master), so there's a chance for translators to get a translation submitted for 2.10 if they're quick :-)

**Comment by zerolab** [comment]
@gasman done 🚤 😂

**Comment by marteinn** [comment]
Thanks for the quick action! Swedish translation updated ✔️

**Pull request merged**
