### PR TITLE
6.0 deprecations - remove icon font and deprecated icons

### PR DESCRIPTION
**Pull request by gasman**

### CODE REVIEW

**Review by laymonage — COMMENTED** [review]
I think I might’ve used some of the deprecated icons in my FeatureCompleteToy viewsets in the testapp, could you update them as well please? Thanks!

**Comment by gasman** [comment]
> I think I might’ve used some of the deprecated icons in my FeatureCompleteToy viewsets in the testapp, could you update them as well please? Thanks!

Done! Just one occurrence of `reset`, which I've changed to `rotate`. (That was one of the icon names I _didn't_ do a global search of the codebase for, for fairly obvious reasons :-) )

**Review by thibaudcolas — APPROVED** [review]
Looking solid! I could see _one_ remaining icon font use which I’ll convert when merging. There’s also further small bits of cleanup, which aren’t worth holding the PR for.

**Comment by thibaudcolas** [comment]
Thanks @gasman! Follow-up (draft) in #11209.

**Pull request merged**
