### PR TITLE
BASE_URL changed to WAGTAILADMIN_BASE_URL

### PR DESCRIPTION
**Pull request by iansprice**
Fix for issue #3248. 

BASE_URL setting renamed to WAGTAILADMIN_BASE_URL. 
Templates/documentation updated; backward compatible for BASE_URL.
If no setting defined, wagtail/wagtailadmin/templatetags/wagtailadmin_tags/base_url_setting does the following: 

- If available, use request.site.root_url
- If not, fallback to building scheme based on request.is_secure() and domain from request.get_host()

### CODE REVIEW

**Comment by iansprice** [comment]
Hmm, can't access the request through context in testing. Will look into this, but if anyone has a quick tip I'll take it!

**Comment by gasman** [comment]
Looks like we're not passing the request object along in the place where we'd need it:

https://github.com/wagtail/wagtail/blob/e64762acbbd9bc7d62edeca88579c3ae885990ff/wagtail/wagtailadmin/views/pages.py#L245-L246

The logic for passing context variables into these emails could do with some tidying up either way (e.g. see https://github.com/wagtail/wagtail/pull/3357#pullrequestreview-31891402) - however, I think we should keep in mind the possibility that the notification email might not be triggered from a web request at all (it might come from a script, or a task queue, or some as-yet-unimagined API for editing pages remotely). For that reason, if we're going to pass the request object as part of the call to `send_notification`, it should probably be an optional parameter.

**Comment by vupham04** [comment]
Hi, this pull request is already addressed through #8268 - so I feel like this should be closed.

**Comment by lb-** [comment]
Thanks for your initial work on this @iansprice - will close this as it has been resolved with a newer PR and is now planned for release in 3.0

**Pull request closed without merging**
