### PR TITLE
Move page default level

### PR DESCRIPTION
**Pull request by Tijani-Dia**
When moving a page, we must select a destination. Currently, the default destination is the root level. This PR aims to set the default destination level to the parent of the page being moved.

A breadcrumb is added at the top of the page to navigate backwards.

Screenshot from 2021-12-21 11-26-37

* Do the tests still pass? Yes
* Does the code comply with the style guide? Yes
* For Python changes: Have you added tests to cover the new/fixed behaviour? Yes
* For front-end changes: Did you test on all of [Wagtail’s supported environments]? No
    * **Please list the exact browser and operating system versions you tested**. Firefox
    * **Please list which assistive technologies you tested**.
* For new features: Has the documentation been updated accordingly? No

### CODE REVIEW

**Comment by lb-** [comment]
@Tijani-Dia thanks for taking the time to put this together, I think this makes sense, would you be able to add some tests for this behaviour though? The new default destination page and also the template tag.

**Comment by Tijani-Dia** [comment]
Thanks @lb- ! I've added a test for both the new default destination page and the template tag.

**Comment by phildexter** [comment]
Hi @lb- are you ok to re-review this one and merge if you're happy? If not we can try and pick it up tomorrow?

**Comment by lb-** [comment]
@phildexter I'm away at the moment so won't be able to run the code locally myself until next week sometime. Happy to take a look then or if you get if first - all good.

**Review by gasman — CHANGES_REQUESTED** [review]
A couple of issues I notice with the breadcrumb:

* It's not possible to navigate to the root section any more. I think both clauses of the query in the `move_breadcrumb` tag should use inclusive=True, so that both the root section and the current section are included in the breadcrumb - this makes it consistent with the main explorer view:

      return {
          'pages': viewed_page.get_ancestors(inclusive=True).descendant_of(cca, inclusive=True).specific(),
          'page_to_move_id': page_to_move.id,
      }

* The styling seems to have regressed from your screenshot above - the line height is reduced, and each item is on its own line. Perhaps there's a conflict with the changes in #7783? Screenshot 2022-01-13 at 15 59 02
 * More generally, I think we should match the styling in wagtailadmin/shared/breadcrumb.html, including using the globe icon for the first item. (It feels a little bit annoying to copy and paste so much template code from there rather than sharing it, but the different URL formats make it difficult to solve that - we can leave that for another time.)

**Comment by zerolab** [comment]
#7837 fixes a number of breadcrumb issues introduced in #7783.
0d2ace6c7 has the necessary breadcrumb markup changes (each `<li>` needs `.breadcrumb-item` and each link needs `.breadcrumb-link`

**Comment by gasman** [comment]
Hmm, there are a few other uses of the breadcrumb component that are probably also broken now - [modeladmin](https://github.com/wagtail/wagtail/blob/main/wagtail/contrib/modeladmin/templates/modeladmin/includes/breadcrumb.html) and [the styleguide](https://github.com/wagtail/wagtail/blob/e3c2237ccc5c2f2115b821f7dd4d4dbba3f2fce9/wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html#L737-L743), and I wouldn't rule out the possibility that third-party code is using it too. Is there any way we can keep this backwards-compatible?

**Comment by zerolab** [comment]
We'd want to roll back some of the CSS changes from #7783. (basically the styling tied to `.breadcrumb-item`, `.breadcrumb-link`)

**Comment by Tijani-Dia** [comment]
Thanks both!

>both the root section and the current section are included in the breadcrumb - this makes it consistent with the main explorer view

I've added a commit for that.

>The styling seems to have regressed from your screenshot above

That's right. I've tried adding `class="breadcrumb-item"` and `class="breadcrumb-link"` and it seemed to fix it. However considering [this](https://github.com/wagtail/wagtail/pull/7805#issuecomment-1012302455) and [this](https://github.com/wagtail/wagtail/pull/7805#issuecomment-1012333479), it might not be the appropriate solution.

I tied the breadcrumb styling to `.breadcrumb-item` and `.breadcrumb-link` following @jacobtoppm's suggestion because (partly, there may be other reasons that led us to do that but this is the one I remember) it was tricky to style the dropdown icon added in the secondary actions menu with the previous styling.

>(It feels a little bit annoying to copy and paste so much template code from there rather than sharing it, but the different URL formats make it difficult to solve that - we can leave that for another time.

Yes, the different URL format make it harder to share that template (that's what I tried in the first place but I enden up thinking that it may not be a good idea). I can try to do that if you think it's the best solution!

**Comment by jacobtoppm** [comment]
I think we ended up going with that approach because it involved fewer nested selectors, with the alternative being css to correct the clashing styles of the breadcrumb + dropdown menu that applied only when both were in use, which felt quite messy (due to the element based selectors applying to the ul and li within the dropdown as well as the breadcrumb). I definitely get the compatibility concerns, and if we're going to replace the breadcrumb as part of the editor rework it may well make sense to deal with making the css slightly more messy for now - but long term, reducing the number of over-eager element based selectors to make our components easier to combine feels like a plus to me.

**Comment by zerolab** [comment]
I think you need to add `li,` to https://github.com/wagtail/wagtail/blob/main/client/scss/components/_breadcrumb.scss#L10 and `a,` to https://github.com/wagtail/wagtail/blob/main/client/scss/components/_breadcrumb.scss#L36 to sort out the backwards compatibility, but I would then update the modeladmin and the styleguide markup to include the classes

**Comment by zerolab** [comment]
@gasman how about we get this in as the changes here did not bring the breadcrumb styling issue. Will look at submitting a fix for the breadcrubms with fallback in mind. will make it easier to review

**Comment by gasman** [comment]
Merged in 317f100a78b8f3a1f3383167fee5ffa852fc3a25 + parents, with the breadcrumb markup updated in ec84b35761383f4caebf227f5d334ceead120dcf to match the old (pre-#7783) explorer breadcrumb. The breadcrumb styling regression will then be fixed by #7866 / #7868.

**Pull request closed without merging**
