### PR TITLE
Document potential data loss for `BaseLogEntry` migration in 3.0

### LINKED ISSUE #9459: Potential data loss when upgrading sub-classes of BaseLogEntry (Wagtail 2.16 -> Wagtail 3.0)
### BaseLogEntry
https://docs.wagtail.org/en/stable/reference/pages/model_reference.html#baselogentry

### Wagtail 3.0 Upgrade Considerations - Replaced data_json TextField with data JSONField in BaseLogEntry
https://docs.wagtail.org/en/stable/releases/3.0.html#replaced-data-json-textfield-with-data-jsonfield-in-baselogentry

### Details
These entries document that these fields have changed from `data_json` (a `TextField`) to `data` (a `JSONField`).

However, if (like me) you have a sub-class of `BaseLogEntry`, the automatically generated migration will result in loss of the log data, because it generates the following migration operations:

```
    operations = [
        migrations.RemoveField(
            model_name='objectdatalogentry',
            name='data_json',
        ),
        migrations.AddField(
            model_name='objectdatalogentry',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
```

Note: this migration was automatically generated by Django 4.0.8, while upgrading from Wagtail 2.16.3 to 3.0.3. I haven't tested with other Django versions.

Similar migrations in the Wagtail core code, have migration operations like this:

eg. https://github.com/wagtail/wagtail/blob/main/wagtail/migrations/0069_log_entry_jsonfield.py#L12

```
    operations = [
        migrations.AlterField(
            model_name="modellogentry",
            name="data_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RenameField(
            model_name="modellogentry",
            old_name="data_json",
            new_name="data",
        ),
```

There is a warning against the `BaseLogEntry` documentation about the change in the field, but I think it would be helpful to have an additional warning suggesting the migration be carefully scrutinised, and potentially replaced with something like the example above. A similar warning in the Upgrade Considerations section pointing to this would also be useful - especially for those who are considering upgrading from 2.15 LTS to the imminent 4.1 LTS release.

I've raised this as a documentation issue, because I doubt there is anything that can be done within the Wagtail code base (or Django for that matter) to solve this problem.

### PR DESCRIPTION
**Pull request by laymonage**
Fixes #9459.

### CODE REVIEW

**Comment by jacobtoppm** [comment]
This looks good, but question for @gasman: since this involves old release notes, do we need to do something special to update the docs for those versions too? Or do you think it's enough to update the 3.0 release notes on the current docs version?

**Comment by laymonage** [comment]
Thoughts on how we should merge this @gasman? I think we should merge this sooner rather than later. I'm happy to do the merge once we agree on which branches we should merge this into.

**Comment by gasman** [comment]
@laymonage We'd need to make a new point release to get the older versions in readthedocs updated, and I can't see us doing that for anything below 4.1, so let's merge this into 4.1, 4.2 and main.

**Review by gasman — APPROVED** [review]

**Comment by laymonage** [comment]
Thanks, merged in 796b3fe12008afb5a7735c62cc995774144bc769 (main), 6b33c65087d413b6c1330f74d623f789b19abf6d (4.1.x), 1d9248b08a21694dac27e69c2f2077bfa561a603 (4.2.x).

**Pull request merged**
