### PR TITLE
Fix drf_yasg schema generation, Fix #4811

### LINKED ISSUE #4811: Make the library compatible with drf-yasg library
https://github.com/axnsan12/drf-yasg is the best swagger generator out there by far.

Unfortunately, it is not possible to integrate with wagtail due to the current API design.

The error when generating swagger schema:
```
Traceback (most recent call last):
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/drf_yasg/inspectors/view.py", line 94, in get_view_serializer
    return self.view.get_serializer()
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/rest_framework/generics.py", line 110, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/wagtail/api/v2/endpoints.py", line 300, in get_serializer_class
    model = type(self.get_object())
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/wagtail/api/v2/endpoints.py", line 437, in get_object
    base = super().get_object()
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/rest_framework/generics.py", line 94, in get_object
    (self.__class__.__name__, lookup_url_kwarg)
AssertionError: Expected view PagesAdminAPIEndpoint to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/drf_yasg/renderers.py", line 34, in render
    return codec.encode(data)
  File "/home/code/swehq/newgifiter/gifiter/blog/venv/lib/python3.6/site-packages/drf_yasg/codecs.py", line 73, in encode
    raise SwaggerValidationError("spec validation failed", errors, spec, self)
drf_yasg.errors.SwaggerValidationError: spec validation failed
```

### PR DESCRIPTION
**Pull request by yihuang**
Thanks for contributing to Wagtail! 🎉

Before submitting, please review the contributor guidelines <http://docs.wagtail.io/en/latest/contributing/index.html> and check the following:

* Do the tests still pass? (http://docs.wagtail.io/en/latest/contributing/developing.html#testing)
* Does the code comply with the style guide? (Run `make lint` from the Wagtail root)
* For Python changes: Have you added tests to cover the new/fixed behaviour?
* For front-end changes: Did you test on all of Wagtail’s supported browsers? **Please list the exact versions you tested**.
* For new features: Has the documentation been updated accordingly?

### CODE REVIEW

**Comment by lb-** [comment]
@yihuang thanks for submitting this, sorry it has been such a long time since this has been looked at.

Were you still keen to look at this, it needs a rebase, plus some unit tests added.

@lingster - did you ever get a chance to test this out, you might need to rebase on master (fix conflicts) to test on the latest release.

**Comment by lb-** [comment]
Will resolve #4811

**Comment by yihuang** [comment]
I just rebased against new master with no conflicts, but I don't have a project at hand to test it.

**Comment by lingster** [comment]
@lb- :+1: to confirm that drf_yasg now renders the swagger page, and there are endpoints to list out documents/images/pages as well as retrieve specific pages. 

image

**Comment by lb-** [comment]
@lingster  - thanks for validating! the screenshot is super helpful, this will need a bit more work before it is ready, if you can take this on (add tests, fix existing breaking tests) let Yihuang know and raise a new PR.

**Comment by yihuang** [comment]
> @lingster  - thanks for validating! the screenshot is super helpful, this will need a bit more work before it is ready, if you can take this on (add tests, fix existing breaking tests) let Yihuang know and raise a new PR.
> 
> 
> 
> 

Yes,  it’s better to be take over by more relevant people, I’m not working on similar projects currently. @lingster please feel free to take it over :)

**Comment by lingster** [comment]
Hi, will love to take a look at this issue, I'm a relatively newbie to wagtail code base. Will see what I can do. On 4 May 2020 13:16, yihuang <notifications@github.com> wrote:



@lingster  - thanks for validating! the screenshot is super helpful, this will need a bit more work before it is ready, if you can take this on (add tests, fix existing breaking tests) let Yihuang know and raise a new PR.



Yes,  it’s better to be take over by more relevant people, I’m not working on similar projects currently. @lingster please feel free to take it over :)

**Comment by lb-** [comment]
@lingster awesome, here is a bit of a guide on how to get started with developing Wagtail
https://docs.wagtail.io/en/stable/contributing/developing.html

Feel free to pop into support on slack and ask any questions if you get stuck
https://github.com/wagtail/wagtail/wiki/Slack

**Comment by lingster** [comment]
@lb- I had a look at the changes, and it seems we would no longer need this PR. The generation of the swagger schema works correctly for wagtail >=2.8 version including the current 2.10rc.
I have tested as well with drf_yasg == 1.17.1 and django >2.2 and 3.0.x
There is an AssertionError raised when loading the swagger schema in 2.8 but this does not appear to impact the loading of the swagger page. The error is:

`AssertionError: Expected view PagesAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
`

**Comment by lb-** [comment]
@lingster - thanks for validating, really appreciate the time taken on this, will close this PR and comment on the related issue accordingly.

**Pull request closed without merging**
