### PR TITLE
Fix bulk publishing of pages without revisions

### LINKED ISSUE #8187: Bulk publishing is broken for pages without revisions
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The bug is in `wagtail.admin.views.pages.bulk_actions.publish.py` in `execute_action`:

`for page in objects:
            page.get_latest_revision().publish(user=user)`

If a page doesn't have any revisions, get_latest_revision() returns None and you get a `'NoneType' object has no attribute 'publish'` error.

### Steps to Reproduce

Create a draft page that has no revisions and try to publish it using bulk actions.

### Technical details

* Python version: 3.10.0
* Django version: 3.2.9
* Wagtail version: 2.15.4 or 2.16.1
* Browser version: Chrome 99.0.4844.74

### PR DESCRIPTION
**Pull request by chosak**
Currently bulk publishing raises an error if you include pages that exist in the database without any revisions. This commit ensures that a revision exists before the page is published.

Fixes #8187.

### CODE REVIEW

**Review by zerolab — APPROVED** [review]
Nice one @chosak.

Would be great to backport this to 2.15/2.16

**Comment by zerolab** [comment]
I thought we had it documented in https://docs.wagtail.org/en/stable/contributing/committing.html but turns out we don't.

Considering this doesn't have additional migrations, it should be a matter of cherry picking the commit on the relevant branches and updating the changelog/release notes. Otherwise, new PR against the target branches

@gasman am I missing anything obvious?

**Comment by gasman** [comment]
@zerolab That sounds right, yep. Given the formatting / linting changes and module reorganisation that has happened since 2.16, it might turn out to be simpler to re-apply the changes manually rather than cherry-picking, but I'll let you decide...

I haven't really been staying on top of day-to-day bugfixes lately - I know there's a couple in stable/2.16.x waiting to be released, and this one looks like it does warrant backporting to 2.15.x as an LTS fix too, so I'll take some time next week to review the 2.15 / 2.16 / 3.0 changelogs and figure out which fixes go where, and plan out a couple of new patch releases.

**Comment by chosak** [comment]
Thanks both. Merged to main in 00adeb8, stable/2.15.x in 6f0f188, and stable/2.16.x in 1a28c44.

@gasman I wasn't sure whether or how to include the 2.15.x changes in the 2.16.x CHANGELOG, or the new 2.15.5.rst file in the 2.16.x branch - I took a stab but please correct if necessary!

**Pull request closed without merging**
