### PR TITLE
Increase Pillow dependency range to include 9.x

### LINKED ISSUE #7817: Add support for Pillow 9.0.0
### Is your proposal related to a problem?

Pillow 9.0.0 [has just been released.](https://github.com/python-pillow/Pillow/releases/tag/9.0.0) Wagtail 2.15.1 [restricts Pillow support to <9.0.0.](https://github.com/wagtail/wagtail/blob/ed4d58ebd84616473b07474b50134d06779cca49/setup.py#L30)

Adding support for the new Pillow release is desired.

### Describe the solution you'd like

Add support for Pillow 9.0.0

### Describe alternatives you've considered

Not applicable.

### Additional context

This is a relevant dependency to the project, and to sites running it.

### PR DESCRIPTION
**Pull request by gasman**
Fixes #7817

### CODE REVIEW

**Comment by adrenaline681** [comment]
Any update on this change?

**Comment by zerolab** [comment]
@adrenaline681 it is in "Needs review", meaning someone has to review and test the change locally. The community can help speed things up by reviewing and testing PRs locally.

To do so, clone the repository and check this PR out (`git checkout pr/7831`, or if using GitHub CLI `gh pr checkout 7831`. Or, to install with pip `pip install -e it+sshgit@github.com:gasman/wagtail.git@:admin/pillow-9#egg=wagtail` and test any site for image workflows (uploading, viewing the image listing, checking renditions get generated properly on the front-end)

**Comment by justinsg** [comment]
I've just tested this using the squash.io link above - was able to upload images, view the listing in the admin area (which includes  tags of the original and a resized thumbnail).

I also tested using wagtail/bakerydemo (with this branch of wagtail) - verified the same as above, and also that images were correctly rendered on the front-end. This included .jpg and .png images (with transparency).

Seems the major change in Pillow 9.x is that Python 3.6 support is removed. Wagtail claims to support Python 3.7+.

LGTM!

**Review by zerolab — APPROVED** [review]

**Comment by gasman** [comment]
Merged in 88150bf8d3b8f2b52c915de1fc62c9aa564b5e05 (main) and eac906e7ed9babf5903eda61ec870fdf3b76dde8 (stable/2.15.x).

**Comment by maltebeckmann** [comment]
Was pillow 9.x included? I just tried adding wagtail 2.4 to a new cookiecutter project with Pillow 9.0.1 but got 
"wagtail 2.4 depends on Pillow<6.0 and >=4.0.0"

**Comment by gasman** [comment]
@maltebeckmann Why are you using Wagtail 2.4? That version is ancient...

**Comment by maltebeckmann** [comment]
> @maltebeckmann Why are you using Wagtail 2.4? That version is ancient...

Oh crap, sleep-deprived. Thanks!

**Pull request closed without merging**
