### PR TITLE
move generate_signature and verify_signature from images/views/serve …

### LINKED ISSUE #4347: wagtail.images.views.serve.generate_signature should be relocated
I've encountered an issue with wagtail.images.views.serve.generate_signature.  When importing it into a models.py file, the class wagtail.images.views.serve.ServeView is created, which invokes a call to get_image_model, which in turn leads to a AppRegistryNotReady exception.

The functions generate_signature and verify_signature are not used at all in wagtail.images.views.serve. In fact, generate_signature is used in wagtail itself only in wagtail.images.views.images, and verify_signature is not used at all. It would make more sense to move these two functions to wagtail.images.views, or wagtail.images.utils, so that importing them does not result in the aforementioned side-effects.

One could then import these functions into wagtail.images.views.serve so as not to break existing code.

### PR DESCRIPTION
**Pull request by nthall**
…to images/utils

Fixes #4347

Thanks for contributing to Wagtail! 🎉

Before submitting, please review the contributor guidelines <https://docs.wagtail.io/en/latest/contributing/index.html> and check the following:

* Do the tests still pass? (https://docs.wagtail.io/en/latest/contributing/developing.html#testing)
* Does the code comply with the style guide? (Run `make lint` from the Wagtail root)
* For Python changes: Have you added tests to cover the new/fixed behaviour?
* For front-end changes: Did you test on all of Wagtail’s supported browsers? **Please list the exact versions you tested**.
* For new features: Has the documentation been updated accordingly?

### CODE REVIEW

**Comment by tomdyson** [comment]
Thanks @nthall!

**Review by kaedroho — APPROVED** [review]
LGTM, thanks!

**Comment by kaedroho** [comment]
@nthall 

Sorry I forgot to ask earlier. How would you like your name written in the release notes?

**Comment by nthall** [comment]
@kaedroho the way you already have it in that commit is fine 👍

**Pull request merged**
