### PR TITLE
Fix spacing around the privacy indicator panel.

### LINKED ISSUE #6446: Privacy button cut off in settings if there are additional panels
### Issue Summary

Privacy button is cut off at the bottom if there are more panels after it. This is in part because of `.field-row`'s negative margin bottom, but removing that still leaves it without white space between the button and the next panel.
 
image

### Steps to Reproduce

Add another `FieldPanel` to the `settings_panels` after the privacy panel

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **No**

### Technical details

* Python version: 3.6.4
* Django version: 3.0.7
* Wagtail version: 2.10.2
* Browser version: Firefox 82, Chrome 85

### PR DESCRIPTION
**Pull request by saevarom**
Fixes #6446 

I did two things:
* Wrapped the whole privacy indicator in a `fieldset` tag. It seems that most field panels do this anyway so this creates a uniform way of spacing things for a panel. 
* Removed the `field-row` class which gives a negative bottom margin.

After the change, this is how the panel looks with additional `FieldPanels`:

Screenshot 2020-10-09 at 17 40 07

### CODE REVIEW

**Comment by zerolab** [comment]
:) looks like we cross-PR-ed (is that a thing?) - #6453
I started off with wrapping the panel content in `fieldset`, but the spec/a11y is a bit ambiguous so decided againsts it as the contents are not rield fields

@thibaudcolas maybe you can advise? happy with either solution

**Comment by thibaudcolas** [comment]
Semantically I don’t think `fieldset` is correct, but the screen reader testing I did indicates it could be used nonetheless as it’s ignored. I assume due to there not being a `legend`. I think I’d go with whatever feels the most pragmatic. Those styles are in bad need of a rewrite, it’s completely crazy to apply styles to bare elements like this in a UI that’s going to be extended by other people like field panels.

**Review by KalobTaulien — APPROVED** [review]
This works well, thank you for this PR! 🎉

**Comment by zerolab** [comment]
@gasman this or #6453 would be good to get in 2.11 as it fixes a styling issue

**Comment by gasman** [comment]
Merged in b7643f869d64e02624724eabb3a6b9ef567249be (went for this one as it sounds like it's had slightly more eyes on it :-) )

**Pull request closed without merging**
