### PR TITLE
add Wagtail colours to documentation sidebar

### PR DESCRIPTION
**Pull request by lb-**
More fleshed out concept of styling docs for #4081 - only affects the sidebar.

This is probably more for discussion/testing than merging at this stage.

### CODE REVIEW

**Comment by kaedroho** [comment]
I'm also in favour of this change. @jjanssen and @gasman have stated their approval on #4081 

Are there any objections? (see #4081 for a screenshot)

**Comment by lb-** [comment]
I have updated #4081 with the screenshots from this actual PR, the colouring for the version number is fixed - just that the screenshots on that one were from an earlier draft version.

**Comment by gasman** [comment]
Looks like everyone's happy with this - @lb- any reason not to go ahead and merge?

**Comment by lb-** [comment]
@gasman great, I will merge it in

**Comment by lb-** [comment]
Merged in https://github.com/wagtail/wagtail/commit/d6da38892a88649191c964fbce339713415bee23

**Comment by gasman** [comment]
Minus 100 brownie points to me for not testing this locally before merge, but Open Sans comes up a bit too light on OS X (on a non-retina screen) for my liking:

screen shot 2018-01-05 at 16 26 02

Any objection to switching it back to something closer to the original (`font-family: "Lato","proxima-nova","Helvetica Neue",Arial,sans-serif;`)?

**Comment by lb-** [comment]
@gasman - good call. I will get that updated in a new PR

**Pull request closed without merging**
