### PR TITLE
Update pip install instructions to work for Windows and zsh user

### PR DESCRIPTION
**Pull request by seyiadel**
I was setting up the [codebase](https://docs.wagtail.org/en/stable/contributing/developing.html#setting-up-the-wagtail-codebase) on my local machine(Window 10, Python 3.10) and the code to install testing and docs dependencies wasn't working `pip install -e '.[testing,docs]' -U` . After removing the apostrophe, It worked. `pip install -e .[testing,docs] -U` . This error was encountered by a fellow contributor too @jadesola123. 

Please go through it as I go on another bug hunt! 

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Review by gasman — CHANGES_REQUESTED** [review]
Thanks @seyiadel!

It seems that we've repeatedly gone round in circles on whether to include the quotes or not...

* #3461
* #6768
* #7312
* https://github.com/wagtail/wagtail/pull/8304#discussion_r845186103

Based on the previous discussions, Windows requires the version without the quotes, zsh requires the version with the quotes, and most other Unix-like systems work with either - so we need to give both versions. We should change this back to what we had before #8304:

    pip install -e .[testing,docs] -U
    # or if using zsh as your shell:
    #    pip install -e '.[testing,docs]' -U

and, if possible, add a comment (only visible to people viewing the .md file source code - which I think can be done by [marking it with a %](https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html#comments)) to tell people not to fiddle with this line again unless they know what they're doing :-)

**Comment by thibaudcolas** [comment]
@seyiadel reading [another issue](https://github.com/mu-editor/mu/issues/852) about this, it seems like there is a version that could work everywhere:

```sh
pip install -e ."[testing,docs]" -U
```

I can confirm this works on macOS with zsh, and also with bash. Could you try it out on Windows and report back?

**Comment by seyiadel** [comment]
> @seyiadel reading [another issue](https://github.com/mu-editor/mu/issues/852) about this, it seems like there is a version that could work everywhere:
> 
> ```shell
> pip install -e ."[testing,docs]" -U
> ```
> 
> I can confirm this works on macOS with zsh, and also with bash. Could you try it out on Windows and report back?

**Comment by thibaudcolas** [comment]
@seyiadel you didn’t type a message in your last comment :) Did you try out the command?

**Comment by seyiadel** [comment]
> @seyiadel you didn’t type a message in your last comment :) Did you try out the command? If this did work – once we change this, I think it’d be good to replicate this change everywhere we use this. Perhaps even share it in our #package-maintainers channel.

I'm having network issues with my github "fatal:unable to access". I'm seeing to it.

**Comment by seyiadel** [comment]
> @seyiadel you didn’t type a message in your last comment :) Did you try out the command? If this did work – once we change this, I think it’d be good to replicate this change everywhere we use this. Perhaps even share it in our #package-maintainers channel.

I'm having network issues with my github "fatal:unable to access". I'm seeing to it.

**Comment by seyiadel** [comment]
> 

This works on Windows. We are good to go! @thibaudcolas @gasman

**Review by thibaudcolas — APPROVED** [review]
Thank you @seyiadel! I credited you as "Oluwaloseyi Adeleye" for this first pull request, please let me know if you’d like another name on there!

**Comment by seyiadel** [comment]
> Thank you @seyiadel! I credited you as "Oluwaloseyi Adeleye" for this first pull request, please let me know if you’d like another name on there!

Thank You, I do appreciate!

**Pull request merged**
