### PR TITLE
Pinterest_embed_support

### PR DESCRIPTION
**Pull request by Dharma-09**
fixed https://github.com/wagtail/wagtail/issues/5471
- Add  pinterest embded urls support .
- Let me know if anymore changes required.

### CODE REVIEW

**Comment by Dharma-09** [comment]
Hey @thibaudcolas any comment on this??

**Review by lb- — CHANGES_REQUESTED** [review]
@Dharma-09 thanks so much for taking the time to contribute but please advise how you tested it.

Screen Shot 2022-03-22 at 8 31 14 am

I checked out this branch, tried entering 
`https://www.pinterest.com/villabalicom/must-visit-places-in-bali/` and I got an error

It appears Pinterest is also adding country domains to their redirects, I originally tried
`https://www.pinterest.com.au/viatortravel/bali-things-to-do/` and got the same error.

I might be missing something but please can you update the original request or the PR description on how you expect this to work (maybe some example URLs and then a screenshot).

**Comment by lb-** [comment]
@Dharma-09 awesome. I'll take another look and hopefully can plan a trip to Bali haha.

**Review by lb- — APPROVED** [review]
Looks great @Dharma-09 - I made a slight tweak to the regex to allow other TLDs but validated fine this time round.

I have put your name on the contributors list 'Dharmik Gangani' - please let me know if you wanted your name listed differently.

Will merge in shortly, congrats on making your first contribution to Wagtail.

Thank you!

**Comment by Dharma-09** [comment]
Thanks @lb- Looking for more contribution in wagtail.

**Pull request merged**
