### PR TITLE
Fix - Documentation on Images>Alternative HTML tags

### PR DESCRIPTION
**Pull request by jlmirocoll**
After checking the example in the doc about using Alternative HTML tags, I found that the example maybe it's not working as expected.

Using the the template tag `image`, I saw that the generated HTML code for the image template tag, sets a hard coded value to the attributes `width` and `height` for the image, and for this reason, I think that the re-size of the image using the `source` tag it's not working.

Old generated HTML code with setted height and width:
imagen

My proposal is to define the two images using the `as` keyword, and then using the `img` HTML tag itself to set the alternative image. Doing it this way, any value for width and height is setted and it can check the condition inside `source` tag as expected.

New generated HTML code:
imagen

_Please check the following:_

-   [x] Do the tests still pass?[^1]

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)

### CODE REVIEW

**Comment by lb-** [comment]
Thanks @jlmirocoll I've flagged as needing a review.

**Review by thibaudcolas — CHANGES_REQUESTED** [review]
Thank you for taking a look at this @jlmirocoll! You’re correct that specifying the `width` and `height` will override the image’s intrinsic dimensions, however this strikes me as the intended behavior in this example. Setting the `width` and `height` will help reduce or avoid any layout shift. I’d expect the kind of pattern used here to override them both with CSS anyway (`width: 100%; height: auto` or similar).

It’d be very unusual for layout around images to be done without any CSS, so I think it makes sense to keep the `width` and `height` as-is to demonstrate a common pattern.

Also note the `img` tag should always have an `alt` attribute.

**Comment by csalom** [comment]
hey @thibaudcolas, I don't understand what you said about the intended behaviour of the example because if we keep the width and height on the img tag, then the `source/srcset` does not work.

**Comment by thibaudcolas** [comment]
@csalom the source element’s `media` is a CSS media query that relates to the width of the viewport, not of the image.

Here is a CodePen with two different images used in the two cases, to demonstrate that this does switch between the images based on the viewport width: https://codepen.io/thibaudcolas/pen/PoBzMVo.

All the `width` and `height` attributes do is determining what size the image is displayed at. They don’t take any part in determining what image gets displayed.

**Pull request closed without merging**
