### PR TITLE
Cast settings' verbose_name to string

### PR DESCRIPTION
**Pull request by SebCorbin**
When using `gettext_lazy` for verbose_name on a generic setting model, you get a `TypeError: __str__ returned non-string (type __proxy__)`

_Please check the following:_

-   [x] Do the tests still pass?
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For new features: Has the documentation been updated accordingly?

### CODE REVIEW

**Comment by lb-** [comment]
Are you able to add a test for this, seems like a use case that will be easily missed if this code gets refactored in the future. 

Thanks for contributing @SebCorbin

**Comment by SebCorbin** [comment]
FYI, I added a name to the tested settings so that `wagtail.admin.tests.test_menu.TestMenuRendering` would pass, but maybe that could be transformed in a general check (i.e. make sure menu items with translatable labels must have a name)

**Comment by lb-** [comment]
Thanks @SebCorbin  I'll flag this for review.

**Review by zerolab — APPROVED** [review]

**Comment by lb-** [comment]
Thank you @SebCorbin

**Pull request merged**
