### PR TITLE
Formalise support for Django 3.2

### LINKED ISSUE #6981: Formalise Django 3.2 support
Django 3.2 has just been [released](https://www.djangoproject.com/weblog/2021/apr/06/django-32-released/)!
Although Wagtail seems to support it (I've seen tests are run against Django master) it is excluded in `setup.py` (`"Django>=2.2,<3.2"`).

It is an issue because the [Poetry](https://python-poetry.org/) package manager cannot install packages declared as being incompatible ([source](https://github.com/python-poetry/poetry/issues/697#issuecomment-470431668)). That means that people currently using Wagtail and Poetry (me for example :D) cannot upgrade to Django 3.2 (not easily at least).

### PR DESCRIPTION
**Pull request by gasman**
Fixes #6981

### CODE REVIEW

**Comment by gasman** [comment]
The remaining failure on MySQL is caused by this commit: https://github.com/django/django/commit/779e615e362108862f1681f965ee9e4f1d0ae6d2. The docs for that commit don't indicate that this is a breaking change, so it's probably an unintended regression in Django.

(#6836 also makes it difficult to test against current MySQL versions - it may be possible to work around that by retrospectively changing the initial migration in wagtail.embeds so that thumbnail_url is a TextField already, but that needs further investigation.)

**Comment by gasman** [comment]
Updated with fix from #6999 and workaround for the order_by/update issue from https://github.com/django/django/commit/779e615e362108862f1681f965ee9e4f1d0ae6d2 - will investigate the latter further and file an issue with Django if necessary.

**Comment by gasman** [comment]
MySQL order_by/update bug now reported to Django in https://code.djangoproject.com/ticket/32645.

**Comment by jpmckinney** [comment]
Some warnings that'd be nice to avoid in `wagtail/core/signals.py`:

> RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.

Basically, `providing_args=[…]` can be removed with no consequence.

**Comment by gasman** [comment]
@jpmckinney Good point... removed those now, cheers!

**Review by auvipy — APPROVED** [review]

**Comment by gasman** [comment]
Merged in f8299885aa916becb9109c881f3ab28408af794e + parents.

**Pull request closed without merging**
