### PR TITLE
Search fixes

### PR DESCRIPTION
**Pull request by kaedroho**

### CODE REVIEW

**Comment by kaedroho** [comment]
Cherry picked those commits and rebased on master

**Comment by gasman** [comment]
@kaedroho Looks like https://github.com/wagtail/wagtail/pull/4019/commits/fb341f093d44385317097ff9e4bc02381cae7886 is another one to be cherry-picked.

**Comment by kaedroho** [comment]
Done!

**Comment by kaedroho** [comment]
@gasman Shall I cherry pick the changes we've backported straight to master now?

**Comment by gasman** [comment]
@kaedroho Yep, go for it!

**Pull request merged**
