### PR TITLE
Fix exclude_fields_in_copy

### LINKED ISSUE #10922: Copying a page with a generated unique field raises a ValidationError
### Issue Summary

I have a Page model, that has a unique UUID field in it. When I'm trying to copy such a page, I receive a ValidationError saying "this Uuid already exists".  

To be specific, at first, it's getting copied as a draft just fine. But the ValidationError occurs when I'm trying to publish a copy.

After some debugging, I suppose that the existing UUID comes from the copied revision of the original page. I was trying to adjust the copying behaviour, but it seems that there is no control over this process when copying from UI. `Page.copy` method isn't called, so there is no way to pass arguments like `update_attrs` or `copy_revisions=False` into CopyPageAction

I'm using `exclude_fields_in_copy` setting, but it doesn't affect revision's copy process.

### Steps to Reproduce

1. Set up a clean wagtail/bakerydemo project
2. Add the following code to the end of `bakerydemo/blog/models.py` :

``` python
import uuid


class TestBlogPage(Page):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True)
    exclude_fields_in_copy = ['uuid']
    
```
3. Create and run migrations:
```bash
./manage.py makemigrations
./manage.py migrate
```

4. Log in to /admin. Navigate to  `Root -> Welcome to the Wagtail Bakery!`
5. Create a child page of type `Test blog page` under the `Welcome to the Wagtail Bakery!` page and publish.
6. Copy the test page. Ensure "Alias" and "Publish copied page" are not checked. Also, you need to slightly tweak the slug and title fields.
7. Publish the copy. Observe ValidationError
image

---

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11.3
-   Django version: 4.2.5
-   Wagtail version: 5.1.1

### LINKED ISSUE #11428: Field defined in exclude_fields_in_copy still gets copied (Wagtail 5.2.2)
### Issue Summary
This is a follow-up to the issue  #10001 as **I can reproduce it in Wagtail 5.2.2**

@Tijani-Dia perfectly described the problem I've been having for ages, so I'll copy the steps from #10001 with a few unimportant changes:

When I copy a page in the admin, some fields get copied even if added to the `exclude_fields_in_copy` list.

### Steps to Reproduce
1. Start a new project with wagtail start myproject
2. Edit models.py as follows:

```python3
from django.db import models

from wagtail.models import Page
from wagtail.admin.panels import FieldPanel


class HomePage(Page):
    pass


class TestPage(Page):
    name = models.CharField(max_length=255, default="name")

    content_panels = Page.content_panels + [FieldPanel("name")]

    exclude_fields_in_copy = ["name"]
```
3. Create and run migrations, create superuser, run server
```bash
./manage.py makemigrations
./manage.py migrate
./manage.py createsuperuser
./manage.py runserver
```

4. Create and publish a TestPage in the admin UI and set any value other than the default one for the name field e.g original:
orig

5. Copy the page (without ticking the Publish copied page and Alias checkboxes):
copying

6. Go to the edit view for the copied page: **the name value is copied from the original page**
copy

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

- Since I've added the `name` field in the `exclude_fields_in_copy` list, I'd expect the copied page to have the default value for that field.

- This issue is related to #10922 where the problem occurs while publishing the copied page with a unique and hidden `uuid` field, that should be auto-generated but somehow makes it into the copy page.   
- It reproduces in Wagtail 5.2.2. I was trying to reproduce it in 4.1, but everything is fine there
- It works fine when `Publish copied page` checkbox is ticked

 
- I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: `3.11.5`
-   Django version: `5.0.1`
-   Wagtail version: `5.2.2`
-   Browser version: `Firefox 121`

### PR DESCRIPTION
**Pull request by elhussienalmasri**
Fixes #11428  , Fixes #10922

 the reason for these two issues is the same ,these two issues may like this issue #11323    and the reason of these issues
already mentioned or may be similar to this #11448 . 
in brief : the fields excluded in the `copied page`  must also be excluded in the `revision` of this page as well.

for this issue #11428

 original page 
Screenshot

the excluded fields must appear in the copied page with default values or null if don ,t have default value, as shown below 
in the Screenshot:

Screenshot2

for this issue #10922 

 I follow the steps mentioned in the issue's description , and same error occurred as well.
After : the error disappear and the copied page could be `published` or be live with `uuid` . as shown below in the Screenshot:

Screenshot3

_Please check the following:_

-   ✅ Do the tests still pass?[^1]
-   ✅ Does the code comply with the style guide?
    -   ✅ Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by lb-** [comment]
Thank you @elhussienalmasri this looks promising. Would you be able to add a unit test or two for this?

This way we will be able to ensure this fix works in the future if code changes happen.

**Comment by elhussienalmasri** [comment]
Thanks @lb-  very much , although I don ,t have much experience in unit test but it seems this PR not need
much unit test , and I will start working on unit tests for this PR as soon as possible.

**Comment by lb-** [comment]
Thanks @elhussienalmasri  - there are a bunch of tests for the current exclude fields in page copy in wagtail/tests/test_page_model.py see the `TestCopyPage` class.

**Comment by elhussienalmasri** [comment]
Great @lb-  really appreciate your advice , I think I able to start working on the unit test for this issue and 
may be finish the work this week in the next few days

**Comment by elhussienalmasri** [comment]
I added the unit test , please let me know if this unit test or this PR need additional work ,Thanks.

**Review by lb- — APPROVED** [review]
Tested before & after, this is working great.

Thank you for explaining the fix and adding a test.

**Comment by elhussienalmasri** [comment]
Thanks @lb- very much  for the quick response , this PR the fastest PR I made get merged.

**Comment by lb-** [comment]
I tried a few times to understand and fix those bugs and completely missed the revision issue. Thanks for your solution. 

I'm glad to see it in 6.0.

**Comment by elhussienalmasri** [comment]
if you solve very similar issue to that  like me , I already solved #11448 and despite this issue merged or not  , of course you will solve it.

**Comment by drimacus182** [comment]
@elhussienalmasri @lb- Thanks a lot for your work on this! 
Can't wait for 6.0 to be released)

**Pull request merged**
