### PR TITLE
Cleanup/3441 snippet modeladmin validation error helper

### PR DESCRIPTION
**Pull request by Nebulosar**
Cleanup tasks for #3441 

Added the validation_message funtion to:

- Snippets

- Modeladmin

- `contrib.settings`

Also updated the tests that run through this code

### CODE REVIEW

**Comment by ababic** [comment]
HI @Nebulosar,

Thank you for helping with this. I think it'll be really valuable to have validation errors handled more consistently throughout Wagtail. I don't think this is far away. However, I think there might perhaps be some misunderstanding around what the existing tests are testing, and the purpose of the `validation_error` helper added by @gasman in #3440.

Please correct me if I've missed something, but it seems you haven't added any tests that show the `validation_error` making a difference in the UI. See the [tests added in #3440](https://github.com/wagtail/wagtail/pull/3440/files#diff-509186d17133395aafeb7c62930e9881) for an example. What we should be looking to confirm is that:

1. Field-specific errors now appear in a list at the top of the page as well as next to relevant field.
2. And non-field errors are also rendered in the same spot.

Do you think you might be able to revise the tests to show this?

**Comment by Nebulosar** [comment]
Hello @ababic ,

After looking at the tests in #3440 I can understand what you mend.

I will look into testing the specific tests to check for UI elements

**Comment by ababic** [comment]
Okay, thanks @Nebulosar. Please let me know once you're happy with things, and I'll review things again.

**Comment by gasman** [comment]
I'm happy to merge this as-is - as I said in #3441, I don't think it's necessary to re-test all the permutations of field/non-field errors as implemented by the `validation_error` helper, as that's all covered by the tests in #3440. Given that we can see the same helper in use here, and we have tests to confirm that it's hooked up correctly and responding to simple validation errors, we can reasonably take it as read that it will respond appropriately to the more esoteric error cases :-)

**Comment by gasman** [comment]
Merged in a03c310858569858d70f349e3f6e3f7a4bf159e3 - thanks @Nebulosar!

**Pull request closed without merging**
