### PR TITLE
Feature: Upgrade notification 2 - LTS

### LINKED ISSUE #7336: Change release notification to link to latest major release notes
Wagtail has a notifcation on the dashboard that is shown if the Wagtail installation is out of date:

image

This notification always links to the latest patch release. So clicking the link in the above screenshot will take the user to https://docs.wagtail.io/en/stable/releases/2.13.3.html

The problem with this is that this Wagtail site is a major version behind, so the release notes of the point release aren't relevant to this user since we only fix new regressions in point releases.

We should instead be pointing to the [2.13 release notes](https://docs.wagtail.io/en/stable/releases/2.13.html), which is much more relevant and interesting to someone on Wagtail 2.12.

### PR DESCRIPTION
**Pull request by tbrlpld**
This is a follow up to #7652 and relates to issues #7336 and #7405.

This PR adds an option to show the upgrade notification only when the currently installed version is behind the latest LTS release. The actually latest version is ignored. 

The following examples should illustrate the display behaviour of the upgrade notification with the new option set:

| Current version | Latest version | Latest LTS version | Show upgrade notification | Description |
|-----------------|---------------|-------------------|----------------------------|------------|
| 2.10.2                  | 2.10.3               | 2.7.13                     | False                                     | LTS older than current |
| 2.10.2                  | 2.11                  | 2.11                         | True                                      | LTS is newer than current |
| 2.10.2                  | 2.12                  | 2.11                         | True                                     | LTS is newer than current, although older than latest |
| 2.11 (LTS)           | 2.11.1                | 2.11.1                       | True                                     | LTS is newer than current |
| 2.11.1 (LTS)         | 2.12                  | 2.11.1                      | False                                     | LTS same as current, although older than latest |
| 2.11.1 (LTS)         | 2.12                  | 2.11.2                      | True                                      | LTS newer than current, although older than latest |
| 2.11.2 (LTS)         | 2.13                  | 2.11.2                      | False                                    | LTS same as current, although older than latest |
| 2.11.2 (LTS)         | 2.14                  | 2.11.2                      | False                                     | LTS same as current, although older than latest |
| 2.11.2 (LTS)         | 2.15                  | 2.15                        | True                                      | LTS newer than current |

Closes #7336 

***

Thanks for contributing to Wagtail! 🎉

Before submitting, please review the contributor guidelines <https://docs.wagtail.io/en/latest/contributing/index.html> and check the following:

* Do the tests still pass? (https://docs.wagtail.io/en/latest/contributing/developing.html#testing) -> Yes
* Does the code comply with the style guide? (Run `make lint` from the Wagtail root) -> Yes
* For Python changes: Have you added tests to cover the new/fixed behaviour? -> Yes
* For front-end changes: Did you test on all of [Wagtail’s supported environments](https://docs.wagtail.io/en/latest/contributing/developing.html#browser-and-device-support)? -> No
    * **Please list the exact browser and operating system versions you tested**.
    * **Please list which assistive technologies you tested**.
* For new features: Has the documentation been updated accordingly? -> Yes

### CODE REVIEW

**Comment by tbrlpld** [comment]
cc @nimasmi

**Review by lb- — APPROVED** [review]
@tbrlpld  thanks for this, I have reviewed this PR and https://github.com/wagtail/wagtail/pull/7652 together.

There were a bunch of changes to this code since you prepared these PRs, changed linting rules, added prettier and also HTML formatting plus we are working towards a bit more clarity about what goes into components vs a new folder `includes`.

So I have rebased your PR with these changes in mind and squashed them, I also included a fix for https://github.com/wagtail/wagtail/issues/8537 as it made sense to do this all at once.

I have validated a few scenarios and this is working great. I moved the position of LTS to inside the JS as this is really part of the version name and putting this in the translations did not make sense.

#### Screenshots

#####  Non-LTS upgrade version

Screen Shot 2022-05-26 at 4 46 58 pm

##### LTS upgrade version

Screen Shot 2022-05-26 at 4 46 30 pm

**Comment by lb-** [comment]
Note: frontend CI will fail but have these other PRs to resolve it

https://github.com/wagtail/wagtail/pull/8591
https://github.com/wagtail/wagtail/pull/8577

**Comment by tbrlpld** [comment]
Thanks for checking,merging and fixing @lb-

**Comment by lb-** [comment]
for completeness - additional validations

* default setting - showing the 2.16.2 as the latest version but linking to the 2.16 release notes
Screen Shot 2022-05-27 at 7 21 12 am

* LTS setting - showing as 2.15.5 but linking to the 2.15 release notes
Screen Shot 2022-05-27 at 7 20 27 am

I have re-worded the release notes to be more clear about this difference 52e87968e2dad66eb0b35d47f7e95ddfcd1bf43e

**Comment by tbrlpld** [comment]
Ah yes, good call. Thanks you @lb-

**Pull request merged**
