### PR TITLE
Separate creation and activation steps in tutorial document

### PR DESCRIPTION
**Pull request by ankit02327**
- Separated the virtual environment creation and activation steps into distinct sections.
- Improved readability by adding clear steps for creating and activating the virtual environment.
- Ensured proper formatting in the tutorial.md file.

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
I'm not sure I understand why this is better?

**Comment by ankit02327** [comment]
I separated the creation and activation steps to improve clarity, especially for beginners. By splitting them, each step is easier to follow and avoids potential confusion when running the commands. I believe it aligns with the principle of keeping instructions simple and explicit.

**Comment by ankit02327** [comment]
@RealOrangeOne Should I close this PR if it is not required now ?

**Comment by gasman** [comment]
Merged in 7745aa628db737e202aa90a942bf108db2efd182

**Pull request closed without merging**
