### PR TITLE
Ensure non-square avatar image will correctly show

### LINKED ISSUE #8428: Avatar image cropping doesn't render as a square when uploaded avatar image isn't a perfect square.
### Issue Summary
When uploading a new user avatar and the image is not a perfect square, the image gets cut off and doesn't display properly. 
image

### Steps to Reproduce

1. Open your user settings.
2. Upload a non-square image and save
3. Renditions don't show up as squares (rounded by CSS) 

### Technical details

* Python version: 3.9
* Django version: 4.0.3
* Wagtail version: 4.0a0
* Browser version: https://www.whatismybrowser.com/w/R6C7DFC

### PR DESCRIPTION
**Pull request by lb-**
- fixes #8428
- [x] Do the tests still pass?[^1]
- [x] Does the code comply with the style guide? 
- [x] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
- [X] **Please list the exact browser and operating system versions you tested**: Safari 15.4, Firefox 99, Chrome 103 all on macOS 12.3
- [X] **Please list which assistive technologies [^3] you tested**: N/A
- [X] For new features: Has the documentation been updated accordingly? N/A

## Testing this change
- places to check when testing this; bottom left sidebar (user logo), user editing page, dashboard header, page history list.

## Screenshots

Screen Shot 2022-05-11 at 10 05 30 pm

Screen Shot 2022-05-11 at 10 09 35 pm

Screen Shot 2022-05-11 at 10 06 25 pm

Screen Shot 2022-05-11 at 10 05 46 pm

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by stevedya** [comment]
**Suggestion:** It looks like images in comments might have this isssue as well. 
Screen Shot 2022-05-12 at 2 02 29 PM
We might need to set `comment-header__avatar` to have `object-fit: cover;` too 👀

**Comment by lb-** [comment]
ahh the joy of multiple generations of css approaches haha, I will get on it.

**Comment by lb-** [comment]
@stevedya that is fixed now

**Comment by zerolab** [comment]
@stevedya any chance you can re-review/retest this?

**Pull request merged**
