### PR TITLE
Fix a few warnings from flake8-comprehensions.

### PR DESCRIPTION
**Pull request by atombrella**
Thanks for contributing to Wagtail! 🎉

I'm not sure how you feel about this. https://pypi.org/project/flake8-comprehensions/ has samples of the various rules. It's a bit more Pythonic.

Before submitting, please review the contributor guidelines <https://docs.wagtail.org/en/latest/contributing/index.html> and check the following:

* Do the tests still pass? (https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
* Does the code comply with the style guide? (Run `make lint` from the Wagtail root)
* For Python changes: Have you added tests to cover the new/fixed behaviour?
* For front-end changes: Did you test on all of [Wagtail’s supported environments](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)?
    * **Please list the exact browser and operating system versions you tested**.
    * **Please list which assistive technologies you tested**.
* For new features: Has the documentation been updated accordingly?

### CODE REVIEW

**Review by gasman — APPROVED** [review]

**Comment by zerolab** [comment]
Note: we should add flake8-comprehensions as an additional depenency to         

https://github.com/wagtail/wagtail/blob/main/.pre-commit-config.yaml#L15

```yaml
    hooks:
      - id: flake8
    additional_dependencies:
      - flake8-comprehensions
```

**Comment by atombrella** [comment]
> Note: we should add flake8-comprehensions as an additional depenency to
> 
> https://github.com/wagtail/wagtail/blob/main/.pre-commit-config.yaml#L15
> 
> ```yaml
>     hooks:
>       - id: flake8
>     additional_dependencies:
>       - flake8-comprehensions
> ```

I only fixed a subset of them, and it's unfortunately a bit difficult to do easily with a regex. There are still a lot of `dict(....)` and other things. I can fix them in this PR, and add the plugin to the `pre-commit-hook` file.

**Comment by zerolab** [comment]
@atombrella that is fair enough. Let's treat this as a small tidy up, and I'll add a follow up issue to add `flake8-comprehensions` to pre-commit and lint.

**Comment by zerolab** [comment]
Merged alongside #7951 (cd87c159ac34 and parents)

**Pull request closed without merging**
