### PR TITLE
When running manage.py loaddata setting locale to Locale.get_default() is wrong.

### PR DESCRIPTION
**Pull request by specialunderwear**
There is no reason at all the locale is not also in the database dump and setting
it to Locale.get_default() is completely random and more likely than not wrong.

We get the following error because at the point this code is called, the default locale does not exist yet:

wagtail.core.models.i18n.Locale.DoesNotExist: Problem installing fixture '/tmp/tmp5jf3l5s9/bla/db.json': Locale matching query does not exist.

### CODE REVIEW

**Comment by lb-** [comment]
Thanks for submitting this @specialunderwear I have flagged for a review.

**Comment by specialunderwear** [comment]
Hi I've just rebased against master and updated the fixtures. This fix is really important for us because we actually move data between applications and databases using the fixtures. It simply doesn't work when hooks are running during data loading.

**Comment by specialunderwear** [comment]
I will try to explain, if this is not sufficient, I will try to make a bakery showcase.
When making a wagtail database dump, since wagtail does not use natural foreign keys in stream fields, it is needed to dump the entire database with all the foreign keys exactly as they are. That means including stuff like contenttypes. The data in contenttypes is also created by migrations, but these migrations might create them with different id's as referenced in the stream fields, because it is not guaranteed a project during it's lifetime added all apps in the order in which they are in INSTALLED_APPS, which has some influence on the migration order. So we need to flush the entire database before import and then start the load data process. During the flushing all wagtails 'made in migration' objects are also deleted. But they are in the database dump, so they will be restored during the import transaction. At least, they would be, if not for the post_save hook that will get triggered during the import process. this import hook will trigger an error because the transaction hasn't finished and the Locale has not yet been created.

In general it is always a very bad idea to have actions triggered on load data (raw=true_ they should simply be disabled and assume all that is need will be in the database dump (which it usually is). There are simply no cases in which this behaviour is not destructive/disruptive when doing data imports.

In our case, we can never do a database import with wagtail data, without creating the locale model first, before importing the entire database. And the models still needs to have the proper primary key for the other data to be properly loaded.

So I believe when loading data (raw=True) all signal handlers should be turned off, because any assumptions on which data is present in the database are not useful or valid.

**Comment by specialunderwear** [comment]
> If your data does not have a locale

I think this is the strange part. Why would your data not have a locale? Only with manually created fixtures you can get to this point. As you said, locale is a required field so it would be impossible to create fixtures with dumpdata without a locale. I think this feuture only exists for the unittest data, which are fixed in this PR.

**Comment by specialunderwear** [comment]
image

**Comment by specialunderwear** [comment]
Look here, this is why I am sending this pull request, wagtail is behaving badly atm ...

**Comment by lb-** [comment]
@specialunderwear - been a while but wondering if this is still an issue you're facing.

Would you mind raising a bug request/report detailing the problem, with a bit more info and why you see the current behaviour as conflicting with Django's way of doing things. 

Not sure on priorities but at least the problem can be discussed outside of this PR and may get a bit more visibility. 

Then link this PR to that raised issue, if you are keen you can also rebase this PR. But maybe it's best to wait for some confirmation that the bug is accepted before doing more on this PR. 

Thank you.

**Comment by specialunderwear** [comment]
Hi, a colleague will add a stacktrace so you know what's causing this.

**Comment by highluca** [comment]
@specialunderwear 
the is the stack trace of the "wagtail.core.models.i18n.Locale.DoesNotExist: Problem installing fixture '/tmp/tmp5jf3l5s9/bla/db.json': Locale matching query does not exist."

Traceback (most recent call last):
  File "/var/lib/virtualenv/PROJECTNAME/bin/manage.py", line 8, in <module>
    sys.exit(main())
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/PROJECTNAME/main.py", line 9, in main
    execute_from_command_line(sys.argv)
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 163, in loaddata
    self.load_label(fixture_label)
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 253, in load_label
    if self.save_obj(obj):
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/core/management/commands/loaddata.py", line 209, in save_obj
    obj.save(using=self.using)
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/core/serializers/base.py", line 288, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/db/models/base.py", line 861, in save_base
    pre_save.send(
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/wagtail/models/i18n.py", line 485, in set_locale_on_new_instance
    instance.locale = Locale.get_default()
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/wagtail/models/i18n.py", line 63, in get_default
    return cls.objects.get_for_language(settings.LANGUAGE_CODE)
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/wagtail/models/i18n.py", line 36, in get_for_language
    return self.get(
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/virtualenv/PROJECTNAME/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
wagtail.models.i18n.Locale.DoesNotExist: Problem installing fixture '/tmp/tmppnf90zzl/PROJECTNAME/db.json': Locale matching query does not exist.

**Comment by allcaps** [comment]
This Django documentation describes the situation, and might be nice to have as reference.
https://docs.djangoproject.com/en/5.1/topics/db/fixtures/#how-fixtures-are-saved-to-the-database

**Comment by thibaudcolas** [comment]
Assigning to myself to create the issue.

**Comment by thibaudcolas** [comment]
After discussion with the core contributors, I have created a new issue for this as suggested by @lb-: #12469. We clearly need more information here before anyone feels comfortable further reviewing the pull request, or working on it. It’d also help if someone else confirmed the presence of the issue.

**Pull request closed without merging**
