### PR TITLE
User group permissions table - simplify layout styling & fix long first column labels

### PR DESCRIPTION
**Pull request by lb-**
- Remove the deprecated `width` attribute usage in the table `col` elements.
- Add a defined width to the first column (model names) so these avoid wrapping unless really needed.
- Remove 10% widths on others, table layout auto being used will automatically space these out.

Follow up to #10867 - see comment from @zerolab in https://github.com/wagtail/wagtail/issues/10867#issuecomment-1929475139_

I think we could do a lot better on this table but it will need some more time and maybe a rethink of how to support really wide tables, hopefully this solution is a small surface area and gives us a nicer layout.

Note: I also tried table layout fixed, this was not suitable for this kind of problem.

#### Before

Screenshot 2024-03-23 at 2 29 07 pm

#### After

Screenshot 2024-03-23 at 2 49 53 pm

### CODE REVIEW

**Comment by lb-** [comment]
OK it looks like every PR is failing unless I add and remove that cache clearing commit, somewhat annoying.

**Comment by gasman** [comment]
Thanks @lb- - this was bothering me too!

Unfortunately it looks like some of the other changes in the meantime (possibly the universal listings updates in #11823) have nullified this change - on bakerydemo I'm still getting ugly wrapping on "Generic settings".

I can improve things by disabling some of the `class="listing"` styles, particularly this one:

```
@media screen and (min-width: 50em) {
    .listing td {
        padding: calc(1em* var(--w-density-factor)) 1em;
    }
}
```

but I think the proper fix is probably to not use `class="listing"` on this table at all, since it doesn't really have much in common semantically with our listing views - and just copy over the styles that we do want, such as the dotted line row separators.

Looking a bit further afield for improvements - I'm wondering if Lock / Unlock really warrant their own columns? I suspect that `LockableMixin` on snippets has fairly limited use in the real world, and it would be fair game for those checkboxes to be part of the "Custom permissions" column for the models that do use it.

**Comment by gasman** [comment]
In fact, I think the styles here might be the primary offender - https://github.com/wagtail/wagtail/commit/1ad22f530d50409aa090b9e57a0118a75ac94a41#diff-32cf9d109232a440035d3bb94252865f0fa2edb915f4440ff652c08d30373181

"If this table contains bulk action checkboxes, make the first column 5rem / 2.5rem" - without accounting for the possibility that the bulk action checkboxes might not actually be in the first column.

**Comment by lb-** [comment]
Thanks Matt. I'll take another look at this.

**Comment by laymonage** [comment]
Thanks LB, I've opened a new PR for this (#12223).

**Comment by lb-** [comment]
Thanks @laymonage

**Pull request closed without merging**
