### PR TITLE
fixed translations in workflow templates

### PR DESCRIPTION
**Pull request by 0saurabh0**
_Please check the following:_

- [x] Do the tests still pass?[^1]
- [] Does the code comply with the style guide? 
    - [ ] Run `make lint` from the Wagtail root. 
- [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
- [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    - [ ] **Please list the exact browser and operating system versions you tested**:
    - [ ] **Please list which assistive technologies [^3] you tested**: 
- [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**. 

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by lb-** [comment]
@0saurabh0  not sure what happened to this branch / PR but I have merged in via f3720a76528069c038c441626961fd2ba97638ab along with some other fixes

Thanks for helping contribute to Wagtail!

Fixes #8214 

See also #8238

**Comment by 0saurabh0** [comment]
I've raised this PR but forgot to see that it was assigned to someone else , that's why I closed it.
So my commits are merged right ?

**Comment by lb-** [comment]
hey @0saurabh0  the commits are merged, thanks for contributing.

Maybe next time just keep the PR open and add a comment to the issue saying that you prepared a PR before seeing someone else was looking at it.

This way they have the opportunity to see it and maybe move on to something else.

Not a big deal at all though, it can be confusing getting started and finding something to work on.

Well done on giving this a go.

one note - always reference the issue you are fixing/relating your PR to when opening one, makes it much easier to track the history of things.

**Comment by 0saurabh0** [comment]
okay  @lb-  I'll keep that in mind from now on.
thanks though..

**Pull request closed without merging**
