### PR TITLE
Fixed Dialog componet's message corners

### LINKED ISSUE #10177: Dialog component's message does not have rounded corners at the top
### Issue Summary

When using the dialog component with a message, the dialog's top side does not have rounded corners:

image

This was a regression in 55d04366f7dd57141de9ec9282d8978b3ccbd7cc when `overflow: hidden;` was added to `.w-dialog__box` in the base dialog styles.

I'm assuming that the `overflow: hidden;` was only removed so that we can display the close button at an offset in the userbar's accessibility checker, and not necessarily required for the generic floating version of the dialog:

<details>
<summary>Screenshot</summary>
image
</details>

In fact, the generic floating dialog uses the same close button styles as the other ones, so this means the `overflow: hidden;` was only necessary for the accessibility checker's dialog:

<details>
<summary>Screenshot</summary>
image
</details>

### Steps to Reproduce

1. Spin up bakerydemo
2. Open Settings > Styleguide
3. Try the "Dialog with success/warning/error" variants of the Dialog component
4. See that the top side of the dialog has no rounded corners

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The top side should be rounded like the bottom, which was how it has been before Wagtail 4.2.

### Suggested fix

Reintroduce `overflow: hidden;` to the `.w-dialog__box` styles in `_dialog.scss` like how we had it before, and add `.w-dialog__box { overflow: visible; }` to the userbar's dialog override in `_userbar.scss`.

Alternatively, add `border-top-*-radius` to `.w-dialog__message` with the same value as the one set in `.w-dialog__box`.

### PR DESCRIPTION
**Pull request by SAMAD101**
Fixes #10177 

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [x] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [x] **Please list the exact browser and operating system versions you tested**:
    - Browser: Mozilla Firefox 110.0-1 ; OS: Manjaro (Arch Linux) 6.1.12-1
    -   [x] **Please list which assistive technologies [^3] you tested**:
    - VS Code, Konsole (KDE Plasma terminal)
-   [ ] For new features: Has the documentation been updated accordingly?

### CODE REVIEW

**Review by laymonage — CHANGES_REQUESTED** [review]
Thanks for the PR. Please provide screenshots to make sure that the issue is fixed.

**Review by laymonage — APPROVED** [review]

**Comment by laymonage** [comment]
Thanks!

I've added you to the contributors list as https://github.com/wagtail/wagtail/blob/a393ea809162acb56024aa274fe386496b932f34/CONTRIBUTORS.rst?plain=1#L700, let me know if you want a different name listed.

**Comment by laymonage** [comment]
Backported to 4.2.1 in 7600327485e766e286c7d47ec26e3611b4376170. Not applicable to 4.1.3 as the regression came in 4.2.

**Comment by SAMAD101** [comment]
> Thanks!
> 
> I've added you to the contributors list as Sam,
> https://github.com/wagtail/wagtail/blob/a393ea809162acb56024aa274fe386496b932f34/CONTRIBUTORS.rst?plain=1#L700 let me know if you want a different name listed.

Thank you very much. Also thanks for the assistance :)

**Pull request merged**
