### PR TITLE
Fix: parse_query_string only returns only one instance of a filter specified multiple times

### PR DESCRIPTION
**Pull request by salty-ivy**
Fixes https://github.com/wagtail/wagtail/issues/10214

### Additional context
 the returned filter is now `QueryDict` instead of regular dict, that solves the problem of getting a list of values, as it can be accessed via `getlist` method.

```python
>>> filters, query = parse_query_string('my query string "this is a phrase" this_is_a:filter key:test1 key:test2', operator='and')
>>> filters
<QueryDict: {'this_is_a': ['filter'], 'key': ['test1', 'test2']}>
>>> filters.getlist('key')
['test1', 'test2']
>>> filters.dict()
{'this_is_a': 'filter', 'key': 'test2'}
```

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?

### CODE REVIEW

**Review by gasman — CHANGES_REQUESTED** [review]
Thanks for the PR @salty-ivy!

As mentioned on #10214, could we look at using [QueryDict](https://docs.djangoproject.com/en/4.1/ref/request-response/#querydict-objects) for this? I think that if we initialise `filters` to a blank QueryDict, then the logic for inserting a new item will just become:

    filters.update({key: value.strip('"') if value.strip('"') is not value else value.strip("'")})

\- no need for the separate cases for "does this key exist already". This also has the benefit that any existing user code that expects a single value for each filter won't break due to it returning a list instead - to get the list, the user code would have to go through `.getlist`.

**Comment by salty-ivy** [comment]
This is a great idea @gasman sorry for missing on initial comment, will get this implemented.

**Comment by salty-ivy** [comment]
@lb-  @gasman this one is ready for another review, thanks.

**Comment by dopry** [comment]
@salty-ivy Thanks for the contribution!  I'll be excited to get my projects updated to use this.

**Comment by salty-ivy** [comment]
> @salty-ivy Thanks for the contribution!  I'll be excited to get my projects updated to use this. 

It's great to hear that!

**Pull request closed without merging**
