### PR TITLE
Grammatically updated the tech doc

### PR DESCRIPTION
**Pull request by zobbs-git**
Small grammatical update to the wagtail documentation

wg1
wg2
wg3

### CODE REVIEW

**Review by lb- — APPROVED** [review]
Looks good - I think this escaping was a leftover from the RST migration.

Screen Shot 2022-10-13 at 8 06 25 am

**Comment by lb-** [comment]
Thanks @zobbs-git  - but could you please let me know your name (or the name you want listed on the contributors list). I could not find your name anywhere.

For now I will just use `Zobbs`

**Comment by zobbs-git** [comment]
> Thank you, my name is Chizoba Nweke. Glad my contribution was helpful!.

**Comment by zobbs-git** [comment]
> Thank you @lb- , my name is Chizoba Nweke. Glad my contribution was helpful!.

**Comment by lb-** [comment]
Awesome. I'll update this PR later and merge it in. Congrats on getting your first merge into Wagtail.

**Comment by lb-** [comment]
Sorry @thibaudcolas I think we were trying to do this at the same time

**Comment by thibaudcolas** [comment]
Oops 😄

**Pull request merged**
