### PR TITLE
Convert edit view in contrib.settings to a class based View

### PR DESCRIPTION
**Pull request by Tijani-Dia**
This PR aims to turn the edit view in contrib.settings to a CBV. This will make it easier to add other settings models (See #6873) and to follow the logic.

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by Tijani-Dia** [comment]
@lb- I've tried reusing the `PermissionCheckedMixin` along with the `PanelMixin`. That's all I found useful for this view. Do you have a generic view in particular in mind that you'd like me to use (instead of the `FormView` maybe)?

**Comment by lb-** [comment]
@Tijani-Dia  what about `EditView`

```
from wagtail.admin.views.generic import EditView
```

See usage examples here
* wagtail/admin/views/collections.py
* wagtail/admin/views/workflows.py
* wagtail/users/views/users.py (most recent adoption)

We are slowly trying to move to these shared Wagtail class views, they build on Django's with the things you mentioned like `PermissionCheckedMixin`

**Comment by Tijani-Dia** [comment]
All right @lb-, I think we can reuse some bits of that `EditView`. I'm on it.

**Comment by Tijani-Dia** [comment]
@lb- I've updated it to use Wagtail's generic `EditView`. Thanks!

**Comment by lb-** [comment]
Thanks @Tijani-Dia I've self-requested a review and will try to take a look soon

**Review by lb- — DISMISSED** [review]
This is working great, thanks for taking on the feedback.

It would be good to adopt the `{% extends "wagtailadmin/generic/base.html" %}` in the HTML templates (it includes the ability to use shared title in the head and a few other things). However, not a blocker for this PR.

**Comment by zerolab** [comment]
#6873 extends this and fixes a few issues (e.g. empty action button for site settings with a single site)

I suggest we merge together and the do any follow up like `{% extends "wagtailadmin/generic/base.html" %}`

**Comment by lb-** [comment]
@zerolab  ok - I must have missed that - I did check the local build and saw that the method was added correctly (on single and multi-site).

I will leave this open for now then.

I did raise https://github.com/wagtail/wagtail/issues/9484 but will maybe close it for now.

**Comment by lb-** [comment]
Might close this in favour of https://github.com/wagtail/wagtail/pull/9390 to avoid confusion.

**Pull request closed without merging**
