### PR TITLE
Few lines added in the file README.MD

### PR DESCRIPTION
**Pull request by ayushkumar152002**
The file README.MD contained a link (https://docs.python.org/3/tutorial/venv.html)  which referred to as  how to create a virtual environment.
But it would be great if the process for creating the virtual environment is written in the file README.MD  so that it would be easy for people to just read and understand the procedure at once

### CODE REVIEW

**Comment by gasman** [comment]
Hi @ayushkumar152002 - thanks for the PR, but this has previously been proposed and rejected at #10976. These instructions only work on Windows - giving instructions that work reliably across all platforms would make this section [as long as the tutorial](https://docs.wagtail.org/en/stable/getting_started/tutorial.html#install-and-run-wagtail). For this reason, we've decided it's better to keep these instructions oriented towards people who are already familiar with Python virtual environments, and link to the tutorial for people who need further guidance.

**Comment by ayushkumar152002** [comment]
Thankyou sir for your suggestion.

**Comment by ayushkumar152002** [comment]
Sir actually I am new to this project so can you please suggest me how can I make better contribution to wagtail project.

**Comment by zerolab** [comment]
@ayushkumar152002 please join the `#new-contributors` channel in the Wagtail Slack ([instructions](https://github.com/wagtail/wagtail/wiki/Slack))

**Pull request closed without merging**
