### PR TITLE
Add alternative sorting for form submission data

### PR DESCRIPTION
**Pull request by Adrian-Turjak**
* Adds an additional optional sorting for submission data
  via a new config entry.
* Add documentation for the full data view and the new config
  entry.

Deals with #3761

### CODE REVIEW

**Comment by timorieber** [comment]
I fully agree with you that form submissions need a sorting option. I vote for implementing "newest first" as default, even though this needs a small upgrade consideration because it's backwards-incompatible.

**Comment by Adrian-Turjak** [comment]
@timorieber I agree that newest first as default makes the most sense, but I bet you there is someone out there who has gotten used to oldest first, and liked it. For that person, I'd rather just add a setting so we can make newest first an option. Because right now, it's hardcoded as oldest first only.

That said, I need to add some tests because the code coverage tests are complaining!

Oh and, it's probably worth keeping the discussion in the issue instead since this pull request may not be the best option: #3761

**Comment by gasman** [comment]
Thanks @Adrian-Turjak!

I'm not keen on making this a config setting, for a couple of reasons: firstly, it's overlooking the multi-user nature of Wagtail. The person who's dealing with form submissions from day to day isn't necessarily the person with the keys to the codebase who can tweak settings according to their personal preference - and it's quite unlikely that it will occur to the user to go to their developer / agency and ask "can you change this setting please?", even if it is annoying them.

Secondly, micro-managing UX design choices is a poor use of config settings. If newest-first is indeed the more natural way of viewing the list - and I think there are good arguments that it is - then we should be bold and fix that for everyone, not just people who are persistent enough to read through the settings docs thinking "how do I want this set up?". (To me, 99% of good UX design is UX that you don't have to think about - it should just be _there_.)

To cater for people who do want the listing to be oldest-first, I think it would be worth making the "Submission date" heading clickable, as we do on other listings. (To be even nicer, we could make this a persistent property on the user profile, but that's probably overkill.) Also, we should keep in mind that this view is also used for CSV output - in this case I think oldest-first _is_ more appropriate (since it essentially acts as a log file) so we should switch the behaviour accordingly.

**Comment by Adrian-Turjak** [comment]
@gasman I totally agree. I'd much prefer we do this right, and I'd also much prefer to make newest first the default.

We can continue the discussion around this in the issue I opened (#3761).

**Pull request closed without merging**
