### PR TITLE
Add secondary actions menu in edit page headers

### PR DESCRIPTION
**Pull request by Tijani-Dia**
See #622.

- The `delete` action is moved from the main actions menu (at the bottom of the edit/create page) to the secondary menu (at the top, next to the breadcrumb).

Screenshot from 2021-12-15 11-57-47

### To-Do
- [ ] Ensure that removing `overflow: hidden;`  from the `.breadcrumb` styles ([here](https://github.com/wagtail/wagtail/blob/main/client/scss/components/_breadcrumb.scss#L4)) won't have undesired effects.

* Do the tests still pass? Yes
* Does the code comply with the style guide? Yes
* For Python changes: Have you added tests to cover the new/fixed behaviour? Yes
* For front-end changes: Did you test on all of [Wagtail’s supported environments]? No
    * **Please list the exact browser and operating system versions you tested**. Firefox
    * **Please list which assistive technologies you tested**. None
* For new features: Has the documentation been updated accordingly? Yes

### CODE REVIEW

**Review by KalobTaulien — APPROVED** [review]
Looks good to me, great work! 

I tested this locally and it does the job as described in the PR. 🎉

**Comment by zerolab** [comment]
The delete button move will likely confuse people. Curious to know the context for this change and whether it is part of the wider editor UI changes work

**Comment by phildexter** [comment]
Hey Dan - yes it is part of the wider changes. The longer term plan is to have this as a place for lots of other page level things.
image
This menu could then be mirrored on the page listing view in future.

This means that the bottom left buttons are much more to do with publishing only, which we think is clearer.
image

We've been discussing the wider UI change designs [here](https://github.com/wagtail/wagtail/discussions/7739), in case you haven't seen it.

I did have a brief discussion with @thibaudcolas about if we needed a wider consultation on moving the delete button as part of this, but our feeling was that it was a relatively small change and so far it's user tested fine (people have found it). However, I'll see if we can do some more user testing in the next week or two.

**Comment by gasman** [comment]
Merged in dd0b398d9c6ed4e7ae9aafc374ab37006d348a7b + parents. Thanks again @Tijani-Dia!

**Comment by phildexter** [comment]
Thanks @gasman

**Pull request closed without merging**
