### PR TITLE
option for assertCanCreateAt to check for saving draft pages

### PR DESCRIPTION
**Pull request by hjwp**
this is something i wanted in my own project, was quite a simple hack to change the helper test utils, thought i'd see if y'all were interested.  
WIP!

* [ ] Do the tests still pass? (http://docs.wagtail.io/en/latest/contributing/developing.html#testing)
* [ ] Does the code comply with the style guide? (Run `make lint` from the Wagtail root)
* [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
* [x] For front-end changes: Did you test on all of Wagtail’s supported browsers? **Please list the exact versions you tested**.
* [ ] For new features: Has the documentation been updated accordingly?

### CODE REVIEW

**Comment by gasman** [comment]
Thanks @hjwp - yep, would be interested in including this!

**Comment by DokuaAsiedu** [comment]
Would you mind me working on the documentation for this pull request?

**Comment by DokuaAsiedu** [comment]
@lb- I have not gotten a response from the author yet. I'm going on to edit the docs for this then?

**Comment by lb-** [comment]
New PR that may potentially supercede this one. 

https://github.com/wagtail/wagtail/pull/9458

**Comment by lb-** [comment]
@hjwp  thanks for this PR (many years ago), it has now been merged with some clean up, unit tests & docs added via #9458

@DokuaAsiedu  - thanks for your epic work on this.

**Comment by DokuaAsiedu** [comment]
> @hjwp thanks for this PR (many years ago), it has now been merged with some clean up, unit tests & docs added via #9458
> 
> @DokuaAsiedu - thanks for your epic work on this.

Thanks @lb- and thanks @hjwp for lmyour contribution

**Pull request closed without merging**
