### PR TITLE
Reorder elements in the order form

### PR DESCRIPTION
**Pull request by kjartansverrisson**
Addresses the issue of incorrect tab-order when logging on using keyboard. 

This change moves the password reset link to the very end of the form html code, while maintaining the same visual location in the browser.

Tested in:
- Chrome 79.0.3945.88
- Safari 13.0.4 (15608.4.9.1.3)
- Firefox 71.0 (64-bit) and 72.0.2 (64-bit)

### CODE REVIEW

**Comment by kjartansverrisson** [comment]
Issue: https://github.com/wagtail/wagtail/issues/5724

**Comment by gasman** [comment]
Thanks @kjartansverrisson! Please can you fix the linting error reported at https://circleci.com/gh/wagtail/wagtail/6607 ?

**Comment by kjartansverrisson** [comment]
Yes of course @gasman. Updated now.

**Comment by ababic** [comment]
Just deferring to @thibaudcolas for thoughts on the use of the fixed size values in the CSS. The UI is feeling fine for me at various screen sizes in chrome, though.

**Pull request merged**
