### PR TITLE
change document file_size to PositiveBigIntegerField

### PR DESCRIPTION
**Pull request by ggetzie**
This is to resolve Issue #12396 and allow users to upload large files.

### CODE REVIEW

**Review by gasman — CHANGES_REQUESTED** [review]
Thanks @ggetzie - this will also need a new migration (see https://docs.wagtail.org/en/stable/contributing/developing.html#running-migrations-for-the-test-app-models , although in this case running `./manage.py makemigrations` on any project running against your Wagtail checkout should work as well).

**Comment by ggetzie** [comment]
Migrations added.

**Review by gasman — APPROVED** [review]
Thanks @ggetzie - all looks good to me!

**Comment by gasman** [comment]
Merged in 9933432ec70d9408e95e022a37755c3f8187996a.

**Pull request closed without merging**
