### PR TITLE
Fix admin submit inputs focus

### PR DESCRIPTION
**Pull request by karranb**
In this PR I'm trying to solve issue #6340. If there is anyone working on this, I'm sorry I did not ask previously :sweat: 

I tested this on chrome and firefox, but this affects a lot of pages and I think I might have missed some of them.

### CODE REVIEW

**Review by allcaps — APPROVED** [review]
Thank you @karranb for your contribution.

I dropped `input:not([type=button])` because:

1. Wagtail does not use `<input type="button" ...`. Only `<button type="button"`
2. I believe the correct way to chain `not` is `input:not([type=submit]):not([type=button])`. In the old situation the one would cancel out the other.

I leave the PR open for another set of eyes.

Browsers tested:
- IE11, Win10
- Chrome 85, OSX
- Firefox 80

**Comment by karranb** [comment]
thanks for these great catches @allcaps

**Comment by allcaps** [comment]
@nmorduch Can you have a look at this?

**Review by allcaps — APPROVED** [review]

**Review by nmorduch — APPROVED** [review]
I will note that comprehensive testing isn't my strongest area, but this looks good to me and I did check that `input`s with `type="submit"` still are getting from elsewhere styles for a disabled state, which they are.

Also: It looks like we _do_ use `<input type="button" ...` in the style guide ([L508](https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html#L508), [L519](https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html#L519), [L530](https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/styleguide/templates/wagtailstyleguide/base.html#L530)), which we probably should stop doing given that it says on that very same same page not to do so.

**Comment by allcaps** [comment]
@karranb and @nmorduch thank you! 

I opened an issue https://github.com/wagtail/wagtail/issues/6388 for the input type button.

And will merge this!

**Pull request merged**
