### PR TITLE
Use `DEBUG=False` for testing `collectstatic` in CI

### PR DESCRIPTION
**Pull request by laymonage**
Testing #11643.

### CODE REVIEW

**Comment by laymonage** [comment]
Looks like the CircleCI is not triggered, possibly because it doesn't like me changing the config since I don't have enough permissions on CircleCI.

However, we can see that it's failing with the expected error on my personal CircleCI account:

https://app.circleci.com/pipelines/github/laymonage/wagtail/1484/workflows/2069c6f0-6956-4b63-8665-9c238ee911b4/jobs/3428

**Comment by gasman** [comment]
The `collectstatic` call here won't fail if there's an existing staticfiles manifest file from a previous successful run. While that might not be an issue given how CircleCI works, I'm wary of only having a test for this that's reliant on a specific detail of the CI environment - which is why my aim in https://github.com/wagtail/wagtail/pull/11647 was to flag up instances of the code pattern that triggers this, rather than replicating how it arises in real-world use.

Would you be happy with us merging both this and #11647, so that we're covering all bases?

**Review by laymonage — COMMENTED** [review]
Good point @gasman, thanks! I've changed the PR to just the CI changes, as well as moving the `ALLOWED_HOSTS` addition in `settings_ui.py` to `settings.py`. This (and reading `DEBUG` from env) will make it much easier to run the testapp locally so we can do interactive testing using the models we have in there.

**Comment by gasman** [comment]
Merged in d93588fb5b5d54b4f136cadfe0cd676d357f1475 (main) / 2d18a8795d (stable/6.0.x).

**Pull request closed without merging**
