### PR TITLE
The overflow in  the viewport of report filters is fixed Issue#8929

### PR DESCRIPTION
**Pull request by Akash-Kumar-Sen**
- Fixed https://github.com/wagtail/wagtail/issues/8929
- Only changed file https://github.com/wagtail/wagtail/blob/main/client/scss/components/_filters.scss

### CODE REVIEW

**Comment by Akash-Kumar-Sen** [comment]
https://user-images.githubusercontent.com/71623442/183364166-7ba4cdaf-5dde-438c-acf2-25033a3a3bfa.mp4

Preview of the output.

**Comment by lb-** [comment]
@PaarthAgarwal  have a look at this change in the context of investigating the form submission listing issue.

**Review by lb- — APPROVED** [review]
@Akash-Kumar-Sen  I ended up going the reverse, pushed a refinement to your branch if that is ok.

using 1fr on the 'listing' section and the minmax on the filtering section.

Also did a fix for the other issue mentioned about the invalid grid-column-start and the form submissions listing.

**Comment by lb-** [comment]
yep - the other thing that was needed was to go from sm to md breakpoint for the breakpoint where the content wraps into one column, there was no practical way it could all fit when the sidebar was expanded.

Thanks for your help on this!

**Comment by lb-** [comment]
@PaarthAgarwal  when you get a chance, please check out the latest main now and confirm there is no longer an issue with the form submission listings as discussed today.

**Comment by Akash-Kumar-Sen** [comment]
@lb- any update on the PR https://github.com/wagtail/wagtail/pull/8960 ?

**Comment by lb-** [comment]
Not yet - only a mere human volunteer - will get to it when I get the chance :) otherwise another core team member will in due course.

**Pull request merged**
