### PR TITLE
Fix Elasticsearch field boosting tests

### PR DESCRIPTION
**Pull request by kaedroho**
The cause was the ``_partials`` field on the test documents was getting a higher score than the ``_all`` field, so Elasticsearch was ignoring the scores of all the non-partial_match fields and two documents being checked had the same score.

I've worked around this by reducing the boost of ``_partials`` very slightly. Weirdly, this causes Elasticsearch to always use the score from the ``_all`` field (even though those scores were much lower).

### CODE REVIEW

**Comment by kaedroho** [comment]
Looks like Elasticsearch is dividing the term frequencies of all the terms in the ``_all`` field by the number of fields that are indexed into it, but this isn't happening to ``_partials`` because we added it so Elasticsearch is treating it like any other field. So if every field is indexed into both ``_partials`` and ``_all``, the score of ``_partials`` will be a lot higher than ``_all``.

**Comment by BertrandBordage** [comment]
Wow, this was so tricky to figure out… Good digging Karl, thank you!

**Comment by kaedroho** [comment]
> Weirdly, this causes Elasticsearch to always use the score from the _all field (even though those scores were much lower).

Elasticsearch seems to be storing a boost of 0.875 which might have something to do with the fact they use a 1-byte float to store it in...

**Comment by kaedroho** [comment]
Looks like the issue there is ``postgres_search`` does not implement ``order_by_relevance`` properly. Setting this parameter to ``False`` should make the search engine revert to the ordering on the passed in ``QuerySet`` but instead it's sorting by ``id`` (https://github.com/wagtail/wagtail/blob/894887e7dad9f97e42c9568d6361ce6e1bbe9d2d/wagtail/contrib/postgres_search/backend.py#L255).

I've marked this as ``expectedFailure`` for now so we can attempt to fix later.

**Comment by kaedroho** [comment]
Fixed properly by #3939

**Pull request closed without merging**
