### PR TITLE
rst to md migration of docs/reference

### PR DESCRIPTION
**Pull request by SilvestriStefano**
Hello, 
I have started to migrate the rST files to MD files as requested in issue #8383 

In the page `project_template` there was a glossary but [documentation guidelines](https://docs.wagtail.org/en/latest/contributing/documentation_guidelines.html#glossary) said to remove it and use bullets instead. That's what I did.
I have also changed the ``tip`` call-out to a ``note`` call-out
**before**
image
**after**
image

***DONE***
- [x] index.md
- [x] project_template.md
- [x] management_commands.md
- [x] hooks.rst
- [x] jinja2.rst
- [x] settings.rst
- [x] signals.rst

***TODO***

_Please check the following:_
-   [x] Does the code comply with the style guide?

### CODE REVIEW

**Comment by SilvestriStefano** [comment]
@lb- hi, yes I am still working on it. I will try to finish as soon as possible.

**Comment by lb-** [comment]
@SilvestriStefano  thanks for reaching out to get feedback and really appreciate the screenshots.

In general - the documentation guidelines advise to avoid too much complex RST usage in the new markdown docs - https://docs.wagtail.org/en/stable/contributing/documentation_guidelines.html#other-restructuredtext-syntax-and-sphinx-directives

However, I do agree in this case it would be nice to preserve the layout if possible.

We do not want to add more plugins though, as this adds more dependencies to the docs.

Based on that, I think you can go with either;

1. Use the field list approach - it seems to render well, does not require a plugin and the syntax is not too complex.
2. Just use a simple list approach with the 'term' being strong and putting the 'definition' on the same line after it. **preferred** - this is a visual change but aligns with our goal of keeping it simple for documentation maintenance.

e.g. using bold. 

```markdown

The following arguments are emitted for both signals:

- **sender** - The page ``class``.
- **instance** - The specific ``Page`` instance.
- **parent_page_before** - The parent page of ``instance`` **before** moving.
- **parent_page_after** - The parent page of ``instance`` **after** moving.
- **url_path_before** - The value of ``instance.url_path`` **before** moving.
- **url_path_after** - The value of ``instance.url_path`` **after** moving.
- **kwargs** - Any other arguments passed to ``pre_page_move.send()`` or ``post_page_move.send()``.
```

another approach is using backticks - see `docs/extending/custom_account_settings.md`

```markdown

The following arguments are emitted for both signals:

-  `sender` - The page ``class``.
-  `instance` - The specific ``Page`` instance.
-  `parent_page_before` - The parent page of ``instance`` **before** moving.
-  `parent_page_after` - The parent page of ``instance`` **after** moving.
-  `url_path_before` - The value of ``instance.url_path`` **before** moving.
-  `url_path_after` - The value of ``instance.url_path`` **after** moving.
-  `kwargs` - Any other arguments passed to ``pre_page_move.send()`` or ``post_page_move.send()``.

```

**Comment by SilvestriStefano** [comment]
@lb- 
Hi, 
thanks for the response. 
Just to clarify: the two MySt extension do not have to be installed, they come when installing myst-parser. All I have to do is add those lines in the `conf.py`.

in the `hooks` page there is usage of both **definition lists** and of **field lists**  and using those extensions would maintain the layout.
image

image


If you prefer I proceed without these extensions, I'll do that.

**Comment by lb-** [comment]
In the spirit of the current Wagtail docs guidelines - let's go without the advanced features - a simple list will be fine as already used in many other places (markdown or RST).

**Comment by SilvestriStefano** [comment]
@lb- 
Ok. I will do that.

**Comment by SilvestriStefano** [comment]
@lb- 
Hello again, 
I have migrated all the files from rst to md but with the last commit apparently there is a conflicting file that I don't understand.
What should I do?

**Review by lb- — COMMENTED** [review]
@SilvestriStefano thank you again for taking the time to contribute, this was super close but I had to do a few fixes, here are some notes for next time:

* Lots of content had `>` before each line - I see why that was done (to emulate the inset) but in our goals of keeping the documentation features used simple it is best to remove this.
* Preferred way of doing inline refs (links) is `[](some_reference)` not `{ref}some_reference`
* Reminder to remove the double backticks as markdown only needs one
* For the most part, `{doc}` refs are not needed and simple links are fine
* There was an odd issue where the `signals` ref and doc auto-ref were in conflict, I have worked around this but it should become a non-issue once all docs are in markdown.

I have fixed these up locally while cleaning up and will merge in shortly.

**Comment by lb-** [comment]
@SilvestriStefano  all merged in - thanks again!
I have added your name as `Stefano Silvestri` to the contributors list, please let me know if you want a different name listed.

**Comment by SilvestriStefano** [comment]
@lb- 
I'm happy to help and thank you for the feedback!

**Pull request merged**
