### PR TITLE
Updated a circle border on the brand logo

### LINKED ISSUE #11449: Contrast themes / WHCM support improvements
Issues reported by @albinazs as part of [WCAG 2.2 accessibility audit](https://github.com/wagtail/wagtail/discussions/11180) – still _to be confirmed_.

## Working on this

Those issues are _unconfirmed_ – please only pick these up unless you’re comfortable with [forced-colors mode / WHCM](https://developer.chrome.com/docs/devtools/rendering/emulate-css), and able to understand which area of Wagtail is mentioned. The first step will be to confirm the issues via comments here, then devise a fix.

### Tooltips

- [ ] Broken design for data-w-tooltip human readable date (no border, solid square instead of an arrow)
- [ ] Broken design for tooltips for sidebar-slim menu items (no border, solid square instead of an arrow)
- [ ] Absent border for the Actions tooltip
- [ ] Absent border for the Status tooltip
- [ ] Absent border for the Actions, Status, Preview, Comments, History and Live tooltips on the editor's header
- [ ] Absent border for the Actions tooltip on the Image

### Menus and menu items

- [ ] No circle around Wagtail brand logo
- [ ] Button and links styled as buttons have different appearance on the main menu as well as menu footer which is confusing
- [ ] No visible state change on hover for menu and menu footer items
- [ ] Low contrast for submenu header icons
- [ ] No visible right border for the submenu header & drawer, that separates visually menu from the page content
- [ ] Unnecessary 3px solid right and left borders on all the menu items
- [ ] No visual indication of the chosen parent menu item when submenu is opened (except Highlight color on the extra left & right borders that seems to work only for some of the items like Pages and Bread categories)

### Side panels

- [ ] No visible state change on hover for the minimap items including Expand-right icon. Same goes for the most of every form-side panel's items
- [ ] Unnecessary 3px solid left border on the minimap items
- [ ] Broken design for the form resize grip for all form panels (square on the right instead of 2 thin central lines)

### Light theme only

- [ ] invisible Admin arrow icon in both open and closed states

### Dark theme only

- [ ] 'Warning' icon has very low contrast
- [ ] disappearing 'plus' sign on the comment icon on hover
- [ ] very low contrast for the Close button on the 'Change privacy' and 'Set schedule' dialogs on the History panel

### Other

- [ ] No visible hover effect for almost all the items on the dashboard
- [ ] Absent border around the language label
- [ ] Inconsistent focus appearance for the Actions dropdown items on the footer - thick ButtonText outline instead of the Highlight like for the rest of the components on the page
- [ ] No visible state change on hover for the date picker's days and light & left months navigation arrows
- [ ] Inconsistent focus appearance for the Draftail containers (ButtonText border instead of a Highlight one like on Text inputs
- [ ] Inconsistent appearance of the plus buttons on hover: Highlight border for the combobox and Green background for adding a block respectively
- [ ] Weird hover appearance for the combobox option items (background change)

### PR DESCRIPTION
**Pull request by nandini584**
Fixes #11449 

I have made some improvements to the design for Menu and Menu-Items. 
The border was added to the brand logo and extra 3px margins were removed from both left and right.

### CODE REVIEW

**Comment by lb-** [comment]
Thanks for taking the time to prepare this PR @nandini584  do you mind including a screenshot of before/after in your PR description - it will help with reviewing.

Also, a reminder to run your formatter on any new code changes. `npm run format` should fix this, or you can look at installing the pre-commit hooks. https://docs.wagtail.org/en/stable/contributing/developing.html#automatically-lint-and-code-format-on-commits

**Comment by nandini584** [comment]
I had some problem with my previous repo throwing an error so I had to reclone it and create another pr, 
[https://github.com/wagtail/wagtail/issues/11449](https://github.com/wagtail/wagtail/issues/11449)

**Comment by lb-** [comment]
Ok. I'll assume this PR can be closed then as https://github.com/wagtail/wagtail/pull/11741 is the newer one.

**Comment by nandini584** [comment]
Yup thanks.

**Pull request closed without merging**
