### PR TITLE
User-defined Snippet Icons

### PR DESCRIPTION
**Pull request by dkirkham**
This Draft PR is an initial implementation of User-defined Snippet Icons, which partially addresses #9652.

It is draft as there are potential changes to the way icons are specified within models, and consequently there are no tests or documentation included. There are also some possible code optimisations (eg. a mixin for the `get_header_icon()` method.)

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [x] For new features: Has the documentation been updated accordingly?

This new capability can be tested by creating an instance of BakeryDemo, and adding `admin_icon = "icon_name"` properties into the models, for instance, in `bakerydemo/breads/models.py`.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by thibaudcolas** [comment]
Looking cool @dkirkham! Do you think this is ready for review or are you intending to work on this further?

**Comment by dkirkham** [comment]
Hi @thibaudcolas, certainly I’ll do more, but I was hoping for some debate and a decision (maybe in #9652 where I reference several options) about the best way to specify the desired icon. Then I can prepare docs and tests accordingly and avoid too much rework.

**Comment by dkirkham** [comment]
Hi @thibaudcolas and @laymonage, I've updated this PR to include tests and documentation. The snippet icon is still specified via the `admin_icon` in the snippet class, but I changed the workings so that this is obtained in exactly one utils function so can be changed relatively easily.

Github was reporting a merge conflict, so I attempted a rebase - though I'm no so sure that worked so well. If this PR is now too difficult to review, I'm happy to submit a fresh PR.

**Comment by zerolab** [comment]
@dkirkham this is now showing 697 changed files and 143 commits, so the rebase didn't quite work.
Perhaps best to open a fresh PR?

**Comment by dkirkham** [comment]
@zerolab, I have prepared a new PR, #9804. `git diff` tells me the two are identical, but github begs to differ.

**Pull request closed without merging**
