### PR TITLE
Change `master` to `main`

### PR DESCRIPTION
**Pull request by nmorduch**
This PR is to accompany renaming the `master` branch to `main`, as per [RFC 63](https://github.com/wagtail/rfcs/blob/master/text/063-avoid-insensitive-language.md)

### CODE REVIEW

**Review by thibaudcolas — CHANGES_REQUESTED** [review]
Thank you @nmorduch, this is looking great.

I spotted one additional line to change: https://github.com/wagtail/wagtail/blame/master/docs/conf.py#L307

After that one additional change gets done, I think we’re good to go.

And reviewed our wiki. There are three pages on there we’ll need to update once the change is made:

- https://github.com/wagtail/wagtail/wiki/Creating-a-new-Wagtail-release
- https://github.com/wagtail/wagtail/wiki/Nightly-testing-of-official-plugins
- https://github.com/wagtail/wagtail/wiki/StreamField-blocks-API

**Comment by nmorduch** [comment]
Updated!

**Review by thibaudcolas — APPROVED** [review]
Nice!

Confetti falling

**Comment by thibaudcolas** [comment]
FYI I’ve updated the wiki pages mentioned above.

**Pull request merged**
