### PR TITLE
Reset search promotions sequence after copying table content

### PR DESCRIPTION
**Pull request by RealOrangeOne**
_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?

We've seen a few cases in production of search being broken due to a corrupt sequence `wagtailsearchpromotions_query_pkey`. Resetting the sequence fixes the issue.

I suspect the issue is around manually inserting rows into a table, where the primary keys may not be continuous. We insert values manually, including an explicit pk, but don't ensure the sequence is set to a value higher than the largest pk.

An example from a site:
```
=> select max(id) from wagtailsearchpromotions_query;
  max
--------
 270690
(1 row)

=> select count(*) from wagtailsearchpromotions_query;
 count
-------
 93411
(1 row)
```

There are far fewer rows than is the largest id, which would result in the sequence being set to the wrong value.

See also https://code.djangoproject.com/ticket/17415

The code is lifted from [`manage.py sqlsequencereset`](https://github.com/django/django/blob/c74a6fad5475495756a5bdb18b2cab2b68d429bc/django/core/management/commands/sqlsequencereset.py). `sequence_reset_sql` is a noop on certain database platforms (including SQLite), which might have helped make this issue harder to find.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
@gasman I think this might want backporting to 5.0 too, as I think that's when the issue was introduced. Because it's in a migration, it's not enough to just change the code. If people have upgraded to 5.0 already, they'd have hit this issue, at which point fixing it in 5.1 will only solve it for those who jump straight from 4.x to 5.1.

**Comment by gasman** [comment]
Thanks @RealOrangeOne! I agree it's worth backporting this to 5.0 too.

Just a suggestion: any reason why we shouldn't run this step in a new migration (which would be migration 0006), so that we can be sure it gets run even on databases that have already applied the broken migration 0004? I'm thinking it's possible that people might have deployed 5.0 without noticing the breakage, or _did_ notice it but reasonably assume that upgrading to a later point release and running `./manage.py migrate` will fix it?

**Comment by RealOrangeOne** [comment]
I can't think of a good one - I've moved it to a new migration.

**Review by gasman — APPROVED** [review]
LGTM, thanks!

**Comment by gasman** [comment]
Merged and backported to 5.0.x and 5.1.x.

**Pull request merged**
