### PR TITLE
Fix #11600 Eleasticsearch7 empty admin search gives 500

### LINKED ISSUE #11600: Eleasticsearch7 empty admin search gives 500
### Issue Summary

When in the admin panel you click on the search icon you get a 500 error. Or when you clear the search input on the global search page you wel see 500 response in network tab.

full stack trace:

```
  File "/home/userapp/env/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/userapp/env/lib/python3.9/site-packages/wagtail/admin/views/generic/permissions.py", line 32, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/userapp/env/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/userapp/env/lib/python3.9/site-packages/wagtail/admin/views/pages/search.py", line 131, in get
    return super().get(request)
  File "/home/userapp/env/lib/python3.9/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "/home/userapp/env/lib/python3.9/site-packages/wagtail/admin/views/pages/search.py", line 155, in get_queryset
    for content_type_id, count in self.all_pages.facet(
  File "/home/userapp/env/lib/python3.9/site-packages/wagtail/search/backends/elasticsearch5.py", line 686, in facet
    body = self._get_es_body()
  File "/home/userapp/env/lib/python3.9/site-packages/wagtail/search/backends/elasticsearch5.py", line 715, in _get_es_body
    body = {"query": self.query_compiler.get_query()}
  File "/home/userapp/env/lib/python3.9/site-packages/wagtail/search/backends/elasticsearch5.py", line 582, in get_query
    inner_query = self.get_inner_query()
  File "/home/userapp/env/lib/python3.9/site-packages/wagtail/search/backends/elasticsearch6.py", line 243, in get_inner_query
    return self._compile_plaintext_query(self.query, fields)
  File "/home/userapp/env/lib/python3.9/site-packages/wagtail/search/backends/elasticsearch6.py", line 142, in _compile_plaintext_query
    match_query = {"query": query.query_string}
AttributeError: 'MatchAll' object has no attribute 'query_string'
```

### Steps to Reproduce

1. Have project with elasticsearch7 backend configured
2. Login to admin
3. Click on the search icon

### Technical details

-   Python version: 3.9.18
-   Django version: 4.2.9
-   Wagtail version: 5.2.2

### Possible fix

The fix i tried locally that seems to work is change this line: https://github.com/wagtail/wagtail/blob/stable/5.2.x/wagtail/search/backends/elasticsearch6.py#L239 to:

```python
if len(fields) == 0 or not isinstance(self.query, PlainText):
```

### PR DESCRIPTION
**Pull request by krukas**
Fixes #11600
Backport PR https://github.com/wagtail/wagtail/pull/11601 (5.2)

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by gasman** [comment]
I don't think this is a valid fix, sorry. The intended behaviour as per 899737012669ec975634dde6bd370a352a34209e is for an empty search to perform a 'match all' query. This fails on the Elasticsearch backend because the autocomplete search does not implement anything other than PlainText queries. This PR changes that behaviour from throwing an error to silently ignoring it and returning no results - however, in this case we want it to handle the 'match all' and return all results. Effectively, this PR as it stands is formalising the incorrect behaviour, rather than fixing it.

**Comment by krukas** [comment]
@gasman You are right for the MatchAll and can add an extra condition for that. Doe we still wanne fail if query is given that is not PlainText or MatchAll, maybe with better Exception message? Or doe we want to silene that error and give back no results?

**Comment by gasman** [comment]
@krukas Best to fail with a meaningful exception for unrecognised query types, I think.

**Comment by krukas** [comment]
@gasman For know i have added a `NotImplementedError` that query is not supported.

**Comment by gasman** [comment]
Merged in ef06e48c7f5fca3dfdcc876c3f18db81244f8d36 (main) / 87684324a5db52a43c82933cc1971d4f6d57fc6f (stable/6.0.x).

**Pull request closed without merging**
