### PR TITLE
Upgrade javascript tooling to Node 10

### PR DESCRIPTION
**Pull request by jjnypr**
(props to @kimlarocca for figuring out the sequencing of the build commands/includes had to be changed) 

Resolves issue #5994

### CODE REVIEW

**Comment by gasman** [comment]
As noted on #5994, the old build script does work on Node 8, so it sounds like the effect of this change is to upgrade our tooling to Node 10, which is certainly no bad thing :-)

If that is indeed the case, `.nvmrc` and `docs/contributing/developing.rst` also need to be updated, possibly along with other bits of our infrastructure (Travis and CircleCI, and the [vagrant-wagtail-develop](https://github.com/wagtail/vagrant-wagtail-develop) / [docker-wagtail-develop](https://github.com/wagtail/docker-wagtail-develop) scripts).

**Comment by jjnypr** [comment]
@gasman I've made the changes w/in the repo that I can find. Couldn't figure out where I could change the version of Node used by Travis. 

here are the other PRs:
https://github.com/wagtail/vagrant-wagtail-develop/pull/26
https://github.com/wagtail/docker-wagtail-develop/pull/9

**Comment by zerolab** [comment]
@jjnypr according to https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions-using-nvmrc, Travis should respect .nvmrc which you updated.

**Comment by gasman** [comment]
Now I come to think of it, I don't think our Travis setup deals with Node at all - since the Django-side tests don't rely on the presence of the static files, it just skips building them.

**Comment by lb-** [comment]
Awesome! thanks @jjnypr 
Note: this will resolve https://github.com/wagtail/wagtail/issues/5653

Plus it might make the babel 6/7 + Jest upgrade path a bit easier #5401

Only thoughts, any reason why we would not go to Node v 12? or even v14 (it will be the LTS by the end of the year)

**Comment by lb-** [comment]
@gasman  - I am happy to submit PRs for the development environments + test out

**Comment by gasman** [comment]
Thanks @jjnypr!

@lb- Looks like @jjnypr has beaten you to the PRs on vagrant-wagtail-develop and docker-wagtail-develop, but additional testing would be very welcome :-)

**Comment by lb-** [comment]
related develop environment PRS
https://github.com/wagtail/vagrant-wagtail-develop/pull/26
https://github.com/wagtail/docker-wagtail-develop/pull/9

**Comment by lb-** [comment]
Thanks @jjnypr  & @kimlarocca 
This has now been merged in via 6ea0cc52f37ef5f6ed27b6f357fcce1efab90495

**Pull request closed without merging**
