### PR TITLE
Use the py command from Python Launcher for Windows in tutorial

### PR DESCRIPTION
**Pull request by Julietadeboye**
_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.
Creating a pull request for [issue#9336](https://github.com/wagtail/wagtail/issues/9336) Improve explanation on getting started tutorial for Windows users

Python3.exe is not defined in windows so each time you want to run a command that includes python3 you will get the error "'python3' is not recognized as an internal or external command, operable program or batch file"
The alternative for this on windows is py -3

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Review by thibaudcolas — COMMENTED** [review]
Just to note I’m not clear this is a good change, as Django Girls uses `python3`. I’ve commented in #9336.

**Comment by Julietadeboye** [comment]
This PR has been updated

**Review by thibaudcolas — APPROVED** [review]
Thank you @Julietadeboye! I’ve updated to explicitly mention "Python Launcher for Windows", since that’s what the `py` command is called.

**Comment by Julietadeboye** [comment]
Thanks Thibaud!!!

**Comment by lb-** [comment]
Added your name @Julietadeboye to the contributors list. Thanks again for taking the time to make Wagtail better. 

https://github.com/wagtail/wagtail/commit/68f52c81549d335a5e81f9b14ad0cdefa4ea5b1e

**Pull request merged**
