### PR TITLE
Add last_published_at to Page model

### LINKED ISSUE #3578: Add 'last_published_at' field to Page model
Previously discussed in #577 and #771, but doesn't seem to have been raised as a ticket in its own right up to now. Necessary for #3565.

#3302 is related - it adds a foreign key from `Page` to the current live revision (if any), which would give you access to the revision's `created_at` date - although that isn't an exact match for last published date, because pages that go through moderation or scheduled publishing may have an actual publishing date that's some time after the revision was created.

### PR DESCRIPTION
**Pull request by gasman**
Add `last_published_at` field to Page model, and use it for the `lastmod` field of sitemap.xml. Fixes #3578 and #3565.

### CODE REVIEW

**Comment by m1kola** [comment]
There are some test failures with Elasticsearch 5. Other than that, everything looks good to me.

**Comment by gasman** [comment]
@m1kola Thanks for the review! The Elasticsearch 5 errors are happening everywhere, not just on this PR - it seems to be a configuration change that happened on Travis about a week ago :-(

**Comment by kaedroho** [comment]
Could we add a data migration with the following query?

```python
Page.objects.filter(has_unpublished_changes=False).update(last_published_at=F('latest_revision_created_at'))
```

**Comment by gasman** [comment]
@kaedroho Good idea! Will add that.

**Comment by gasman** [comment]
Rebased, and added data migration as suggested - @kaedroho / @m1kola, please can you quickly review the latest commit?

**Comment by m1kola** [comment]
@gasman All looks good to me. Feel free to merge when CI done with tests.

**Pull request merged**
