### PR TITLE
return Http404 -> raise Http404

### PR DESCRIPTION
**Pull request by dest81**
Current PR fixes error:
```
AttributeError at /<wagtailadmin>/bulk/wagtailcore/page/get/
'Http404' object has no attribute 'has_header'
```

### CODE REVIEW

**Comment by lb-** [comment]
@dest81 thankyou for submitting this fix, however it would be great to have a unit test come with it also so that we don't accidentally introduce the bug in the future again. 

Could you also update the description with a bit of info on how to reproduce the bug so we can manually test the fix. 

Thanks so much.

**Comment by dest81** [comment]
> @dest81 thankyou for submitting this fix, however it would be great to have a unit test come with it also so that we don't accidentally introduce the bug in the future again.

Sorry that I didn't get into details. [Http404 is an exception](https://docs.djangoproject.com/en/4.0/topics/http/views/#the-http404-exception) so it should be raised and not returned. I am not sure if this can or should be covered by tests. This is more like typo :). I checked other parts of the wagtail code and everywhere it is used properly.

How to reproduce:
1. install wagtail or run any existing application with installed wagtail.
2. log in to wagtail admin
3. open url `<domain_name>/<wagtailadmin>/bulk/wagtailcore/page/get/ `   

P.S. additionally to previous commit I have corrected import `django.http.response` -> `django.http`

**Comment by lb-** [comment]
@dest81 thanks for explaining how to reproduce. 

I still think we should try to get a test for this as even though it is a typo it got missed and could become a typo again. 

A good example of this is a bad rebase for a future / existing Merge request. 

Thanks so much for finding this and let us know if you can put a test in also.

**Comment by lb-** [comment]
@dest81 we are planning to get this into some previous releases I have put a basic test for this and also validated your fix as working as expected. thanks again for putting this PR up.

**Comment by lb-** [comment]
@gasman I have merged into main and also cherry picked into [2.15.x](https://github.com/wagtail/wagtail/commit/3cd7e967c157d5daf36b9dc5f37ad212b620879c) / [2.16.x](https://github.com/wagtail/wagtail/commit/8e2eaa68215409d4b778857b2428d5c1461bad93) stable branches, each with the relevant release notes.

I have hopefully done this correctly, I have not yet added the previous release notes to the main branch, happy to do if needed.

**Pull request merged**
