### PR TITLE
fix: MutationObserver in dirty form check only tests direct descendants

### PR DESCRIPTION
**Pull request by kituuu**
#11142 

I was working on this issue in which the function [isValidInputNode()](https://github.com/wagtail/wagtail/blob/main/client/src/controllers/UnsavedController.ts#L291) was checking only the current node and was failing if input is nested deep inside for e.g. if the node is <div><input/></div> this function fails.
To fix this, I added a querySelector check in addition to this to check whether any input node is present inside the current node (on which the isValidInputNode() is called)
`const isValidInputNode = (node) =>
        node.nodeType === node.ELEMENT_NODE &&
        (['INPUT', 'TEXTAREA', 'SELECT'].includes(node.tagName) ||
          node.querySelector('input, textarea, select') !== null);`
Also in the comments, @SebCorbin suggested to add some extra tests in `UnsavedController.test.js` . I have never written a jest test before this. I know my test might be wrong. Can you give me some resources so that I can understand about test and write correct required tests. 

Also, there is another way of improving this isValidInput function. By using traversing through all the childs of the node one by one to find the input element

### CODE REVIEW

**Comment by kituuu** [comment]
@lb- @SebCorbin Can you help me a bit. Sorry, I was busy with my college exams.

**Comment by kituuu** [comment]
I will try to complete it in a day or two. : )

**Comment by lb-** [comment]
I'll mark this as a draft PR. It's an easy way to indicate the PR is not really ready for a full review.

**Comment by kituuu** [comment]
Hey @lb- Ig it ready for review.

**Review by Apiraa — APPROVED** [review]

**Comment by kituuu** [comment]
@lb- 🙃

**Review by lb- — APPROVED** [review]
Thank you @kituuu  these tests are great.

I have made a few tweaks and will merge in;

1. I removed some of the comments /console logs in the tests + added more line breaks (purely cleanup items)
2. I have pulled up the node check to a class method and avoided re-declaring the valid node list twice by using `localName` https://developer.mozilla.org/en-US/docs/Web/API/Element/localName instead of `tagName` so we can just have one array of nodes as follows;

```ts
  getIsValidNode(node: Node | null) {
    if (!node || node.nodeType !== node.ELEMENT_NODE) return false;

    const validElements = ['input', 'textarea', 'select'];

    return (
      validElements.includes((node as Element).localName) ||
      (node as Element).querySelector(validElements.join(',')) !== null
    );
  }
```

I have tested this new behaviour on Chrome 124, Firefox 123 & Safari 17.1.

I also ran the previous code against the newly added tests to confirm that the tests fail on the old code (great stuff!).

Thanks again for taking the time to contribute here, this has been a long term pain point and it's great to see it's essentially a one line fix with added confidence that this will keep working in the future with unit tests.

**Comment by lb-** [comment]
Just a tip for future, it's much easier if you create a new branch for each thing you work on. This way your `main` can keep in sync with the Wagtail repo's main.

**Pull request merged**
