### PR TITLE
Addition of new "description" property to AbstractImage class

### PR DESCRIPTION
**Pull request by Chiemezuo**
This is my experimental approach on including a mandatory `image_description` in the `AbstractImage` class for the GSoC "Alt Text Capabilities" project.
This PR is a draft to discuss further modifications with mentors @Stormheg @SaptakS @thibaudcolas 

The screenshot below shows what the change would look like on the admin dashboard so far:
image

### CODE REVIEW

**Review by Stormheg — APPROVED** [review]
Test drove this with bakerydemo and it looks good to me. Great work @Chiemezuo 👍 👍 

I think the only thing left is do is to add release notes. Did you have a draft of that @Chiemezuo? Could you post them here?

**Comment by Chiemezuo** [comment]
@Stormheg This PR is just a new model field. It doesn't really change anything about the existing implementation, so there aren't upgrade considerations. Do I still need to draft a release note for it?

**Comment by lb-** [comment]
Just rebasing with release notes.

**Comment by lb-** [comment]
I'd recommend we review the wording for this message on the multiple upload.

> Please provide an image description to comply with best practices for accessibility.

However, this does not seem a blocker for this PR right now. 

@Chiemezuo  can you check this wording separately with @thibaudcolas  or @Stormheg + maybe also the usage of the error styling as this is not strictly an error. I know though that there are some issues with the colours for the warning variation of this - https://github.com/wagtail/wagtail/issues/12259

Screenshot 2024-10-11 at 4 10 36 pm

**Comment by lb-** [comment]
Merged via ff4f27b131125602cc312f50bef1fb3b2f0ac1f0

**Comment by Chiemezuo** [comment]
Hi @lb- 
Thanks a bunch for this!

**Comment by kaedroho** [comment]
There's no indication to end users what this field is for, it's also limited to 255 characters just like the title.

Could we add help text and reconsider the 255 character limit?

**Comment by Chiemezuo** [comment]
This is coming pretty late, but would we like to bring back this conversation (if that is still the case)? @kaedroho 

cc @Stormheg

**Comment by Stormheg** [comment]
Does @wagtail/accessibility have opinions about Karl's suggestions?

**Pull request merged**
