### PR TITLE
Fix tests to work across all search backends

### PR DESCRIPTION
**Pull request by gasman**
Early stages of addressing #9901, to make tests work against all search backends, not just the fallback one. So far it looks like the root causes of the failures are quite diverse, and it's not going to be a straightforward case of applying one fix everywhere.

Incorporates #10210 and #10211

### CODE REVIEW

**Comment by gasman** [comment]
All remaining test failures against SQLite are legitimate bugs / omissions in the SQLite backend:

* #9903
* #10217
* #10218

**Comment by gasman** [comment]
All tests are hopefully now working against the postgresql backend, except for [this one](https://github.com/wagtail/wagtail/blob/dc48dcce8a0480bf09629a16a5a3583d2234788e/wagtail/tests/test_page_queryset.py#L860-L868) which fails to annotate the queryset just like SQLite does, presumably because it's not running an actual search.

**Comment by gasman** [comment]
The first test failure I looked at on MySQL (`wagtail.api.v2.tests.test_documents.TestDocumentListing.test_search_for_james_joyce`) succeeds when TestDocumentListing is changed from a TestCase to a TransactionTestCase, which would suggest that it's not possible to query the FTS index inside the same transaction that the index entries were inserted, or something to that effect.

**Comment by gasman** [comment]
> it's not possible to query the FTS index inside the same transaction that the index entries were inserted

Looks like this is indeed the case: https://stackoverflow.com/a/37199217/1853523

Corroborated by adding the following to wagtail.search.tests.test_mysql_backend.TestMySQLSearchBackend (which is a `TransactionTestCase` so does not have any built-in transactions of its own):

    def test_simple(self):
        with transaction.atomic():
            models.Book.objects.create(title="Matilda", publication_date=datetime.date(1995, 1, 1), number_of_pages=100)
            results = self.backend.search(
                PlainText("matilda"), models.Book.objects.all()
            )
            self.assertSetEqual({r.title for r in results}, {"Matilda"})

This returns no results from the search, but does succeed if the `with transaction.atomic()` is removed.

**Comment by gasman** [comment]
The failing tests on MySQL are now the same ones as on Sqlite (I think...): partial matches / autocompletion, and annotate_score.

**Comment by gasman** [comment]
The test suite is now "fixed" in the sense that it correctly reports the working and broken functionality of each backend, so I'm declaring this done. We can't switch to the real tests until the relevant bugs are fixed, so I've now reverted that change (a1134fe0b7c5666cd084992abef8ac0b702d003d) to allow this to be merged as an internal cleanup PR.

**Review by laymonage — APPROVED** [review]
Looks good to me, thanks for breaking down the commits!

**Comment by gasman** [comment]
Merged in f88796b3dd + parents

**Pull request closed without merging**
