### PR TITLE
Include wagtail-factories as part of wagtail.test.utils

### PR DESCRIPTION
**Pull request by gasman**
As per https://github.com/wagtail/wagtail/pull/10296#issuecomment-1490161209 - include our own copy of wagtail-factories in `wagtail.test.utils` so that we don't have to deal with side effects of the circular dependency between wagtail and wagtail-factories.

### CODE REVIEW

**Review by laymonage — APPROVED** [review]
Seems OK to me. Though I wonder if it'd be better to make it a submodule so it's easier to update, or would that only be a hassle in getting a dev environment set up (not to mention the inclusion of other files e.g. tests)?

**Comment by gasman** [comment]
I'm not really a fan of submodules at the best of times - they're fiddly to maintain and require you to remember the subtly different options for `git clone` and so on...

In this case, given that I've had to tweak the code slightly to deal with different import paths and linting, I'm not sure it would work anyhow.

**Comment by laymonage** [comment]
Yeah I agree it does add friction when doing git operations, which might also require us to update our CI setup. Let's not bother then 👍 

> In this case, given that I've had to tweak the code slightly to deal with different import paths and linting, I'm not sure it would work anyhow.

It would probably work if you push those changes to your fork and use the ref for the submodule. You can rebase every time wagtail-factories upstream gets updated, and update the submodule ref. I imagine it would be easier merging wagtail-factories updates that way compared to (I assume) copying the changes manually to here, but likely not worth the added faff of submodules.

**Comment by gasman** [comment]
Merged in 9e4226dd61145cc413cb83d46d45b81a0ecdf8b1

**Pull request closed without merging**
