### PR TITLE
Add ability to make keyboard shortcut Global

### LINKED ISSUE #11844: Add ability to make a keyboard shortcut global with the Stimulus `KeyboardController`/`w-kbd`
### Is your proposal related to a problem?

Currently, the global shortcuts for saving the page or toggling the preview pane change behaviour when you are focused on a text field.

Screenshot 2024-04-13 at 12 30 27 pm

For example, when editing a page, `cmd + s` will save the page normally (as in save the new edited page to the CMS database) but if you are focused on a text input field it will fall-back to the browser behaviour and try to save the HTML of the current page to your downloads folder.

Screenshot 2024-04-13 at 12 33 06 pm

Similarly, the `cmd + p` will try to print the page when focused on a text input instead of toggling the preview pane.

Screenshot 2024-04-13 at 12 32 57 pm

### Describe the solution you'd like

I have assumed we do not want to avoid conflicting shortctuts with the browser, the `cmd+s` and `cmd+p` usage conflicts with the browser's normal behaviour. This is probably OK as the user is very unlikely to mean 'save html to the desktop' and 'print the view', plus these shortcuts have been in use for many years so we do not want to change that.

Instead, I recommend we enhance the newly introduced ( https://github.com/wagtail/wagtail/pull/11740 ) Stimulus `KeyboardController` to allow for a 'scope' to be set to global.

Introducing a new Stimulus value `scope` as a String would allow the current behaviour to be defaulted to an empty string and allow for a new `global` scope to be introduced as part of this change.

#### Example of current state

```html
<button type="submit" class="button action-save" data-controller="w-kbd" data-w-kbd-key-value="mod+s">
    Save draft
</button>
```

#### Example of proposed usage

```html
<button type="submit" class="button action-save" data-controller="w-kbd" data-w-kbd-key-value="mod+s" data-w-kbd-scope-value="global">
    Save draft
</button>
```

#### Code approach (suggested)

We would add a new package https://www.npmjs.com/package/bind-mousetrap-global that is the recommended MouseTrap way to do this.

```diff
# ... other imports
++import addGlobalBinds from 'bind-mousetrap-global';
++
++addGlobalBinds(Mousetrap);

# ... other stuff
export class KeyboardController extends Controller<
  HTMLButtonElement | HTMLAnchorElement
> {
  static values = {
    key: { default: '', type: String },
++    scope: { default: '', type: String },
  };

  /** Keyboard shortcut string. */
  declare keyValue: string;
++  /** Scope of the keyboard shortcut, defaults to the normal MouseTrap (non-input) scope. */
++  declare scopeValue: '' | 'global';

# ... other stuff
  keyValueChanged(key: string, previousKey: string) {
    if (previousKey && previousKey !== key) {
      Mousetrap.unbind(previousKey);
    }

--    Mousetrap.bind(key, this.handleKey);
++    if (this.scopeValue === 'global') {
++      Mousetrap.bindGlobal(key, this.handleKey);
++    } else {
++      Mousetrap.bind(key, this.handleKey);
++    }
  }
}
```

### Describe alternatives you've considered

* As noted above, we could avoid risky global keyboard shortcuts but that seems unhelpful.
* We could leave this as is but as we want to communicate keyboard shortcuts more I recommend we make the behaviour the same for suitable shortcuts.

### Additional context

* See https://github.com/wagtail/wagtail/pull/11740 for the addition of the Stimulus controller approach
* See https://github.com/wagtail/wagtail/issues/3949 for the main issue covering the longer term goals for keyboard shortcuts

### Working on this

* Anyone can contribute to this.
* JavaScript unit tests are a must for this new behaviour
* All existing `mod+s` (save) and `mod+p` preview panel shortcuts MUST be updated to use this new behaviour.
* View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

### PR DESCRIPTION
**Pull request by NXPY123**
Fixes #11844 

Adds the ability to make a keyboard shortcut global using `bind-mousetrap-global` and adding a `scope` Stimulus value.

### CODE REVIEW

**Comment by NXPY123** [comment]
I had to do:
```python
import 'mousetrap/plugins/global-bind/mousetrap-global-bind';
```

instead of :
```python
import addGlobalBinds from 'bind-mousetrap-global'

addGlobalBinds(mousetrap)
```

because it kept giving this error:
```bash
client/src/controllers/KeyboardController.ts:63:17 - error TS2339: Property 'bindGlobal' does not exist on type 'MousetrapStatic'.
```

Also when I press the shortcut the second time immediately after the first, it also triggers the browser shortcut set (for example: if I press mod+P twice rapidly, it triggers `Print`). Wouldn't this be undesirable?

**Comment by lb-** [comment]
Thanks @NXPY123 I'll try to review this soon, I have flagged for 6.1 as I think this would be good to get in alongside the other keyboard shortcuts improvements.

**Review by lb- — APPROVED** [review]
This works great, incredible stuff here @NXPY123  - your unit tests added are great also.

I like your approach to use the built in plugin for the Mousetrap bind global, as such you do not need to install the package.json package at all. I will remove this when merging though.

The other change I have done is ensure the `mod+p` one is also global.

The nice thing about this is that if we adopt a different (non-mousetrap) library in the future we have a solid suite of tests to support up that migration.

**Comment by NXPY123** [comment]
> This works great, incredible stuff here @NXPY123 - your unit tests added are great also.
> 
> I like your approach to use the built in plugin for the Mousetrap bind global, as such you do not need to install the package.json package at all. I will remove this when merging though.
> 
> The other change I have done is ensure the `mod+p` one is also global.
> 
> The nice thing about this is that if we adopt a different (non-mousetrap) library in the future we have a solid suite of tests to support up that migration.

Thank you so much! If there are more issues to work on I'll be glad to take them up!

**Pull request merged**
