### PR TITLE
Documentation for upload_to method

### PR DESCRIPTION
**Pull request by Dharma-09**
- issue #2601 Documentation for image upload_to Methods
Here is referencing which i use :\
=> [https://docs.djangoproject.com/en/4.0/topics/http/file-uploads/](url) 
=>[https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html](url).

@lb-  You can review it now 🚀.Let me know if anymore changes required.

### CODE REVIEW

**Review by lb- — CHANGES_REQUESTED** [review]
@Dharma-09 thanks for taking the time to submit this PR.

* Please use the new markdown syntax for any new docs - https://docs.wagtail.org/en/stable/contributing/documentation_guidelines.html#id1
* This reads like it is a primer on `upload_to` but the Django docs already cover this https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.FileField.upload_to
* Instead, I think the goal of the original issue raised was to document that `AbstractImage` and `AbstractRendition` support a method `get_upload_to` which can be on the class when you are using a custom image model.
* This is a great start but we need to document the Wagtail feature (the method on those abstract models) and probably just reference the Django docs for how `upload_to` actually works.
* Also, it needs to be clear that this is only available when you have a custom image model https://docs.wagtail.org/en/stable/advanced_topics/images/custom_image_model.html

**Comment by lb-** [comment]
Note: rebasing on master should resolve the CI issues, remember you will need to force push to your remote branch.

**Comment by Dharma-09** [comment]
Ok ,I will changes in pull request which you mentioned.Thanks @lb- for clarifying me.

**Comment by lb-** [comment]
No problems. Thanks for being willing to give it another go.

**Comment by MaryAyobami** [comment]
> Ok ,I will changes in pull request which you mentioned.Thanks @lb- for clarifying me.

Hello Dharma, are you still moving forward with the changes you suggested?
I'd like to contribute if you are not

**Comment by MaryAyobami** [comment]
> > Ok ,I will changes in pull request which you mentioned.Thanks @lb- for clarifying me.
> 
> Hello Dharma, are you still moving forward with the changes you suggested? I'd like to contribute if you are not

@Dharma-09

**Comment by lb-** [comment]
@MaryAyobami  if you are still keen on picking this up and finishing it off - go for it.

**Comment by lb-** [comment]
Closing in favour of newer PR for the same issue https://github.com/wagtail/wagtail/pull/11505

**Pull request closed without merging**
