### PR TITLE
fix storybook (pattern library) tabs data

### LINKED ISSUE #9092: Tabs in storybook are broken
Tabs are no longer appearing in storybook. The console is throwing errors.

Screenshot from 2022-08-26 22-44-21

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

-   Wagtail version: Latest main branch
-   Browser version: Chrome 98 (Edge on Ubuntu)

### PR DESCRIPTION
**Pull request by lb-**
- fixes #9092

Screen Shot 2022-08-29 at 8 48 47 pm

### CODE REVIEW

**Comment by lb-** [comment]
no idea why the UI tests are failing from this change - looks like a timeout issue.

```
 FAIL  client/tests/integration/groups.test.js (7.551 s)
  ● Groups › axe

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

       8 |   });
       9 |
    > 10 |   it('axe', async () => {
         |   ^
      11 |     await expect(page).toPassAxeTests({
      12 |       exclude: '.skiplink, .sidebar__collapse-toggle, #wagtail-sidebar',
      13 |     });

      at groups.test.js:10:3
      at Object.<anonymous> (groups.test.js:1:26)

 PASS  client/tests/integration/users.test.js

Test Suites: 1 failed, 1 skipped, 4 passed, 5 of 6 total
Tests:       1 failed, 4 skipped, 12 passed, 17 total
Snapshots:   0 total
Time:        26.808 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wagtail@1.0.0 test:integration: `./client/tests/integration/node_modules/.bin/jest --config ./client/tests/integration/jest.config.js "--runInBand" "--reporters=default" "--reporters=jest-junit"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wagtail@1.0.0 test:integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2022-09-06T10_03_42_805Z-debug.log


Exited with code exit status 1

```

**Comment by lb-** [comment]
Rebased.
Note @thibaudcolas  we will need this in before we start looking at moving the Tabs to Stimulus controllers + would be good to have our storybook pattern library working again for tabs.

**Comment by lb-** [comment]
I'll rebase this and probably just merge in - it's a small change and this is blocking us testing some other storybook items.

**Review by laymonage — APPROVED** [review]
Haven't checked the storybook as I couldn't get it to run locally, but I'm familiar with the difference between `visible_children` and `visible_children_with_identifiers` and the fact that we now use the latter for tabs, so I think this change makes sense

**Comment by lb-** [comment]
Thanks @laymonage  - appreciate the quick review.

The other context is that Thibaud is getting the storybook functional again + getting it to be set up in the CI so hopefully this will add to the test cases once working again.

https://github.com/wagtail/wagtail/pull/10089

**Pull request merged**
