### PR TITLE
Bugfix 11306 updating modal close

### LINKED ISSUE #11306: New Dialog (modal) does not visibly show a close button if there is no message
### Issue Summary

While exploring the Dialog templates I have found that the close button does not show (it renders but is not visible) when there is no message declared in the Dialog.

From what I can see, this will only impact admin use for a small edge case. Models in workflow that do not have a latest revision, probably snippets could be set up this way or manual imports of Pages without setting a latest_revision.

This is visible in the Styleguide page though.

Screenshot 2023-12-05 at 8 38 30 pm

### Proposed solution

We could look at making the icon use the default colour (`theme('colors.icon-primary')`) and then override this when there is a message. 

1. Update the default colours in client/scss/components/_dialog.scss
2. Set a different colour either with Tailwind classes or a custom class in wagtail/admin/templates/wagtailadmin/shared/dialog/dialog.html

Something like this...

```html
        <div class="w-dialog__overlay" data-action="click->w-dialog#hide"></div>
        <div class="w-dialog__box">
            <button type="button" class="w-dialog__close-button{% if message_heading and message_icon_name %} w-text-grey-600{% endif %}" aria-label="{% trans 'Close dialog' %}" data-action="w-dialog#hide">
                {% icon name='cross' classname="w-dialog__close-icon" %}
            </button>
```

### Steps to Reproduce

1. In a new Wagtail project, install the Styleguide app
4. Navigate to the styleguide page via the settings menu - http://localhost:8000/admin/styleguide/
5. In the dialogs section, trigger the 'Simple dialog'
6. Expected: Close button should be visible
7. Actual: Close button is there (can be tabbed to) but is not visible

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

-   Python version: 3.11
-   Wagtail version: 6.0a
-   Browser version: Firefox 120 on macOS 13.5

### Additional info

The close button for the same modal used for the site facing accessibility content shows a visible close button, this has differen styling though. See https://github.com/wagtail/wagtail/blob/main/client/scss/components/_userbar.scss#L235

Screenshot 2023-12-05 at 8 39 18 pm

### PR DESCRIPTION
**Pull request by nandini584**
#11306 I have done as suggested in the proposed solution and changed the color of the cross icon to primary.

Screenshot 2023-12-09 195426

Fixes #...

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by lb-** [comment]
It looks like this code is for a different issue @nandini584

**Comment by nandini584** [comment]
It is for the close button not visible issue #11306. Could you look into it?

**Comment by lb-** [comment]
Look at the files changed tab, there's no CSS changes that I can see. The changes are for the ActionController issue instead. Unless GitHub is showing me the wrong thing.

**Comment by DevilsAutumn** [comment]
@nandini584 Looks like you've pushed the changes of https://github.com/wagtail/wagtail/pull/11319 here.

**Comment by nandini584** [comment]
I will look into it. I must have been confused with the branch.

**Comment by lb-** [comment]
Closing this PR as #11329 appears to be the replacement PR with the right code changes.

**Pull request closed without merging**
