### PR TITLE
Fixed python command for running the server

### PR DESCRIPTION
**Pull request by talkshrey**
_Please check the following:_

- [x] Do the tests still pass?[^1]
- [x] Does the code comply with the style guide? 
- [x] Run `make lint` from the Wagtail root. 
- [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
- [x] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
- [x] **Please list the exact browser and operating system versions you tested**:
          Chrome - Version 99.0.4844.84
          OS - Version 22000.556
- [ ] For new features: Has the documentation been updated accordingly?

### CODE REVIEW

**Comment by talkshrey** [comment]
It seems I am facing some issues while running circle ci frontend tests.

**Comment by lb-** [comment]
@talkshrey you may need to rebase on `main` and squash your commits, then force push to this branch

**Review by lb- — APPROVED** [review]
Thanks!

**Comment by lb-** [comment]
@talkshrey  I could really use the remote branch sorry as it had a lot of noise on it with merging in multiple times from main, maybe next type give a go at `rebase` for new branches with one change.

Nonetheless - this is merged in via f3720a76528069c038c441626961fd2ba97638ab thank you

**Pull request closed without merging**
