### PR TITLE
Add migration to replace JSON null values with empty objects in log entries' data

### PR DESCRIPTION
**Pull request by laymonage**
Follow-up to #10727 and fixes the issue mentioned in https://github.com/wagtail/wagtail/pull/8021#issuecomment-1231843290.

This is not required to fix the issue in the timestamp fix migration, but I think it'd be nice to still have this migration so all log entries's data are normalised into JSON objects. This really should've been part of the [`0068_log_entry_empty_object`](https://github.com/wagtail/wagtail/blob/main/wagtail/migrations/0068_log_entry_empty_object.py) migration anyway.

## torchbox/wagtail-torchbox result

Running this on [torchbox/wagtail-torchbox](https://github.com/torchbox/wagtail-torchbox) for demonstration.

**Note that the site was upgraded to Wagtail 3.0rc1 on 28 April 2022.** You can see that the data for the logs after that date are normalised to empty objects even before this migration.

### Before

image

### After

image

### CODE REVIEW

**Comment by laymonage** [comment]
Asking for feedback from @Scotchester if you have time, no worries if not. Just wondering what your thoughts are on this and how you got around this on your project, since you mentioned the problem in https://github.com/wagtail/wagtail/pull/8021#issuecomment-1231843290.

**Review by th3hamm0r — APPROVED** [review]
Haven't tested it, but the code looks good to me, and the comments are easy to understand :+1:

**Review by zerolab — APPROVED** [review]

**Comment by laymonage** [comment]
Thanks both, I've merged this and cherry-picked it to 5.1 as I think it's logical to have this along with the other log entry fixes.

- `stable/5.1.x`: 3179ea06bbced2828e40b2069c785e20a3e80ffe
- `main`: `3179ea06bbced2828e40b2069c785e20a3e80ffe`

**Comment by Scotchester** [comment]
Thanks for following up on this, @laymonage! I honestly don't remember how we got around it. We may not have, as that was around the time we really had to pivot to a different project.

**Pull request closed without merging**
