### PR TITLE
Documentation: Configure API to use the DRF's TokenAuthentication

### PR DESCRIPTION
**Pull request by krzysztofjeziorny**
A tutorial part how to implement the DRF's `TokenAuthentication` for API access protection.

Having to research the method myself I propose to extend the documentation with an example how to implement the `TokenAuthentication` from the Django REST Framework.

### CODE REVIEW

**Review by thibaudcolas — COMMENTED** [review]
Thank you @krzysztofjeziorny! I think this is a solid addition but I’m surprised you didn’t mention the need to add `TokenAuthentication` to `DEFAULT_AUTHENTICATION_CLASSES`. Did you skip that on purpose or should we add it as well?

**Comment by krzysztofjeziorny** [comment]
> Did you skip that on purpose or should we add it as well?

This strange feeling in the back of the head there _was_ something I didn't mention: yes, of course, the settings need

```python
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication"
    ],
}
```

**Comment by krzysztofjeziorny** [comment]
I extended the needed changes to settings.py, I hope this time it's clearer.

One could ponder how much more detail to put in this part, like mentioning how to generate the token (per manage.py command or in the Django admin).

**Comment by krzysztofjeziorny** [comment]
Yeah, more details and also a fix :)

**Review by thibaudcolas — APPROVED** [review]
All looking great, thank you! This will be available in the "latest" docs shortly, and then in the "stable" doc once Wagtail v6.3 is released in November.

Re level of details – we don’t want to go too far towards duplicating the already-good DRF docs, but I think we can certainly use one example of API access protection, and we might as well have it be "end to end".

**Pull request merged**
