### PR TITLE
Improved 'purge_page_from_cache' to purge the url for any managed language

### PR DESCRIPTION
**Pull request by kaedroho**
Rebase of https://github.com/wagtail/wagtail/pull/3024 with some cleanups

### CODE REVIEW

**Comment by kaedroho** [comment]
I noticed that in testing that, by default, this purges URLs for 86 different languages. I think we should make this feature disabled by default and you opt in to it by setting the specific languages you want to purge in the ``WAGTAILFRONTENDCACHE`` setting

**Comment by pyMan** [comment]
@kaedroho I'll be happy to go on on this, but I cannot work on it before than two months at least

**Comment by pyMan** [comment]
@kaedroho do you prefer a common settings for each defined backend or a specific setting for each backend?

**Comment by kaedroho** [comment]
@pyMan I prefer a common setting for all backends. So perhaps a separate setting is the best way to go.

**Comment by pyMan** [comment]
@kaedroho I should be done

**Comment by gasman** [comment]
Merged in b3fa09b95ed7474a3307a6afa317e0d504e2fc86 - thanks @pyMan and @kaedroho!

**Pull request closed without merging**
