### PR TITLE
Replaced twitter references in the docs with more appropriate alternatives

### LINKED ISSUE #12483: Replace Twitter references in the docs with more appropriate alternatives
### Pertinent section of the Wagtail docs

Our official tutorial, embeds docs, third-party tutorials.

### Details

While we’re X users, we’ve decided to move the bulk of our activity to other platforms ([see our announcement](https://x.com/WagtailCMS/status/1834237886285103507)). We have a few Twitter references which are out of date as the platform’s changed names, and we’d now rather switch to showcasing networks that are more relevant for us and Wagtail users (for example Facebook or LinkedIn).

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

There are a few references, so this could be separate PRs from different people:

- [ ] OEmbed docs examples
- [ ] Official tutorial
- [ ] Site settings examples

### PR DESCRIPTION
**Pull request by Srishti-j18**
Fixed #12483
-  Replace Twitter references in the docs with X
- [X] Links pointing to Twitter/X
- [X] Text references mentioning Twitter

### CODE REVIEW

**Comment by Srishti-j18** [comment]
just give me few min , There are some changes which should be done.

**Review by laymonage — CHANGES_REQUESTED** [review]
Thank you for giving it a go, but please carefully read the issue – it's not about replacing Twitter with X.

> While we’re X users, we’ve decided to move the bulk of our activity to other platforms ([see our announcement](https://x.com/WagtailCMS/status/1834237886285103507)). We have a few Twitter references which are out of date as the platform’s changed names, and **we’d now rather switch to showcasing networks that are more relevant for us and Wagtail users (for example Facebook or LinkedIn)**.

X is not a "more appropriate alternative". It's what we want to move away from.

**Comment by Srishti-j18** [comment]
Hi @thibaudcolas ,
I made some minor changes in these two PRs related to [#12483](https://github.com/wagtail/wagtail/issues/12483) in the documentation sections only. However, I also found several references in the wagtail/embeds files and others. Please let me know if those need to be updated as well.
I'm not sure how deeper you want these changes to be, so let me know your preference.

**Comment by Srishti-j18** [comment]
> Thank you for giving it a go, but please carefully read the issue – it's not about replacing Twitter with X.
> 
> > While we’re X users, we’ve decided to move the bulk of our activity to other platforms ([see our announcement](https://x.com/WagtailCMS/status/1834237886285103507)). We have a few Twitter references which are out of date as the platform’s changed names, and **we’d now rather switch to showcasing networks that are more relevant for us and Wagtail users (for example Facebook or LinkedIn)**.
> 
> X is not a "more appropriate alternative". It's what we want to move away from.

Oops, sorry! I didn’t read it properly. that mean we have to replace all the Twitter references with other URLs like Facebook, LinkedIn, Slack, etc..
I have a question, though: There’s only one Twitter URL, right? Now that we have more references, how do I know which one suits each context better?

**Comment by laymonage** [comment]
> how do I know which one suits each context better?

That's where the work is needed 🙂 You need to read the part of the docs that you'd like to change, and use your judgement to decide what other social media would be a good example. For example, the following docs for the settings module incorrectly says Twitter even though the code says Facebook:

https://github.com/wagtail/wagtail/blob/3a5ae9c6956e7bef811ee715b8b4fa0f9dd31ec2/docs/reference/contrib/settings.md?plain=1#L277

> Or all references should be there in each places .

It's not about referring to all the social media we have. It's about changing an example that uses Twitter/X into another example that uses something else.

**Comment by Srishti-j18** [comment]
> That's where the work is needed 🙂 You need to read the part of the docs that you'd like to change, and use your judgement to decide what other social media would be a good example.  

Oh ok , don't know why I am doing many mistakes today 🥲.

**Comment by lb-** [comment]
@Srishti-j18 don't worry about making mistakes, it's sometimes hard to understand the goals without all the context. 

A tip for future might be to post on the issue with a comment that's a rough suggestion of how you think it could wb fixed. 

E.g. I'm thinking that we should update this file (/path/to/file) and replace X with Y and add Z. 

This helps you and others get clarity on the original issue of the goals and quick (hopefully) feedback on ideas. 

Then, when you do a PR, you'll have already done the lightweight feedback loop. The PR can focus on the code change, not eh code AND the solution discovery. 

Not everything can work this way, but it may help you get to a PR that's good to go sooner. 

Also, it's ok if someone else picks up the issue. There's always more to be involved with, don't feel you have to rush to a PR.

**Comment by Srishti-j18** [comment]
Thanks so much for the advice, @lb-  😊 I'll definitely start sharing rough ideas on issues to get feedback early—it makes a lot of sense. I’ll also keep in mind not to rush, as there’s always more to contribute. Thanks again for the support!

**Comment by thibaudcolas** [comment]
@Srishti-j18 in addition to not really following what the issue is about, you’ve also not noticed that someone else said they were interested in working on this 😐. I’m going to close this PR so they can give it a shot.

**Comment by Srishti-j18** [comment]
> @Srishti-j18 in addition to not really following what the issue is about, you’ve also not noticed that someone else said they were interested in working on this 😐. I’m going to close this PR so they can give it a shot.

@thibaudcolas I thought since you had said [no](https://github.com/wagtail/wagtail/issues/12483#issuecomment-2442818750) to him , he might not be working on the issue, which is why I started on it. Apologies for jumping in with the silly PR. But I didn’t ignore him. Also when I knew he again interested ,I even suggested collaborating.
ok ,I’ll look for another issue.

**Comment by thibaudcolas** [comment]
@Srishti-j18 you might be confusing different issues here. I appreciate you wanting to apologise but it also reads like you’re blaming me for the problems here. I never wrote anywhere that #12483 is undecided. It’s always been:

> Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

Another contributor read that, added their comment, and their question was "is there anything else you would like to add/suggest?". That’s what I said "no" to.

Anyway, please be more attentive in the future. We’re all trying to help here but we also have a limited amount of time to dedicate to pull requests.

**Comment by Srishti-j18** [comment]
@thibaud, I apologize again. I realize I misread the comment and misunderstood your response. I’ve had a lot on my mind lately, which led to some mistakes.
I really appreciate the Wagtail community's commitment to supporting and encouraging contributors, and I respect all the help you offer. 
I’ll make sure to be more attentive in future. Thank you for your understanding.

**Pull request closed without merging**
