### PR TITLE
Elasticsearch 8 compatibility

### PR DESCRIPTION
**Pull request by leewesleyv**
# Fixes

Introduction of a new Elasticsearch backend that adds compatibility for the following changes/deprecations:

* Elasticsearch client initialisation; `verify_certs` and `http_auth` are deprecated for the hosts dictionary. 
* Elasticsearch API method calling; Positional arguments can’t be used with the new Elasticsearch API methods. The use of keyword argument is enforced.
* Index settings; The settings dictionary structure when calling the API method `create` is expected differently.
* Boosting; The boost parameter on field indices/mappings has been removed. Boost needs to be used while querying.

# To do

- [ ] All tests pass
- [x] The code complies with the style guide
- [x] Added tests to cover the new feature
- [ ] Documentation has been updated

# Nice to have?
- [ ] Improvement of boosted searching
- [ ] Additional features (release in Elasticsearch 8)

**Additional**

1. With the current state of the PR, the boosting feature is disabled **for Elasticsearch 8**. We only provide a warning to the user that boosting is not supported and ignore it in the search fields definition. I think that this needs to be implemented where we execute the query, `search()` for example. 
2. New features that have been added in Elasticsearch 8 have not been included in the PR (yet?). For now it is solely solves compatibility issues.

If you have an idea on how we should implement boosting or what kind of new features should included, please let me know. Help would be greatly appreciated!

### CODE REVIEW

**Comment by gasman** [comment]
Thanks @leewesleyv! Will try to fit in a review of this in the next few days.

The lack of query-time boosting is a known issue for Elasticsearch 6 and 7 too - @KIRA009 has expressed an interest in fixing this (https://github.com/wagtail/wagtail/issues/5422#issuecomment-1625598162) so it may well turn out that once that fix is in, we can rebase this PR on top of it and get boosting working on Elasticsearch 8 for free (or with relatively little work)...

**Comment by gasman** [comment]
Thanks again for your work on this @leewesleyv! I've now prepared a new PR at #10686, building on the new boosting implementation in #10653.

**Comment by leewesleyv** [comment]
@gasman is there anything I can help with in https://github.com/wagtail/wagtail/pull/10686?

**Comment by gasman** [comment]
If you can give it a review (either on the code level, or testing it out in a "real-world" situation) that would be very welcome! Alternatively, if you're up for investigating some of the test failures in the full test suite as mentioned there, that would be really helpful too - I suspect those aren't specifically related to Elasticsearch though.

**Pull request closed without merging**
