### PR TITLE
Adding verbosity to rebuild_references_index

### PR DESCRIPTION
**Pull request by MRZHD1**
_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [x] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by MRZHD1** [comment]
Will keep this in draft until tests can be run by someone else. Tests aren't working on my system.

**Comment by 4the4ryushin** [comment]
okay so i have figured out the issues in this PR, you haven't properly followed the  python coding  styles  guidelines 
checkout your failed backend circleci tests.
nevertheless i am gonna  fix the code and add some tests, and if you want i can add the docs lemme know

**Comment by gasman** [comment]
Thanks @MRZHD1!

The tests here are currently failing because the code isn't indented correctly - each indentation level should always be 4 spaces.
Also, I'd suggest putting the test in [wagtail/tests/test_reference_index.py](https://github.com/wagtail/wagtail/blob/main/wagtail/tests/test_reference_index.py) rather than wagtail/search/tests/test_backends.py, as it isn't related to searching.

Feel free to ask on the #new-contributors channel [on Slack](https://github.com/wagtail/wagtail/wiki/Slack) if you need help getting tests set up locally.

**Comment by zerolab** [comment]
I was going to link to the docs and point out we use `pre-commit` for automatic local linting. Turns out we don't have that in the docs.

For this, do follow the intructions in https://pre-commit.com/#installation (in short, `pip install pre-commit`, then in the repository directory `pre-commit install`, and finally `pre-commit run black --all-files` just this once on the branch)

**Comment by 4the4ryushin** [comment]
@MRZHD1  you have committed you code in your main branch, is that okay? i think you should follow the standard procedure of making a seperate branch and then committing into it

**Comment by 4the4ryushin** [comment]
@MRZHD1 could you please give me access to commit to this PR

**Comment by MRZHD1** [comment]
Yup I can do that, and yeah I realize I did that mistake now. Sorry about that!

**Comment by MRZHD1** [comment]
@gasman I just realized that my IDE was still set up for ruby which I used 2 indents, woops!

**Comment by MRZHD1** [comment]
> salty-ivy

Not sure how to add collaborators to PRs, just to repos. I added you to the repo though 🤔

**Comment by salty-ivy** [comment]
@MRZHD1 why don't you use pre-comit hook to fix it automatically, I  did made the pr

**Comment by MRZHD1** [comment]
Because it's not working on my system which is quite annoying. I don't know the issue with git, I might have to reinstall.

**Comment by salty-ivy** [comment]
Wait let me make the commit to this pr

**Comment by MRZHD1** [comment]
Alright 👍

**Comment by salty-ivy** [comment]
Wait let me make the commit and check

**Comment by salty-ivy** [comment]
@MRZHD1 there you go its all set, apparently it wasn't an issue with git i suppose you were unable to imply the pre-comit  hook , whenever it runs before commit, it make fixes and you had to commit again thats how it works, you still had some formatting missing imports and indentation problems

i have fixed all of them, and tests have passed its ready to review.

**Comment by salty-ivy** [comment]
@gasman , its ready for review, thanks a lot everyone

**Comment by gasman** [comment]
Looks like you've inadvertently removed the test again in the final commit: https://github.com/wagtail/wagtail/pull/9602/commits/b20c3ab2071478362e161674dc31037c29b8384b

**Comment by salty-ivy** [comment]
> Looks like you've inadvertently removed the test again in the final commit: [b20c3ab](https://github.com/wagtail/wagtail/commit/b20c3ab2071478362e161674dc31037c29b8384b)

i think it got removed when i fetched from @MRZHD1 main branch, no worries i would add them 
originally it was throwing an error that import statement is unused,
i would fix it after the tests

**Comment by MRZHD1** [comment]
Thank you so much for the help, and I apologize for dragging this out @salty-ivy

**Comment by MRZHD1** [comment]
I'll write the documentation later today :+1:

**Comment by salty-ivy** [comment]
@gasman okay now its working, sorry for the delay, although i am not sure where  must the tests reside 
1. wagtail/search/tests/test_backends.py OR
2. wagtail/tests/test_reference_index.py
i went with first option.

**Comment by MRZHD1** [comment]
It should be put in [wagtail/tests/test_reference_index.py](https://github.com/wagtail/wagtail/blob/main/wagtail/tests/test_reference_index.py) He mentioned this earlier

**Comment by salty-ivy** [comment]
> It should be put in [wagtail/tests/test_reference_index.py](https://github.com/wagtail/wagtail/blob/main/wagtail/tests/test_reference_index.py) He mentioned this earlier

ahhh, okayy fixing it up just a min

**Comment by salty-ivy** [comment]
done!

**Comment by salty-ivy** [comment]
> I'll write the documentation later today 👍

be sure that, you can successfully fetch the code from this branch

**Comment by MRZHD1** [comment]
I think that's it! :smile:

**Comment by gasman** [comment]
Great work, both! Merged in 748c082e01d01fda6d467228552c00046945d9ab (+parents).

**Comment by lb-** [comment]
Well done all!

**Pull request closed without merging**
