### PR TITLE
ReadOnlyPanel continued

### PR DESCRIPTION
**Pull request by brylie**
Continued from #6067 based on the discussion in #2893

### CODE REVIEW

**Comment by marteinn** [comment]
Thanks for the work so far! Some comments and ideas I have.

- Is there a reason why heading is not auto-populated as with `FieldPanel`? 
- We should follow the existing pattern in the edit_handler module and move markup to external template files.
- I think we should support more fields types (right now when I try to use a image nothing gets shown). I'm pretty certain we will otherwise get a lot of questions on this. 
- We should add tests to simplify future maintenance.

**Comment by Pomax** [comment]
gentle bump to hopefully not have this work get lost - it'd be super valuable still =)

**Comment by jeffykle** [comment]
How can I render the help_text?

**Comment by brylie** [comment]
@KalobTaulien any progress on reviewing this PR?

**Comment by thibaudcolas** [comment]
For anyone interested in this, more recent implementation: #9129

**Comment by Pomax** [comment]
@thibaudcolas I assume this can be closed, then?

**Comment by zerolab** [comment]
Let's mark this as closed. Good shout @Pomax

**Pull request closed without merging**
