### PR TITLE
Eslint cleanup no plusplus rule

### PR DESCRIPTION
**Pull request by Lovelyfin00**
Fixes `no plus plus` rule for issue wagtail/wagtail#8731
## Fix summary

- After removing the rule from the eslintrc file, I got issues from 8 files when I ran `npm run lint`

**sequences.ts file**

The fix for this file was to replace `++` with `+= 1`

**Sidebar.stories.tsx file**

- The issue on this file was the `++` in the `for i `loop. I removed the `for i` loop and replaced with `forEach` loop. But in order to get the index, I didn't want to give the arrow function in `forEach` loop two arguments, which is `value` and `index` because only the `index` was needed which would make the `value` argument redundant.
- To fix that, I imported the `range` util and gave it a min value of 0, the max value of 100 which was what was used in the previous `for i` loop.

**SidebarPanel.tsx file**

The fix was to replace `--` with `-= 1`

**BaseSequenceBlock.js file**

- Removed the `for i` loop and replaced with `forEach` loop. The set the min value for the `range` imported to variable `index` and max value to the length of the array been looped through.
- I also replaced `++` with `+= 1`
I `console.log( i )`  before replacing with `forEach` and after replacing

<table>
  <tr>
    <td>Before</td>
     <td>After</td>
  </tr>
  <tr>
    <td valign="top"></td>
    <td valign="top">
  </tr>
</table>

**ListBlock.js file**

- Removed the `for i` loop and replaced with `forEach` loop. The set the min value for the `range` imported to  `0` and max value to the length of the array been looped through.
- I `console.log( i )`  before replacing with `forEach` and after replacing to check if the results correlates

**StreamBlock.js file**

- Removed the `for i` loop and replaced with `forEach` loop. The set the min value for the `range` imported to  `0` and max value to the length of the array been looped through.

**core.js file**

The fix for this file was to replace `++` with `+= 1`

**typed_table_block.js file**

- Removed the `for i` loop and replaced with `forEach` loop. The set the min value for the `range` imported to  `0` and max value to the length of the array been looped through.
-

### CODE REVIEW

**Comment by lb-** [comment]
@Lovelyfin00 great stuff here - it's looking pretty solid to me - please mark as ready if you're happy for a full review of this. 

Thanks also for the explanation - it really helps!

**Comment by Lovelyfin00** [comment]
I would mark as ready for a review soon. I just need to add screenshots to two of the files and that's it

**Comment by Lovelyfin00** [comment]
Hi @lb- 
The result for the console was too log so I couldn't screenshot
I'll just leave it like this so you can review
I'm sure I would need to make some corrections after your review

**Comment by lb-** [comment]
@Lovelyfin00 don't worry about the failing test

> Wagtail CI / test-postgres (3.10, git+https://git

This one is checking Wagtail against the unreleased version of Django - it will sometimes fail as either a bug is introduced in Django or a potential thing for Wagtail to fix in the coming release.

**Review by lb- — APPROVED** [review]
Code changes look good - have done a bit of smoke testing locally and all is working well

Thank you!

**Pull request merged**
