### PR TITLE
Add account details page redux

### PR DESCRIPTION
**Pull request by mope**
Add an account details page that allows the user to update their username, email address, first name and last name as specified in #615. Now with added password fields!

### CODE REVIEW

**Comment by mope** [comment]
Needs tests.

**Comment by mope** [comment]
Ready.

**Comment by davecranwell** [comment]
Thanks @mope, looks good to me.

I would still have expected a password to be required to change username or email address, but this is fine for now. We could add it in a later PR.

Needs Django review.

**Comment by gasman** [comment]
This will need to be updated to handle custom user models, specifically ones without a username field,  via similar logic to #1388. We also need to consider the ability to disable this interface, e.g. for sites using LDAP.

**Comment by davecranwell** [comment]
#2293 has addressed the need for a password to change password. Any chance we can complete this now, @mope ?

**Pull request closed without merging**
