### PR TITLE
Added media queries to the summary numbers to enable responsive…

### LINKED ISSUE #3591: Summary numbers not responsive
### Issue Summary

If the summary section has items with more than 4 digits, they will overlap on small screens. The font size really should not be hardcoded like it is currently. It should be responsive and make use of media queries.

#### Desktop
screen shot 2017-05-11 at 6 38 49 pm

#### Tablet
screen shot 2017-05-11 at 6 38 37 pm

#### Mobile
screen shot 2017-05-11 at 6 38 19 pm

### Steps to Reproduce

Create 1000+ items on a summary section

### Technical details

* Python version: 3.5.2
* Django version: 1.11.1
* Wagtail version: 1.11.0
* Browser version: Chrome 58 on Mac OS X 10

### PR DESCRIPTION
**Pull request by MichaelPalmer1**
Added some media queries to make the summary numbers responsive. This fixes #3591.

### CODE REVIEW

**Comment by MichaelPalmer1** [comment]
Sure, I'll take a look. I also wanted to double check on a layout issue where the rows got misaligned when there was a mix of large and small numbers.

**Comment by MichaelPalmer1** [comment]
@jjanssen Sorry for the delay in getting back to you. To be honest, I forgot about this PR. It looks like at the current breakpoint values, 6 digit summaries will not break the layout. See the below screenshots and let me know if you still think a tweak is needed.

## 1440px width (Large Desktop)
screen shot 2017-11-21 at 5 44 14 pm

## 1024px width (Desktop)
screen shot 2017-11-21 at 5 43 59 pm

## 768px width (Tablet)
screen shot 2017-11-21 at 5 44 31 pm

## 425px width (Mobile)
screen shot 2017-11-21 at 5 44 47 pm

**Comment by jjanssen** [comment]
No problem @MichaelPalmer1 we all get caught up sometimes. I'll have a look at tomorrow and we can probably wrap-up this PR 😄

**Comment by jjanssen** [comment]
Thanks for your 1st time contribution 🎉  Your change got merged with 8b7510e  
I made a minor change to group `li:before` together, so it's consolidated to that single selector.

**Pull request closed without merging**
