### PR TITLE
Documentation - update sphinx theme to fix dark mode issues + add copy code button

### PR DESCRIPTION
**Pull request by lb-**
- Upgrade Wagtail sphinx theme to 5.3.2
- Upgrade MyST parser to 0.18.1
- https://github.com/wagtail/sphinx_wagtail_theme/blob/main/CHANGELOG.md#531---2022-10-13
- Addition of copy button to code snippets, resolve multiple issues with the dark mode theme.
- The main fix is no longer flashing the light theme when your device is on dark mode on load.

### CODE REVIEW

**Comment by lb-** [comment]
MR ready now - hopefully I have done this right, even though `sphinx_wagtail_theme` includes `sphinx_copybutton` it appears that I had to also add it to Wagtail's explicit requirements.

I will add this to 4.1 - so that the annoying flashing of dark/light content on load can be resolved.

**Comment by gasman** [comment]
Link underlines are showing as dark blue for me, in both Chrome and Firefox:
Screenshot 2022-10-14 at 16 02 18

I'm assuming this isn't intentional, given that the "After" screenshots on https://github.com/wagtail/sphinx_wagtail_theme/pull/207 still show light blue.

We also need to add `sphinx-copybutton` to `documentation_extras` in setup.py - I suggest giving it a version range of `sphinx-copybutton>=0.5,<1.0` (in both setup.py and docs/requirements.txt).

(Regarding why it isn't picking up the dependency in sphinx_wagtail_theme - is that actually defined anywhere other than requirements.txt? That won't get picked up when packaging sphinx_wagtail_theme for pypi, unless there's some config magic I'm unaware of...)

**Comment by lb-** [comment]
Thanks Matt. I'll take a look at this.

**Comment by lb-** [comment]
PR up for the link fixes https://github.com/wagtail/sphinx_wagtail_theme/pull/224 (on Sphinx Wagtail theme)

**Comment by lb-** [comment]
Accidentally deleted the original branch (well, renamed) - I did not realise it would close the PR sorry.

New PR up https://github.com/wagtail/wagtail/pull/9376

**Pull request closed without merging**
