### PR TITLE
Fix for: Not allowed extension not showing in the error message #11802

### LINKED ISSUE #11802: Not allowed extension not showing in the error message.
### Issue Summary

Not allowed extension showing as blank when using the WAGTAILDOCS_EXTENSIONS setting.

### Steps to Reproduce
1. Start a new project with `wagtail start myproject`
2. Add WAGTAILDOCS_EXTENSIONS = ["doc", "pdf"]
3. Log onto Wagtail, navigate to Documents on the side menu
4. Add a new document with txt extension.
5. Error thrown File extension “” is not allowed. Allowed extensions are: doc, docx,  pdf. Instead of File extension “txt” is not allowed. Allowed extensions are: doc, docx,  pdf

image (1)

### Technical details

-   Python version: 3.11.5
-   Django version: 5.0.3
-   Wagtail version: 6.0
-   Browser version: Chrome 122 and Firefox 123

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

### PR DESCRIPTION
**Pull request by Th0masCat**
Fixes #11802 : Not allowed extension not showing in the error message
I experimented with a few other methods to solve this issue, but those led to errors. I have implemented the potential fix recommended by @rd3m for now until a better solution is available

### CODE REVIEW

**Comment by gasman** [comment]
Thanks @Th0masCat! Please can you add a test for this?

**Comment by Th0masCat** [comment]
Sure thing!

**Comment by Th0masCat** [comment]
@gasman I have added a test case as requested👍

**Review by RealOrangeOne — APPROVED** [review]

**Comment by RealOrangeOne** [comment]
Merged in https://github.com/wagtail/wagtail/commit/5cc28acc563ff258d02a2cbea3de3bad87dfbfe6 - thanks!

**Pull request closed without merging**
