### PR TITLE
fixed imports in tutorial

### PR DESCRIPTION
**Pull request by engineervix**
As I was going through the tutorial and running the code on my machine, I was getting `ImportError`s. These were caused by imports such as `from wagtail.core.fields import RichTextField`. I have updated the docs by adding `wagtail` prefixes where applicable. For instance:
 `from wagtail.wagtailcore.fields import RichTextField` instead of `from wagtail.core.fields import RichTextField`

### CODE REVIEW

**Comment by thibaudcolas** [comment]
Hi @engineervix 👋, thanks for looking into this.

I think you may be running into this because there is a version mismatch between the Wagtail version you're using and that of the tutorial. Those paths were renamed very recently (Wagtail 2.0, not released yet, see https://github.com/wagtail/wagtail/blob/master/docs/releases/2.0.rst#wagtail-module-path-updates).

If you look at the tutorial for the [latest stable release](http://docs.wagtail.io/en/v1.13.1/getting_started/tutorial.html), 1.13, the paths seem to be correct.

Could you let me know whether that solves it?

**Comment by engineervix** [comment]
@thibaudcolas thanks for the quick response. I'm using the latest stable release (1.13) and from your [link](http://docs.wagtail.io/en/v1.13.1/getting_started/tutorial.html) the docs seem to be fine! Ah :see_no_evil: :see_no_evil:, now I get it -- I think I had initially accessed the [docs based on the latest, unreleased version (2.0)](http://docs.wagtail.io/en/latest/getting_started/tutorial.html), and I thought those were the docs for version 1.13! My bad, I apologize for my ignorance. I appreciate your quick response and guidance, thanks for pointing me in the right direction. :blush: :blush:

**Comment by thibaudcolas** [comment]
Argh, this is because of #3375 😞 . Sorry this has happened to you!

**Comment by engineervix** [comment]
No worries @thibaudcolas! I'm all good now! However, I think other wagtail newcomers may face a similar problem and perhaps get discouraged. After retracing my steps, I realized that the problem actually came from the [getting started section of the wagtail.io website](https://wagtail.io/developers/), where I was directed to the wrong version of the docs. I have proposed that the link on the website be changed (#4151). This may save future wagtail developers from going through what I went through :smiley:

**Comment by simobasso** [comment]
@thibaudcolas you simple need to select the `stable` version in the readthedocs options.

I think here https://readthedocs.org/dashboard/wagtail/versions/

schermata 2017-12-20 alle 20 40 11

**Comment by gasman** [comment]
Thanks for the report @engineervix! Have updated the link on https://wagtail.io/developers/ now.

(@simobasso The readthedocs config isn't the problem - http://docs.wagtail.io/ is already configured to redirect to the latest release version.)

**Comment by simobasso** [comment]
> (@simobasso The readthedocs config isn't the problem - http://docs.wagtail.io/ is already configured to redirect to the latest release version.)

@gasman Yeah! But I think is better `stable` instead of `latest` in this case. :)

**Comment by engineervix** [comment]
Thank you so much :relaxed: :relaxed: :smiley:

**Pull request closed without merging**
