### PR TITLE
Remove woff fonts

### PR DESCRIPTION
**Pull request by zerolab**
Now that #7535 made it official, removing a number of woff fonts. wagtail.woff is still there as we have a few cases of icon font usage

This was raised in #6130

### CODE REVIEW

**Comment by Stormheg** [comment]
I'm happy to review this, but don't let that stop others from reviewing and merging this PR 🙂

**Review by Stormheg — APPROVED** [review]
LGTM, thanks @zerolab ❤️

**Comment by zerolab** [comment]
Merged in 614ec3fc2a656b25db710b80f9e60f1c8effd7a4

**Comment by Stormheg** [comment]
Thanks for merging Dan! 👍
I intended to merge this soon after approving, but forgot to do so 😅

**Comment by zerolab** [comment]
Got some spare time so slowly in working through the queue :)

**Pull request closed without merging**
