### PR TITLE
fixing a small typo in the documentation.

### PR DESCRIPTION
**Pull request by mehrdadmoradii**
_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by lb-** [comment]
Thanks @mehrdadmoradii - appreciate the clean up here. 

I've triggered the CI (shouldn't be a problem) and we will merge this in shortly.

**Comment by mehrdadmoradii** [comment]
> Thanks @mehrdadmoradii - appreciate the clean up here. 
> 
> 
> 
> I've triggered the CI (shouldn't be a problem) and we will merge this in shortly. 

Thanks LB!

**Comment by lb-** [comment]
Thanks @mehrdadmoradii - I have added you to the contributors list as 'Mehrdad Moradizadeh' - let me know if you want your name listed differently. 

Congrats on your first commit to Wagtail.

**Comment by mehrdadmoradii** [comment]
> Thanks @mehrdadmoradii - I have added you to the contributors list as 'Mehrdad Moradizadeh' - let me know if you want your name listed differently.
> 
> Congrats on your first commit to Wagtail.

@lb- My name on the list looks perfect, thanks for that!

looking forward to the next contributions.

**Pull request merged**
