### PR TITLE
Add support for Python 3.13

### PR DESCRIPTION
**Pull request by gasman**

### CODE REVIEW

**Comment by zerolab** [comment]
I like that all we needed was adding the version and the tests are all nice and green. One thing missing is the trove classifier near https://github.com/wagtail/wagtail/blob/main/setup.py#L113 ;)

**Comment by gasman** [comment]
@zerolab Good catch! Was hoping I could just copy everything from #10991 and be good to go, but there's always one more thing... :-)

Updated in e44bfd16c28d01674afba4722768e139482a229a now.

**Review by zerolab — APPROVED** [review]
LGTM

**Comment by lb-** [comment]
Just added release notes, will merge shortly.

Thanks @gasman

**Pull request merged**
