### PR TITLE
feat: allow float for image size

### PR DESCRIPTION
**Pull request by dopry**
SVGs allow for floating point width and height in the viewbox definition Illustrator and other editing tools generate floating point values and the SVG support code in development use the Viewbox width and height for the image width and height.  While the SVG implementation in willow could round this width and height, from a fidelity perspective it is best to defer rounding to as late a possible to minimize artifacts such as skewing that could be created by rounding errors.

For example a designer with a poorly scaled coordinate system who zoomed in way to far in illustrator and ended up with a viewbox like 0 0 0.320 0.480. If we rounded this at image  load it would result in a 1x1 image. if max: 320x480 were set, it would result in a 320x320 with pretty extreme skewing.  However if the *max* operation mathematically scales .320x.480 it would yield a 320x480 image. 

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by lb-** [comment]
@dopry are you able to add some unit tests for this?

**Comment by gasman** [comment]
We might need to consider how this relates to #8042 - there are known issues with rounding errors due to us performing multiple image/float conversions. (Since this specific PR is really just relaxing some validation criteria, I _think_ the worst that could happen is that some existing faulty code that wrongly resizes something to <1 pixels will fail with an obscure error in the image library rather than a descriptive error up-front - but would be good to sanity-check that.)

**Comment by dopry** [comment]
I can work on some tests in a week or two. I'm not familiar with where these values are used, so I'm not sure what exactly to test. Are there any existing tests around scaling that would need to be modified or specific tests that you (@lb- , @gasman) would require?

**Comment by gasman** [comment]
Addressed as part of #9842.

**Pull request closed without merging**
