### PR TITLE
Change of some formatting in inserting_images.md

### PR DESCRIPTION
**Pull request by DokuaAsiedu**
- Changed heading level of 'Choosing an image to insert' to h3 as it seemed to give more insight on 'Inserting images using the image chooser field'
- Wrapped 'Search' tab within an emphasis tag.

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by DokuaAsiedu** [comment]
There is something I noticed and it was that the 'Choose a format' window did not show when adding images, at least for when I was testing the bakery demo as an editor. Don't know whether something on the backend had changed but the documentation was not up to date to reflect it or maybe something else. I don't know if this could be an issue so would like to confirm from you guys @thibaudcolas and @lb- .

**Review by lb- — APPROVED** [review]
Thanks @DokuaAsiedu - will merge this in.

Just a heads up though that this editor's guide is soon to be replaced by a separate website - see https://github.com/wagtail/guide

Nonetheless, for now we should try to add any final touches.

I will add your name to the contributor's list  - is `Dokua Asiedu` correct?

**Comment by DokuaAsiedu** [comment]
> Thanks @DokuaAsiedu - will merge this in.
> 
> Just a heads up though that this editor's guide is soon to be replaced by a separate website - see https://github.com/wagtail/guide
> 
> Nonetheless, for now we should try to add any final touches.
> 
> I will add your name to the contributor's list - is `Dokua Asiedu` correct?

Yes the name is correct.
So rather than editing the files in the wagtail/wagtail docs folder, we should edit the wagtail/guide repository (a branch of it)?

**Comment by lb-** [comment]
@DokuaAsiedu maybe have a read of https://github.com/wagtail/guide/discussions/105

Much of the content from the docs folder (editors guide) has been migrated over. 

Contributors on that site will need a login but this is not fully ready to go just yet - maybe add a comment about this specific change and also that you would be interested in having access to edit/ update when it's ready.

**Pull request merged**
